In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os
import re
import json
import time
import random
import requests
import pandas as pd

from bs4 import BeautifulSoup
from pathlib import Path
from datetime import datetime
from urllib.parse import quote_plus, urljoin

BASE_DIR = Path("/content/drive/MyDrive/Calorify")

PHASE2_DIR = BASE_DIR / "phase2_text_calorie"
DATA_DIR = PHASE2_DIR / "data"
SCRAPED_RAW_DIR = DATA_DIR / "scraped_raw"
CLEAN_DIR = DATA_DIR / "cleaned"
RESULTS_DIR = PHASE2_DIR / "results"
MODELS_DIR = PHASE2_DIR / "models"
LOGS_DIR = PHASE2_DIR / "logs"

folders = [
    PHASE2_DIR,
    DATA_DIR,
    SCRAPED_RAW_DIR,
    CLEAN_DIR,
    RESULTS_DIR,
    MODELS_DIR,
    LOGS_DIR
]

for folder in folders:
    folder.mkdir(parents=True, exist_ok=True)

print("Phase 2 scraping folders created successfully.")
for folder in folders:
    print(folder)

Mounted at /content/drive
Phase 2 scraping folders created successfully.
/content/drive/MyDrive/Calorify/phase2_text_calorie
/content/drive/MyDrive/Calorify/phase2_text_calorie/data
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/scraped_raw
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned
/content/drive/MyDrive/Calorify/phase2_text_calorie/results
/content/drive/MyDrive/Calorify/phase2_text_calorie/models
/content/drive/MyDrive/Calorify/phase2_text_calorie/logs

In [2]:
# Cell 2 — Define food classes, search queries, and scraping source configuration

FOOD_CLASSES = [
    "burger",
    "pizza",
    "fries",
    "pasta",
    "rice",
    "chicken",
    "salad",
    "sandwich",
    "sushi",
    "steak"
]

SEARCH_QUERIES = {
    "burger": [
        "burger",
        "cheeseburger",
        "beef burger",
        "chicken burger",
        "turkey burger"
    ],
    "pizza": [
        "pizza",
        "pepperoni pizza",
        "cheese pizza",
        "margherita pizza",
        "vegetable pizza"
    ],
    "fries": [
        "fries",
        "french fries",
        "potato fries",
        "sweet potato fries",
        "loaded fries"
    ],
    "pasta": [
        "pasta",
        "chicken pasta",
        "spaghetti",
        "alfredo pasta",
        "tomato pasta"
    ],
    "rice": [
        "rice",
        "fried rice",
        "chicken rice",
        "rice bowl",
        "vegetable rice"
    ],
    "chicken": [
        "chicken",
        "grilled chicken",
        "fried chicken",
        "chicken breast",
        "roasted chicken"
    ],
    "salad": [
        "salad",
        "caesar salad",
        "chicken salad",
        "green salad",
        "greek salad"
    ],
    "sandwich": [
        "sandwich",
        "club sandwich",
        "chicken sandwich",
        "grilled cheese sandwich",
        "turkey sandwich"
    ],
    "sushi": [
        "sushi",
        "sushi roll",
        "california roll",
        "tuna roll",
        "salmon roll"
    ],
    "steak": [
        "steak",
        "grilled steak",
        "beef steak",
        "sirloin steak",
        "steak dinner"
    ]
}

SCRAPING_SOURCES = {
    "allrecipes": {
        "base_url": "https://www.allrecipes.com",
        "search_url_template": "https://www.allrecipes.com/search?q={query}"
    }
}

TARGET_RECORDS_PER_CLASS = 50

print("Food classes:", len(FOOD_CLASSES))
print("Target records per class:", TARGET_RECORDS_PER_CLASS)

print("\nClasses and number of queries:")
for food_class in FOOD_CLASSES:
    print(food_class, ":", len(SEARCH_QUERIES[food_class]))

print("\nScraping sources:")
for source_name, config in SCRAPING_SOURCES.items():
    print(source_name, ":", config["base_url"])

Food classes: 10
Target records per class: 50

Classes and number of queries:
burger : 5
pizza : 5
fries : 5
pasta : 5
rice : 5
chicken : 5
salad : 5
sandwich : 5
sushi : 5
steak : 5

Scraping sources:
allrecipes : https://www.allrecipes.com

In [3]:
# Cell 3 — Safe request helper and search page test

def safe_get(url, sleep_min=1, sleep_max=2, timeout=20):
    """
    Send a GET request with browser-like headers and simple delay.
    Returns the response object or None if the request fails.
    """
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        ),
        "Accept-Language": "en-US,en;q=0.9",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    }

    try:
        time.sleep(random.uniform(sleep_min, sleep_max))
        response = requests.get(url, headers=headers, timeout=timeout)
        return response

    except Exception as e:
        print("Request error:", e)
        return None


# Test one Allrecipes search page
test_query = "burger"
encoded_query = quote_plus(test_query)

test_search_url = SCRAPING_SOURCES["allrecipes"]["search_url_template"].format(
    query=encoded_query
)

print("Test search URL:")
print(test_search_url)

response = safe_get(test_search_url)

if response is None:
    print("No response returned.")
else:
    print("Status code:", response.status_code)
    print("Final URL:", response.url)
    print("HTML length:", len(response.text))
    print("First 300 characters:")
    print(response.text[:300])

Test search URL:
https://www.allrecipes.com/search?q=burger
Status code: 402
Final URL: https://www.allrecipes.com/search?q=burger
HTML length: 612
First 300 characters:
<p>
  If you are a reader experiencing an access issue, please contact
  <a href="mailto:support@people.inc">support@people.inc</a>. <br>
  To help us troubleshoot more quickly, you may include your IP address. <br>
  You can find it by visiting
  <a href="https://icanhazip.com" target="_blank" rel=

In [4]:
# Cell 4 — Test alternative recipe scraping sources

CANDIDATE_SOURCES = {
    "bbc_good_food": {
        "base_url": "https://www.bbcgoodfood.com",
        "search_url_template": "https://www.bbcgoodfood.com/search?q={query}"
    },
    "skinnytaste": {
        "base_url": "https://www.skinnytaste.com",
        "search_url_template": "https://www.skinnytaste.com/?s={query}"
    },
    "taste_of_home": {
        "base_url": "https://www.tasteofhome.com",
        "search_url_template": "https://www.tasteofhome.com/?s={query}"
    },
    "food_network": {
        "base_url": "https://www.foodnetwork.com",
        "search_url_template": "https://www.foodnetwork.com/search/{query}-"
    }
}

test_query = "burger"
encoded_query = quote_plus(test_query)

source_test_results = []

for source_name, config in CANDIDATE_SOURCES.items():
    search_url = config["search_url_template"].format(query=encoded_query)

    print("\nTesting source:", source_name)
    print("URL:", search_url)

    response = safe_get(search_url, sleep_min=1, sleep_max=2)

    if response is None:
        result = {
            "source_name": source_name,
            "status_code": None,
            "html_length": 0,
            "final_url": None,
            "works": False
        }
        print("No response.")
    else:
        result = {
            "source_name": source_name,
            "status_code": response.status_code,
            "html_length": len(response.text),
            "final_url": response.url,
            "works": response.status_code == 200 and len(response.text) > 5000
        }

        print("Status code:", response.status_code)
        print("HTML length:", len(response.text))
        print("Final URL:", response.url)
        print("Works:", result["works"])

    source_test_results.append(result)

source_test_df = pd.DataFrame(source_test_results)

print("\nSource test summary:")
display(source_test_df)# Cell 4 — Test alternative recipe scraping sources

CANDIDATE_SOURCES = {
    "bbc_good_food": {
        "base_url": "https://www.bbcgoodfood.com",
        "search_url_template": "https://www.bbcgoodfood.com/search?q={query}"
    },
    "skinnytaste": {
        "base_url": "https://www.skinnytaste.com",
        "search_url_template": "https://www.skinnytaste.com/?s={query}"
    },
    "taste_of_home": {
        "base_url": "https://www.tasteofhome.com",
        "search_url_template": "https://www.tasteofhome.com/?s={query}"
    },
    "food_network": {
        "base_url": "https://www.foodnetwork.com",
        "search_url_template": "https://www.foodnetwork.com/search/{query}-"
    }
}

test_query = "burger"
encoded_query = quote_plus(test_query)

source_test_results = []

for source_name, config in CANDIDATE_SOURCES.items():
    search_url = config["search_url_template"].format(query=encoded_query)

    print("\nTesting source:", source_name)
    print("URL:", search_url)

    response = safe_get(search_url, sleep_min=1, sleep_max=2)

    if response is None:
        result = {
            "source_name": source_name,
            "status_code": None,
            "html_length": 0,
            "final_url": None,
            "works": False
        }
        print("No response.")
    else:
        result = {
            "source_name": source_name,
            "status_code": response.status_code,
            "html_length": len(response.text),
            "final_url": response.url,
            "works": response.status_code == 200 and len(response.text) > 5000
        }

        print("Status code:", response.status_code)
        print("HTML length:", len(response.text))
        print("Final URL:", response.url)
        print("Works:", result["works"])

    source_test_results.append(result)

source_test_df = pd.DataFrame(source_test_results)

print("\nSource test summary:")
display(source_test_df)

Testing source: bbc_good_food
URL: https://www.bbcgoodfood.com/search?q=burger
Status code: 200
HTML length: 962908
Final URL: https://www.bbcgoodfood.com/search?q=burger
Works: True

Testing source: skinnytaste
URL: https://www.skinnytaste.com/?s=burger
Status code: 200
HTML length: 585691
Final URL: https://www.skinnytaste.com/?s=burger
Works: True

Testing source: taste_of_home
URL: https://www.tasteofhome.com/?s=burger
Status code: 200
HTML length: 168249
Final URL: https://www.tasteofhome.com/?s=burger
Works: True

Testing source: food_network
URL: https://www.foodnetwork.com/search/burger-
Status code: 403
HTML length: 395
Final URL: https://www.foodnetwork.com/search/burger-
Works: False

Source test summary:

,source_name,status_code,html_length,final_url,works
0,bbc_good_food,200,962908,https://www.bbcgoodfood.com/search?q=burger,True
1,skinnytaste,200,585691,https://www.skinnytaste.com/?s=burger,True
2,taste_of_home,200,168249,https://www.tasteofhome.com/?s=burger,True
3,food_network,403,395,https://www.foodnetwork.com/search/burger-,False

Testing source: bbc_good_food
URL: https://www.bbcgoodfood.com/search?q=burger
Status code: 200
HTML length: 962908
Final URL: https://www.bbcgoodfood.com/search?q=burger
Works: True

Testing source: skinnytaste
URL: https://www.skinnytaste.com/?s=burger
Status code: 200
HTML length: 585691
Final URL: https://www.skinnytaste.com/?s=burger
Works: True

Testing source: taste_of_home
URL: https://www.tasteofhome.com/?s=burger
Status code: 200
HTML length: 168249
Final URL: https://www.tasteofhome.com/?s=burger
Works: True

Testing source: food_network
URL: https://www.foodnetwork.com/search/burger-
Status code: 403
HTML length: 395
Final URL: https://www.foodnetwork.com/search/burger-
Works: False

Source test summary:

,source_name,status_code,html_length,final_url,works
0,bbc_good_food,200,962908,https://www.bbcgoodfood.com/search?q=burger,True
1,skinnytaste,200,585691,https://www.skinnytaste.com/?s=burger,True
2,taste_of_home,200,168249,https://www.tasteofhome.com/?s=burger,True
3,food_network,403,395,https://www.foodnetwork.com/search/burger-,False

In [5]:
# Cell 5 — Extract candidate recipe links from working search pages

def extract_candidate_links_from_search(source_name, query, max_links=30):
    """
    Extract candidate recipe links from a search results page.
    This is an inspection function before building the final scraper.
    """
    config = CANDIDATE_SOURCES[source_name]
    encoded_query = quote_plus(query)
    search_url = config["search_url_template"].format(query=encoded_query)

    response = safe_get(search_url, sleep_min=1, sleep_max=2)

    if response is None:
        print("No response returned.")
        return []

    print("Source:", source_name)
    print("Search URL:", search_url)
    print("Status code:", response.status_code)
    print("HTML length:", len(response.text))

    soup = BeautifulSoup(response.text, "html.parser")
    links = []

    for a_tag in soup.find_all("a", href=True):
        href = a_tag.get("href")
        text = a_tag.get_text(" ", strip=True)

        if not href:
            continue

        full_url = urljoin(config["base_url"], href)

        if source_name == "bbc_good_food":
            is_recipe_link = "/recipes/" in full_url

        elif source_name == "skinnytaste":
            is_recipe_link = (
                "skinnytaste.com" in full_url
                and "/?s=" not in full_url
                and "#" not in full_url
                and len(full_url.split("/")) >= 4
            )

        else:
            is_recipe_link = False

        if is_recipe_link:
            links.append({
                "source_name": source_name,
                "query": query,
                "title_text": text,
                "url": full_url
            })

    links_df = pd.DataFrame(links).drop_duplicates(subset=["url"])

    print("Candidate recipe links found:", len(links_df))

    if not links_df.empty:
        display(links_df.head(max_links))

    return links_df


bbc_burger_links_df = extract_candidate_links_from_search(
    source_name="bbc_good_food",
    query="burger",
    max_links=20
)

skinnytaste_burger_links_df = extract_candidate_links_from_search(
    source_name="skinnytaste",
    query="burger",
    max_links=20
)

Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=burger
Status code: 200
HTML length: 962908
Candidate recipe links found: 86

,source_name,query,title_text,url
0,bbc_good_food,burger,Easy dinner ideas,https://www.bbcgoodfood.com/recipes/collection...
1,bbc_good_food,burger,High protein recipes,https://www.bbcgoodfood.com/recipes/collection...
2,bbc_good_food,burger,Chocolate bakes,https://www.bbcgoodfood.com/recipes/collection...
3,bbc_good_food,burger,Quick pastas,https://www.bbcgoodfood.com/recipes/collection...
4,bbc_good_food,burger,May recipes,https://www.bbcgoodfood.com/recipes/collection...
5,bbc_good_food,burger,Barbecue ideas,https://www.bbcgoodfood.com/recipes/collection...
6,bbc_good_food,burger,Quick and easy,https://www.bbcgoodfood.com/recipes/collection...
8,bbc_good_food,burger,Family recipes,https://www.bbcgoodfood.com/recipes/collection...
9,bbc_good_food,burger,One-pots,https://www.bbcgoodfood.com/recipes/collection...
10,bbc_good_food,burger,Slow cooker recipes,https://www.bbcgoodfood.com/recipes/collection...
11,bbc_good_food,burger,Traybakes,https://www.bbcgoodfood.com/recipes/collection...
12,bbc_good_food,burger,Air fryer recipes,https://www.bbcgoodfood.com/recipes/collection...
13,bbc_good_food,burger,Batch cooking,https://www.bbcgoodfood.com/recipes/collection...
14,bbc_good_food,burger,Occasion recipes,https://www.bbcgoodfood.com/recipes/category/s...
16,bbc_good_food,burger,Breakfast,https://www.bbcgoodfood.com/recipes/collection...
17,bbc_good_food,burger,Lunch,https://www.bbcgoodfood.com/recipes/collection...
20,bbc_good_food,burger,Diet type,https://www.bbcgoodfood.com/recipes/category/d...
21,bbc_good_food,burger,Vegan,https://www.bbcgoodfood.com/recipes/collection...
22,bbc_good_food,burger,Vegetarian,https://www.bbcgoodfood.com/recipes/collection...
24,bbc_good_food,burger,Cuisines,https://www.bbcgoodfood.com/recipes/category/c...

Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=burger
Status code: 200
HTML length: 585691
Candidate recipe links found: 86

,source_name,query,title_text,url
0,skinnytaste,burger,About Gina,https://www.skinnytaste.com/about/
1,skinnytaste,burger,Skinnytaste Community,https://skinnytaste.raptive.com/?utm_campaign=...
2,skinnytaste,burger,About,https://www.skinnytaste.com/join-skinnytaste-c...
3,skinnytaste,burger,Contact,https://www.skinnytaste.com/contact-me/
4,skinnytaste,burger,Book Tour,https://www.skinnytaste.com/book-tour/
5,skinnytaste,burger,My Shop,https://www.skinnytaste.com/shop/
6,skinnytaste,burger,,https://www.skinnytaste.com/
8,skinnytaste,burger,Recipes,https://www.skinnytaste.com/recipe-index/
10,skinnytaste,burger,Category Index,https://www.skinnytaste.com/category-index/
11,skinnytaste,burger,High Fiber,https://www.skinnytaste.com/high-fiber-recipes/
12,skinnytaste,burger,High Protein,https://www.skinnytaste.com/high-protein/
13,skinnytaste,burger,Anti Inflammatory,https://www.skinnytaste.com/anti-inflammatory-...
14,skinnytaste,burger,Weight Watchers,https://www.skinnytaste.com/smart-points/
15,skinnytaste,burger,Dairy Free Recipes,https://www.skinnytaste.com/recipes/dairy-free/
16,skinnytaste,burger,Gluten Free,https://www.skinnytaste.com/recipes/gluten-free/
17,skinnytaste,burger,Low Carb,https://www.skinnytaste.com/recipes/low-carb/
18,skinnytaste,burger,Low Sodium,https://www.skinnytaste.com/low-sodium/
19,skinnytaste,burger,Vegan Recipes,https://www.skinnytaste.com/recipes/vegan/
20,skinnytaste,burger,Vegetarian,https://www.skinnytaste.com/recipes/vegetarian/
21,skinnytaste,burger,Whole 30,https://www.skinnytaste.com/recipes/whole-30/

In [6]:
# Cell 6 — Refine candidate recipe link filtering

from urllib.parse import urlparse

def is_valid_bbc_good_food_recipe_url(url):
    """
    BBC Good Food recipe URLs usually look like:
    https://www.bbcgoodfood.com/recipes/recipe-slug

    We exclude:
    /recipes/collection/...
    /recipes/category/...
    /recipes/...
    """
    parsed = urlparse(url)
    path_parts = [part for part in parsed.path.split("/") if part]

    if len(path_parts) != 2:
        return False

    if path_parts[0] != "recipes":
        return False

    blocked_second_parts = {"collection", "category"}
    if path_parts[1] in blocked_second_parts:
        return False

    return True


def is_valid_skinnytaste_recipe_url(url, title_text, query):
    """
    Skinnytaste recipe pages are usually post URLs.
    This filter removes navigation/category/about pages and keeps URLs
    likely related to the query.
    """
    parsed = urlparse(url)
    path = parsed.path.strip("/").lower()
    title = str(title_text).strip().lower()
    query_terms = str(query).lower().split()

    if not path:
        return False

    blocked_paths = [
        "about",
        "contact-me",
        "shop",
        "book-tour",
        "recipe-index",
        "category-index",
        "recipes",
        "category",
        "smart-points",
        "high-fiber-recipes",
        "high-protein",
        "anti-inflammatory-recipes",
        "low-sodium",
        "join-skinnytaste-community"
    ]

    for blocked in blocked_paths:
        if path == blocked or path.startswith(blocked + "/"):
            return False

    if "skinnytaste.com" not in parsed.netloc:
        return False

    if len(title) < 5:
        return False

    has_query_term = any(term in title for term in query_terms)
    has_query_term_in_url = any(term in path for term in query_terms)

    return has_query_term or has_query_term_in_url


def extract_refined_recipe_links_from_search(source_name, query, max_links=30):
    """
    Extract more accurate recipe links from a search results page.
    """
    config = CANDIDATE_SOURCES[source_name]
    encoded_query = quote_plus(query)
    search_url = config["search_url_template"].format(query=encoded_query)

    response = safe_get(search_url, sleep_min=1, sleep_max=2)

    if response is None:
        print("No response returned.")
        return pd.DataFrame()

    print("Source:", source_name)
    print("Search URL:", search_url)
    print("Status code:", response.status_code)
    print("HTML length:", len(response.text))

    soup = BeautifulSoup(response.text, "html.parser")
    links = []

    for a_tag in soup.find_all("a", href=True):
        href = a_tag.get("href")
        title_text = a_tag.get_text(" ", strip=True)

        if not href:
            continue

        full_url = urljoin(config["base_url"], href)

        if source_name == "bbc_good_food":
            is_recipe_link = is_valid_bbc_good_food_recipe_url(full_url)

        elif source_name == "skinnytaste":
            is_recipe_link = is_valid_skinnytaste_recipe_url(
                url=full_url,
                title_text=title_text,
                query=query
            )

        else:
            is_recipe_link = False

        if is_recipe_link:
            links.append({
                "source_name": source_name,
                "query": query,
                "title_text": title_text,
                "url": full_url
            })

    links_df = pd.DataFrame(links)

    if not links_df.empty:
        links_df = links_df.drop_duplicates(subset=["url"]).reset_index(drop=True)

    print("Refined recipe links found:", len(links_df))

    if not links_df.empty:
        display(links_df.head(max_links))

    return links_df


bbc_burger_refined_df = extract_refined_recipe_links_from_search(
    source_name="bbc_good_food",
    query="burger",
    max_links=20
)

skinnytaste_burger_refined_df = extract_refined_recipe_links_from_search(
    source_name="skinnytaste",
    query="burger",
    max_links=20
)

Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=burger
Status code: 200
HTML length: 962908
Refined recipe links found: 24

,source_name,query,title_text,url
0,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/burger-bowl
1,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/falafel-bu...
2,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/15-minute-...
3,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/the-big-do...
4,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/next-level...
5,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/superhealt...
6,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/smash-burgers
7,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/mexican-ch...
8,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/soft-burge...
9,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/spiced-hal...
10,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/prawn-salm...
11,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/halloumi-b...
12,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/chickpea-c...
13,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/miso-mushr...
14,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/green-burgers
15,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/fully-load...
16,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/korean-fri...
17,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/lean-turke...
18,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/classic-bu...
19,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/molten-che...

Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=burger
Status code: 200
HTML length: 585691
Refined recipe links found: 10

,source_name,query,title_text,url
0,skinnytaste,burger,Black Bean Burgers with Chipotle Mayonnaise,https://www.skinnytaste.com/spicy-black-bean-b...
1,skinnytaste,burger,Turkey Burger Recipe,https://www.skinnytaste.com/turkey-burger-recipe/
2,skinnytaste,burger,Cheeseburger Casserole,https://www.skinnytaste.com/cheeseburger-casse...
3,skinnytaste,burger,Homemade Hamburger Helper,https://www.skinnytaste.com/homemade-hamburger...
4,skinnytaste,burger,The 4 Best Burger Presses of 2024,https://www.skinnytaste.com/best-burger-presses/
5,skinnytaste,burger,Juicy Lucy (Stuffed Turkey Cheeseburger),https://www.skinnytaste.com/turkey-burgers-stu...
6,skinnytaste,burger,20 Best Burger Recipes,https://www.skinnytaste.com/burger-recipes/
7,skinnytaste,burger,Chicken Burger,https://www.skinnytaste.com/chicken-burger/
8,skinnytaste,burger,Juicy Turkey Burgers with Zucchini,https://www.skinnytaste.com/turkey-burgers-wit...
9,skinnytaste,burger,Cheeseburger Crunch Wrap,https://www.skinnytaste.com/cheeseburger-crunc...

In [7]:
# Cell 7 — Scrape one BBC Good Food recipe page

def extract_number(value):
    """
    Extract the first numeric value from a text field.
    Examples:
    "709 kcal" -> 709
    "23.5g" -> 23.5
    """
    if value is None:
        return None

    text = str(value)
    match = re.search(r"(\d+(?:\.\d+)?)", text)

    if match:
        return float(match.group(1))

    return None


def is_recipe_type(item):
    """
    Check whether a JSON-LD item is a Recipe object.
    """
    item_type = item.get("@type")

    if isinstance(item_type, list):
        return "Recipe" in item_type

    return item_type == "Recipe"


def find_recipe_json_ld(soup):
    """
    Find Recipe JSON-LD data inside a recipe page.
    """
    scripts = soup.find_all("script", type="application/ld+json")

    for script in scripts:
        raw_json = script.string or script.get_text(strip=True)

        if not raw_json:
            continue

        try:
            data = json.loads(raw_json)
        except Exception:
            continue

        items_to_check = []

        if isinstance(data, dict):
            items_to_check.append(data)

            if "@graph" in data and isinstance(data["@graph"], list):
                items_to_check.extend(data["@graph"])

        elif isinstance(data, list):
            items_to_check.extend(data)

        for item in items_to_check:
            if isinstance(item, dict) and is_recipe_type(item):
                return item

    return None


def scrape_bbc_good_food_recipe(url, food_class=None, query=None):
    """
    Scrape one BBC Good Food recipe page.
    """
    response = safe_get(url, sleep_min=1, sleep_max=2)

    if response is None:
        return None

    if response.status_code != 200:
        print("Failed URL:", url)
        print("Status code:", response.status_code)
        return None

    soup = BeautifulSoup(response.text, "html.parser")
    recipe_json = find_recipe_json_ld(soup)

    if recipe_json is None:
        print("No Recipe JSON-LD found for:", url)
        return None

    recipe_name = recipe_json.get("name")

    ingredients = recipe_json.get("recipeIngredient", [])
    if isinstance(ingredients, list):
        ingredients_text = " ".join([str(item) for item in ingredients])
    else:
        ingredients_text = str(ingredients)

    nutrition = recipe_json.get("nutrition", {})
    if not isinstance(nutrition, dict):
        nutrition = {}

    calories = extract_number(nutrition.get("calories"))
    protein = extract_number(nutrition.get("proteinContent"))
    fat = extract_number(nutrition.get("fatContent"))
    carbs = extract_number(nutrition.get("carbohydrateContent"))

    record = {
        "source_site": "bbc_good_food",
        "food_class": food_class,
        "query": query,
        "recipe_name": recipe_name,
        "ingredients_text": ingredients_text,
        "calories": calories,
        "protein": protein,
        "fat": fat,
        "carbs": carbs,
        "source_url": url,
        "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    return record


# Test on first BBC burger recipe link
test_bbc_url = bbc_burger_refined_df.iloc[0]["url"]

print("Testing BBC recipe URL:")
print(test_bbc_url)

test_bbc_record = scrape_bbc_good_food_recipe(
    url=test_bbc_url,
    food_class="burger",
    query="burger"
)

print("\nScraped record:")
print(test_bbc_record)

if test_bbc_record is not None:
    print("\nIngredients length:", len(test_bbc_record["ingredients_text"]))
    print("Calories:", test_bbc_record["calories"])
    print("Protein:", test_bbc_record["protein"])
    print("Fat:", test_bbc_record["fat"])
    print("Carbs:", test_bbc_record["carbs"])

Testing BBC recipe URL:
https://www.bbcgoodfood.com/recipes/burger-bowl

Scraped record:
{'source_site': 'bbc_good_food', 'food_class': 'burger', 'query': 'burger', 'recipe_name': 'Burger bowl', 'ingredients_text': '2 large potatoes cut into rough chunks 2 tbsp vegetable oil 2 tbsp Cajun spice mix 1 tsp garlic granules (optional) 250g lean beef mince 25g crinkle cut pickles plus 1 tbsp brine from the jar 1 Iceberg lettuce shredded 1 red onion onion, finely sliced into rings and rinsed in cold water, if you like (this will reduce the strong raw onion flavour) 150g cherry tomatoes halved 50g cheddar grated 3 tbsp low-sugar ketchup 2 tbsp light mayonnaise ½ tbsp American mustard', 'calories': 207.0, 'protein': 18.0, 'fat': 13.0, 'carbs': 19.0, 'source_url': 'https://www.bbcgoodfood.com/recipes/burger-bowl', 'scraped_at': '2026-05-11 23:58:00'}

Ingredients length: 468
Calories: 207.0
Protein: 18.0
Fat: 13.0
Carbs: 19.0

In [8]:
# Cell 8 — Test scraping multiple BBC Good Food recipe pages

def scrape_multiple_bbc_links(links_df, food_class, max_pages=10):
    """
    Scrape multiple BBC Good Food recipe pages from a links dataframe.
    This is a small test before building the full crawler.
    """
    records = []
    failed_urls = []

    selected_links = links_df.head(max_pages)

    print("Testing multiple BBC recipe pages")
    print("Food class:", food_class)
    print("Pages to test:", len(selected_links))

    for idx, row in selected_links.iterrows():
        url = row["url"]
        query = row["query"]

        print("\nScraping page:", idx)
        print("URL:", url)

        record = scrape_bbc_good_food_recipe(
            url=url,
            food_class=food_class,
            query=query
        )

        if record is None:
            failed_urls.append(url)
            print("Result: failed")
            continue

        has_required_fields = (
            record["recipe_name"] is not None
            and record["ingredients_text"] is not None
            and len(record["ingredients_text"]) > 0
            and record["calories"] is not None
        )

        if has_required_fields:
            records.append(record)
            print("Result: success")
            print("Recipe:", record["recipe_name"])
            print("Calories:", record["calories"])
        else:
            failed_urls.append(url)
            print("Result: missing required fields")
            print("Recipe:", record["recipe_name"])
            print("Calories:", record["calories"])
            print("Ingredients length:", len(record["ingredients_text"]) if record["ingredients_text"] else 0)

    records_df = pd.DataFrame(records)

    print("\nMultiple page scraping test finished.")
    print("Successful records:", len(records))
    print("Failed pages:", len(failed_urls))

    if not records_df.empty:
        display(records_df[[
            "food_class",
            "query",
            "recipe_name",
            "calories",
            "protein",
            "fat",
            "carbs",
            "source_url"
        ]])

    return records_df, failed_urls


bbc_burger_test_records_df, bbc_burger_failed_urls = scrape_multiple_bbc_links(
    links_df=bbc_burger_refined_df,
    food_class="burger",
    max_pages=10
)

Testing multiple BBC recipe pages
Food class: burger
Pages to test: 10

Scraping page: 0
URL: https://www.bbcgoodfood.com/recipes/burger-bowl
Result: success
Recipe: Burger bowl
Calories: 207.0

Scraping page: 1
URL: https://www.bbcgoodfood.com/recipes/falafel-burgers-0
Result: success
Recipe: Falafel burgers
Calories: 175.0

Scraping page: 2
URL: https://www.bbcgoodfood.com/recipes/15-minute-chicken-halloumi-burgers
Result: success
Recipe: 15-minute chicken & halloumi burgers
Calories: 737.0

Scraping page: 3
URL: https://www.bbcgoodfood.com/recipes/the-big-double-cheeseburger-secret-sauce
Result: success
Recipe: The ultimate beef burger
Calories: 893.0

Scraping page: 4
URL: https://www.bbcgoodfood.com/recipes/next-level-chicken-burgers
Result: success
Recipe: Next level chicken burgers
Calories: 794.0

Scraping page: 5
URL: https://www.bbcgoodfood.com/recipes/superhealthy-salmon-burgers
Result: success
Recipe: Superhealthy salmon burgers
Calories: 292.0

Scraping page: 6
URL: https://www.bbcgoodfood.com/recipes/smash-burgers
Result: success
Recipe: Smash burgers
Calories: 666.0

Scraping page: 7
URL: https://www.bbcgoodfood.com/recipes/mexican-chicken-burger
Result: success
Recipe: Mexican chicken burger
Calories: 709.0

Scraping page: 8
URL: https://www.bbcgoodfood.com/recipes/soft-burger-buns
Result: success
Recipe: Soft burger buns
Calories: 210.0

Scraping page: 9
URL: https://www.bbcgoodfood.com/recipes/spiced-halloumi-pineapple-burger-zingy-slaw
Result: success
Recipe: Spiced halloumi & pineapple burger with zingy slaw
Calories: 264.0

Multiple page scraping test finished.
Successful records: 10
Failed pages: 0

,food_class,query,recipe_name,calories,protein,fat,carbs,source_url
0,burger,burger,Burger bowl,207.0,18.0,13.0,19.0,https://www.bbcgoodfood.com/recipes/burger-bowl
1,burger,burger,Falafel burgers,175.0,6.0,8.0,18.0,https://www.bbcgoodfood.com/recipes/falafel-bu...
2,burger,burger,15-minute chicken & halloumi burgers,737.0,39.0,42.0,49.0,https://www.bbcgoodfood.com/recipes/15-minute-...
3,burger,burger,The ultimate beef burger,893.0,56.0,37.0,82.0,https://www.bbcgoodfood.com/recipes/the-big-do...
4,burger,burger,Next level chicken burgers,794.0,33.0,33.0,90.0,https://www.bbcgoodfood.com/recipes/next-level...
5,burger,burger,Superhealthy salmon burgers,292.0,29.0,17.0,7.0,https://www.bbcgoodfood.com/recipes/superhealt...
6,burger,burger,Smash burgers,666.0,37.0,39.0,41.0,https://www.bbcgoodfood.com/recipes/smash-burgers
7,burger,burger,Mexican chicken burger,709.0,46.0,34.0,52.0,https://www.bbcgoodfood.com/recipes/mexican-ch...
8,burger,burger,Soft burger buns,210.0,6.0,5.0,35.0,https://www.bbcgoodfood.com/recipes/soft-burge...
9,burger,burger,Spiced halloumi & pineapple burger with zingy ...,264.0,11.0,14.0,19.0,https://www.bbcgoodfood.com/recipes/spiced-hal...

In [9]:
# Cell 9 — Test BBC Good Food recipe link extraction for all classes

bbc_link_test_rows = []
bbc_all_class_links = {}

for food_class in FOOD_CLASSES:
    print("\n====================================")
    print("Testing BBC links for class:", food_class)
    print("====================================")

    class_links = []

    for query in SEARCH_QUERIES[food_class]:
        print("\nQuery:", query)

        links_df = extract_refined_recipe_links_from_search(
            source_name="bbc_good_food",
            query=query,
            max_links=10
        )

        if links_df is not None and not links_df.empty:
            class_links.append(links_df)

        time.sleep(1)

    if class_links:
        class_links_df = pd.concat(class_links, ignore_index=True)
        class_links_df = class_links_df.drop_duplicates(subset=["url"]).reset_index(drop=True)
    else:
        class_links_df = pd.DataFrame(columns=["source_name", "query", "title_text", "url"])

    bbc_all_class_links[food_class] = class_links_df

    link_count = len(class_links_df)

    bbc_link_test_rows.append({
        "food_class": food_class,
        "unique_links_found": link_count
    })

    print("\nFinished class:", food_class)
    print("Unique BBC recipe links found:", link_count)

bbc_link_test_df = pd.DataFrame(bbc_link_test_rows)

print("\nBBC link extraction test summary:")
display(bbc_link_test_df)

print("\nClasses with fewer than 50 links:")
display(bbc_link_test_df[bbc_link_test_df["unique_links_found"] < TARGET_RECORDS_PER_CLASS])

====================================
Testing BBC links for class: burger
====================================

Query: burger
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=burger
Status code: 200
HTML length: 962908
Refined recipe links found: 24

,source_name,query,title_text,url
0,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/burger-bowl
1,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/falafel-bu...
2,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/15-minute-...
3,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/the-big-do...
4,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/next-level...
5,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/superhealt...
6,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/smash-burgers
7,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/mexican-ch...
8,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/soft-burge...
9,bbc_good_food,burger,,https://www.bbcgoodfood.com/recipes/spiced-hal...

Query: cheeseburger
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=cheeseburger
Status code: 200
HTML length: 660375
Refined recipe links found: 13

,source_name,query,title_text,url
0,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/one-pot-ch...
1,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/nacho-chee...
2,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/cheeseburg...
3,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/cheeseburg...
4,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/veg-packed...
5,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/cheeseburg...
6,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/french-oni...
7,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/cheeseburgers
8,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/pork-thyme...
9,bbc_good_food,cheeseburger,,https://www.bbcgoodfood.com/recipes/the-big-do...

Query: beef burger
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=beef+burger
Status code: 200
HTML length: 955511
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/the-big-do...
1,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/beef-burge...
2,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/barbecue-b...
3,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/beef-burge...
4,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/beef-strog...
5,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/beef-red-p...
6,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/beer-batte...
7,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/harissa-be...
8,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/slow-cooke...
9,bbc_good_food,beef burger,,https://www.bbcgoodfood.com/recipes/burger-bowl

Query: chicken burger
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=chicken+burger
Status code: 200
HTML length: 970596
Refined recipe links found: 25

,source_name,query,title_text,url
0,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/next-level...
1,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/mexican-ch...
2,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/korean-fri...
3,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/fully-load...
4,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/crispiest-...
5,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/sriracha-g...
6,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/jerk-chick...
7,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/crispy-jap...
8,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/buffalo-ch...
9,bbc_good_food,chicken burger,,https://www.bbcgoodfood.com/recipes/bbq-chicke...

Query: turkey burger
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=turkey+burger
Status code: 200
HTML length: 958205
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/lean-turke...
1,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/turkey-bur...
2,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/harissa-tu...
3,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/spiced-tur...
4,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/turkey-bur...
5,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/turkey-bur...
6,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/thai-turke...
7,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/lemon-thym...
8,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/caesar-tur...
9,bbc_good_food,turkey burger,,https://www.bbcgoodfood.com/recipes/turkey-cor...

Finished class: burger
Unique BBC recipe links found: 90

====================================
Testing BBC links for class: pizza
====================================

Query: pizza
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=pizza
Status code: 200
HTML length: 902131
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/pizza-sauce
1,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/quick-pizz...
2,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/pizza-marg...
3,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/basic-pizz...
4,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/no-yeast-p...
5,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/pizza-home...
6,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/triple-che...
7,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/puff-pastr...
8,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/chicken-ti...
9,bbc_good_food,pizza,,https://www.bbcgoodfood.com/recipes/tortilla-p...

Query: pepperoni pizza
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=pepperoni+pizza
Status code: 200
HTML length: 901215
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/pepperoni-...
1,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/pizza-pie
2,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/triple-che...
3,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/pizza-sauce
4,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/quick-pizz...
5,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/tortilla-p...
6,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/pizza-marg...
7,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/basic-pizz...
8,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/pizza-fond...
9,bbc_good_food,pepperoni pizza,,https://www.bbcgoodfood.com/recipes/potato-cho...

Query: cheese pizza
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=cheese+pizza
Status code: 200
HTML length: 959867
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/spinach-bl...
1,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/caramelise...
2,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/roast-caul...
3,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/brussels-b...
4,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/no-cook-go...
5,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/cauliflowe...
6,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/best-ever-...
7,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/cheese-bac...
8,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/classic-ch...
9,bbc_good_food,cheese pizza,,https://www.bbcgoodfood.com/recipes/pizza-marg...

Query: margherita pizza
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=margherita+pizza
Status code: 200
HTML length: 905688
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/next-level...
1,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/very-simpl...
2,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/pizza-marg...
3,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/vegan-pizz...
4,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/ultimate-p...
5,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/lighter-pi...
6,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/pizza-sauce
7,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/quick-pizz...
8,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/basic-pizz...
9,bbc_good_food,margherita pizza,,https://www.bbcgoodfood.com/recipes/no-yeast-p...

Query: vegetable pizza
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=vegetable+pizza
Status code: 200
HTML length: 1005431
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/roasted-sp...
1,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/versatile-...
2,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/pizza-sauce
3,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/quick-pizz...
4,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/pizza-marg...
5,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/basic-pizz...
6,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/vegetable-...
7,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/rustic-veg...
8,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/slow-cooke...
9,bbc_good_food,vegetable pizza,,https://www.bbcgoodfood.com/recipes/no-yeast-p...

Finished class: pizza
Unique BBC recipe links found: 69

====================================
Testing BBC links for class: fries
====================================

Query: fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=fries
Status code: 200
HTML length: 972117
Refined recipe links found: 24

,source_name,query,title_text,url
0,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/korean-fri...
1,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/egg-fried-...
2,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/next-level...
3,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/prawn-frie...
4,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/chorizo-eg...
5,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/chicken-gi...
6,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/pineapple-...
7,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/pan-fried-...
8,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/pan-fried-...
9,bbc_good_food,fries,,https://www.bbcgoodfood.com/recipes/salmon-egg...

Query: french fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=french+fries
Status code: 200
HTML length: 978393
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/air-fryer-...
1,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-fries
2,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/korean-fri...
3,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/egg-fried-...
4,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-oni...
5,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/beef-strog...
6,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/next-level...
7,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/meatball-m...
8,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/greek-load...
9,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-toast

Query: potato fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=potato+fries
Status code: 200
HTML length: 1012934
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/sweet-pota...
1,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/air-fryer-...
2,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/steaks-gou...
3,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/roast-aube...
4,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/polenta-sw...
5,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/leek-kale-...
6,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/chimichurr...
7,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/smoked-had...
8,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/ultimate-r...
9,bbc_good_food,potato fries,,https://www.bbcgoodfood.com/recipes/potato-pep...

Query: sweet potato fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=sweet+potato+fries
Status code: 200
HTML length: 1014743
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/sweet-pota...
1,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/air-fryer-...
2,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/steaks-gou...
3,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/roast-aube...
4,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/polenta-sw...
5,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/chimichurr...
6,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/satay-swee...
7,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/spinach-sw...
8,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/stir-fry-c...
9,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/piri-piri-...

Query: loaded fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=loaded+fries
Status code: 200
HTML length: 975665
Refined recipe links found: 25

,source_name,query,title_text,url
0,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/loaded-fries
1,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/greek-load...
2,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/korean-fri...
3,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/egg-fried-...
4,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/next-level...
5,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/meatball-m...
6,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/prawn-frie...
7,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/chorizo-eg...
8,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/pineapple-...
9,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/chicken-gi...

Finished class: fries
Unique BBC recipe links found: 72

====================================
Testing BBC links for class: pasta
====================================

Query: pasta
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=pasta
Status code: 200
HTML length: 947848
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/chicken-pa...
1,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/cajun-chic...
2,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/chicken-ba...
3,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/pasta-salm...
4,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/fajita-sty...
5,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/pasta-alla...
6,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/orzo-tomat...
7,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/caponata-p...
8,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/creamy-mus...
9,bbc_good_food,pasta,,https://www.bbcgoodfood.com/recipes/creamy-gar...

Query: chicken pasta
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=chicken+pasta
Status code: 200
HTML length: 958470
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/chicken-pa...
1,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/cajun-chic...
2,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/creamy-chi...
3,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/chicken-pa...
4,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/healthy-ch...
5,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/chicken-ba...
6,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/honey-must...
7,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/creamy-spi...
8,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/chicken-pa...
9,bbc_good_food,chicken pasta,,https://www.bbcgoodfood.com/recipes/15-minute-...

Query: spaghetti
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=spaghetti
Status code: 200
HTML length: 885227
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/best-spagh...
1,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/ultimate-s...
2,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/spaghetti-...
3,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/prawn-hari...
4,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/spaghetti-...
5,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/next-level...
6,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/tuna-caper...
7,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/next-level...
8,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/next-level...
9,bbc_good_food,spaghetti,,https://www.bbcgoodfood.com/recipes/super-smok...

Query: alfredo pasta
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=alfredo+pasta
Status code: 200
HTML length: 942731
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/chicken-al...
1,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/chicken-sp...
2,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/baked-came...
3,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/cajun-chic...
4,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/chicken-al...
5,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/chicken-pa...
6,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/chicken-ba...
7,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/pasta-salm...
8,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/fajita-sty...
9,bbc_good_food,alfredo pasta,,https://www.bbcgoodfood.com/recipes/alfredo-sauce

Query: tomato pasta
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=tomato+pasta
Status code: 200
HTML length: 989704
Refined recipe links found: 25

,source_name,query,title_text,url
0,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/orzo-tomat...
1,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/frankie-pa...
2,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/sardine-to...
3,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/chunky-sau...
4,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/tuna-sundr...
5,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/baked-feta...
6,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/roasted-as...
7,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/pasta-toma...
8,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/tuna-tomat...
9,bbc_good_food,tomato pasta,,https://www.bbcgoodfood.com/recipes/cheese-tom...

Finished class: pasta
Unique BBC recipe links found: 101

====================================
Testing BBC links for class: rice
====================================

Query: rice
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=rice
Status code: 200
HTML length: 983688
Refined recipe links found: 24

,source_name,query,title_text,url
0,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/easiest-ev...
1,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/spicy-caul...
2,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/egg-fried-...
3,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/easy-pilau...
4,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/chicken-le...
5,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/a-nice-ric...
6,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/prawn-frie...
7,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/baked-rice...
8,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/fajita-chi...
9,bbc_good_food,rice,,https://www.bbcgoodfood.com/recipes/chicken-gi...

Query: fried rice
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=fried+rice
Status code: 200
HTML length: 980859
Refined recipe links found: 25

,source_name,query,title_text,url
0,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/egg-fried-...
1,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/prawn-frie...
2,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/chorizo-eg...
3,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/chicken-gi...
4,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/pineapple-...
5,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/salmon-egg...
6,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/sausage-so...
7,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/fridge-rai...
8,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/spiced-fri...
9,bbc_good_food,fried rice,,https://www.bbcgoodfood.com/recipes/eggy-fried...

Query: chicken rice
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=chicken+rice
Status code: 200
HTML length: 975590
Refined recipe links found: 23

,source_name,query,title_text,url
0,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/fajita-chi...
1,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/one-pot-ch...
2,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/spring-oni...
3,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/hainanese-...
4,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/satay-chic...
5,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/oven-baked...
6,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/creamy-cur...
7,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/creamy-chi...
8,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/miso-chick...
9,bbc_good_food,chicken rice,,https://www.bbcgoodfood.com/recipes/chinese-po...

Query: rice bowl
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=rice+bowl
Status code: 200
HTML length: 1007056
Refined recipe links found: 24

,source_name,query,title_text,url
0,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/fajita-chi...
1,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/satay-chic...
2,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/green-curr...
3,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/jerk-prawn...
4,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/easy-salmo...
5,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/peanut-chi...
6,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/japanese-s...
7,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/black-bean...
8,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/chicken-ri...
9,bbc_good_food,rice bowl,,https://www.bbcgoodfood.com/recipes/steamed-sa...

Query: vegetable rice
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=vegetable+rice
Status code: 200
HTML length: 995003
Refined recipe links found: 26

,source_name,query,title_text,url
0,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/root-veget...
1,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/chilli-con...
2,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/easiest-ev...
3,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/chunky-veg...
4,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/versatile-...
5,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/spicy-vege...
6,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/egg-fried-...
7,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/coriander-...
8,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/prawn-frie...
9,bbc_good_food,vegetable rice,,https://www.bbcgoodfood.com/recipes/mushroom-r...

Finished class: rice
Unique BBC recipe links found: 81

====================================
Testing BBC links for class: chicken
====================================

Query: chicken
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=chicken
Status code: 200
HTML length: 965638
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/chicken-ch...
1,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/chicken-pa...
2,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/chicken-korma
3,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/marry-me-c...
4,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/chicken-no...
5,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/chicken-ti...
6,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/thai-green...
7,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/chicken-sa...
8,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/chinese-ch...
9,bbc_good_food,chicken,,https://www.bbcgoodfood.com/recipes/chicken-ar...

Query: grilled chicken
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=grilled+chicken
Status code: 200
HTML length: 970349
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/cajun-gril...
1,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/grilled-ch...
2,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/grilled-ch...
3,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/tagliatell...
4,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/chicken-ch...
5,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/grilled-ch...
6,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/crunchy-be...
7,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/chicken-na...
8,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/grilled-pe...
9,bbc_good_food,grilled chicken,,https://www.bbcgoodfood.com/recipes/frango-chu...

Query: fried chicken
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=fried+chicken
Status code: 200
HTML length: 967750
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/korean-fri...
1,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/next-level...
2,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/pan-fried-...
3,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/korean-fri...
4,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/southern-f...
5,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/crispiest-...
6,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/stir-fried...
7,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/fried-chic...
8,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/buttermilk...
9,bbc_good_food,fried chicken,,https://www.bbcgoodfood.com/recipes/kentucky-f...

Query: chicken breast
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=chicken+breast
Status code: 200
HTML length: 961054
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/air-fryer-...
1,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/baked-chic...
2,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/baked-chic...
3,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/cheese-spi...
4,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/chicken-br...
5,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/poached-ch...
6,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/chicken-ch...
7,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/sweet-spic...
8,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/chicken-no...
9,bbc_good_food,chicken breast,,https://www.bbcgoodfood.com/recipes/chicken-korma

Query: roasted chicken
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=roasted+chicken
Status code: 200
HTML length: 979197
Refined recipe links found: 26

,source_name,query,title_text,url
0,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/classic-ro...
1,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/roast-chic...
2,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/air-fryer-...
3,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/roast-chic...
4,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/foolproof-...
5,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/roast-chic...
6,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/slow-cooke...
7,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/pot-roast-...
8,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/spring-one...
9,bbc_good_food,roasted chicken,,https://www.bbcgoodfood.com/recipes/roast-chic...

Finished class: chicken
Unique BBC recipe links found: 110

====================================
Testing BBC links for class: salad
====================================

Query: salad
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=salad
Status code: 200
HTML length: 999650
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/chicken-sa...
1,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/no-cook-ch...
2,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/epic-summe...
3,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/10minute-c...
4,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/halloumi-c...
5,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/greek-salad
6,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/salade-nic...
7,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/next-level...
8,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/tuna-aspar...
9,bbc_good_food,salad,,https://www.bbcgoodfood.com/recipes/allotment-...

Query: caesar salad
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=caesar+salad
Status code: 200
HTML length: 962412
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/caesar-sal...
1,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/chicken-ca...
2,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/next-level...
3,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/ultimate-m...
4,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/kale-caesa...
5,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/perfect-ca...
6,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/caesar-sal...
7,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/broccoli-c...
8,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/chargrille...
9,bbc_good_food,caesar salad,,https://www.bbcgoodfood.com/recipes/caesar-sal...

Query: chicken salad
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=chicken+salad
Status code: 200
HTML length: 977178
Refined recipe links found: 26

,source_name,query,title_text,url
0,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/green-chic...
1,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/chicken-sa...
2,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/asian-pull...
3,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/pesto-chic...
4,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/thai-mince...
5,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/chilli-lim...
6,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/shredded-c...
7,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/coronation...
8,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/asian-chic...
9,bbc_good_food,chicken salad,,https://www.bbcgoodfood.com/recipes/chicken-ch...

Query: green salad
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=green+salad
Status code: 200
HTML length: 1004217
Refined recipe links found: 24

,source_name,query,title_text,url
0,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/goats-chee...
1,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/green-sala...
2,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/green-sala...
3,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/shredded-g...
4,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/greek-salad
5,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/chopped-gr...
6,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/green-godd...
7,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/chilli-gre...
8,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/green-chic...
9,bbc_good_food,green salad,,https://www.bbcgoodfood.com/recipes/red-spiced...

Query: greek salad
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=greek+salad
Status code: 200
HTML length: 989401
Refined recipe links found: 23

,source_name,query,title_text,url
0,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/greek-salad
1,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/griddled-c...
2,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/greek-sala...
3,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/pork-souvl...
4,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/feta-cakes...
5,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/greek-sala...
6,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/simple-gre...
7,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/bean-feta-...
8,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/lamb-kebab...
9,bbc_good_food,greek salad,,https://www.bbcgoodfood.com/recipes/greek-sala...

Finished class: salad
Unique BBC recipe links found: 101

====================================
Testing BBC links for class: sandwich
====================================

Query: sandwich
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=sandwich
Status code: 200
HTML length: 947782
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/classic-vi...
1,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/coronation...
2,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/classic-sp...
3,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/caprese-sa...
4,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/next-level...
5,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/fried-chic...
6,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/elvis-sand...
7,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/panuozzo-s...
8,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/pastrami-s...
9,bbc_good_food,sandwich,,https://www.bbcgoodfood.com/recipes/tuna-salad...

Query: club sandwich
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=club+sandwich
Status code: 200
HTML length: 942624
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/egg-cress-...
1,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/club-sandwich
2,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/green-club...
3,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/mackerel-c...
4,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/salmon-clu...
5,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/kids-club-...
6,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/classic-vi...
7,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/coronation...
8,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/classic-sp...
9,bbc_good_food,club sandwich,,https://www.bbcgoodfood.com/recipes/the-breakf...

Query: chicken sandwich
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=chicken+sandwich
Status code: 200
HTML length: 968925
Refined recipe links found: 30

,source_name,query,title_text,url
0,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/caprese-ch...
1,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/coronation...
2,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/chicken-ch...
3,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/classic-vi...
4,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/fried-chic...
5,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/crispy-chi...
6,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/chicken-pa...
7,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/marry-me-c...
8,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/easy-coron...
9,bbc_good_food,chicken sandwich,,https://www.bbcgoodfood.com/recipes/chicken-korma

Query: grilled cheese sandwich
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=grilled+cheese+sandwich
Status code: 200
HTML length: 971883
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/quattro-fo...
1,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/classic-vi...
2,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/cauliflowe...
3,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/best-ever-...
4,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/classic-ch...
5,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/spinach-sq...
6,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/cheese-sauce
7,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/next-level...
8,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/reuben-san...
9,bbc_good_food,grilled cheese sandwich,,https://www.bbcgoodfood.com/recipes/eggy-chees...

Query: turkey sandwich
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=turkey+sandwich
Status code: 200
HTML length: 952105
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/classic-vi...
1,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/ultimate-t...
2,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/turkey-tik...
3,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/crispy-chi...
4,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/mediterran...
5,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/turkey-bol...
6,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/coronation...
7,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/ham-turkey...
8,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/tasty-turk...
9,bbc_good_food,turkey sandwich,,https://www.bbcgoodfood.com/recipes/roast-pota...

Finished class: sandwich
Unique BBC recipe links found: 107

====================================
Testing BBC links for class: sushi
====================================

Query: sushi
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=sushi
Status code: 200
HTML length: 859553
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/japanese-s...
1,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/easy-salmo...
2,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/quick-sush...
3,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/sesame-gin...
4,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/salmon-sus...
5,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/sushi-rice
6,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/simple-sushi
7,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/sushi-rice...
8,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/smoked-sal...
9,bbc_good_food,sushi,,https://www.bbcgoodfood.com/recipes/build-your...

Query: sushi roll
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=sushi+roll
Status code: 200
HTML length: 965520
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/salmon-cuc...
1,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/easy-bread...
2,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/kelp-smoke...
3,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/japanese-s...
4,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/next-level...
5,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/super-saus...
6,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/cinnamon-r...
7,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/vegetarian...
8,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/puff-pastr...
9,bbc_good_food,sushi roll,,https://www.bbcgoodfood.com/recipes/caramelise...

Query: california roll
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=california+roll
Status code: 200
HTML length: 969323
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/classic-ca...
1,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/easy-bread...
2,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/next-level...
3,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/super-saus...
4,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/cinnamon-r...
5,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/vegetarian...
6,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/puff-pastr...
7,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/caramelise...
8,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/california...
9,bbc_good_food,california roll,,https://www.bbcgoodfood.com/recipes/christmas-...

Query: tuna roll
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=tuna+roll
Status code: 200
HTML length: 968027
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/easy-bread...
1,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/next-level...
2,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/tuna-caper...
3,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/tuna-aspar...
4,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/super-saus...
5,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/tuna-pasta...
6,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/cinnamon-r...
7,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/vegetarian...
8,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/lemony-tun...
9,bbc_good_food,tuna roll,,https://www.bbcgoodfood.com/recipes/lentil-tun...

Query: salmon roll
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=salmon+roll
Status code: 200
HTML length: 970284
Refined recipe links found: 28

,source_name,query,title_text,url
0,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/double-sal...
1,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/salmon-cuc...
2,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/creamy-sal...
3,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/air-fryer-...
4,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/pasta-salm...
5,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/easy-bread...
6,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/super-easy...
7,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/teriyaki-s...
8,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/spiced-sal...
9,bbc_good_food,salmon roll,,https://www.bbcgoodfood.com/recipes/teriyaki-s...

Finished class: sushi
Unique BBC recipe links found: 92

====================================
Testing BBC links for class: steak
====================================

Query: steak
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=steak
Status code: 200
HTML length: 967042
Refined recipe links found: 23

,source_name,query,title_text,url
0,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/easy-steak...
1,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/steak-ale-pie
2,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/cauliflowe...
3,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/next-level...
4,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/air-fryer-...
5,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/spanish-po...
6,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/smoky-stea...
7,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/proper-bee...
8,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/one-pan-si...
9,bbc_good_food,steak,,https://www.bbcgoodfood.com/recipes/steak-blue...

Query: grilled steak
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=grilled+steak
Status code: 200
HTML length: 980677
Refined recipe links found: 24

,source_name,query,title_text,url
0,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/grilled-st...
1,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/grilled-st...
2,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/quick-stea...
3,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/easy-steak...
4,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/steak-ale-pie
5,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/crispy-gri...
6,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/cauliflowe...
7,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/next-level...
8,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/air-fryer-...
9,bbc_good_food,grilled steak,,https://www.bbcgoodfood.com/recipes/smoky-stea...

Query: beef steak
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=beef+steak
Status code: 200
HTML length: 955697
Refined recipe links found: 30

,source_name,query,title_text,url
0,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/beef-strog...
1,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/slow-cooke...
2,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/beef-goulash
3,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/crispy-chi...
4,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/beef-bourg...
5,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/beef-curry
6,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/cauliflowe...
7,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/air-fryer-...
8,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/easy-steak...
9,bbc_good_food,beef steak,,https://www.bbcgoodfood.com/recipes/next-level...

Query: sirloin steak
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=sirloin+steak
Status code: 200
HTML length: 961112
Refined recipe links found: 23

,source_name,query,title_text,url
0,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/one-pan-si...
1,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/simple-sir...
2,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/sirloin-st...
3,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/sirloin-st...
4,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/beef-strog...
5,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/sesame-ste...
6,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/easy-steak...
7,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/steak-aube...
8,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/next-level...
9,bbc_good_food,sirloin steak,,https://www.bbcgoodfood.com/recipes/steak-ale-pie

Query: steak dinner
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=steak+dinner
Status code: 200
HTML length: 988864
Refined recipe links found: 25

,source_name,query,title_text,url
0,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/easy-steak...
1,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/steak-ale-pie
2,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/sesame-ste...
3,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/next-level...
4,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/one-pan-si...
5,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/cauliflowe...
6,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/air-fryer-...
7,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/smoky-stea...
8,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/rump-steak
9,bbc_good_food,steak dinner,,https://www.bbcgoodfood.com/recipes/proper-bee...

Finished class: steak
Unique BBC recipe links found: 64

BBC link extraction test summary:

  food_class  unique_links_found
0     burger                  90
1      pizza                  69
2      fries                  72
3      pasta                 101
4       rice                  81
5    chicken                 110
6      salad                 101
7   sandwich                 107
8      sushi                  92
9      steak                  64

Classes with fewer than 50 links:

Empty DataFrame
Columns: [food_class, unique_links_found]
Index: []

In [10]:
# Cell 10 — Scrape BBC pilot records for all classes

def scrape_bbc_records_for_class(food_class, links_df, target_records=10):
    """
    Scrape valid BBC Good Food recipe records for one class.
    """
    records = []
    failed_urls = []

    print("Scraping class:", food_class)
    print("Available links:", len(links_df))
    print("Target records:", target_records)

    for idx, row in links_df.iterrows():
        if len(records) >= target_records:
            break

        url = row["url"]
        query = row["query"]

        print("\nScraping URL:")
        print(url)

        record = scrape_bbc_good_food_recipe(
            url=url,
            food_class=food_class,
            query=query
        )

        if record is None:
            failed_urls.append(url)
            print("Result: failed")
            continue

        ingredients_text = record.get("ingredients_text")
        calories = record.get("calories")

        has_required_fields = (
            record.get("recipe_name") is not None
            and ingredients_text is not None
            and len(ingredients_text) > 0
            and calories is not None
        )

        if has_required_fields:
            records.append(record)
            print("Result: success")
            print("Recipe:", record["recipe_name"])
            print("Calories:", record["calories"])
        else:
            failed_urls.append(url)
            print("Result: missing required fields")
            print("Recipe:", record.get("recipe_name"))
            print("Calories:", record.get("calories"))

    return records, failed_urls


all_bbc_pilot_records = []
all_bbc_pilot_failed_urls = []

for food_class in FOOD_CLASSES:
    print("\n====================================")
    print("Pilot scraping for class:", food_class)
    print("====================================")

    links_df = bbc_all_class_links[food_class]

    class_records, class_failed_urls = scrape_bbc_records_for_class(
        food_class=food_class,
        links_df=links_df,
        target_records=10
    )

    all_bbc_pilot_records.extend(class_records)

    for failed_url in class_failed_urls:
        all_bbc_pilot_failed_urls.append({
            "food_class": food_class,
            "failed_url": failed_url
        })

bbc_pilot_df = pd.DataFrame(all_bbc_pilot_records)
bbc_pilot_failed_df = pd.DataFrame(all_bbc_pilot_failed_urls)

print("\nBBC pilot scraping finished.")
print("Pilot dataset shape:", bbc_pilot_df.shape)

print("\nRecords per class:")
print(bbc_pilot_df["food_class"].value_counts())

print("\nFailed URLs:", len(bbc_pilot_failed_df))

bbc_pilot_output_path = SCRAPED_RAW_DIR / "bbc_text_calorie_pilot_raw.csv"
bbc_pilot_failed_path = LOGS_DIR / "bbc_pilot_failed_urls.csv"

bbc_pilot_df.to_csv(bbc_pilot_output_path, index=False)
bbc_pilot_failed_df.to_csv(bbc_pilot_failed_path, index=False)

print("\nPilot raw dataset saved to:")
print(bbc_pilot_output_path)

print("\nFailed URLs log saved to:")
print(bbc_pilot_failed_path)

display(bbc_pilot_df.head(10))

====================================
Pilot scraping for class: burger
====================================
Scraping class: burger
Available links: 90
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/burger-bowl
Result: success
Recipe: Burger bowl
Calories: 207.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/falafel-burgers-0
Result: success
Recipe: Falafel burgers
Calories: 175.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/15-minute-chicken-halloumi-burgers
Result: success
Recipe: 15-minute chicken & halloumi burgers
Calories: 737.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/the-big-double-cheeseburger-secret-sauce
Result: success
Recipe: The ultimate beef burger
Calories: 893.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-chicken-burgers
Result: success
Recipe: Next level chicken burgers
Calories: 794.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/superhealthy-salmon-burgers
Result: success
Recipe: Superhealthy salmon burgers
Calories: 292.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/smash-burgers
Result: success
Recipe: Smash burgers
Calories: 666.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/mexican-chicken-burger
Result: success
Recipe: Mexican chicken burger
Calories: 709.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/soft-burger-buns
Result: success
Recipe: Soft burger buns
Calories: 210.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/spiced-halloumi-pineapple-burger-zingy-slaw
Result: success
Recipe: Spiced halloumi & pineapple burger with zingy slaw
Calories: 264.0

====================================
Pilot scraping for class: pizza
====================================
Scraping class: pizza
Available links: 69
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-sauce
Result: success
Recipe: Pizza sauce
Calories: 120.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/quick-pizza-dough-2
Result: success
Recipe: Quick pizza dough
Calories: 656.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-margherita-4-easy-steps
Result: success
Recipe: Pizza Margherita in 4 easy steps
Calories: 431.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/basic-pizza-dough
Result: success
Recipe: Pizza dough
Calories: 504.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/no-yeast-pizza-dough
Result: success
Recipe: No yeast pizza dough
Calories: 352.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-homemade-sauce
Result: success
Recipe: Pizza with homemade sauce
Calories: 511.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/triple-cheese-pepperoni-jalapeno-pizza
Result: success
Recipe: Detroit-style pizza
Calories: 586.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/puff-pastry-pizzas
Request error: HTTPSConnectionPool(host='www.bbcgoodfood.com', port=443): Read timed out. (read timeout=20)
Result: failed

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-tikka-masala-naans
Result: success
Recipe: Chicken tikka masala pizzas
Calories: 683.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/tortilla-pizza
Request error: HTTPSConnectionPool(host='www.bbcgoodfood.com', port=443): Read timed out. (read timeout=20)
Result: failed

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-margherita-pizza
Result: success
Recipe: Next level Margherita pizza
Calories: 693.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/cookie-dough-pizza
Result: success
Recipe: Cookie dough pizza
Calories: 432.0

====================================
Pilot scraping for class: fries
====================================
Scraping class: fries
Available links: 72
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/korean-fried-chicken
Result: success
Recipe: Korean fried chicken
Calories: 487.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/egg-fried-rice
Result: success
Recipe: Easy egg-fried rice
Calories: 387.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-fried-chicken
Result: success
Recipe: Next level fried chicken
Calories: 556.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/prawn-fried-rice
Result: success
Recipe: Prawn fried rice
Calories: 418.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chorizo-egg-fried-rice
Result: success
Recipe: Chorizo egg-fried rice
Calories: 325.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-ginger-fried-rice
Result: success
Recipe: Chicken & ginger fried rice
Calories: 535.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/pineapple-fried-rice
Result: success
Recipe: Pineapple fried rice
Calories: 301.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/pan-fried-salmon
Result: success
Recipe: Pan-fried salmon
Calories: 386.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/pan-fried-chicken-mushroom-sauce
Result: success
Recipe: Pan-fried chicken in mushroom sauce
Calories: 600.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/salmon-egg-fried-rice
Result: success
Recipe: Salmon egg-fried rice
Calories: 432.0

====================================
Pilot scraping for class: pasta
====================================
Scraping class: pasta
Available links: 101
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-pasta-bake
Result: success
Recipe: Chicken pasta bake
Calories: 575.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/cajun-chicken-one-pot
Result: success
Recipe: Cajun chicken pasta
Calories: 555.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-bacon-pasta
Result: success
Recipe: Chicken & bacon pasta
Calories: 857.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/pasta-salmon-peas
Result: success
Recipe: Pasta with salmon & peas
Calories: 463.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/fajita-style-pasta
Result: success
Recipe: Fajita-style pasta
Calories: 395.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/pasta-alla-vodka
Result: success
Recipe: Pasta alla vodka
Calories: 866.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/orzo-tomato-soup
Result: success
Recipe: Tomato & pasta soup
Calories: 349.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/caponata-pasta
Result: success
Recipe: Caponata pasta
Calories: 542.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/creamy-mushroom-pasta
Result: success
Recipe: Creamy mushroom pasta
Calories: 801.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/creamy-garlic-pasta
Result: success
Recipe: Creamy garlic pasta
Calories: 699.0

====================================
Pilot scraping for class: rice
====================================
Scraping class: rice
Available links: 81
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/easiest-ever-paella
Result: success
Recipe: Easiest ever seafood rice
Calories: 593.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/spicy-cauliflower-halloumi-rice
Result: success
Recipe: Spicy cauliflower & halloumi rice
Calories: 337.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/egg-fried-rice
Result: success
Recipe: Easy egg-fried rice
Calories: 387.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/easy-pilau-rice
Result: success
Recipe: Easy pilau rice
Calories: 226.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-leek-brown-rice-stir-fry
Result: success
Recipe: Chicken, leek & brown rice stir-fry
Calories: 398.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/a-nice-rice-pudding
Result: success
Recipe: Rice pudding
Calories: 214.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/prawn-fried-rice
Result: success
Recipe: Prawn fried rice
Calories: 418.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/baked-rice-pudding
Result: success
Recipe: Classic rice pudding
Calories: 358.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/fajita-chicken-rice-bowl-with-burnt-lime
Result: success
Recipe: Fajita chicken rice bowl with burnt lime
Calories: 321.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-ginger-fried-rice
Result: success
Recipe: Chicken & ginger fried rice
Calories: 535.0

====================================
Pilot scraping for class: chicken
====================================
Scraping class: chicken
Available links: 110
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-chorizo-jambalaya
Result: success
Recipe: Chicken & chorizo jambalaya
Calories: 445.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-pasta-bake
Result: success
Recipe: Chicken pasta bake
Calories: 575.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-korma
Result: success
Recipe: Chicken korma
Calories: 376.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/marry-me-chicken
Result: success
Recipe: 'Marry me' chicken
Calories: 584.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-noodle-soup
Result: success
Recipe: Chicken noodle soup
Calories: 266.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-tikka-masala
Result: success
Recipe: Chicken tikka masala
Calories: 345.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/thai-green-chicken-curry
Result: success
Recipe: Thai green chicken curry
Calories: 275.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-satay-salad
Result: success
Recipe: Chicken satay salad
Calories: 353.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chinese-chicken-curry
Result: success
Recipe: Chinese chicken curry
Calories: 264.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-arrabbiata-stew-parmesan-dumplings
Result: success
Recipe: Chicken arrabbiata stew & parmesan dumplings
Calories: 512.0

====================================
Pilot scraping for class: salad
====================================
Scraping class: salad
Available links: 101
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-satay-salad
Result: success
Recipe: Chicken satay salad
Calories: 353.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/no-cook-chickpea-salad
Result: success
Recipe: Chickpea salad
Calories: 111.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/epic-summer-salad
Result: success
Recipe: Epic summer salad
Calories: 392.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/10minute-couscous-salad
Result: success
Recipe: 10-minute couscous salad
Calories: 468.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/halloumi-carrot-orange-salad
Result: success
Recipe: Halloumi, carrot & orange salad
Calories: 338.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/greek-salad
Result: success
Recipe: Greek salad
Calories: 211.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/salade-nicoise
Result: success
Recipe: Salade niçoise
Calories: 661.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-potato-salad
Result: success
Recipe: Next level potato salad
Calories: 310.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/tuna-asparagus-white-bean-salad
Result: success
Recipe: Tuna, asparagus & white bean salad
Calories: 245.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/allotment-salad
Result: success
Recipe: Allotment salad
Calories: 122.0

====================================
Pilot scraping for class: sandwich
====================================
Scraping class: sandwich
Available links: 107
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/classic-victoria-sandwich-recipe
Result: success
Recipe: Classic Victoria sandwich recipe
Calories: 507.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/coronation-chickpea-sandwich-filler
Result: success
Recipe: Coronation chickpea sandwich filler
Calories: 220.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/classic-sponge-sandwich
Result: success
Recipe: Classic sponge sandwich
Calories: 568.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/caprese-sandwich
Result: success
Recipe: Caprese sandwich
Calories: 462.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-steak-sandwich
Result: success
Recipe: Next level steak sandwich
Calories: 1166.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/fried-chicken-waffle-sandwich
Result: success
Recipe: Fried chicken waffle sandwich
Calories: 989.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/elvis-sandwich
Result: success
Recipe: Elvis sandwich
Calories: 952.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/panuozzo-sandwich
Result: success
Recipe: Panuozzo sandwich
Calories: 552.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/pastrami-sandwich
Result: success
Recipe: Pastrami sandwich
Calories: 867.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/tuna-salad-sandwich
Result: success
Recipe: Tuna salad sandwich
Calories: 474.0

====================================
Pilot scraping for class: sushi
====================================
Scraping class: sushi
Available links: 92
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/japanese-salmon-avocado-rice
Result: success
Recipe: Easy salmon sushi rice bowl
Calories: 713.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/easy-salmon-sushi-rice-bowl
Result: success
Recipe: Easy salmon sushi rice bowl
Calories: 713.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/quick-sushi-bowl
Result: success
Recipe: Quick sushi bowl
Calories: 498.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/sesame-ginger-sushi-bowls
Result: success
Recipe: Sesame & ginger sushi bowls
Calories: 449.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/salmon-sushi-salad
Result: success
Recipe: Salmon sushi salad
Calories: 862.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/sushi-rice
Result: success
Recipe: Perfect sushi rice
Calories: 432.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/simple-sushi
Result: success
Recipe: Simple sushi
Calories: 390.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/sushi-rice-bowl-beef-egg-chilli-sauce
Result: success
Recipe: Sushi rice bowl with beef, egg & chilli sauce
Calories: 621.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/smoked-salmon-avocado-sushi
Result: success
Recipe: Smoked salmon & avocado sushi
Calories: 49.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/build-your-own-salmon-sushi-burrito
Result: success
Recipe: Build-your-own salmon sushi burrito
Calories: 441.0

====================================
Pilot scraping for class: steak
====================================
Scraping class: steak
Available links: 64
Target records: 10

Scraping URL:
https://www.bbcgoodfood.com/recipes/easy-steak-pie
Result: success
Recipe: Easy steak pie
Calories: 611.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/steak-ale-pie
Result: success
Recipe: Next level steak & ale pie
Calories: 939.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/cauliflower-steaks-roasted-red-pepper-olive-salsa
Result: success
Recipe: Roasted cauliflower steaks
Calories: 277.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-steak-diane
Result: success
Recipe: Steak Diane
Calories: 402.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/air-fryer-steak
Result: success
Recipe: Air fryer steak
Calories: 523.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/spanish-pork-beans
Result: success
Recipe: Spanish pork shoulder steaks with beans
Calories: 454.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/smoky-steak-cajun-potatoes-spicy-slaw
Result: success
Recipe: Smoky steak with Cajun potatoes & spicy slaw
Calories: 802.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/proper-beef-ale-mushroom-pie
Result: success
Recipe: Steak, ale & mushroom pie
Calories: 1282.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/one-pan-sirloin-steak-creamy-mushroom-sauce
Result: success
Recipe: One-pan sirloin steak & creamy mushroom sauce
Calories: 1078.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/steak-blue-cheese-pie
Result: success
Recipe: Steak & blue cheese pie
Calories: 831.0

BBC pilot scraping finished.
Pilot dataset shape: (100, 11)

Records per class:
food_class
burger      10
pizza       10
fries       10
pasta       10
rice        10
chicken     10
salad       10
sandwich    10
sushi       10
steak       10
Name: count, dtype: int64

Failed URLs: 2

Pilot raw dataset saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/scraped_raw/bbc_text_calorie_pilot_raw.csv

Failed URLs log saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/logs/bbc_pilot_failed_urls.csv

,source_site,food_class,query,recipe_name,ingredients_text,calories,protein,fat,carbs,source_url,scraped_at
0,bbc_good_food,burger,burger,Burger bowl,2 large potatoes cut into rough chunks 2 tbsp ...,207.0,18.0,13.0,19.0,https://www.bbcgoodfood.com/recipes/burger-bowl,2026-05-12 00:11:07
1,bbc_good_food,burger,burger,Falafel burgers,400g can chickpeas rinsed and drained 1 small...,175.0,6.0,8.0,18.0,https://www.bbcgoodfood.com/recipes/falafel-bu...,2026-05-12 00:11:08
2,bbc_good_food,burger,burger,15-minute chicken & halloumi burgers,2 chicken breast fillets 1 tbsp oil plus extra...,737.0,39.0,42.0,49.0,https://www.bbcgoodfood.com/recipes/15-minute-...,2026-05-12 00:11:10
3,bbc_good_food,burger,burger,The ultimate beef burger,1 small onion finely chopped 4 sesame-topped ...,893.0,56.0,37.0,82.0,https://www.bbcgoodfood.com/recipes/the-big-do...,2026-05-12 00:11:11
4,bbc_good_food,burger,burger,Next level chicken burgers,2 large chicken breasts sunflower oil for deep...,794.0,33.0,33.0,90.0,https://www.bbcgoodfood.com/recipes/next-level...,2026-05-12 00:11:13
5,bbc_good_food,burger,burger,Superhealthy salmon burgers,"4 boneless, skinless salmon fillets about 550g...",292.0,29.0,17.0,7.0,https://www.bbcgoodfood.com/recipes/superhealt...,2026-05-12 00:11:15
6,bbc_good_food,burger,burger,Smash burgers,"4 burger buns sesame topped or brioche, whiche...",666.0,37.0,39.0,41.0,https://www.bbcgoodfood.com/recipes/smash-burgers,2026-05-12 00:11:17
7,bbc_good_food,burger,burger,Mexican chicken burger,1 chicken breast 1 tsp chipotle paste 1 lime j...,709.0,46.0,34.0,52.0,https://www.bbcgoodfood.com/recipes/mexican-ch...,2026-05-12 00:11:19
8,bbc_good_food,burger,burger,Soft burger buns,200ml whole milk plus extra for brushing 50g u...,210.0,6.0,5.0,35.0,https://www.bbcgoodfood.com/recipes/soft-burge...,2026-05-12 00:11:20
9,bbc_good_food,burger,burger,Spiced halloumi & pineapple burger with zingy ...,½ red cabbage grated 2 carrots grated 100g rad...,264.0,11.0,14.0,19.0,https://www.bbcgoodfood.com/recipes/spiced-hal...,2026-05-12 00:11:22

In [11]:
# Cell 11 — Relevance filtering rules for scraped recipe records

CLASS_KEYWORDS = {
    "burger": [
        "burger", "cheeseburger", "hamburger"
    ],
    "pizza": [
        "pizza", "pizzas"
    ],
    "fries": [
        "fries", "french fries", "chips", "loaded fries", "sweet potato fries"
    ],
    "pasta": [
        "pasta", "spaghetti", "alfredo", "penne", "lasagne", "lasagna",
        "tagliatelle", "fettuccine", "macaroni", "orzo"
    ],
    "rice": [
        "rice", "risotto", "paella", "pilau", "biryani", "jambalaya"
    ],
    "chicken": [
        "chicken"
    ],
    "salad": [
        "salad", "slaw"
    ],
    "sandwich": [
        "sandwich", "club sandwich", "toastie", "wrap", "bagel", "panini"
    ],
    "sushi": [
        "sushi", "maki", "nigiri", "sashimi", "sushi bowl", "sushi rice"
    ],
    "steak": [
        "steak", "sirloin", "ribeye", "beef steak"
    ]
}

CLASS_NEGATIVE_KEYWORDS = {
    "fries": [
        "fried rice", "fried chicken", "pan-fried", "stir-fried", "egg-fried rice"
    ],
    "sandwich": [
        "victoria sandwich", "sponge sandwich", "cake"
    ],
    "pizza": [
        "pizza sauce", "pizza dough"
    ],
    "steak": [
        "cauliflower steak", "cauliflower steaks"
    ],
    "sushi": [
        "bread roll", "sausage roll", "cinnamon roll"
    ]
}


def normalize_text_for_filtering(text):
    """
    Normalize text before relevance filtering.
    """
    if text is None:
        return ""
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9\s\-]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def is_relevant_record(record):
    """
    Decide whether a scraped record is relevant to its assigned food_class.
    Uses recipe name, source URL, and query text.
    """
    food_class = record.get("food_class")
    recipe_name = normalize_text_for_filtering(record.get("recipe_name"))
    source_url = normalize_text_for_filtering(record.get("source_url"))
    query = normalize_text_for_filtering(record.get("query"))

    combined_text = " ".join([recipe_name, source_url, query])

    positive_keywords = CLASS_KEYWORDS.get(food_class, [])
    negative_keywords = CLASS_NEGATIVE_KEYWORDS.get(food_class, [])

    for neg_kw in negative_keywords:
        if neg_kw in combined_text:
            return False

    for pos_kw in positive_keywords:
        if pos_kw in combined_text:
            return True

    return False


# Test relevance filtering on pilot dataset
bbc_pilot_df["is_relevant"] = bbc_pilot_df.apply(
    lambda row: is_relevant_record(row.to_dict()),
    axis=1
)

print("Pilot relevance summary:")
print(bbc_pilot_df.groupby("food_class")["is_relevant"].value_counts())

print("\nRejected pilot records:")
rejected_pilot_df = bbc_pilot_df[bbc_pilot_df["is_relevant"] == False]
display(rejected_pilot_df[[
    "food_class",
    "query",
    "recipe_name",
    "calories",
    "source_url"
]])

Pilot relevance summary:
food_class  is_relevant
burger      True           10
chicken     True           10
fries       False          10
pasta       True           10
pizza       True            6
            False           4
rice        True           10
salad       True           10
sandwich    True            8
            False           2
steak       True            9
            False           1
sushi       True           10
Name: count, dtype: int64

Rejected pilot records:

,food_class,query,recipe_name,calories,source_url
10,pizza,pizza,Pizza sauce,120.0,https://www.bbcgoodfood.com/recipes/pizza-sauce
11,pizza,pizza,Quick pizza dough,656.0,https://www.bbcgoodfood.com/recipes/quick-pizz...
13,pizza,pizza,Pizza dough,504.0,https://www.bbcgoodfood.com/recipes/basic-pizz...
14,pizza,pizza,No yeast pizza dough,352.0,https://www.bbcgoodfood.com/recipes/no-yeast-p...
20,fries,fries,Korean fried chicken,487.0,https://www.bbcgoodfood.com/recipes/korean-fri...
21,fries,fries,Easy egg-fried rice,387.0,https://www.bbcgoodfood.com/recipes/egg-fried-...
22,fries,fries,Next level fried chicken,556.0,https://www.bbcgoodfood.com/recipes/next-level...
23,fries,fries,Prawn fried rice,418.0,https://www.bbcgoodfood.com/recipes/prawn-frie...
24,fries,fries,Chorizo egg-fried rice,325.0,https://www.bbcgoodfood.com/recipes/chorizo-eg...
25,fries,fries,Chicken & ginger fried rice,535.0,https://www.bbcgoodfood.com/recipes/chicken-gi...
26,fries,fries,Pineapple fried rice,301.0,https://www.bbcgoodfood.com/recipes/pineapple-...
27,fries,fries,Pan-fried salmon,386.0,https://www.bbcgoodfood.com/recipes/pan-fried-...
28,fries,fries,Pan-fried chicken in mushroom sauce,600.0,https://www.bbcgoodfood.com/recipes/pan-fried-...
29,fries,fries,Salmon egg-fried rice,432.0,https://www.bbcgoodfood.com/recipes/salmon-egg...
70,sandwich,sandwich,Classic Victoria sandwich recipe,507.0,https://www.bbcgoodfood.com/recipes/classic-vi...
72,sandwich,sandwich,Classic sponge sandwich,568.0,https://www.bbcgoodfood.com/recipes/classic-sp...
92,steak,steak,Roasted cauliflower steaks,277.0,https://www.bbcgoodfood.com/recipes/cauliflowe...

In [12]:
# Cell 12 — Improve relevance filtering and fries search queries

# Replace weak fries queries with more precise UK/US terms
SEARCH_QUERIES["fries"] = [
    "french fries",
    "loaded fries",
    "sweet potato fries",
    "air fryer chips",
    "homemade chips",
    "potato wedges",
    "oven chips",
    "skinny fries"
]

# Update positive keywords for fries
CLASS_KEYWORDS["fries"] = [
    "fries",
    "french fries",
    "loaded fries",
    "sweet potato fries",
    "chips",
    "oven chips",
    "air fryer chips",
    "potato wedges",
    "wedges"
]

# Strengthen negative keywords
CLASS_NEGATIVE_KEYWORDS["fries"] = [
    "fried rice",
    "egg-fried rice",
    "prawn fried rice",
    "chorizo egg-fried rice",
    "chicken ginger fried rice",
    "pineapple fried rice",
    "salmon egg-fried rice",
    "fried chicken",
    "korean fried chicken",
    "next level fried chicken",
    "pan-fried",
    "stir-fried"
]

CLASS_NEGATIVE_KEYWORDS["pizza"] = [
    "pizza sauce",
    "pizza dough",
    "no yeast pizza dough",
    "basic pizza dough",
    "quick pizza dough"
]

CLASS_NEGATIVE_KEYWORDS["sandwich"] = [
    "victoria sandwich",
    "sponge sandwich",
    "cake"
]

CLASS_NEGATIVE_KEYWORDS["steak"] = [
    "cauliflower steak",
    "cauliflower steaks"
]


def is_relevant_record_v2(record):
    """
    Decide whether a scraped record is relevant to its assigned food_class.

    Important:
    This version does NOT use the query text for positive matching,
    because the query can make irrelevant results look relevant.
    """
    food_class = record.get("food_class")
    recipe_name = normalize_text_for_filtering(record.get("recipe_name"))
    source_url = normalize_text_for_filtering(record.get("source_url"))

    combined_text = " ".join([recipe_name, source_url])

    positive_keywords = CLASS_KEYWORDS.get(food_class, [])
    negative_keywords = CLASS_NEGATIVE_KEYWORDS.get(food_class, [])

    for neg_kw in negative_keywords:
        if neg_kw in combined_text:
            return False

    for pos_kw in positive_keywords:
        if pos_kw in combined_text:
            return True

    return False


# Apply improved filter on pilot dataset
bbc_pilot_df["is_relevant_v2"] = bbc_pilot_df.apply(
    lambda row: is_relevant_record_v2(row.to_dict()),
    axis=1
)

print("Pilot relevance summary with v2:")
print(bbc_pilot_df.groupby("food_class")["is_relevant_v2"].value_counts())

print("\nRejected pilot records with v2:")
rejected_pilot_v2_df = bbc_pilot_df[bbc_pilot_df["is_relevant_v2"] == False]
display(rejected_pilot_v2_df[[
    "food_class",
    "query",
    "recipe_name",
    "calories",
    "source_url"
]])

print("\nUpdated fries queries:")
for query in SEARCH_QUERIES["fries"]:
    print("-", query)

Pilot relevance summary with v2:
food_class  is_relevant_v2
burger      True              10
chicken     True              10
fries       False             10
pasta       True              10
pizza       True               6
            False              4
rice        True              10
salad       True              10
sandwich    True               8
            False              2
steak       True               9
            False              1
sushi       True              10
Name: count, dtype: int64

Rejected pilot records with v2:

,food_class,query,recipe_name,calories,source_url
10,pizza,pizza,Pizza sauce,120.0,https://www.bbcgoodfood.com/recipes/pizza-sauce
11,pizza,pizza,Quick pizza dough,656.0,https://www.bbcgoodfood.com/recipes/quick-pizz...
13,pizza,pizza,Pizza dough,504.0,https://www.bbcgoodfood.com/recipes/basic-pizz...
14,pizza,pizza,No yeast pizza dough,352.0,https://www.bbcgoodfood.com/recipes/no-yeast-p...
20,fries,fries,Korean fried chicken,487.0,https://www.bbcgoodfood.com/recipes/korean-fri...
21,fries,fries,Easy egg-fried rice,387.0,https://www.bbcgoodfood.com/recipes/egg-fried-...
22,fries,fries,Next level fried chicken,556.0,https://www.bbcgoodfood.com/recipes/next-level...
23,fries,fries,Prawn fried rice,418.0,https://www.bbcgoodfood.com/recipes/prawn-frie...
24,fries,fries,Chorizo egg-fried rice,325.0,https://www.bbcgoodfood.com/recipes/chorizo-eg...
25,fries,fries,Chicken & ginger fried rice,535.0,https://www.bbcgoodfood.com/recipes/chicken-gi...
26,fries,fries,Pineapple fried rice,301.0,https://www.bbcgoodfood.com/recipes/pineapple-...
27,fries,fries,Pan-fried salmon,386.0,https://www.bbcgoodfood.com/recipes/pan-fried-...
28,fries,fries,Pan-fried chicken in mushroom sauce,600.0,https://www.bbcgoodfood.com/recipes/pan-fried-...
29,fries,fries,Salmon egg-fried rice,432.0,https://www.bbcgoodfood.com/recipes/salmon-egg...
70,sandwich,sandwich,Classic Victoria sandwich recipe,507.0,https://www.bbcgoodfood.com/recipes/classic-vi...
72,sandwich,sandwich,Classic sponge sandwich,568.0,https://www.bbcgoodfood.com/recipes/classic-sp...
92,steak,steak,Roasted cauliflower steaks,277.0,https://www.bbcgoodfood.com/recipes/cauliflowe...

Updated fries queries:
- french fries
- loaded fries
- sweet potato fries
- air fryer chips
- homemade chips
- potato wedges
- oven chips
- skinny fries

In [14]:
# Cell 13 — Re-test BBC Good Food links for fries only using improved queries

print("Testing updated BBC links for fries")

fries_links_list = []

for query in SEARCH_QUERIES["fries"]:
    print("\nQuery:", query)

    links_df = extract_refined_recipe_links_from_search(
        source_name="bbc_good_food",
        query=query,
        max_links=15
    )

    if links_df is not None and not links_df.empty:
        fries_links_list.append(links_df)

    time.sleep(1)

if fries_links_list:
    fries_links_updated_df = pd.concat(fries_links_list, ignore_index=True)
    fries_links_updated_df = fries_links_updated_df.drop_duplicates(subset=["url"]).reset_index(drop=True)
else:
    fries_links_updated_df = pd.DataFrame(columns=["source_name", "query", "title_text", "url"])

print("\nUpdated fries links finished.")
print("Unique fries links found:", len(fries_links_updated_df))

display(fries_links_updated_df.head(30))

Testing updated BBC links for fries

Query: french fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=french+fries
Status code: 200
HTML length: 978393
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/air-fryer-...
1,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-fries
2,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/korean-fri...
3,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/egg-fried-...
4,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-oni...
5,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/beef-strog...
6,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/next-level...
7,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/meatball-m...
8,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/greek-load...
9,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-toast
10,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/prawn-frie...
11,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/chorizo-eg...
12,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/pineapple-...
13,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/chicken-gi...
14,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/chicken-ch...

Query: loaded fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=loaded+fries
Status code: 200
HTML length: 975665
Refined recipe links found: 25

,source_name,query,title_text,url
0,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/loaded-fries
1,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/greek-load...
2,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/korean-fri...
3,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/egg-fried-...
4,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/next-level...
5,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/meatball-m...
6,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/prawn-frie...
7,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/chorizo-eg...
8,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/pineapple-...
9,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/chicken-gi...
10,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/chicken-ch...
11,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/pan-fried-...
12,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/best-ever-...
13,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/vegan-bean...
14,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/sausage-so...

Query: sweet potato fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=sweet+potato+fries
Status code: 200
HTML length: 1014743
Refined recipe links found: 27

,source_name,query,title_text,url
0,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/sweet-pota...
1,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/air-fryer-...
2,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/steaks-gou...
3,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/roast-aube...
4,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/polenta-sw...
5,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/chimichurr...
6,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/satay-swee...
7,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/spinach-sw...
8,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/stir-fry-c...
9,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/piri-piri-...
10,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/ultimate-r...
11,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/sesame-sal...
12,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/sweet-pota...
13,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/lentil-swe...
14,bbc_good_food,sweet potato fries,,https://www.bbcgoodfood.com/recipes/roasted-sw...

Query: air fryer chips
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=air+fryer+chips
Status code: 200
HTML length: 979236
Refined recipe links found: 26

,source_name,query,title_text,url
0,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fried-...
1,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
2,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
3,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
4,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/vintage-ch...
5,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
6,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
7,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/chocolate-...
8,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
9,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
10,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
11,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
12,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
13,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...
14,bbc_good_food,air fryer chips,,https://www.bbcgoodfood.com/recipes/air-fryer-...

Query: homemade chips
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=homemade+chips
Status code: 200
HTML length: 984271
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/rib-eye-st...
1,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/vintage-ch...
2,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/oven-roast...
3,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/quick-roas...
4,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/ultimate-a...
5,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/chocolate-...
6,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/chocolate-...
7,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/homemade-h...
8,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/chocolate-...
9,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/chewy-choc...
10,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/homemade-t...
11,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/classic-ho...
12,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/chip-shop-...
13,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/good-you-g...
14,bbc_good_food,homemade chips,,https://www.bbcgoodfood.com/recipes/next-level...

Query: potato wedges
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=potato+wedges
Status code: 200
HTML length: 993374
Refined recipe links found: 29

,source_name,query,title_text,url
0,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/potato-wedges
1,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/air-fryer-...
2,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/paprika-po...
3,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/lean-turke...
4,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/tuna-melt-...
5,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/lemon-herb...
6,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/cajun-chic...
7,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/spiced-swe...
8,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/spiced-pot...
9,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/lemon-rose...
10,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/homemade-b...
11,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/sweet-pota...
12,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/waste-noth...
13,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/italian-po...
14,bbc_good_food,potato wedges,,https://www.bbcgoodfood.com/recipes/oven-pork-...

Query: oven chips
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=oven+chips
Status code: 200
HTML length: 989328
Refined recipe links found: 30

,source_name,query,title_text,url
0,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/chunky-ove...
1,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/indian-ove...
2,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/ultimate-o...
3,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/oven-roast...
4,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/celeriac-o...
5,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/quick-roas...
6,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/vintage-ch...
7,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/lighter-la...
8,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/oven-baked...
9,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/brilliant-...
10,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/grilled-ha...
11,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/oven-baked...
12,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/chocolate-...
13,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/spicy-oven...
14,bbc_good_food,oven chips,,https://www.bbcgoodfood.com/recipes/chocolate-...

Query: skinny fries
Source: bbc_good_food
Search URL: https://www.bbcgoodfood.com/search?q=skinny+fries
Status code: 200
HTML length: 974361
Refined recipe links found: 24

,source_name,query,title_text,url
0,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/baked-skin...
1,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/korean-fri...
2,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/egg-fried-...
3,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/next-level...
4,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/prawn-frie...
5,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/chorizo-eg...
6,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/pineapple-...
7,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/chicken-gi...
8,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/chicken-ch...
9,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/pan-fried-...
10,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/loaded-fries
11,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/sweet-pota...
12,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/sausage-so...
13,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/salmon-egg...
14,bbc_good_food,skinny fries,,https://www.bbcgoodfood.com/recipes/air-fryer-...

Updated fries links finished.
Unique fries links found: 151

,source_name,query,title_text,url
0,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/air-fryer-...
1,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-fries
2,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/korean-fri...
3,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/egg-fried-...
4,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-oni...
5,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/beef-strog...
6,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/next-level...
7,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/meatball-m...
8,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/greek-load...
9,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-toast
10,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/prawn-frie...
11,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/chorizo-eg...
12,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/pineapple-...
13,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/chicken-gi...
14,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/chicken-ch...
15,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/pan-fried-...
16,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/pan-fried-...
17,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/pan-fried-...
18,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/loaded-fries
19,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/vegan-bean...
20,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/french-app...
21,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/sweet-pota...
22,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/sausage-so...
23,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/air-fryer-...
24,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/salmon-egg...
25,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/fridge-rai...
26,bbc_good_food,french fries,,https://www.bbcgoodfood.com/recipes/peanut-but...
27,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/best-ever-...
28,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/korean-fri...
29,bbc_good_food,loaded fries,,https://www.bbcgoodfood.com/recipes/spiced-fri...

In [15]:
# Cell 14 — Test scraping relevant fries records only

fries_test_records = []
fries_test_rejected = []
fries_test_failed = []

for idx, row in fries_links_updated_df.iterrows():
    if len(fries_test_records) >= 10:
        break

    url = row["url"]
    query = row["query"]

    print("\nScraping URL:")
    print(url)

    record = scrape_bbc_good_food_recipe(
        url=url,
        food_class="fries",
        query=query
    )

    if record is None:
        fries_test_failed.append(url)
        print("Result: failed")
        continue

    if is_relevant_record_v2(record):
        fries_test_records.append(record)
        print("Result: relevant")
        print("Recipe:", record["recipe_name"])
        print("Calories:", record["calories"])
    else:
        fries_test_rejected.append(record)
        print("Result: rejected")
        print("Recipe:", record["recipe_name"])

fries_test_df = pd.DataFrame(fries_test_records)
fries_rejected_df = pd.DataFrame(fries_test_rejected)

print("\nFries relevance scraping test finished.")
print("Relevant fries records:", len(fries_test_df))
print("Rejected fries records:", len(fries_rejected_df))
print("Failed URLs:", len(fries_test_failed))

if not fries_test_df.empty:
    display(fries_test_df[[
        "food_class",
        "query",
        "recipe_name",
        "calories",
        "source_url"
    ]])

if not fries_rejected_df.empty:
    print("\nRejected examples:")
    display(fries_rejected_df[[
        "food_class",
        "query",
        "recipe_name",
        "calories",
        "source_url"
    ]].head(10))

Scraping URL:
https://www.bbcgoodfood.com/recipes/air-fryer-french-fries
Result: relevant
Recipe: Air fryer French fries
Calories: 204.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/french-fries
Result: relevant
Recipe: French fries
Calories: 317.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/korean-fried-chicken
Result: rejected
Recipe: Korean fried chicken

Scraping URL:
https://www.bbcgoodfood.com/recipes/egg-fried-rice
Result: rejected
Recipe: Easy egg-fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/french-onion-soup
Result: rejected
Recipe: French onion soup

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-stroganoff
Result: rejected
Recipe: Beef stroganoff

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-fried-chicken
Result: rejected
Recipe: Next level fried chicken

Scraping URL:
https://www.bbcgoodfood.com/recipes/meatball-marinara-fries
Result: relevant
Recipe: Meatball marinara fries
Calories: 399.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/greek-loaded-fries
Result: relevant
Recipe: Feta, tomato & olive loaded fries
Calories: 290.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/french-toast
Result: rejected
Recipe: French toast

Scraping URL:
https://www.bbcgoodfood.com/recipes/prawn-fried-rice
Result: rejected
Recipe: Prawn fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/chorizo-egg-fried-rice
Result: rejected
Recipe: Chorizo egg-fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/pineapple-fried-rice
Result: rejected
Recipe: Pineapple fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-ginger-fried-rice
Result: rejected
Recipe: Chicken & ginger fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-chorizo-jambalaya
Result: rejected
Recipe: Chicken & chorizo jambalaya

Scraping URL:
https://www.bbcgoodfood.com/recipes/pan-fried-salmon
Result: rejected
Recipe: Pan-fried salmon

Scraping URL:
https://www.bbcgoodfood.com/recipes/pan-fried-chicken-mushroom-sauce
Result: rejected
Recipe: Pan-fried chicken in mushroom sauce

Scraping URL:
https://www.bbcgoodfood.com/recipes/pan-fried-pork-creme-fraiche-prunes
Result: rejected
Recipe: Pan-fried pork with crème fraîche & prunes

Scraping URL:
https://www.bbcgoodfood.com/recipes/loaded-fries
Result: relevant
Recipe: Loaded fries
Calories: 415.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/vegan-bean-chilli-fries
Result: relevant
Recipe: Vegan bean chilli fries
Calories: 428.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/french-apple-tart
Result: rejected
Recipe: French apple tart

Scraping URL:
https://www.bbcgoodfood.com/recipes/sweet-potato-fries
Result: relevant
Recipe: Sweet potato fries
Calories: 120.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/sausage-soy-fried-rice
Result: rejected
Recipe: Sausage & soy fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/air-fryer-sweet-potato-fries
Result: relevant
Recipe: Air fryer sweet potato fries
Calories: 244.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/salmon-egg-fried-rice
Result: rejected
Recipe: Salmon egg-fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/fridge-raid-fried-rice
Result: rejected
Recipe: Fridge-raid fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/peanut-butter-stuffed-french-toast
Result: rejected
Recipe: Peanut butter-stuffed French toast

Scraping URL:
https://www.bbcgoodfood.com/recipes/best-ever-oven-chips
Result: relevant
Recipe: Loaded chips ideas
Calories: 409.0

Scraping URL:
https://www.bbcgoodfood.com/recipes/korean-fried-chicken-burgers
Result: rejected
Recipe: Korean fried chicken burgers

Scraping URL:
https://www.bbcgoodfood.com/recipes/spiced-fried-rice-with-sausage
Result: rejected
Recipe: Spiced fried rice with sausage

Scraping URL:
https://www.bbcgoodfood.com/recipes/thai-fried-prawn-pineapple-rice
Result: rejected
Recipe: Thai fried prawn & pineapple rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/eggy-fried-rice
Result: rejected
Recipe: Eggy fried rice

Scraping URL:
https://www.bbcgoodfood.com/recipes/loaded-potato-skins
Result: rejected
Recipe: Loaded potato skins

Scraping URL:
https://www.bbcgoodfood.com/recipes/steaks-goulash-sauce-sweet-potato-fries
Result: relevant
Recipe: Steaks with goulash sauce & sweet potato fries
Calories: 452.0

Fries relevance scraping test finished.
Relevant fries records: 10
Rejected fries records: 24
Failed URLs: 0

,food_class,query,recipe_name,calories,source_url
0,fries,french fries,Air fryer French fries,204.0,https://www.bbcgoodfood.com/recipes/air-fryer-...
1,fries,french fries,French fries,317.0,https://www.bbcgoodfood.com/recipes/french-fries
2,fries,french fries,Meatball marinara fries,399.0,https://www.bbcgoodfood.com/recipes/meatball-m...
3,fries,french fries,"Feta, tomato & olive loaded fries",290.0,https://www.bbcgoodfood.com/recipes/greek-load...
4,fries,french fries,Loaded fries,415.0,https://www.bbcgoodfood.com/recipes/loaded-fries
5,fries,french fries,Vegan bean chilli fries,428.0,https://www.bbcgoodfood.com/recipes/vegan-bean...
6,fries,french fries,Sweet potato fries,120.0,https://www.bbcgoodfood.com/recipes/sweet-pota...
7,fries,french fries,Air fryer sweet potato fries,244.0,https://www.bbcgoodfood.com/recipes/air-fryer-...
8,fries,loaded fries,Loaded chips ideas,409.0,https://www.bbcgoodfood.com/recipes/best-ever-...
9,fries,sweet potato fries,Steaks with goulash sauce & sweet potato fries,452.0,https://www.bbcgoodfood.com/recipes/steaks-gou...

Rejected examples:

,food_class,query,recipe_name,calories,source_url
0,fries,french fries,Korean fried chicken,487.0,https://www.bbcgoodfood.com/recipes/korean-fri...
1,fries,french fries,Easy egg-fried rice,387.0,https://www.bbcgoodfood.com/recipes/egg-fried-...
2,fries,french fries,French onion soup,618.0,https://www.bbcgoodfood.com/recipes/french-oni...
3,fries,french fries,Beef stroganoff,438.0,https://www.bbcgoodfood.com/recipes/beef-strog...
4,fries,french fries,Next level fried chicken,556.0,https://www.bbcgoodfood.com/recipes/next-level...
5,fries,french fries,French toast,401.0,https://www.bbcgoodfood.com/recipes/french-toast
6,fries,french fries,Prawn fried rice,418.0,https://www.bbcgoodfood.com/recipes/prawn-frie...
7,fries,french fries,Chorizo egg-fried rice,325.0,https://www.bbcgoodfood.com/recipes/chorizo-eg...
8,fries,french fries,Pineapple fried rice,301.0,https://www.bbcgoodfood.com/recipes/pineapple-...
9,fries,french fries,Chicken & ginger fried rice,535.0,https://www.bbcgoodfood.com/recipes/chicken-gi...

In [16]:
# Cell 15 — Final BBC scraped dataset collection

# Replace fries links with the improved fries links
bbc_all_class_links["fries"] = fries_links_updated_df

def scrape_final_bbc_records_for_class(food_class, links_df, target_records=50):
    """
    Scrape final relevant BBC Good Food records for one class.
    Keeps only records that pass relevance filtering.
    """
    records = []
    failed_urls = []
    rejected_records = []
    seen_urls = set()

    print("Final scraping class:", food_class)
    print("Available links:", len(links_df))
    print("Target records:", target_records)

    for idx, row in links_df.iterrows():
        if len(records) >= target_records:
            break

        url = row["url"]
        query = row["query"]

        if url in seen_urls:
            continue

        seen_urls.add(url)

        print("\nScraping URL:")
        print(url)

        record = scrape_bbc_good_food_recipe(
            url=url,
            food_class=food_class,
            query=query
        )

        if record is None:
            failed_urls.append({
                "food_class": food_class,
                "query": query,
                "url": url,
                "reason": "scrape_failed"
            })
            print("Result: failed")
            continue

        ingredients_text = record.get("ingredients_text")
        calories = record.get("calories")

        has_required_fields = (
            record.get("recipe_name") is not None
            and ingredients_text is not None
            and len(ingredients_text) > 0
            and calories is not None
        )

        if not has_required_fields:
            failed_urls.append({
                "food_class": food_class,
                "query": query,
                "url": url,
                "reason": "missing_required_fields"
            })
            print("Result: missing required fields")
            continue

        if not is_relevant_record_v2(record):
            rejected_records.append(record)
            print("Result: rejected")
            print("Recipe:", record.get("recipe_name"))
            continue

        records.append(record)
        print("Result: accepted")
        print("Recipe:", record["recipe_name"])
        print("Calories:", record["calories"])
        print("Collected so far:", len(records), "/", target_records)

    return records, failed_urls, rejected_records


final_bbc_records = []
final_failed_urls = []
final_rejected_records = []

for food_class in FOOD_CLASSES:
    print("\n====================================")
    print("Final scraping for class:", food_class)
    print("====================================")

    links_df = bbc_all_class_links[food_class]

    class_records, class_failed_urls, class_rejected_records = scrape_final_bbc_records_for_class(
        food_class=food_class,
        links_df=links_df,
        target_records=TARGET_RECORDS_PER_CLASS
    )

    final_bbc_records.extend(class_records)
    final_failed_urls.extend(class_failed_urls)
    final_rejected_records.extend(class_rejected_records)

    print("\nClass finished:", food_class)
    print("Accepted records:", len(class_records))
    print("Failed URLs:", len(class_failed_urls))
    print("Rejected records:", len(class_rejected_records))

final_bbc_df = pd.DataFrame(final_bbc_records)
final_failed_df = pd.DataFrame(final_failed_urls)
final_rejected_df = pd.DataFrame(final_rejected_records)

print("\nFinal BBC scraping finished.")
print("Final dataset shape:", final_bbc_df.shape)

print("\nRecords per class:")
print(final_bbc_df["food_class"].value_counts())

print("\nFailed URLs:", len(final_failed_df))
print("Rejected records:", len(final_rejected_df))

final_raw_output_path = SCRAPED_RAW_DIR / "bbc_text_calorie_final_raw.csv"
final_failed_output_path = LOGS_DIR / "bbc_final_failed_urls.csv"
final_rejected_output_path = LOGS_DIR / "bbc_final_rejected_records.csv"

final_bbc_df.to_csv(final_raw_output_path, index=False)
final_failed_df.to_csv(final_failed_output_path, index=False)
final_rejected_df.to_csv(final_rejected_output_path, index=False)

print("\nFinal raw dataset saved to:")
print(final_raw_output_path)

print("\nFailed URLs log saved to:")
print(final_failed_output_path)

print("\nRejected records log saved to:")
print(final_rejected_output_path)

display(final_bbc_df.head(10))

====================================
Final scraping for class: burger
====================================
Final scraping class: burger
Available links: 90
Target records: 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/burger-bowl
Result: accepted
Recipe: Burger bowl
Calories: 207.0
Collected so far: 1 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/falafel-burgers-0
Result: accepted
Recipe: Falafel burgers
Calories: 175.0
Collected so far: 2 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/15-minute-chicken-halloumi-burgers
Result: accepted
Recipe: 15-minute chicken & halloumi burgers
Calories: 737.0
Collected so far: 3 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/the-big-double-cheeseburger-secret-sauce
Result: accepted
Recipe: The ultimate beef burger
Calories: 893.0
Collected so far: 4 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-chicken-burgers
Result: accepted
Recipe: Next level chicken burgers
Calories: 794.0
Collected so far: 5 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/superhealthy-salmon-burgers
Result: accepted
Recipe: Superhealthy salmon burgers
Calories: 292.0
Collected so far: 6 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/smash-burgers
Result: accepted
Recipe: Smash burgers
Calories: 666.0
Collected so far: 7 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/mexican-chicken-burger
Result: accepted
Recipe: Mexican chicken burger
Calories: 709.0
Collected so far: 8 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/soft-burger-buns
Result: accepted
Recipe: Soft burger buns
Calories: 210.0
Collected so far: 9 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/spiced-halloumi-pineapple-burger-zingy-slaw
Result: accepted
Recipe: Spiced halloumi & pineapple burger with zingy slaw
Calories: 264.0
Collected so far: 10 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/prawn-salmon-burgers-spicy-mayo
Result: accepted
Recipe: Prawn & salmon burgers with spicy mayo
Calories: 504.0
Collected so far: 11 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/halloumi-burgers
Result: accepted
Recipe: Halloumi burgers
Calories: 455.0
Collected so far: 12 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/chickpea-coriander-burgers
Result: accepted
Recipe: Chickpea & coriander burgers
Calories: 344.0
Collected so far: 13 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/miso-mushroom-halloumi-burgers
Result: accepted
Recipe: Miso mushroom & halloumi burgers
Calories: 452.0
Collected so far: 14 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/green-burgers
Result: accepted
Recipe: Green burgers
Calories: 233.0
Collected so far: 15 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/fully-loaded-cajun-chicken-burgers
Result: accepted
Recipe: Cajun chicken burgers
Calories: 721.0
Collected so far: 16 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/korean-fried-chicken-burgers
Result: accepted
Recipe: Korean fried chicken burgers
Calories: 415.0
Collected so far: 17 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/lean-turkey-burger-sweet-potato-wedges
Result: accepted
Recipe: Turkey burger with sweet potato wedges
Calories: 428.0
Collected so far: 18 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/classic-burger-sauce
Result: accepted
Recipe: Classic burger sauce
Calories: 61.0
Collected so far: 19 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/molten-cheese-stuffed-burgers
Result: accepted
Recipe: Molten cheese-stuffed burgers
Calories: 654.0
Collected so far: 20 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pork-apple-burgers
Result: accepted
Recipe: Pork & apple burgers
Calories: 364.0
Collected so far: 21 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/crispiest-buttermilk-fried-chicken-burgers
Result: accepted
Recipe: Crispiest buttermilk fried chicken burgers
Calories: 522.0
Collected so far: 22 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/sriracha-glazed-chicken-burger-pickled-cabbage
Result: accepted
Recipe: Sriracha-glazed chicken burger & pickled cabbage
Calories: 577.0
Collected so far: 23 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/swedish-meatball-burgers
Result: accepted
Recipe: Swedish meatball burgers
Calories: 175.0
Collected so far: 24 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/one-pot-cheeseburger-pasta
Result: accepted
Recipe: One-pot cheeseburger pasta
Calories: 687.0
Collected so far: 25 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/nacho-cheeseburger
Result: accepted
Recipe: Nacho cheeseburger
Calories: 667.0
Collected so far: 26 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/cheeseburger-chips
Result: accepted
Recipe: Cheeseburger & chips
Calories: 558.0
Collected so far: 27 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/cheeseburgers-0
Result: accepted
Recipe: Cheeseburgers
Calories: 343.0
Collected so far: 28 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/veg-packed-cheeseburgers
Result: accepted
Recipe: Veg-packed cheeseburgers
Calories: 509.0
Collected so far: 29 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/cheeseburger-hot-dogs-with-sticky-sweet-sour-onions
Result: accepted
Recipe: Cheeseburger hot dogs with sticky sweet & sour onions
Calories: 678.0
Collected so far: 30 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/french-onion-cheeseburger
Result: accepted
Recipe: French onion cheeseburger
Calories: 700.0
Collected so far: 31 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/cheeseburgers
Result: accepted
Recipe: Best cheeseburgers
Calories: 723.0
Collected so far: 32 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pork-thyme-cheeseburgers
Result: accepted
Recipe: Pork & thyme cheeseburgers
Calories: 508.0
Collected so far: 33 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/tex-mex-burger
Result: accepted
Recipe: Tex-Mex burger
Calories: 589.0
Collected so far: 34 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/really-easy-beefburgers
Result: accepted
Recipe: Really easy beefburgers
Calories: 496.0
Collected so far: 35 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/great-breakfast-burger
Result: accepted
Recipe: The great breakfast burger
Calories: 801.0
Collected so far: 36 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-burgers-learn-make
Result: accepted
Recipe: Homemade beef burgers
Calories: 562.0
Collected so far: 37 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/barbecue-beef-burger
Result: accepted
Recipe: Barbecue beef burger
Calories: 248.0
Collected so far: 38 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-burger-sweet-potato-chilli-chips
Result: accepted
Recipe: Beef burger with sweet potato chilli chips
Calories: 467.0
Collected so far: 39 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-stroganoff
Result: rejected
Recipe: Beef stroganoff

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-red-pepper-burgers
Result: accepted
Recipe: Beef & red pepper burgers
Calories: 199.0
Collected so far: 40 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/beer-battered-fish-burgers
Result: accepted
Recipe: Beer-battered fish burgers
Calories: 716.0
Collected so far: 41 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/harissa-beef-tomato-bulgur
Result: rejected
Recipe: Harissa beef & tomato bulgur

Scraping URL:
https://www.bbcgoodfood.com/recipes/slow-cooker-beef-stew
Result: rejected
Recipe: Slow-cooker beef stew

Scraping URL:
https://www.bbcgoodfood.com/recipes/braised-beef-onepot
Result: rejected
Recipe: Chinese-style braised beef one-pot

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-salsa-burgers
Result: accepted
Recipe: Beef & salsa burgers
Calories: 313.0
Collected so far: 42 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-curry
Result: rejected
Recipe: Beef curry

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-vegetable-casserole
Result: rejected
Recipe: Beef stew

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-goulash
Result: rejected
Recipe: Beef goulash

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-bourguignon
Result: rejected
Recipe: Beef bourguignon

Scraping URL:
https://www.bbcgoodfood.com/recipes/crispy-chilli-beef
Result: rejected
Recipe: Crispy chilli beef

Scraping URL:
https://www.bbcgoodfood.com/recipes/slow-cooker-beef-bourguignon
Result: rejected
Recipe: Slow cooker beef bourguignon

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-enchiladas
Result: rejected
Recipe: Beef enchiladas

Scraping URL:
https://www.bbcgoodfood.com/recipes/beef-wellington
Result: rejected
Recipe: Beef wellington

Scraping URL:
https://www.bbcgoodfood.com/recipes/porcini-buttered-roast-beef-sirloin-with-pickled-peppercorn-sauce
Result: rejected
Recipe: Porcini-buttered roast beef sirloin with pickled peppercorn sauce

Scraping URL:
https://www.bbcgoodfood.com/recipes/jerk-chicken-burger
Result: accepted
Recipe: Jerk chicken burger
Calories: 417.0
Collected so far: 43 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/crispy-japanese-style-chicken-burgers
Result: accepted
Recipe: Crispy Japanese-style chicken burgers
Calories: 715.0
Collected so far: 44 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/buffalo-chicken-burgers-ranch-slaw
Result: accepted
Recipe: Buffalo chicken burgers & ranch slaw
Calories: 744.0
Collected so far: 45 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/bbq-chicken-burgers
Result: accepted
Recipe: BBQ chicken burgers
Calories: 406.0
Collected so far: 46 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/crisp-chicken-burgers-lemon-mayo
Result: accepted
Recipe: Crisp chicken burgers with lemon mayo
Calories: 396.0
Collected so far: 47 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/italian-style-chicken-burger-chips
Result: accepted
Recipe: Italian-style chicken burger & chips
Calories: 495.0
Collected so far: 48 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/peanut-butter-chicken
Result: rejected
Recipe: Peanut butter chicken

Scraping URL:
https://www.bbcgoodfood.com/recipes/easy-butter-chicken
Result: rejected
Recipe: Easy butter chicken

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-chorizo-jambalaya
Result: rejected
Recipe: Chicken & chorizo jambalaya

Scraping URL:
https://www.bbcgoodfood.com/recipes/classic-butter-chicken
Result: rejected
Recipe: Classic butter chicken

Scraping URL:
https://www.bbcgoodfood.com/recipes/old-delhi-style-butter-chicken
Result: rejected
Recipe: Old Delhi-style butter chicken

Scraping URL:
https://www.bbcgoodfood.com/recipes/peanut-butter-chicken-curry
Result: rejected
Recipe: Peanut butter chicken curry

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-katsu-curry-burger
Result: accepted
Recipe: Chicken katsu curry burger
Calories: 1080.0
Collected so far: 49 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/slow-cooker-butter-chicken
Result: rejected
Recipe: Slow-cooker butter chicken

Scraping URL:
https://www.bbcgoodfood.com/recipes/cardamom-butter-chicken
Result: rejected
Recipe: Cardamom butter chicken

Scraping URL:
https://www.bbcgoodfood.com/recipes/caesar-brussels-slaw-parmesan-chicken-schnitzel-burgers
Result: accepted
Recipe: Caesar brussels slaw & parmesan chicken schnitzel burgers
Calories: 855.0
Collected so far: 50 / 50

Class finished: burger
Accepted records: 50
Failed URLs: 0
Rejected records: 21

====================================
Final scraping for class: pizza
====================================
Final scraping class: pizza
Available links: 69
Target records: 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-sauce
Result: rejected
Recipe: Pizza sauce

Scraping URL:
https://www.bbcgoodfood.com/recipes/quick-pizza-dough-2
Result: rejected
Recipe: Quick pizza dough

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-margherita-4-easy-steps
Result: accepted
Recipe: Pizza Margherita in 4 easy steps
Calories: 431.0
Collected so far: 1 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/basic-pizza-dough
Result: rejected
Recipe: Pizza dough

Scraping URL:
https://www.bbcgoodfood.com/recipes/no-yeast-pizza-dough
Result: rejected
Recipe: No yeast pizza dough

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-homemade-sauce
Result: accepted
Recipe: Pizza with homemade sauce
Calories: 511.0
Collected so far: 2 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/triple-cheese-pepperoni-jalapeno-pizza
Result: accepted
Recipe: Detroit-style pizza
Calories: 586.0
Collected so far: 3 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/puff-pastry-pizzas
Result: accepted
Recipe: Puff pastry pizzas
Calories: 357.0
Collected so far: 4 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/chicken-tikka-masala-naans
Result: accepted
Recipe: Chicken tikka masala pizzas
Calories: 683.0
Collected so far: 5 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/tortilla-pizza
Result: accepted
Recipe: Tortilla pizza
Calories: 266.0
Collected so far: 6 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-margherita-pizza
Result: accepted
Recipe: Next level Margherita pizza
Calories: 693.0
Collected so far: 7 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/cookie-dough-pizza
Result: accepted
Recipe: Cookie dough pizza
Calories: 432.0
Collected so far: 8 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/sourdough-pizza
Result: accepted
Recipe: Sourdough pizza
Calories: 502.0
Collected so far: 9 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/egg-rocket-pizzas
Result: accepted
Recipe: Egg & rocket pizzas
Calories: 327.0
Collected so far: 10 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/gluten-free-pizza
Result: accepted
Recipe: Gluten-free pizza
Calories: 740.0
Collected so far: 11 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/vegan-pizza-margherita
Result: accepted
Recipe: Vegan pizza Margherita
Calories: 688.0
Collected so far: 12 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/hummus-flatbread-pizzas-with-roasted-veg
Result: accepted
Recipe: Hummus flatbread pizzas with roasted veg
Calories: 423.0
Collected so far: 13 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-fondue-dip
Result: accepted
Recipe: Pizza fondue dip
Calories: 166.0
Collected so far: 14 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pepperoni-pizza-rolls
Result: accepted
Recipe: Pepperoni pizza rolls
Calories: 319.0
Collected so far: 15 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pitta-pizzas-0
Result: accepted
Recipe: Pitta pizzas
Calories: 379.0
Collected so far: 16 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza
Result: accepted
Recipe: Pizza
Calories: 446.0
Collected so far: 17 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/cauliflower-crust-pizza
Result: accepted
Recipe: Cauliflower crust pizza
Calories: 463.0
Collected so far: 18 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/superhealthy-pizza
Result: accepted
Recipe: Superhealthy pizza
Calories: 479.0
Collected so far: 19 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-pie-2
Result: accepted
Recipe: Pizza pie
Calories: 390.0
Collected so far: 20 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/very-simple-margherita-pizza
Result: accepted
Recipe: Very simple Margherita pizza
Calories: 577.0
Collected so far: 21 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/keto-pizza
Result: accepted
Recipe: Keto pizza
Calories: 402.0
Collected so far: 22 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/spinach-blue-cheese-pizza
Result: accepted
Recipe: Spinach & blue cheese pizza
Calories: 462.0
Collected so far: 23 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/mozzarella-stuffed-crust-pizza
Result: accepted
Recipe: Mozzarella stuffed crust pizza
Calories: 573.0
Collected so far: 24 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-pie
Result: accepted
Recipe: Pepperoni pizza pie
Calories: 401.0
Collected so far: 25 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/potato-chorizo-pizza-breads-peppery-tomato-salad
Result: accepted
Recipe: Potato & chorizo pizza breads with peppery tomato salad
Calories: 287.0
Collected so far: 26 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/deep-dish-meatball-marinara-pizza
Result: accepted
Recipe: Deep-dish meatball marinara pizza
Calories: 686.0
Collected so far: 27 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pinwheel-pizzas
Result: accepted
Recipe: Pinwheel pizzas
Calories: 271.0
Collected so far: 28 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/pizza-pockets
Result: accepted
Recipe: Pizza pockets
Calories: 562.0
Collected so far: 29 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/caramelised-onion-goats-cheese-pizza
Result: accepted
Recipe: Caramelised onion & goat's cheese pizza
Calories: 443.0
Collected so far: 30 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/roast-cauliflower-cheese-pizza
Result: accepted
Recipe: Roast cauliflower cheese pizza
Calories: 438.0
Collected so far: 31 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/brussels-blue-cheese-pizza
Result: accepted
Recipe: Brussels & blue cheese pizza
Calories: 738.0
Collected so far: 32 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/no-cook-goats-cheese-pizza
Result: accepted
Recipe: No-cook goat's cheese pizza
Calories: 384.0
Collected so far: 33 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/cauliflower-cheese-0
Result: rejected
Recipe: Cauliflower cheese

Scraping URL:
https://www.bbcgoodfood.com/recipes/best-ever-macaroni-cheese-recipe
Result: rejected
Recipe: Best ever macaroni cheese recipe

Scraping URL:
https://www.bbcgoodfood.com/recipes/cheese-bacon-scone-pizza
Result: accepted
Recipe: Cheese & bacon scone pizza
Calories: 542.0
Collected so far: 34 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/classic-cheese-scones
Result: rejected
Recipe: Classic cheese scones

Scraping URL:
https://www.bbcgoodfood.com/recipes/pesto-pizza-aubergine-goats-cheese
Result: accepted
Recipe: Pesto pizza with aubergine & goat’s cheese
Calories: 431.0
Collected so far: 35 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/blue-cheese-pancetta-pizza-grilled-peaches
Result: accepted
Recipe: Blue cheese & pancetta pizza with grilled peaches
Calories: 488.0
Collected so far: 36 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/cheese-sauce
Result: rejected
Recipe: Cheese sauce

Scraping URL:
https://www.bbcgoodfood.com/recipes/next-level-cauliflower-cheese
Result: rejected
Recipe: Next-level cauliflower cheese

Scraping URL:
https://www.bbcgoodfood.com/recipes/cheese-bacon-turnovers
Result: rejected
Recipe: Cheese & bacon turnovers

Scraping URL:
https://www.bbcgoodfood.com/recipes/fish-pie-mac-n-cheese
Result: rejected
Recipe: Fish pie mac ’n’ cheese

Scraping URL:
https://www.bbcgoodfood.com/recipes/baked-ratatouille-goats-cheese
Result: rejected
Recipe: Baked ratatouille & goat’s cheese

Scraping URL:
https://www.bbcgoodfood.com/recipes/macaroni-cheese-lasagne
Result: rejected
Recipe: Macaroni cheese lasagne

Scraping URL:
https://www.bbcgoodfood.com/recipes/ultimate-pizza-margherita
Result: accepted
Recipe: Ultimate pizza Margherita
Calories: 593.0
Collected so far: 37 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/lighter-pizza-margherita
Result: accepted
Recipe: Lighter Pizza Margherita
Calories: 498.0
Collected so far: 38 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/roasted-spring-vegetable-pizza
Result: accepted
Recipe: Roasted spring vegetable pizza
Calories: 290.0
Collected so far: 39 / 50

Scraping URL:
https://www.bbcgoodfood.com/recipes/versatile-veg-soup
Result: rejected
Recipe: Vegetable soup

Scraping URL:
https://www.bbcgoodfood.com/recipes/vegetable-bean-chilli
Result: rejected

,source_site,food_class,query,recipe_name,ingredients_text,calories,protein,fat,carbs,source_url,scraped_at
0,bbc_good_food,burger,burger,Burger bowl,2 large potatoes cut into rough chunks 2 tbsp ...,207.0,18.0,13.0,19.0,https://www.bbcgoodfood.com/recipes/burger-bowl,2026-05-12 00:34:19
1,bbc_good_food,burger,burger,Falafel burgers,400g can chickpeas rinsed and drained 1 small...,175.0,6.0,8.0,18.0,https://www.bbcgoodfood.com/recipes/falafel-bu...,2026-05-12 00:34:21
2,bbc_good_food,burger,burger,15-minute chicken & halloumi burgers,2 chicken breast fillets 1 tbsp oil plus extra...,737.0,39.0,42.0,49.0,https://www.bbcgoodfood.com/recipes/15-minute-...,2026-05-12 00:34:23
3,bbc_good_food,burger,burger,The ultimate beef burger,1 small onion finely chopped 4 sesame-topped ...,893.0,56.0,37.0,82.0,https://www.bbcgoodfood.com/recipes/the-big-do...,2026-05-12 00:34:25
4,bbc_good_food,burger,burger,Next level chicken burgers,2 large chicken breasts sunflower oil for deep...,794.0,33.0,33.0,90.0,https://www.bbcgoodfood.com/recipes/next-level...,2026-05-12 00:34:27
5,bbc_good_food,burger,burger,Superhealthy salmon burgers,"4 boneless, skinless salmon fillets about 550g...",292.0,29.0,17.0,7.0,https://www.bbcgoodfood.com/recipes/superhealt...,2026-05-12 00:34:28
6,bbc_good_food,burger,burger,Smash burgers,"4 burger buns sesame topped or brioche, whiche...",666.0,37.0,39.0,41.0,https://www.bbcgoodfood.com/recipes/smash-burgers,2026-05-12 00:34:30
7,bbc_good_food,burger,burger,Mexican chicken burger,1 chicken breast 1 tsp chipotle paste 1 lime j...,709.0,46.0,34.0,52.0,https://www.bbcgoodfood.com/recipes/mexican-ch...,2026-05-12 00:34:32
8,bbc_good_food,burger,burger,Soft burger buns,200ml whole milk plus extra for brushing 50g u...,210.0,6.0,5.0,35.0,https://www.bbcgoodfood.com/recipes/soft-burge...,2026-05-12 00:34:33
9,bbc_good_food,burger,burger,Spiced halloumi & pineapple burger with zingy ...,½ red cabbage grated 2 carrots grated 100g rad...,264.0,11.0,14.0,19.0,https://www.bbcgoodfood.com/recipes/spiced-hal...,2026-05-12 00:34:35

In [17]:
# Cell 16 — Raw dataset audit

print("Raw dataset shape:")
print(final_bbc_df.shape)

print("\nColumns:")
print(final_bbc_df.columns.tolist())

print("\nRecords per class:")
class_counts = final_bbc_df["food_class"].value_counts()
print(class_counts)

print("\nMissing values per column:")
print(final_bbc_df.isna().sum())

print("\nDuplicate source URLs:")
print(final_bbc_df["source_url"].duplicated().sum())

print("\nDuplicate recipe names:")
print(final_bbc_df["recipe_name"].duplicated().sum())

print("\nNutrition summary:")
display(final_bbc_df[["calories", "protein", "fat", "carbs"]].describe())

print("\nCalories summary by class:")
display(
    final_bbc_df.groupby("food_class")["calories"]
    .agg(["count", "min", "max", "mean", "median"])
    .sort_values("count", ascending=False)
)

print("\nSample records from each class:")
for food_class in FOOD_CLASSES:
    print("\n====================================")
    print("Class:", food_class)
    print("====================================")

    sample_df = final_bbc_df[final_bbc_df["food_class"] == food_class][[
        "food_class",
        "recipe_name",
        "calories",
        "protein",
        "fat",
        "carbs",
        "source_url"
    ]].head(10)

    display(sample_df)

Raw dataset shape:
(428, 11)

Columns:
['source_site', 'food_class', 'query', 'recipe_name', 'ingredients_text', 'calories', 'protein', 'fat', 'carbs', 'source_url', 'scraped_at']

Records per class:
food_class
burger      50
fries       50
salad       50
pasta       50
rice        50
chicken     50
pizza       39
sandwich    39
steak       32
sushi       18
Name: count, dtype: int64

Missing values per column:
source_site         0
food_class          0
query               0
recipe_name         0
ingredients_text    0
calories            0
protein             0
fat                 1
carbs               3
source_url          0
scraped_at          0
dtype: int64

Duplicate source URLs:
12

Duplicate recipe names:
13

Nutrition summary:

          calories      protein         fat       carbs
count   428.000000   428.000000  427.000000  425.000000
mean    488.946262    37.042991   22.975504   42.725882
std     225.768216   223.331000   15.413796   24.109913
min      49.000000     0.400000    1.000000    0.400000
25%     332.750000    15.750000   12.000000   24.000000
50%     452.000000    27.000000   19.000000   42.000000
75%     619.500000    37.000000   30.515000   59.000000
max    1394.000000  4637.000000   89.000000  129.000000

Calories summary by class:

            count    min     max        mean  median
food_class
burger         50   61.0  1080.0  514.480000   506.0
chicken        50  239.0   857.0  432.120000   407.5
fries          50  120.0  1394.0  406.660000   393.5
pasta          50  115.0  1140.0  605.440000   568.0
rice           50   58.0   834.0  454.780000   411.5
salad          50  111.0   838.0  403.940000   376.0
pizza          39  166.0   740.0  470.435897   446.0
sandwich       39  125.0  1256.0  616.974359   583.0
steak          32  225.0  1282.0  591.781250   516.5
sushi          18   49.0   862.0  391.777778   411.0

Sample records from each class:

====================================
Class: burger
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
0,burger,Burger bowl,207.0,18.0,13.0,19.0,https://www.bbcgoodfood.com/recipes/burger-bowl
1,burger,Falafel burgers,175.0,6.0,8.0,18.0,https://www.bbcgoodfood.com/recipes/falafel-bu...
2,burger,15-minute chicken & halloumi burgers,737.0,39.0,42.0,49.0,https://www.bbcgoodfood.com/recipes/15-minute-...
3,burger,The ultimate beef burger,893.0,56.0,37.0,82.0,https://www.bbcgoodfood.com/recipes/the-big-do...
4,burger,Next level chicken burgers,794.0,33.0,33.0,90.0,https://www.bbcgoodfood.com/recipes/next-level...
5,burger,Superhealthy salmon burgers,292.0,29.0,17.0,7.0,https://www.bbcgoodfood.com/recipes/superhealt...
6,burger,Smash burgers,666.0,37.0,39.0,41.0,https://www.bbcgoodfood.com/recipes/smash-burgers
7,burger,Mexican chicken burger,709.0,46.0,34.0,52.0,https://www.bbcgoodfood.com/recipes/mexican-ch...
8,burger,Soft burger buns,210.0,6.0,5.0,35.0,https://www.bbcgoodfood.com/recipes/soft-burge...
9,burger,Spiced halloumi & pineapple burger with zingy ...,264.0,11.0,14.0,19.0,https://www.bbcgoodfood.com/recipes/spiced-hal...

====================================
Class: pizza
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
50,pizza,Pizza Margherita in 4 easy steps,431.0,19.0,15.0,59.0,https://www.bbcgoodfood.com/recipes/pizza-marg...
51,pizza,Pizza with homemade sauce,511.0,22.0,20.0,59.0,https://www.bbcgoodfood.com/recipes/pizza-home...
52,pizza,Detroit-style pizza,586.0,29.0,23.0,63.0,https://www.bbcgoodfood.com/recipes/triple-che...
53,pizza,Puff pastry pizzas,357.0,10.0,18.0,38.0,https://www.bbcgoodfood.com/recipes/puff-pastr...
54,pizza,Chicken tikka masala pizzas,683.0,47.0,16.0,83.0,https://www.bbcgoodfood.com/recipes/chicken-ti...
55,pizza,Tortilla pizza,266.0,11.0,14.0,23.0,https://www.bbcgoodfood.com/recipes/tortilla-p...
56,pizza,Next level Margherita pizza,693.0,31.0,18.0,98.0,https://www.bbcgoodfood.com/recipes/next-level...
57,pizza,Cookie dough pizza,432.0,5.0,21.0,55.0,https://www.bbcgoodfood.com/recipes/cookie-dou...
58,pizza,Sourdough pizza,502.0,21.0,15.0,69.0,https://www.bbcgoodfood.com/recipes/sourdough-...
59,pizza,Egg & rocket pizzas,327.0,15.0,11.0,39.0,https://www.bbcgoodfood.com/recipes/egg-rocket...

====================================
Class: fries
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
89,fries,Air fryer French fries,204.0,3.0,7.0,30.0,https://www.bbcgoodfood.com/recipes/air-fryer-...
90,fries,French fries,317.0,5.0,10.0,49.0,https://www.bbcgoodfood.com/recipes/french-fries
91,fries,Meatball marinara fries,399.0,25.0,20.0,29.0,https://www.bbcgoodfood.com/recipes/meatball-m...
92,fries,"Feta, tomato & olive loaded fries",290.0,7.0,15.0,30.0,https://www.bbcgoodfood.com/recipes/greek-load...
93,fries,Loaded fries,415.0,15.0,24.0,32.0,https://www.bbcgoodfood.com/recipes/loaded-fries
94,fries,Vegan bean chilli fries,428.0,8.0,23.0,44.0,https://www.bbcgoodfood.com/recipes/vegan-bean...
95,fries,Sweet potato fries,120.0,1.0,3.0,20.0,https://www.bbcgoodfood.com/recipes/sweet-pota...
96,fries,Air fryer sweet potato fries,244.0,3.0,3.0,48.0,https://www.bbcgoodfood.com/recipes/air-fryer-...
97,fries,Loaded chips ideas,409.0,4.0,19.0,53.0,https://www.bbcgoodfood.com/recipes/best-ever-...
98,fries,Steaks with goulash sauce & sweet potato fries,452.0,33.0,14.0,43.0,https://www.bbcgoodfood.com/recipes/steaks-gou...

====================================
Class: pasta
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
139,pasta,Chicken pasta bake,575.0,33.0,30.0,41.0,https://www.bbcgoodfood.com/recipes/chicken-pa...
140,pasta,Cajun chicken pasta,555.0,28.0,20.0,63.0,https://www.bbcgoodfood.com/recipes/cajun-chic...
141,pasta,Chicken & bacon pasta,857.0,35.0,58.0,46.0,https://www.bbcgoodfood.com/recipes/chicken-ba...
142,pasta,Pasta with salmon & peas,463.0,25.0,19.0,44.0,https://www.bbcgoodfood.com/recipes/pasta-salm...
143,pasta,Fajita-style pasta,395.0,23.0,14.0,41.0,https://www.bbcgoodfood.com/recipes/fajita-sty...
144,pasta,Pasta alla vodka,866.0,20.0,43.0,73.0,https://www.bbcgoodfood.com/recipes/pasta-alla...
145,pasta,Tomato & pasta soup,349.0,12.0,12.0,45.0,https://www.bbcgoodfood.com/recipes/orzo-tomat...
146,pasta,Caponata pasta,542.0,14.0,14.0,85.0,https://www.bbcgoodfood.com/recipes/caponata-p...
147,pasta,Creamy mushroom pasta,801.0,29.0,52.0,45.0,https://www.bbcgoodfood.com/recipes/creamy-mus...
148,pasta,Creamy garlic pasta,699.0,20.0,38.0,66.0,https://www.bbcgoodfood.com/recipes/creamy-gar...

====================================
Class: rice
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
189,rice,Easiest ever seafood rice,593.0,30.0,15.0,81.0,https://www.bbcgoodfood.com/recipes/easiest-ev...
190,rice,Spicy cauliflower & halloumi rice,337.0,14.0,14.0,36.0,https://www.bbcgoodfood.com/recipes/spicy-caul...
191,rice,Easy egg-fried rice,387.0,12.0,14.0,53.0,https://www.bbcgoodfood.com/recipes/egg-fried-...
192,rice,Easy pilau rice,226.0,5.0,5.0,39.0,https://www.bbcgoodfood.com/recipes/easy-pilau...
193,rice,"Chicken, leek & brown rice stir-fry",398.0,26.0,16.0,33.0,https://www.bbcgoodfood.com/recipes/chicken-le...
194,rice,Rice pudding,214.0,8.0,3.0,40.0,https://www.bbcgoodfood.com/recipes/a-nice-ric...
195,rice,Prawn fried rice,418.0,22.0,11.0,54.0,https://www.bbcgoodfood.com/recipes/prawn-frie...
196,rice,Classic rice pudding,358.0,6.0,21.0,36.0,https://www.bbcgoodfood.com/recipes/baked-rice...
197,rice,Fajita chicken rice bowl with burnt lime,321.0,31.0,6.0,31.0,https://www.bbcgoodfood.com/recipes/fajita-chi...
198,rice,Chicken & ginger fried rice,535.0,31.0,14.0,67.0,https://www.bbcgoodfood.com/recipes/chicken-gi...

====================================
Class: chicken
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
239,chicken,Chicken & chorizo jambalaya,445.0,30.0,10.0,64.0,https://www.bbcgoodfood.com/recipes/chicken-ch...
240,chicken,Chicken pasta bake,575.0,33.0,30.0,41.0,https://www.bbcgoodfood.com/recipes/chicken-pa...
241,chicken,Chicken korma,376.0,40.0,11.0,28.0,https://www.bbcgoodfood.com/recipes/chicken-korma
242,chicken,'Marry me' chicken,584.0,38.0,38.0,21.0,https://www.bbcgoodfood.com/recipes/marry-me-c...
243,chicken,Chicken noodle soup,266.0,34.0,2.0,26.0,https://www.bbcgoodfood.com/recipes/chicken-no...
244,chicken,Chicken tikka masala,345.0,31.0,19.0,13.0,https://www.bbcgoodfood.com/recipes/chicken-ti...
245,chicken,Thai green chicken curry,275.0,17.0,19.0,9.0,https://www.bbcgoodfood.com/recipes/thai-green...
246,chicken,Chicken satay salad,353.0,38.0,10.0,24.0,https://www.bbcgoodfood.com/recipes/chicken-sa...
247,chicken,Chinese chicken curry,264.0,40.0,8.0,7.0,https://www.bbcgoodfood.com/recipes/chinese-ch...
248,chicken,Chicken arrabbiata stew & parmesan dumplings,512.0,24.0,33.0,29.0,https://www.bbcgoodfood.com/recipes/chicken-ar...

====================================
Class: salad
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
289,salad,Chicken satay salad,353.0,38.0,10.0,24.0,https://www.bbcgoodfood.com/recipes/chicken-sa...
290,salad,Chickpea salad,111.0,4.0,5.0,10.0,https://www.bbcgoodfood.com/recipes/no-cook-ch...
291,salad,Epic summer salad,392.0,8.0,30.0,18.0,https://www.bbcgoodfood.com/recipes/epic-summe...
292,salad,10-minute couscous salad,468.0,16.0,24.0,44.0,https://www.bbcgoodfood.com/recipes/10minute-c...
293,salad,"Halloumi, carrot & orange salad",338.0,16.0,23.0,15.0,https://www.bbcgoodfood.com/recipes/halloumi-c...
294,salad,Greek salad,211.0,5.0,17.0,8.0,https://www.bbcgoodfood.com/recipes/greek-salad
295,salad,Salade niçoise,661.0,34.0,42.0,32.0,https://www.bbcgoodfood.com/recipes/salade-nic...
296,salad,Next level potato salad,310.0,3.0,23.0,21.0,https://www.bbcgoodfood.com/recipes/next-level...
297,salad,"Tuna, asparagus & white bean salad",245.0,24.0,5.0,23.0,https://www.bbcgoodfood.com/recipes/tuna-aspar...
298,salad,Allotment salad,122.0,4.0,7.0,7.0,https://www.bbcgoodfood.com/recipes/allotment-...

====================================
Class: sandwich
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
339,sandwich,Coronation chickpea sandwich filler,220.0,5.0,11.0,22.0,https://www.bbcgoodfood.com/recipes/coronation...
340,sandwich,Caprese sandwich,462.0,21.0,23.0,42.0,https://www.bbcgoodfood.com/recipes/caprese-sa...
341,sandwich,Next level steak sandwich,1166.0,69.0,63.0,76.0,https://www.bbcgoodfood.com/recipes/next-level...
342,sandwich,Fried chicken waffle sandwich,989.0,56.0,26.0,129.0,https://www.bbcgoodfood.com/recipes/fried-chic...
343,sandwich,Elvis sandwich,952.0,35.0,63.0,57.0,https://www.bbcgoodfood.com/recipes/elvis-sand...
344,sandwich,Panuozzo sandwich,552.0,22.0,25.0,58.0,https://www.bbcgoodfood.com/recipes/panuozzo-s...
345,sandwich,Pastrami sandwich,867.0,32.0,57.0,51.0,https://www.bbcgoodfood.com/recipes/pastrami-s...
346,sandwich,Tuna salad sandwich,474.0,21.0,23.0,42.0,https://www.bbcgoodfood.com/recipes/tuna-salad...
347,sandwich,Reuben sandwich,682.0,36.0,37.0,47.0,https://www.bbcgoodfood.com/recipes/reuben-san...
348,sandwich,Caprese chicken sandwiches,574.0,52.0,17.0,51.0,https://www.bbcgoodfood.com/recipes/caprese-ch...

====================================
Class: sushi
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
378,sushi,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/japanese-s...
379,sushi,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/easy-salmo...
380,sushi,Quick sushi bowl,498.0,27.0,11.0,70.0,https://www.bbcgoodfood.com/recipes/quick-sush...
381,sushi,Sesame & ginger sushi bowls,449.0,17.0,21.0,44.0,https://www.bbcgoodfood.com/recipes/sesame-gin...
382,sushi,Salmon sushi salad,862.0,27.0,43.0,87.0,https://www.bbcgoodfood.com/recipes/salmon-sus...
383,sushi,Perfect sushi rice,432.0,6.0,1.0,99.0,https://www.bbcgoodfood.com/recipes/sushi-rice
384,sushi,Simple sushi,390.0,8.0,9.0,70.0,https://www.bbcgoodfood.com/recipes/simple-sushi
385,sushi,"Sushi rice bowl with beef, egg & chilli sauce",621.0,41.0,23.0,63.0,https://www.bbcgoodfood.com/recipes/sushi-rice...
386,sushi,Smoked salmon & avocado sushi,49.0,2.0,2.0,7.0,https://www.bbcgoodfood.com/recipes/smoked-sal...
387,sushi,Build-your-own salmon sushi burrito,441.0,19.0,26.0,30.0,https://www.bbcgoodfood.com/recipes/build-your...

====================================
Class: steak
====================================

,food_class,recipe_name,calories,protein,fat,carbs,source_url
396,steak,Easy steak pie,611.0,39.0,36.0,32.0,https://www.bbcgoodfood.com/recipes/easy-steak...
397,steak,Next level steak & ale pie,939.0,38.0,49.0,80.0,https://www.bbcgoodfood.com/recipes/steak-ale-pie
398,steak,Steak Diane,402.0,24.0,26.0,4.0,https://www.bbcgoodfood.com/recipes/next-level...
399,steak,Air fryer steak,523.0,46.0,37.0,NaN,https://www.bbcgoodfood.com/recipes/air-fryer-...
400,steak,Spanish pork shoulder steaks with beans,454.0,39.0,14.0,35.0,https://www.bbcgoodfood.com/recipes/spanish-po...
401,steak,Smoky steak with Cajun potatoes & spicy slaw,802.0,47.0,50.0,40.0,https://www.bbcgoodfood.com/recipes/smoky-stea...
402,steak,"Steak, ale & mushroom pie",1282.0,54.0,68.0,107.0,https://www.bbcgoodfood.com/recipes/proper-bee...
403,steak,One-pan sirloin steak & creamy mushroom sauce,1078.0,55.0,89.0,5.0,https://www.bbcgoodfood.com/recipes/one-pan-si...
404,steak,Steak & blue cheese pie,831.0,44.0,50.0,49.0,https://www.bbcgoodfood.com/recipes/steak-blue...
405,steak,Sesame steak & buckwheat noodle bowls,550.0,34.0,16.0,65.0,https://www.bbcgoodfood.com/recipes/sesame-ste...

In [18]:
# Cell 17 — Detailed quality issue inspection

audit_df = final_bbc_df.copy()

print("Dataset shape before cleaning:")
print(audit_df.shape)

print("\nRecords per class:")
print(audit_df["food_class"].value_counts())

print("\nRows with duplicate source_url:")
duplicate_url_df = audit_df[audit_df["source_url"].duplicated(keep=False)].sort_values("source_url")
print("Duplicate URL rows:", len(duplicate_url_df))
display(duplicate_url_df[[
    "food_class",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url"
]])

print("\nRows with duplicate recipe_name:")
duplicate_name_df = audit_df[audit_df["recipe_name"].duplicated(keep=False)].sort_values("recipe_name")
print("Duplicate recipe name rows:", len(duplicate_name_df))
display(duplicate_name_df[[
    "food_class",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url"
]])

print("\nRows with missing nutrition values:")
missing_nutrition_df = audit_df[
    audit_df[["calories", "protein", "fat", "carbs"]].isna().any(axis=1)
]
print("Missing nutrition rows:", len(missing_nutrition_df))
display(missing_nutrition_df[[
    "food_class",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url"
]])

print("\nNutrition outlier rows:")
outlier_df = audit_df[
    (audit_df["calories"] > 1200)
    | (audit_df["protein"] > 120)
    | (audit_df["fat"] > 100)
    | (audit_df["carbs"] > 150)
    | (audit_df["calories"] < 50)
]
print("Outlier rows:", len(outlier_df))
display(outlier_df[[
    "food_class",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url"
]].sort_values(["protein", "calories"], ascending=False))

SUSPICIOUS_KEYWORDS_BY_CLASS = {
    "burger": [
        "sauce", "bun", "buns", "pasta"
    ],
    "pizza": [
        "dough", "sauce", "fondue", "cookie", "dip"
    ],
    "fries": [
        "hummus", "pitta chips", "pasta chips", "fish & chips"
    ],
    "pasta": [
        "soup", "sauce for pasta"
    ],
    "rice": [
        "rice pudding", "cauliflower rice"
    ],
    "chicken": [
        "salad", "pasta"
    ],
    "salad": [
        "dressing", "wrap", "burgers"
    ],
    "sandwich": [
        "cake", "biscuit", "biscuits", "cookie", "cookies", "ice cream", "shortbread", "raspberry"
    ],
    "sushi": [
        "sweet sushi", "sushi rice"
    ],
    "steak": [
        "pork", "tuna steak", "pie", "pudding"
    ]
}

def has_suspicious_keyword(row):
    food_class = row["food_class"]
    recipe_name = normalize_text_for_filtering(row["recipe_name"])
    source_url = normalize_text_for_filtering(row["source_url"])
    combined_text = recipe_name + " " + source_url

    suspicious_keywords = SUSPICIOUS_KEYWORDS_BY_CLASS.get(food_class, [])

    for keyword in suspicious_keywords:
        if keyword in combined_text:
            return True

    return False

audit_df["is_suspicious"] = audit_df.apply(has_suspicious_keyword, axis=1)

print("\nSuspicious rows by class:")
print(audit_df.groupby("food_class")["is_suspicious"].value_counts())

print("\nSuspicious examples:")
suspicious_df = audit_df[audit_df["is_suspicious"] == True]
display(suspicious_df[[
    "food_class",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url"
]].sort_values(["food_class", "recipe_name"]))

print("\nClean candidate count if we remove duplicates, missing nutrition, outliers, and suspicious rows:")

clean_candidate_df = audit_df.copy()

clean_candidate_df = clean_candidate_df.drop_duplicates(subset=["source_url"])
clean_candidate_df = clean_candidate_df.drop_duplicates(subset=["recipe_name"])
clean_candidate_df = clean_candidate_df.dropna(subset=["calories", "protein", "fat", "carbs"])

clean_candidate_df = clean_candidate_df[
    (clean_candidate_df["calories"] >= 50)
    & (clean_candidate_df["calories"] <= 1200)
    & (clean_candidate_df["protein"] <= 120)
    & (clean_candidate_df["fat"] <= 100)
    & (clean_candidate_df["carbs"] <= 150)
]

clean_candidate_df = clean_candidate_df[clean_candidate_df["is_suspicious"] == False]

print(clean_candidate_df.shape)

print("\nClean candidate records per class:")
print(clean_candidate_df["food_class"].value_counts())

Dataset shape before cleaning:
(428, 11)

Records per class:
food_class
burger      50
fries       50
salad       50
pasta       50
rice        50
chicken     50
pizza       39
sandwich    39
steak       32
sushi       18
Name: count, dtype: int64

Rows with duplicate source_url:
Duplicate URL rows: 24

,food_class,recipe_name,calories,protein,fat,carbs,source_url
140,pasta,Cajun chicken pasta,555.0,28.0,20.0,63.0,https://www.bbcgoodfood.com/recipes/cajun-chic...
252,chicken,Cajun chicken pasta,555.0,28.0,20.0,63.0,https://www.bbcgoodfood.com/recipes/cajun-chic...
26,burger,Cheeseburger & chips,558.0,38.0,21.0,58.0,https://www.bbcgoodfood.com/recipes/cheeseburg...
115,fries,Cheeseburger & chips,558.0,38.0,21.0,58.0,https://www.bbcgoodfood.com/recipes/cheeseburg...
258,chicken,Chicken & bacon pasta,857.0,35.0,58.0,46.0,https://www.bbcgoodfood.com/recipes/chicken-ba...
141,pasta,Chicken & bacon pasta,857.0,35.0,58.0,46.0,https://www.bbcgoodfood.com/recipes/chicken-ba...
240,chicken,Chicken pasta bake,575.0,33.0,30.0,41.0,https://www.bbcgoodfood.com/recipes/chicken-pa...
139,pasta,Chicken pasta bake,575.0,33.0,30.0,41.0,https://www.bbcgoodfood.com/recipes/chicken-pa...
246,chicken,Chicken satay salad,353.0,38.0,10.0,24.0,https://www.bbcgoodfood.com/recipes/chicken-sa...
289,salad,Chicken satay salad,353.0,38.0,10.0,24.0,https://www.bbcgoodfood.com/recipes/chicken-sa...
282,chicken,"Chicken, spinach & bacon alfredo pasta bake",757.0,30.0,43.0,60.0,https://www.bbcgoodfood.com/recipes/chicken-sp...
173,pasta,"Chicken, spinach & bacon alfredo pasta bake",757.0,30.0,43.0,60.0,https://www.bbcgoodfood.com/recipes/chicken-sp...
287,chicken,Crispiest buttermilk fried chicken burgers,522.0,28.0,17.0,61.0,https://www.bbcgoodfood.com/recipes/crispiest-...
21,burger,Crispiest buttermilk fried chicken burgers,522.0,28.0,17.0,61.0,https://www.bbcgoodfood.com/recipes/crispiest-...
378,sushi,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/japanese-s...
202,rice,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/japanese-s...
285,chicken,Korean fried chicken burgers,415.0,19.0,20.0,38.0,https://www.bbcgoodfood.com/recipes/korean-fri...
16,burger,Korean fried chicken burgers,415.0,19.0,20.0,38.0,https://www.bbcgoodfood.com/recipes/korean-fri...
118,fries,Turkey burger with sweet potato wedges,428.0,40.0,13.0,32.0,https://www.bbcgoodfood.com/recipes/lean-turke...
17,burger,Turkey burger with sweet potato wedges,428.0,40.0,13.0,32.0,https://www.bbcgoodfood.com/recipes/lean-turke...
341,sandwich,Next level steak sandwich,1166.0,69.0,63.0,76.0,https://www.bbcgoodfood.com/recipes/next-level...
410,steak,Next level steak sandwich,1166.0,69.0,63.0,76.0,https://www.bbcgoodfood.com/recipes/next-level...
98,fries,Steaks with goulash sauce & sweet potato fries,452.0,33.0,14.0,43.0,https://www.bbcgoodfood.com/recipes/steaks-gou...
416,steak,Steaks with goulash sauce & sweet potato fries,452.0,33.0,14.0,43.0,https://www.bbcgoodfood.com/recipes/steaks-gou...

Rows with duplicate recipe_name:
Duplicate recipe name rows: 25

,food_class,recipe_name,calories,protein,fat,carbs,source_url
140,pasta,Cajun chicken pasta,555.0,28.0,20.0,63.0,https://www.bbcgoodfood.com/recipes/cajun-chic...
252,chicken,Cajun chicken pasta,555.0,28.0,20.0,63.0,https://www.bbcgoodfood.com/recipes/cajun-chic...
26,burger,Cheeseburger & chips,558.0,38.0,21.0,58.0,https://www.bbcgoodfood.com/recipes/cheeseburg...
115,fries,Cheeseburger & chips,558.0,38.0,21.0,58.0,https://www.bbcgoodfood.com/recipes/cheeseburg...
141,pasta,Chicken & bacon pasta,857.0,35.0,58.0,46.0,https://www.bbcgoodfood.com/recipes/chicken-ba...
258,chicken,Chicken & bacon pasta,857.0,35.0,58.0,46.0,https://www.bbcgoodfood.com/recipes/chicken-ba...
139,pasta,Chicken pasta bake,575.0,33.0,30.0,41.0,https://www.bbcgoodfood.com/recipes/chicken-pa...
240,chicken,Chicken pasta bake,575.0,33.0,30.0,41.0,https://www.bbcgoodfood.com/recipes/chicken-pa...
246,chicken,Chicken satay salad,353.0,38.0,10.0,24.0,https://www.bbcgoodfood.com/recipes/chicken-sa...
289,salad,Chicken satay salad,353.0,38.0,10.0,24.0,https://www.bbcgoodfood.com/recipes/chicken-sa...
173,pasta,"Chicken, spinach & bacon alfredo pasta bake",757.0,30.0,43.0,60.0,https://www.bbcgoodfood.com/recipes/chicken-sp...
282,chicken,"Chicken, spinach & bacon alfredo pasta bake",757.0,30.0,43.0,60.0,https://www.bbcgoodfood.com/recipes/chicken-sp...
21,burger,Crispiest buttermilk fried chicken burgers,522.0,28.0,17.0,61.0,https://www.bbcgoodfood.com/recipes/crispiest-...
287,chicken,Crispiest buttermilk fried chicken burgers,522.0,28.0,17.0,61.0,https://www.bbcgoodfood.com/recipes/crispiest-...
378,sushi,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/japanese-s...
202,rice,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/japanese-s...
379,sushi,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/easy-salmo...
16,burger,Korean fried chicken burgers,415.0,19.0,20.0,38.0,https://www.bbcgoodfood.com/recipes/korean-fri...
285,chicken,Korean fried chicken burgers,415.0,19.0,20.0,38.0,https://www.bbcgoodfood.com/recipes/korean-fri...
410,steak,Next level steak sandwich,1166.0,69.0,63.0,76.0,https://www.bbcgoodfood.com/recipes/next-level...
341,sandwich,Next level steak sandwich,1166.0,69.0,63.0,76.0,https://www.bbcgoodfood.com/recipes/next-level...
98,fries,Steaks with goulash sauce & sweet potato fries,452.0,33.0,14.0,43.0,https://www.bbcgoodfood.com/recipes/steaks-gou...
416,steak,Steaks with goulash sauce & sweet potato fries,452.0,33.0,14.0,43.0,https://www.bbcgoodfood.com/recipes/steaks-gou...
118,fries,Turkey burger with sweet potato wedges,428.0,40.0,13.0,32.0,https://www.bbcgoodfood.com/recipes/lean-turke...
17,burger,Turkey burger with sweet potato wedges,428.0,40.0,13.0,32.0,https://www.bbcgoodfood.com/recipes/lean-turke...

Rows with missing nutrition values:
Missing nutrition rows: 3

,food_class,recipe_name,calories,protein,fat,carbs,source_url
330,salad,Chicken & bacon caesar salad,530.0,39.0,NaN,NaN,https://www.bbcgoodfood.com/recipes/chicken-ba...
399,steak,Air fryer steak,523.0,46.0,37.0,NaN,https://www.bbcgoodfood.com/recipes/air-fryer-...
417,steak,Seared tuna steak,225.0,44.0,6.0,NaN,https://www.bbcgoodfood.com/recipes/seared-tun...

Nutrition outlier rows:
Outlier rows: 6

,food_class,recipe_name,calories,protein,fat,carbs,source_url
176,pasta,Chicken & broccoli pasta bake,764.0,4637.0,34.0,65.0,https://www.bbcgoodfood.com/recipes/chicken-br...
377,sandwich,Best ever Christmas leftovers sandwich,1237.0,61.0,66.0,94.0,https://www.bbcgoodfood.com/recipes/best-ever-...
376,sandwich,Ultimate turkey sandwich,1256.0,60.0,67.0,97.0,https://www.bbcgoodfood.com/recipes/ultimate-t...
106,fries,Air-fryer or oven-cooked fish & chips,1394.0,55.0,85.0,98.0,https://www.bbcgoodfood.com/recipes/air-fryer-...
402,steak,"Steak, ale & mushroom pie",1282.0,54.0,68.0,107.0,https://www.bbcgoodfood.com/recipes/proper-bee...
386,sushi,Smoked salmon & avocado sushi,49.0,2.0,2.0,7.0,https://www.bbcgoodfood.com/recipes/smoked-sal...

Suspicious rows by class:
food_class  is_suspicious
burger      False            46
            True              4
chicken     False            43
            True              7
fries       False            48
            True              2
pasta       False            47
            True              3
pizza       False            35
            True              4
rice        False            47
            True              3
salad       False            43
            True              7
sandwich    False            34
            True              5
steak       False            23
            True              9
sushi       False            13
            True              5
Name: count, dtype: int64

Suspicious examples:

,food_class,recipe_name,calories,protein,fat,carbs,source_url
18,burger,Classic burger sauce,61.0,0.4,1.0,2.0,https://www.bbcgoodfood.com/recipes/classic-bu...
24,burger,One-pot cheeseburger pasta,687.0,43.0,30.0,57.0,https://www.bbcgoodfood.com/recipes/one-pot-ch...
8,burger,Soft burger buns,210.0,6.0,5.0,35.0,https://www.bbcgoodfood.com/recipes/soft-burge...
3,burger,The ultimate beef burger,893.0,56.0,37.0,82.0,https://www.bbcgoodfood.com/recipes/the-big-do...
252,chicken,Cajun chicken pasta,555.0,28.0,20.0,63.0,https://www.bbcgoodfood.com/recipes/cajun-chic...
267,chicken,Cajun grilled chicken with lime black-eyed bea...,491.0,48.0,20.0,30.0,https://www.bbcgoodfood.com/recipes/cajun-gril...
258,chicken,Chicken & bacon pasta,857.0,35.0,58.0,46.0,https://www.bbcgoodfood.com/recipes/chicken-ba...
240,chicken,Chicken pasta bake,575.0,33.0,30.0,41.0,https://www.bbcgoodfood.com/recipes/chicken-pa...
246,chicken,Chicken satay salad,353.0,38.0,10.0,24.0,https://www.bbcgoodfood.com/recipes/chicken-sa...
282,chicken,"Chicken, spinach & bacon alfredo pasta bake",757.0,30.0,43.0,60.0,https://www.bbcgoodfood.com/recipes/chicken-sp...
274,chicken,"Grilled peach, chicken & feta salad",302.0,29.0,15.0,13.0,https://www.bbcgoodfood.com/recipes/grilled-pe...
105,fries,Air fryer pasta chips,144.0,4.0,4.0,21.0,https://www.bbcgoodfood.com/recipes/air-fryer-...
111,fries,Homemade hummus with pitta chips,227.0,7.0,11.0,28.0,https://www.bbcgoodfood.com/recipes/homemade-h...
149,pasta,Hearty pasta soup,286.0,11.0,9.0,44.0,https://www.bbcgoodfood.com/recipes/hearty-pas...
179,pasta,Roasted pepper sauce for pasta or chicken,115.0,3.0,4.0,19.0,https://www.bbcgoodfood.com/recipes/roasted-pe...
145,pasta,Tomato & pasta soup,349.0,12.0,12.0,45.0,https://www.bbcgoodfood.com/recipes/orzo-tomat...
57,pizza,Cookie dough pizza,432.0,5.0,21.0,55.0,https://www.bbcgoodfood.com/recipes/cookie-dou...
63,pizza,Pizza fondue dip,166.0,7.0,14.0,2.0,https://www.bbcgoodfood.com/recipes/pizza-fond...
51,pizza,Pizza with homemade sauce,511.0,22.0,20.0,59.0,https://www.bbcgoodfood.com/recipes/pizza-home...
58,pizza,Sourdough pizza,502.0,21.0,15.0,69.0,https://www.bbcgoodfood.com/recipes/sourdough-...
196,rice,Classic rice pudding,358.0,6.0,21.0,36.0,https://www.bbcgoodfood.com/recipes/baked-rice...
204,rice,How to make cauliflower rice,58.0,5.0,1.0,4.0,https://www.bbcgoodfood.com/recipes/cauliflowe...
194,rice,Rice pudding,214.0,8.0,3.0,40.0,https://www.bbcgoodfood.com/recipes/a-nice-ric...
326,salad,Caesar salad burgers,383.0,26.0,20.0,24.0,https://www.bbcgoodfood.com/recipes/caesar-sal...
306,salad,Caesar salad dressing,148.0,2.0,15.0,1.0,https://www.bbcgoodfood.com/recipes/caesar-sal...
321,salad,Caesar salad wrap,722.0,40.0,37.0,53.0,https://www.bbcgoodfood.com/recipes/caesar-sal...
304,salad,Easy salad dressing,214.0,0.4,23.0,1.0,https://www.bbcgoodfood.com/recipes/easy-salad...
312,salad,Lentil salad with tahini dressing,460.0,18.0,21.0,42.0,https://www.bbcgoodfood.com/recipes/lentil-sal...
333,salad,Rare beef & anchovy salad with rocket & caesar...,477.0,30.0,39.0,2.0,https://www.bbcgoodfood.com/recipes/rare-beef-...
331,salad,Warm potato salad with caesar dressing,321.0,7.0,20.0,32.0,https://www.bbcgoodfood.com/recipes/warm-potat...
356,sandwich,Air fryer ice cream cookie sandwich,606.0,8.0,29.0,76.0,https://www.bbcgoodfood.com/recipes/air-fryer-...
359,sandwich,Chocolate peanut butter shortbread sandwiches,363.0,2.0,18.0,44.0,https://www.bbcgoodfood.com/recipes/chocolate-...
358,sandwich,Ginger cookie sandwiches with lemon mascarpone,227.0,2.0,12.0,28.0,https://www.bbcgoodfood.com/recipes/ginger-coo...
353,sandwich,Luscious lemon & raspberry sandwich,577.0,6.0,31.0,68.0,https://www.bbcgoodfood.com/recipes/luscious-l...
351,sandwich,Rhubarb & custard sandwich biscuits,237.0,2.0,10.0,34.0,https://www.bbcgoodfood.com/recipes/rhubarb-cu...
415,steak,Easy steak & mushroom pie,680.0,39.0,43.0,32.0,https://www.bbcgoodfood.com/recipes/easy-steak...
396,steak,Easy steak pie,611.0,39.0,36.0,32.0,https://www.bbcgoodfood.com/recipes/easy-steak...
406,steak,Fruity pork steaks,304.0,33.0,9.0,25.0,https://www.bbcgoodfood.com/recipes/fruity-por...
397,steak,Next level steak & ale pie,939.0,38.0,49.0,80.0,https://www.bbcgoodfood.com/recipes/steak-ale-pie
417,steak,Seared tuna steak,225.0,44.0,6.0,NaN,https://www.bbcgoodfood.com/recipes/seared-tun...
400,steak,Spanish pork shoulder steaks with beans,454.0,39.0,14.0,35.0,https://www.bbcgoodfood.com/recipes/spanish-po...
404,steak,Steak & blue cheese pie,831.0,44.0,50.0,49.0,https://www.bbcgoodfood.com/recipes/steak-blue...
409,steak,Steak & kidney pudding,904.0,40.0,45.0,79.0,https://www.bbcgoodfood.com/recipes/steak-kidn...
402,steak,"Steak, ale & mushroom pie",1282.0,54.0,68.0,107.0,https://www.bbcgoodfood.com/recipes/proper-bee...
378,sushi,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/japanese-s...
379,sushi,Easy salmon sushi rice bowl,713.0,41.0,27.0,73.0,https://www.bbcgoodfood.com/recipes/easy-salmo...
383,sushi,Perfect sushi rice,432.0,6.0,1.0,99.0,https://www.bbcgoodfood.com/recipes/sushi-rice
385,sushi,"Sushi rice bowl with beef, egg & chilli sauce",621.0,41.0,23.0,63.0,https://www.bbcgoodfood.com/recipes/sushi-rice...
389,sushi,Sweet sushi,168.0,2.0,3.0,33.0,https://www.bbcgoodfood.com/recipes/sweet-sushi

Clean candidate count if we remove duplicates, missing nutrition, outliers, and suspicious rows:
(365, 12)

Clean candidate records per class:
food_class
rice        47
burger      46
pasta       46
fries       45
salad       41
chicken     41
pizza       35
sandwich    32
steak       20
sushi       12
Name: count, dtype: int64

In [19]:
# Cell 18 — Smart cleaning candidate v1

clean_work_df = final_bbc_df.copy()

clean_work_df["normalized_recipe_name"] = clean_work_df["recipe_name"].apply(normalize_text_for_filtering)
clean_work_df["normalized_source_url"] = clean_work_df["source_url"].apply(normalize_text_for_filtering)


def hard_reject_reason(row):
    """
    Return a hard rejection reason for records that are clearly not suitable
    for the intended class.
    """
    food_class = row["food_class"]
    name = row["normalized_recipe_name"]

    if food_class == "burger":
        if "burger sauce" in name:
            return "burger_sauce_only"
        if "burger buns" in name or name.endswith("buns"):
            return "burger_buns_only"
        if "cheeseburger pasta" in name or "burger pasta" in name:
            return "burger_pasta_dish"

    if food_class == "pizza":
        if "pizza sauce" in name:
            return "pizza_sauce_only"
        if "pizza dough" in name:
            return "pizza_dough_only"
        if "cookie dough pizza" in name:
            return "dessert_pizza"
        if "pizza fondue dip" in name or "pizza dip" in name:
            return "pizza_dip"

    if food_class == "fries":
        if "pitta chips" in name:
            return "pitta_chips_not_fries"
        if "pasta chips" in name:
            return "pasta_chips_not_fries"
        if "tortilla chips" in name:
            return "tortilla_chips_not_fries"

    if food_class == "pasta":
        if "pasta soup" in name:
            return "pasta_soup"
        if "sauce for pasta" in name:
            return "pasta_sauce_only"

    if food_class == "rice":
        if "rice pudding" in name:
            return "rice_dessert"
        if "cauliflower rice" in name:
            return "cauliflower_rice_not_rice"

    if food_class == "chicken":
        if "pasta" in name:
            return "chicken_pasta_belongs_to_pasta"
        if "salad" in name:
            return "chicken_salad_belongs_to_salad"

    if food_class == "salad":
        if "salad dressing" in name:
            return "salad_dressing_only"
        if "salad wrap" in name:
            return "salad_wrap_not_salad"
        if "salad burgers" in name:
            return "salad_burger_not_salad"

    if food_class == "sandwich":
        dessert_terms = [
            "cake",
            "biscuit",
            "biscuits",
            "cookie",
            "cookies",
            "ice cream",
            "shortbread",
            "raspberry",
            "custard"
        ]

        for term in dessert_terms:
            if term in name:
                return "dessert_sandwich"

    if food_class == "sushi":
        if name == "sweet sushi":
            return "sweet_sushi_dessert"
        if name == "perfect sushi rice":
            return "sushi_rice_only"

    if food_class == "steak":
        if "pork" in name:
            return "pork_steak_not_target"
        if "tuna steak" in name:
            return "tuna_steak_not_target"
        if "steak pie" in name or "steak & ale pie" in name or "steak ale pie" in name:
            return "steak_pie_not_steak_plate"
        if "steak & kidney pudding" in name or "kidney pudding" in name:
            return "steak_pudding_not_steak_plate"

    return None


def nutrition_reject_reason(row):
    """
    Return rejection reason for missing or impossible nutrition values.
    """
    required_cols = ["calories", "protein", "fat", "carbs"]

    for col in required_cols:
        if pd.isna(row[col]):
            return "missing_nutrition"

    if row["protein"] > 120:
        return "protein_outlier"

    if row["calories"] < 30:
        return "calories_too_low"

    if row["calories"] > 1600:
        return "calories_too_high"

    if row["fat"] > 120:
        return "fat_outlier"

    if row["carbs"] > 180:
        return "carbs_outlier"

    return None


def get_class_match_score(food_class, name):
    """
    Score how strongly the recipe name matches a class.
    Used only for resolving duplicates across classes.
    """
    score = 0

    if food_class == "pizza":
        if "pizza" in name or "pizzas" in name:
            score += 5

    elif food_class == "burger":
        if "burger" in name or "burgers" in name or "cheeseburger" in name or "beefburger" in name:
            score += 5

    elif food_class == "fries":
        if "fries" in name or "chips" in name or "wedges" in name:
            score += 5

    elif food_class == "pasta":
        pasta_terms = ["pasta", "spaghetti", "penne", "lasagne", "lasagna", "tagliatelle", "fettuccine", "macaroni", "orzo"]
        if any(term in name for term in pasta_terms):
            score += 5

    elif food_class == "rice":
        rice_terms = ["rice", "risotto", "paella", "pilau", "biryani", "jambalaya"]
        if any(term in name for term in rice_terms):
            score += 5

    elif food_class == "chicken":
        if "chicken" in name:
            score += 2

    elif food_class == "salad":
        if "salad" in name or "slaw" in name:
            score += 5

    elif food_class == "sandwich":
        sandwich_terms = ["sandwich", "sandwiches", "toastie", "panini", "sub sandwich"]
        if any(term in name for term in sandwich_terms):
            score += 5

    elif food_class == "sushi":
        sushi_terms = ["sushi", "maki", "onigiri", "sushi bowl", "sushi rice bowl", "sushi rolls"]
        if any(term in name for term in sushi_terms):
            score += 5

    elif food_class == "steak":
        steak_terms = ["steak", "steaks", "sirloin", "rib-eye", "rib eye", "rump steak"]
        if any(term in name for term in steak_terms):
            score += 5

    return score


CLASS_PRIORITY_FOR_DUPLICATES = {
    "burger": 1,
    "pizza": 2,
    "pasta": 3,
    "rice": 4,
    "sushi": 5,
    "steak": 6,
    "salad": 7,
    "sandwich": 8,
    "fries": 9,
    "chicken": 10
}


def build_drop_reason(row):
    reasons = []

    nutrition_reason = nutrition_reject_reason(row)
    if nutrition_reason is not None:
        reasons.append(nutrition_reason)

    hard_reason = hard_reject_reason(row)
    if hard_reason is not None:
        reasons.append(hard_reason)

    if len(reasons) == 0:
        return ""

    return "|".join(reasons)


clean_work_df["drop_reason"] = clean_work_df.apply(build_drop_reason, axis=1)

hard_removed_df = clean_work_df[clean_work_df["drop_reason"] != ""].copy()
clean_stage_df = clean_work_df[clean_work_df["drop_reason"] == ""].copy()

print("Initial raw shape:")
print(clean_work_df.shape)

print("\nRows removed by hard rules:")
print(len(hard_removed_df))

print("\nHard removal reasons:")
print(hard_removed_df["drop_reason"].value_counts())

print("\nShape after hard removal:")
print(clean_stage_df.shape)

# Score records before duplicate resolution
clean_stage_df["dedupe_match_score"] = clean_stage_df.apply(
    lambda row: get_class_match_score(row["food_class"], row["normalized_recipe_name"]),
    axis=1
)

clean_stage_df["class_priority"] = clean_stage_df["food_class"].map(CLASS_PRIORITY_FOR_DUPLICATES)

# Resolve duplicate source URLs
before_url_dedup = len(clean_stage_df)

clean_stage_df = clean_stage_df.sort_values(
    by=["source_url", "dedupe_match_score", "class_priority"],
    ascending=[True, False, True]
)

clean_stage_df = clean_stage_df.drop_duplicates(subset=["source_url"], keep="first")

after_url_dedup = len(clean_stage_df)

# Resolve duplicate recipe names
before_name_dedup = len(clean_stage_df)

clean_stage_df = clean_stage_df.sort_values(
    by=["recipe_name", "dedupe_match_score", "class_priority"],
    ascending=[True, False, True]
)

clean_stage_df = clean_stage_df.drop_duplicates(subset=["recipe_name"], keep="first")

after_name_dedup = len(clean_stage_df)

# Remove helper columns from final cleaned candidate
cleaned_candidate_v1_df = clean_stage_df.drop(
    columns=[
        "normalized_recipe_name",
        "normalized_source_url",
        "drop_reason",
        "dedupe_match_score",
        "class_priority"
    ],
    errors="ignore"
).reset_index(drop=True)

print("\nDuplicate source_url rows removed:")
print(before_url_dedup - after_url_dedup)

print("\nDuplicate recipe_name rows removed:")
print(before_name_dedup - after_name_dedup)

print("\nCleaned candidate v1 shape:")
print(cleaned_candidate_v1_df.shape)

print("\nCleaned candidate v1 records per class:")
print(cleaned_candidate_v1_df["food_class"].value_counts())

print("\nMissing values after cleaning:")
print(cleaned_candidate_v1_df.isna().sum())

print("\nNutrition summary after cleaning:")
display(cleaned_candidate_v1_df[["calories", "protein", "fat", "carbs"]].describe())

print("\nCalories summary by class after cleaning:")
display(
    cleaned_candidate_v1_df.groupby("food_class")["calories"]
    .agg(["count", "min", "max", "mean", "median"])
    .sort_values("count", ascending=False)
)

# Save cleaning audit files
cleaned_candidate_v1_path = CLEAN_DIR / "bbc_text_calorie_cleaned_candidate_v1.csv"
hard_removed_v1_path = LOGS_DIR / "bbc_cleaning_v1_hard_removed.csv"

cleaned_candidate_v1_df.to_csv(cleaned_candidate_v1_path, index=False)
hard_removed_df.to_csv(hard_removed_v1_path, index=False)

print("\nCleaned candidate v1 saved to:")
print(cleaned_candidate_v1_path)

print("\nHard removed rows saved to:")
print(hard_removed_v1_path)

Initial raw shape:
(428, 14)

Rows removed by hard rules:
41

Hard removal reasons:
drop_reason
dessert_sandwich                           5
chicken_pasta_belongs_to_pasta             4
chicken_salad_belongs_to_salad             3
rice_dessert                               2
pork_steak_not_target                      2
steak_pie_not_steak_plate                  2
salad_dressing_only                        2
missing_nutrition                          2
pasta_soup                                 2
burger_buns_only                           1
protein_outlier                            1
tortilla_chips_not_fries                   1
pitta_chips_not_fries                      1
pasta_chips_not_fries                      1
dessert_pizza                              1
pizza_dip                                  1
burger_pasta_dish                          1
burger_sauce_only                          1
salad_burger_not_salad                     1
salad_wrap_not_salad                       1
pasta_sauce_only                           1
cauliflower_rice_not_rice                  1
sweet_sushi_dessert                        1
sushi_rice_only                            1
steak_pudding_not_steak_plate              1
missing_nutrition|tuna_steak_not_target    1
Name: count, dtype: int64

Shape after hard removal:
(387, 14)

Duplicate source_url rows removed:
7

Duplicate recipe_name rows removed:
1

Cleaned candidate v1 shape:
(379, 11)

Cleaned candidate v1 records per class:
food_class
rice        47
burger      47
pasta       46
salad       45
fries       44
chicken     41
pizza       37
sandwich    33
steak       25
sushi       14
Name: count, dtype: int64

Missing values after cleaning:
source_site         0
food_class          0
query               0
recipe_name         0
ingredients_text    0
calories            0
protein             0
fat                 0
carbs               0
source_url          0
scraped_at          0
dtype: int64

Nutrition summary after cleaning:

          calories    protein         fat       carbs
count   379.000000  379.00000  379.000000  379.000000
mean    493.424802   26.70343   23.244169   42.713720
std     222.134443   13.87972   15.463211   24.138651
min      49.000000    1.00000    1.000000    0.400000
25%     338.500000   17.00000   12.000000   24.000000
50%     455.000000   27.00000   19.000000   42.000000
75%     622.500000   36.00000   31.500000   58.000000
max    1394.000000   69.00000   89.000000  129.000000

Calories summary by class after cleaning:

            count    min     max        mean  median
food_class
burger         47  175.0  1080.0  526.936170   508.0
rice           47  164.0   834.0  470.404255   418.0
pasta          46  371.0  1140.0  625.173913   587.5
salad          45  111.0   838.0  404.444444   374.0
fries          44  120.0  1394.0  403.590909   379.0
chicken        41  239.0   707.0  409.243902   368.0
pizza          37  266.0   740.0  479.702703   462.0
sandwich       33  125.0  1256.0  632.909091   619.0
steak          25  253.0  1282.0  599.080000   510.0
sushi          14   49.0   862.0  359.000000   351.5

Cleaned candidate v1 saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/bbc_text_calorie_cleaned_candidate_v1.csv

Hard removed rows saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/logs/bbc_cleaning_v1_hard_removed.csv

In [20]:
# Cell 19 — Test one Skinnytaste recipe page scraper

def scrape_skinnytaste_recipe(url, food_class=None, query=None):
    """
    Scrape one Skinnytaste recipe page using JSON-LD when available.
    Returns a structured recipe record.
    """
    response = safe_get(url, sleep_min=1, sleep_max=2)

    if response is None:
        return None

    if response.status_code != 200:
        print("Failed URL:", url)
        print("Status code:", response.status_code)
        return None

    soup = BeautifulSoup(response.text, "html.parser")
    recipe_json = find_recipe_json_ld(soup)

    if recipe_json is None:
        print("No Recipe JSON-LD found for:", url)
        return None

    recipe_name = recipe_json.get("name")

    ingredients = recipe_json.get("recipeIngredient", [])
    if isinstance(ingredients, list):
        ingredients_text = " ".join([str(item) for item in ingredients])
    else:
        ingredients_text = str(ingredients)

    nutrition = recipe_json.get("nutrition", {})
    if not isinstance(nutrition, dict):
        nutrition = {}

    calories = extract_number(nutrition.get("calories"))
    protein = extract_number(nutrition.get("proteinContent"))
    fat = extract_number(nutrition.get("fatContent"))
    carbs = extract_number(nutrition.get("carbohydrateContent"))

    record = {
        "source_site": "skinnytaste",
        "food_class": food_class,
        "query": query,
        "recipe_name": recipe_name,
        "ingredients_text": ingredients_text,
        "calories": calories,
        "protein": protein,
        "fat": fat,
        "carbs": carbs,
        "source_url": url,
        "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    return record


# Use one known Skinnytaste burger link from the earlier refined search
test_skinnytaste_url = skinnytaste_burger_refined_df.iloc[0]["url"]

print("Testing Skinnytaste recipe URL:")
print(test_skinnytaste_url)

test_skinnytaste_record = scrape_skinnytaste_recipe(
    url=test_skinnytaste_url,
    food_class="burger",
    query="burger"
)

print("\nScraped Skinnytaste record:")
print(test_skinnytaste_record)

if test_skinnytaste_record is not None:
    print("\nIngredients length:", len(test_skinnytaste_record["ingredients_text"]))
    print("Calories:", test_skinnytaste_record["calories"])
    print("Protein:", test_skinnytaste_record["protein"])
    print("Fat:", test_skinnytaste_record["fat"])
    print("Carbs:", test_skinnytaste_record["carbs"])

Testing Skinnytaste recipe URL:
https://www.skinnytaste.com/spicy-black-bean-burgers-with-chipotle/

Scraped Skinnytaste record:
{'source_site': 'skinnytaste', 'food_class': 'burger', 'query': 'burger', 'recipe_name': 'Spicy Black Bean Burgers with Chipotle Mayonnaise', 'ingredients_text': "3 1/2 tbsp light mayonnaise (Hellman's) 1 tbsp canned chipotle in adobo sauce 16 oz can black beans (rinsed and drained) 1/2  red bell pepper (cut into 2 inch pieces) 1/2 cup chopped scallions 3 tbsp chopped cilantro 3 cloves garlic (peeled) 1  jumbo egg 1 tbsp cumin 1/4 to 1/2 tsp kosher salt 1 tsp hot sauce 1/2 cup quick oats (use gf oats for gluten free) 4  whole wheat 100 calorie buns (Martin's*) 1  small hass avocado (sliced thin)", 'calories': 362.5, 'protein': 18.0, 'fat': 14.0, 'carbs': 50.0, 'source_url': 'https://www.skinnytaste.com/spicy-black-bean-burgers-with-chipotle/', 'scraped_at': '2026-05-12 01:52:01'}

Ingredients length: 439
Calories: 362.5
Protein: 18.0
Fat: 14.0
Carbs: 50.0

In [21]:
# Cell 20 — Extract Skinnytaste links for classes that need supplementation

SUPPLEMENT_CLASSES = ["pizza", "sandwich", "steak", "sushi"]

CURRENT_CLEAN_COUNTS = cleaned_candidate_v1_df["food_class"].value_counts().to_dict()

SUPPLEMENT_TARGETS = {
    food_class: max(0, TARGET_RECORDS_PER_CLASS - CURRENT_CLEAN_COUNTS.get(food_class, 0))
    for food_class in SUPPLEMENT_CLASSES
}

SKINNYTASTE_SEARCH_QUERIES = {
    "pizza": [
        "pizza",
        "pepperoni pizza",
        "margherita pizza",
        "flatbread pizza",
        "pizza recipe"
    ],
    "sandwich": [
        "sandwich",
        "chicken sandwich",
        "turkey sandwich",
        "grilled cheese",
        "wrap"
    ],
    "steak": [
        "steak",
        "beef steak",
        "sirloin steak",
        "grilled steak",
        "steak recipe"
    ],
    "sushi": [
        "sushi",
        "sushi bowl",
        "sushi roll",
        "poke bowl",
        "salmon bowl",
        "tuna bowl"
    ]
}

print("Current clean counts:")
for food_class in SUPPLEMENT_CLASSES:
    print(food_class, "current:", CURRENT_CLEAN_COUNTS.get(food_class, 0), "needed:", SUPPLEMENT_TARGETS[food_class])

skinnytaste_supplement_links = {}

for food_class in SUPPLEMENT_CLASSES:
    print("\n====================================")
    print("Extracting Skinnytaste links for:", food_class)
    print("====================================")

    class_links = []

    for query in SKINNYTASTE_SEARCH_QUERIES[food_class]:
        print("\nQuery:", query)

        links_df = extract_refined_recipe_links_from_search(
            source_name="skinnytaste",
            query=query,
            max_links=20
        )

        if links_df is not None and not links_df.empty:
            class_links.append(links_df)

        time.sleep(1)

    if class_links:
        class_links_df = pd.concat(class_links, ignore_index=True)
        class_links_df = class_links_df.drop_duplicates(subset=["url"]).reset_index(drop=True)
    else:
        class_links_df = pd.DataFrame(columns=["source_name", "query", "title_text", "url"])

    skinnytaste_supplement_links[food_class] = class_links_df

    print("\nFinished:", food_class)
    print("Unique Skinnytaste links found:", len(class_links_df))

    if not class_links_df.empty:
        display(class_links_df.head(20))

print("\nSkinnytaste supplement link summary:")
for food_class, links_df in skinnytaste_supplement_links.items():
    print(food_class, "links:", len(links_df), "needed:", SUPPLEMENT_TARGETS[food_class])

Current clean counts:
pizza current: 37 needed: 13
sandwich current: 33 needed: 17
steak current: 25 needed: 25
sushi current: 14 needed: 36

====================================
Extracting Skinnytaste links for: pizza
====================================

Query: pizza
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=pizza
Status code: 200
HTML length: 577514
Refined recipe links found: 10

,source_name,query,title_text,url
0,skinnytaste,pizza,Chicken Crust Pizza,https://www.skinnytaste.com/chicken-crust-pizza/
1,skinnytaste,pizza,Breakfast Pizza (Packed With Protein!),https://www.skinnytaste.com/breakfast-pizza/
2,skinnytaste,pizza,Fruit Pizza,https://www.skinnytaste.com/fruit-pizza/
3,skinnytaste,pizza,The 4 Best Pizza Stones of 2024,https://www.skinnytaste.com/best-pizza-stones/
4,skinnytaste,pizza,Spicy Salmon Sushi Pizza,https://www.skinnytaste.com/spicy-salmon-sushi...
5,skinnytaste,pizza,Pizza Sausage Rolls,https://www.skinnytaste.com/pizza-sausage-rolls/
6,skinnytaste,pizza,Pepperoni Pizza Bites,https://www.skinnytaste.com/pepperoni-pizza-bi...
7,skinnytaste,pizza,Spaghetti Squash Crust Pizza,https://www.skinnytaste.com/spaghetti-squash-c...
8,skinnytaste,pizza,Margherita Pizza,https://www.skinnytaste.com/margherita-pizza/
9,skinnytaste,pizza,Thin Tortilla Pizza,https://www.skinnytaste.com/cast-iron-thin-cru...

Query: pepperoni pizza
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=pepperoni+pizza
Status code: 200
HTML length: 513851
Refined recipe links found: 1

,source_name,query,title_text,url
0,skinnytaste,pepperoni pizza,Pepperoni Pizza Bites,https://www.skinnytaste.com/pepperoni-pizza-bi...

Query: margherita pizza
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=margherita+pizza
Status code: 200
HTML length: 514350
Refined recipe links found: 1

,source_name,query,title_text,url
0,skinnytaste,margherita pizza,Margherita Pizza,https://www.skinnytaste.com/margherita-pizza/

Query: flatbread pizza
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=flatbread+pizza
Status code: 200
HTML length: 522600
Refined recipe links found: 2

,source_name,query,title_text,url
0,skinnytaste,flatbread pizza,Lavash Flatbread Pizzas,https://www.skinnytaste.com/lavash-flatbread-p...
1,skinnytaste,flatbread pizza,Smoked Salmon Breakfast Flatbread,https://www.skinnytaste.com/smoked-salmon-brea...

Query: pizza recipe
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=pizza+recipe
Status code: 200
HTML length: 582901
Refined recipe links found: 38

,source_name,query,title_text,url
0,skinnytaste,pizza recipe,Holiday Recipes,https://www.skinnytaste.com/holiday-recipes/
1,skinnytaste,pizza recipe,Saved Recipes,https://www.skinnytaste.com/how-to-view-your-s...
2,skinnytaste,pizza recipe,Beef Recipes,https://www.skinnytaste.com/main-ingredient/be...
3,skinnytaste,pizza recipe,Chicken Recipes,https://www.skinnytaste.com/main-ingredient/ch...
4,skinnytaste,pizza recipe,Fish Recipes,https://www.skinnytaste.com/main-ingredient/fi...
5,skinnytaste,pizza recipe,Lamb Recipes,https://www.skinnytaste.com/main-ingredient/la...
6,skinnytaste,pizza recipe,Pasta Recipes,https://www.skinnytaste.com/main-ingredient/pa...
7,skinnytaste,pizza recipe,Pork Recipes,https://www.skinnytaste.com/main-ingredient/po...
8,skinnytaste,pizza recipe,Pumpkin Recipes,https://www.skinnytaste.com/main-ingredient/pu...
9,skinnytaste,pizza recipe,Seafood Recipes,https://www.skinnytaste.com/main-ingredient/se...
10,skinnytaste,pizza recipe,Shrimp Recipes,https://www.skinnytaste.com/main-ingredient/sh...
11,skinnytaste,pizza recipe,Turkey Recipes,https://www.skinnytaste.com/main-ingredient/tu...
12,skinnytaste,pizza recipe,Grilling Recipes,https://www.skinnytaste.com/grilled-recipes/
13,skinnytaste,pizza recipe,One Pot Recipes,https://www.skinnytaste.com/one-pot/
14,skinnytaste,pizza recipe,Back To School,https://www.skinnytaste.com/holiday-recipes/ba...
15,skinnytaste,pizza recipe,Christmas,https://www.skinnytaste.com/holiday-recipes/ch...
16,skinnytaste,pizza recipe,Cinco De Mayo,https://www.skinnytaste.com/holiday-recipes/ci...
17,skinnytaste,pizza recipe,Easter Recipes,https://www.skinnytaste.com/holiday-recipes/ea...
18,skinnytaste,pizza recipe,Father’s Day,https://www.skinnytaste.com/holiday-recipes/fa...
19,skinnytaste,pizza recipe,Halloween,https://www.skinnytaste.com/holiday-recipes/ha...

Finished: pizza
Unique Skinnytaste links found: 42

,source_name,query,title_text,url
0,skinnytaste,pizza,Chicken Crust Pizza,https://www.skinnytaste.com/chicken-crust-pizza/
1,skinnytaste,pizza,Breakfast Pizza (Packed With Protein!),https://www.skinnytaste.com/breakfast-pizza/
2,skinnytaste,pizza,Fruit Pizza,https://www.skinnytaste.com/fruit-pizza/
3,skinnytaste,pizza,The 4 Best Pizza Stones of 2024,https://www.skinnytaste.com/best-pizza-stones/
4,skinnytaste,pizza,Spicy Salmon Sushi Pizza,https://www.skinnytaste.com/spicy-salmon-sushi...
5,skinnytaste,pizza,Pizza Sausage Rolls,https://www.skinnytaste.com/pizza-sausage-rolls/
6,skinnytaste,pizza,Pepperoni Pizza Bites,https://www.skinnytaste.com/pepperoni-pizza-bi...
7,skinnytaste,pizza,Spaghetti Squash Crust Pizza,https://www.skinnytaste.com/spaghetti-squash-c...
8,skinnytaste,pizza,Margherita Pizza,https://www.skinnytaste.com/margherita-pizza/
9,skinnytaste,pizza,Thin Tortilla Pizza,https://www.skinnytaste.com/cast-iron-thin-cru...
10,skinnytaste,flatbread pizza,Lavash Flatbread Pizzas,https://www.skinnytaste.com/lavash-flatbread-p...
11,skinnytaste,flatbread pizza,Smoked Salmon Breakfast Flatbread,https://www.skinnytaste.com/smoked-salmon-brea...
12,skinnytaste,pizza recipe,Holiday Recipes,https://www.skinnytaste.com/holiday-recipes/
13,skinnytaste,pizza recipe,Saved Recipes,https://www.skinnytaste.com/how-to-view-your-s...
14,skinnytaste,pizza recipe,Beef Recipes,https://www.skinnytaste.com/main-ingredient/be...
15,skinnytaste,pizza recipe,Chicken Recipes,https://www.skinnytaste.com/main-ingredient/ch...
16,skinnytaste,pizza recipe,Fish Recipes,https://www.skinnytaste.com/main-ingredient/fi...
17,skinnytaste,pizza recipe,Lamb Recipes,https://www.skinnytaste.com/main-ingredient/la...
18,skinnytaste,pizza recipe,Pasta Recipes,https://www.skinnytaste.com/main-ingredient/pa...
19,skinnytaste,pizza recipe,Pork Recipes,https://www.skinnytaste.com/main-ingredient/po...

====================================
Extracting Skinnytaste links for: sandwich
====================================

Query: sandwich
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=sandwich
Status code: 200
HTML length: 596544
Refined recipe links found: 10

,source_name,query,title_text,url
0,skinnytaste,sandwich,Grilled Chicken Sandwich,https://www.skinnytaste.com/grilled-chicken-sa...
1,skinnytaste,sandwich,English Muffin Breakfast Sandwich,https://www.skinnytaste.com/english-muffin-bre...
2,skinnytaste,sandwich,Open Faced Tuna Sandwich with Avocado,https://www.skinnytaste.com/open-faced-tuna-sa...
3,skinnytaste,sandwich,Air Fryer Salmon Fish Sandwich,https://www.skinnytaste.com/air-fryer-salmon-s...
4,skinnytaste,sandwich,Air Fryer Chicken Sandwich with Sriracha Mayo,https://www.skinnytaste.com/air-fryer-chicken-...
5,skinnytaste,sandwich,High Protein Bread (Oat Sandwich Rolls),https://www.skinnytaste.com/high-protein-bread...
6,skinnytaste,sandwich,Air Fryer Fried Shrimp Sandwich with Tartar Sauce,https://www.skinnytaste.com/air-fryer-shrimp-s...
7,skinnytaste,sandwich,Egg Tomato and Scallion Sandwich,https://www.skinnytaste.com/egg-tomato-and-sca...
8,skinnytaste,sandwich,Slow Cooker French Dip Sandwich with Carameliz...,https://www.skinnytaste.com/slow-cooker-french...
9,skinnytaste,sandwich,Bacon Egg and Avocado Breakfast Sandwich,https://www.skinnytaste.com/bacon-egg-and-avoc...

Query: chicken sandwich
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=chicken+sandwich
Status code: 200
HTML length: 592083
Refined recipe links found: 11

,source_name,query,title_text,url
0,skinnytaste,chicken sandwich,Chicken Recipes,https://www.skinnytaste.com/main-ingredient/ch...
1,skinnytaste,chicken sandwich,Grilled Chicken Sandwich,https://www.skinnytaste.com/grilled-chicken-sa...
2,skinnytaste,chicken sandwich,Air Fryer Chicken Sandwich with Sriracha Mayo,https://www.skinnytaste.com/air-fryer-chicken-...
3,skinnytaste,chicken sandwich,Grilled Chicken Sandwich with Avocado and Tomato,https://www.skinnytaste.com/grilled-chicken-sa...
4,skinnytaste,chicken sandwich,Chicken Club Lettuce Wrap Sandwich,https://www.skinnytaste.com/chicken-club-lettu...
5,skinnytaste,chicken sandwich,"Cubano Chicken (Pickle, Ham and Swiss Chicken ...",https://www.skinnytaste.com/cubano-chicken-pic...
6,skinnytaste,chicken sandwich,Classic Chicken Salad,https://www.skinnytaste.com/chicken-salad/
7,skinnytaste,chicken sandwich,Buffalo Chicken Salad,https://www.skinnytaste.com/buffalo-chicken-sa...
8,skinnytaste,chicken sandwich,Chicken Fajitas,https://www.skinnytaste.com/chicken-fajitas-45...
9,skinnytaste,chicken sandwich,Hot Chicken Philly Cheesesteak Dip,https://www.skinnytaste.com/hot-chicken-philly...
10,skinnytaste,chicken sandwich,Chicken Quesadilla,https://www.skinnytaste.com/chicken-quesadillas/

Query: turkey sandwich
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=turkey+sandwich
Status code: 200
HTML length: 586773
Refined recipe links found: 11

,source_name,query,title_text,url
0,skinnytaste,turkey sandwich,Turkey Recipes,https://www.skinnytaste.com/main-ingredient/tu...
1,skinnytaste,turkey sandwich,Turkey Cuban Sandwich,https://www.skinnytaste.com/skinny-turkey-cuba...
2,skinnytaste,turkey sandwich,English Muffin Breakfast Sandwich,https://www.skinnytaste.com/english-muffin-bre...
3,skinnytaste,turkey sandwich,Turkey Club,https://www.skinnytaste.com/turkey-club/
4,skinnytaste,turkey sandwich,Chicken Club Lettuce Wrap Sandwich,https://www.skinnytaste.com/chicken-club-lettu...
5,skinnytaste,turkey sandwich,Juicy Turkey Burgers with Zucchini,https://www.skinnytaste.com/turkey-burgers-wit...
6,skinnytaste,turkey sandwich,Open Faced Turkey Melts,https://www.skinnytaste.com/open-faced-turkey-...
7,skinnytaste,turkey sandwich,Turkey Meatballs,https://www.skinnytaste.com/skinny-italian-mea...
8,skinnytaste,turkey sandwich,Buffalo Turkey Cheeseburger with Blue Cheese B...,https://www.skinnytaste.com/buffalo-turkey-bur...
9,skinnytaste,turkey sandwich,Ground Turkey Taco Lettuce Wraps,https://www.skinnytaste.com/turkey-taco-lettuc...
10,skinnytaste,turkey sandwich,BLT Roll Ups with Turkey and Avocado,https://www.skinnytaste.com/blt-roll-ups-with-...

Query: grilled cheese
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=grilled+cheese
Status code: 200
HTML length: 590978
Refined recipe links found: 10

,source_name,query,title_text,url
0,skinnytaste,grilled cheese,Grilling Recipes,https://www.skinnytaste.com/grilled-recipes/
1,skinnytaste,grilled cheese,Grilled Rainbow Peppers with Herb Cream Cheese,https://www.skinnytaste.com/grilled-rainbow-pe...
2,skinnytaste,grilled cheese,Grilled Stone Fruit Salad with Honey Goat Chee...,https://www.skinnytaste.com/grilled-stone-frui...
3,skinnytaste,grilled cheese,Grilled Shrimp and Watermelon Chopped Salad,https://www.skinnytaste.com/grilled-shrimp-and...
4,skinnytaste,grilled cheese,Mexican-Inspired Grilled Corn Salad with Cotija,https://www.skinnytaste.com/mexican-inspired-g...
5,skinnytaste,grilled cheese,Grilled Eggplant with Feta,https://www.skinnytaste.com/grilled-eggplant-w...
6,skinnytaste,grilled cheese,"Grilled Chicken Tacos with Lettuce Slaw, Avoca...",https://www.skinnytaste.com/grilled-chicken-ta...
7,skinnytaste,grilled cheese,Grilled Pizza,https://www.skinnytaste.com/grilled-pizza/
8,skinnytaste,grilled cheese,Strawberries Spinach Salad with Grilled Chicken,https://www.skinnytaste.com/grilled-chicken-sa...
9,skinnytaste,grilled cheese,Gnocchi with Grilled Chicken in Roasted Red Pe...,https://www.skinnytaste.com/gnocchi-with-grill...

Query: wrap
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=wrap
Status code: 200
HTML length: 592761
Refined recipe links found: 10

,source_name,query,title_text,url
0,skinnytaste,wrap,Prosciutto Wrapped Stuffed Turkey Tenderloin R...,https://www.skinnytaste.com/stuffed-turkey-ten...
1,skinnytaste,wrap,11 Easy Lettuce Wraps,https://www.skinnytaste.com/lettuce-wraps/
2,skinnytaste,wrap,"Buffalo Chicken Lettuce Wraps (Slow Cooker, In...",https://www.skinnytaste.com/crock-pot-buffalo-...
3,skinnytaste,wrap,Asian Chicken Lettuce Wraps,https://www.skinnytaste.com/asian-chicken-lett...
4,skinnytaste,wrap,Bacon-Wrapped Air Fryer Chicken Breast,https://www.skinnytaste.com/bacon-wrapped-air-...
5,skinnytaste,wrap,Cheeseburger Crunch Wrap,https://www.skinnytaste.com/cheeseburger-crunc...
6,skinnytaste,wrap,Air Fryer Bacon Wrapped Pork Tenderloin,https://www.skinnytaste.com/air-fryer-bacon-wr...
7,skinnytaste,wrap,Shrimp Dumpling Bowls (or Lettuce Wraps),https://www.skinnytaste.com/shrimp-dumpling-le...
8,skinnytaste,wrap,Omelet Tortilla Breakfast Wrap,https://www.skinnytaste.com/omelet-tortilla-br...
9,skinnytaste,wrap,Tuna Salad Endive Wraps,https://www.skinnytaste.com/tuna-salad-wraps-2...

Finished: sandwich
Unique Skinnytaste links found: 48

,source_name,query,title_text,url
0,skinnytaste,sandwich,Grilled Chicken Sandwich,https://www.skinnytaste.com/grilled-chicken-sa...
1,skinnytaste,sandwich,English Muffin Breakfast Sandwich,https://www.skinnytaste.com/english-muffin-bre...
2,skinnytaste,sandwich,Open Faced Tuna Sandwich with Avocado,https://www.skinnytaste.com/open-faced-tuna-sa...
3,skinnytaste,sandwich,Air Fryer Salmon Fish Sandwich,https://www.skinnytaste.com/air-fryer-salmon-s...
4,skinnytaste,sandwich,Air Fryer Chicken Sandwich with Sriracha Mayo,https://www.skinnytaste.com/air-fryer-chicken-...
5,skinnytaste,sandwich,High Protein Bread (Oat Sandwich Rolls),https://www.skinnytaste.com/high-protein-bread...
6,skinnytaste,sandwich,Air Fryer Fried Shrimp Sandwich with Tartar Sauce,https://www.skinnytaste.com/air-fryer-shrimp-s...
7,skinnytaste,sandwich,Egg Tomato and Scallion Sandwich,https://www.skinnytaste.com/egg-tomato-and-sca...
8,skinnytaste,sandwich,Slow Cooker French Dip Sandwich with Carameliz...,https://www.skinnytaste.com/slow-cooker-french...
9,skinnytaste,sandwich,Bacon Egg and Avocado Breakfast Sandwich,https://www.skinnytaste.com/bacon-egg-and-avoc...
10,skinnytaste,chicken sandwich,Chicken Recipes,https://www.skinnytaste.com/main-ingredient/ch...
11,skinnytaste,chicken sandwich,Grilled Chicken Sandwich with Avocado and Tomato,https://www.skinnytaste.com/grilled-chicken-sa...
12,skinnytaste,chicken sandwich,Chicken Club Lettuce Wrap Sandwich,https://www.skinnytaste.com/chicken-club-lettu...
13,skinnytaste,chicken sandwich,"Cubano Chicken (Pickle, Ham and Swiss Chicken ...",https://www.skinnytaste.com/cubano-chicken-pic...
14,skinnytaste,chicken sandwich,Classic Chicken Salad,https://www.skinnytaste.com/chicken-salad/
15,skinnytaste,chicken sandwich,Buffalo Chicken Salad,https://www.skinnytaste.com/buffalo-chicken-sa...
16,skinnytaste,chicken sandwich,Chicken Fajitas,https://www.skinnytaste.com/chicken-fajitas-45...
17,skinnytaste,chicken sandwich,Hot Chicken Philly Cheesesteak Dip,https://www.skinnytaste.com/hot-chicken-philly...
18,skinnytaste,chicken sandwich,Chicken Quesadilla,https://www.skinnytaste.com/chicken-quesadillas/
19,skinnytaste,turkey sandwich,Turkey Recipes,https://www.skinnytaste.com/main-ingredient/tu...

====================================
Extracting Skinnytaste links for: steak
====================================

Query: steak
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=steak
Status code: 200
HTML length: 598600
Refined recipe links found: 10

,source_name,query,title_text,url
0,skinnytaste,steak,Fall Steak Salad with Sweet Potatoes,https://www.skinnytaste.com/fall-steak-salad-w...
1,skinnytaste,steak,Grilled Chimichurri Steak (Flank Steak),https://www.skinnytaste.com/grilled-flank-stea...
2,skinnytaste,steak,Grilled Skirt Steak and Elote Tacos,https://www.skinnytaste.com/skirt-steak-tacos/
3,skinnytaste,steak,"Salisbury Steak Meatballs (Instant Pot, Stove,...",https://www.skinnytaste.com/salisbury-steak-me...
4,skinnytaste,steak,Air Fryer Breaded Cubed Steak,https://www.skinnytaste.com/air-fryer-breaded-...
5,skinnytaste,steak,Air Fryer Steak,https://www.skinnytaste.com/air-fryer-steak/
6,skinnytaste,steak,Salisbury Steak with Mushroom Gravy,https://www.skinnytaste.com/skinny-salisbury-s...
7,skinnytaste,steak,"Grilled Steak With Tomatoes, Red Onion and Bal...",https://www.skinnytaste.com/grilled-flank-stea...
8,skinnytaste,steak,Grilled Flank Steak with Black Bean and Corn S...,https://www.skinnytaste.com/grilled-flank-stea...
9,skinnytaste,steak,Carne en Bistec – Colombian Steak with Onions ...,https://www.skinnytaste.com/carne-bistec-colom...

Query: beef steak
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=beef+steak
Status code: 200
HTML length: 597412
Refined recipe links found: 11

,source_name,query,title_text,url
0,skinnytaste,beef steak,Beef Recipes,https://www.skinnytaste.com/main-ingredient/be...
1,skinnytaste,beef steak,Grilled Chimichurri Steak (Flank Steak),https://www.skinnytaste.com/grilled-flank-stea...
2,skinnytaste,beef steak,Soy Marinated Flank Steak,https://www.skinnytaste.com/soy-marinated-flan...
3,skinnytaste,beef steak,Carne Asada Steak Salad,https://www.skinnytaste.com/carne-asada-steak-...
4,skinnytaste,beef steak,"Skirt Steak, Baby Bok Choy and Zucchini Stir-Fry",https://www.skinnytaste.com/skirt-steak-baby-b...
5,skinnytaste,beef steak,Grilled Steak Fajitas,https://www.skinnytaste.com/grilled-steak-faji...
6,skinnytaste,beef steak,Air Fryer Steak,https://www.skinnytaste.com/air-fryer-steak/
7,skinnytaste,beef steak,Loaded Philly Cheesesteak Baked Potato,https://www.skinnytaste.com/loaded-philly-chee...
8,skinnytaste,beef steak,"Salisbury Steak Meatballs (Instant Pot, Stove,...",https://www.skinnytaste.com/salisbury-steak-me...
9,skinnytaste,beef steak,Salisbury Steak with Mushroom Gravy,https://www.skinnytaste.com/skinny-salisbury-s...
10,skinnytaste,beef steak,Air Fryer Breaded Cubed Steak,https://www.skinnytaste.com/air-fryer-breaded-...

Query: sirloin steak
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=sirloin+steak
Status code: 200
HTML length: 524165
Refined recipe links found: 1

,source_name,query,title_text,url
0,skinnytaste,sirloin steak,Steak Taco Lettuce Wraps,https://www.skinnytaste.com/grilled-steak-lett...

Query: grilled steak
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=grilled+steak
Status code: 200
HTML length: 596851
Refined recipe links found: 11

,source_name,query,title_text,url
0,skinnytaste,grilled steak,Grilling Recipes,https://www.skinnytaste.com/grilled-recipes/
1,skinnytaste,grilled steak,"Grilled Steak With Tomatoes, Red Onion and Bal...",https://www.skinnytaste.com/grilled-flank-stea...
2,skinnytaste,grilled steak,Grilled Steak Fajitas,https://www.skinnytaste.com/grilled-steak-faji...
3,skinnytaste,grilled steak,Grilled Chimichurri Steak (Flank Steak),https://www.skinnytaste.com/grilled-flank-stea...
4,skinnytaste,grilled steak,Grilled Skirt Steak and Elote Tacos,https://www.skinnytaste.com/skirt-steak-tacos/
5,skinnytaste,grilled steak,Grilled Flank Steak with Black Bean and Corn S...,https://www.skinnytaste.com/grilled-flank-stea...
6,skinnytaste,grilled steak,Grilled Balsamic Steak with Tomatoes and Arugula,https://www.skinnytaste.com/grilled-balsamic-s...
7,skinnytaste,grilled steak,Soy Marinated Flank Steak,https://www.skinnytaste.com/soy-marinated-flan...
8,skinnytaste,grilled steak,Steak Taco Lettuce Wraps,https://www.skinnytaste.com/grilled-steak-lett...
9,skinnytaste,grilled steak,Steak & Caramelized Onions with Arugula and Pasta,https://www.skinnytaste.com/steak-caramelized-...
10,skinnytaste,grilled steak,Grilled Brussels Sprouts with Balsamic Glaze,https://www.skinnytaste.com/grilled-brussels-s...

Query: steak recipe
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=steak+recipe
Status code: 200
HTML length: 597215
Refined recipe links found: 38

,source_name,query,title_text,url
0,skinnytaste,steak recipe,Holiday Recipes,https://www.skinnytaste.com/holiday-recipes/
1,skinnytaste,steak recipe,Saved Recipes,https://www.skinnytaste.com/how-to-view-your-s...
2,skinnytaste,steak recipe,Beef Recipes,https://www.skinnytaste.com/main-ingredient/be...
3,skinnytaste,steak recipe,Chicken Recipes,https://www.skinnytaste.com/main-ingredient/ch...
4,skinnytaste,steak recipe,Fish Recipes,https://www.skinnytaste.com/main-ingredient/fi...
5,skinnytaste,steak recipe,Lamb Recipes,https://www.skinnytaste.com/main-ingredient/la...
6,skinnytaste,steak recipe,Pasta Recipes,https://www.skinnytaste.com/main-ingredient/pa...
7,skinnytaste,steak recipe,Pork Recipes,https://www.skinnytaste.com/main-ingredient/po...
8,skinnytaste,steak recipe,Pumpkin Recipes,https://www.skinnytaste.com/main-ingredient/pu...
9,skinnytaste,steak recipe,Seafood Recipes,https://www.skinnytaste.com/main-ingredient/se...
10,skinnytaste,steak recipe,Shrimp Recipes,https://www.skinnytaste.com/main-ingredient/sh...
11,skinnytaste,steak recipe,Turkey Recipes,https://www.skinnytaste.com/main-ingredient/tu...
12,skinnytaste,steak recipe,Grilling Recipes,https://www.skinnytaste.com/grilled-recipes/
13,skinnytaste,steak recipe,One Pot Recipes,https://www.skinnytaste.com/one-pot/
14,skinnytaste,steak recipe,Back To School,https://www.skinnytaste.com/holiday-recipes/ba...
15,skinnytaste,steak recipe,Christmas,https://www.skinnytaste.com/holiday-recipes/ch...
16,skinnytaste,steak recipe,Cinco De Mayo,https://www.skinnytaste.com/holiday-recipes/ci...
17,skinnytaste,steak recipe,Easter Recipes,https://www.skinnytaste.com/holiday-recipes/ea...
18,skinnytaste,steak recipe,Father’s Day,https://www.skinnytaste.com/holiday-recipes/fa...
19,skinnytaste,steak recipe,Halloween,https://www.skinnytaste.com/holiday-recipes/ha...

Finished: steak
Unique Skinnytaste links found: 47

,source_name,query,title_text,url
0,skinnytaste,steak,Fall Steak Salad with Sweet Potatoes,https://www.skinnytaste.com/fall-steak-salad-w...
1,skinnytaste,steak,Grilled Chimichurri Steak (Flank Steak),https://www.skinnytaste.com/grilled-flank-stea...
2,skinnytaste,steak,Grilled Skirt Steak and Elote Tacos,https://www.skinnytaste.com/skirt-steak-tacos/
3,skinnytaste,steak,"Salisbury Steak Meatballs (Instant Pot, Stove,...",https://www.skinnytaste.com/salisbury-steak-me...
4,skinnytaste,steak,Air Fryer Breaded Cubed Steak,https://www.skinnytaste.com/air-fryer-breaded-...
5,skinnytaste,steak,Air Fryer Steak,https://www.skinnytaste.com/air-fryer-steak/
6,skinnytaste,steak,Salisbury Steak with Mushroom Gravy,https://www.skinnytaste.com/skinny-salisbury-s...
7,skinnytaste,steak,"Grilled Steak With Tomatoes, Red Onion and Bal...",https://www.skinnytaste.com/grilled-flank-stea...
8,skinnytaste,steak,Grilled Flank Steak with Black Bean and Corn S...,https://www.skinnytaste.com/grilled-flank-stea...
9,skinnytaste,steak,Carne en Bistec – Colombian Steak with Onions ...,https://www.skinnytaste.com/carne-bistec-colom...
10,skinnytaste,beef steak,Beef Recipes,https://www.skinnytaste.com/main-ingredient/be...
11,skinnytaste,beef steak,Soy Marinated Flank Steak,https://www.skinnytaste.com/soy-marinated-flan...
12,skinnytaste,beef steak,Carne Asada Steak Salad,https://www.skinnytaste.com/carne-asada-steak-...
13,skinnytaste,beef steak,"Skirt Steak, Baby Bok Choy and Zucchini Stir-Fry",https://www.skinnytaste.com/skirt-steak-baby-b...
14,skinnytaste,beef steak,Grilled Steak Fajitas,https://www.skinnytaste.com/grilled-steak-faji...
15,skinnytaste,beef steak,Loaded Philly Cheesesteak Baked Potato,https://www.skinnytaste.com/loaded-philly-chee...
16,skinnytaste,sirloin steak,Steak Taco Lettuce Wraps,https://www.skinnytaste.com/grilled-steak-lett...
17,skinnytaste,grilled steak,Grilling Recipes,https://www.skinnytaste.com/grilled-recipes/
18,skinnytaste,grilled steak,Grilled Balsamic Steak with Tomatoes and Arugula,https://www.skinnytaste.com/grilled-balsamic-s...
19,skinnytaste,grilled steak,Steak & Caramelized Onions with Arugula and Pasta,https://www.skinnytaste.com/steak-caramelized-...

====================================
Extracting Skinnytaste links for: sushi
====================================

Query: sushi
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=sushi
Status code: 200
HTML length: 575553
Refined recipe links found: 1

,source_name,query,title_text,url
0,skinnytaste,sushi,Spicy Salmon Sushi Pizza,https://www.skinnytaste.com/spicy-salmon-sushi...

Query: sushi bowl
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=sushi+bowl
Status code: 200
HTML length: 514678
Refined recipe links found: 2

,source_name,query,title_text,url
0,skinnytaste,sushi bowl,Super Bowl Recipes,https://www.skinnytaste.com/holiday-recipes/su...
1,skinnytaste,sushi bowl,Spicy Canned Salmon Rice Bowl,https://www.skinnytaste.com/spicy-canned-salmo...

Query: sushi roll
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=sushi+roll
Status code: 200
HTML length: 514959
Refined recipe links found: 1

,source_name,query,title_text,url
0,skinnytaste,sushi roll,California Roll Cucumber Salad,https://www.skinnytaste.com/california-roll-cu...

Query: poke bowl
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=poke+bowl
Status code: 200
HTML length: 549237
Refined recipe links found: 5

,source_name,query,title_text,url
0,skinnytaste,poke bowl,Super Bowl Recipes,https://www.skinnytaste.com/holiday-recipes/su...
1,skinnytaste,poke bowl,Tofu Poke Bowl,https://www.skinnytaste.com/tofu-poke-bowl/
2,skinnytaste,poke bowl,Spicy Tuna Poke Bowl,https://www.skinnytaste.com/spicy-tuna-poke-bo...
3,skinnytaste,poke bowl,Ahi Poke Bowl with Mango,https://www.skinnytaste.com/ahi-poke-bowl/
4,skinnytaste,poke bowl,Shoyu Ahi Tuna Poke,https://www.skinnytaste.com/shoyu-aji-poke/

Query: salmon bowl
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=salmon+bowl
Status code: 200
HTML length: 587748
Refined recipe links found: 10

,source_name,query,title_text,url
0,skinnytaste,salmon bowl,Super Bowl Recipes,https://www.skinnytaste.com/holiday-recipes/su...
1,skinnytaste,salmon bowl,Teriyaki Salmon Bowl (Air Fryer or Oven),https://www.skinnytaste.com/teriyaki-salmon-bo...
2,skinnytaste,salmon bowl,Asian Salmon Bowl,https://www.skinnytaste.com/seattle-asian-salm...
3,skinnytaste,salmon bowl,Korean-Inspired Salmon Rice Bowl,https://www.skinnytaste.com/korean-salmon-rice...
4,skinnytaste,salmon bowl,"Honey Sriracha Roasted Salmon Rice Bowls (GF, DF)",https://www.skinnytaste.com/salmon-rice-bowls/
5,skinnytaste,salmon bowl,5-Minute Microwave Salmon Rice Bowl with Bok Choy,https://www.skinnytaste.com/microwave-salmon-r...
6,skinnytaste,salmon bowl,Spicy Canned Salmon Rice Bowl,https://www.skinnytaste.com/spicy-canned-salmo...
7,skinnytaste,salmon bowl,Seattle Smoked Salmon Chowder,https://www.skinnytaste.com/smoked-salmon-chow...
8,skinnytaste,salmon bowl,Baked Salmon Cakes,https://www.skinnytaste.com/baked-salmon-cakes/
9,skinnytaste,salmon bowl,Blackened Air Fryer Salmon Bites,https://www.skinnytaste.com/blackened-air-frye...

Query: tuna bowl
Source: skinnytaste
Search URL: https://www.skinnytaste.com/?s=tuna+bowl
Status code: 200
HTML length: 558505
Refined recipe links found: 6

,source_name,query,title_text,url
0,skinnytaste,tuna bowl,Super Bowl Recipes,https://www.skinnytaste.com/holiday-recipes/su...
1,skinnytaste,tuna bowl,Spicy Tuna Poke Bowl,https://www.skinnytaste.com/spicy-tuna-poke-bo...
2,skinnytaste,tuna bowl,Tuna Sub-in-a-Tub,https://www.skinnytaste.com/tuna-sub-in-a-tub/
3,skinnytaste,tuna bowl,Shoyu Ahi Tuna Poke,https://www.skinnytaste.com/shoyu-aji-poke/
4,skinnytaste,tuna bowl,Tofu Poke Bowl,https://www.skinnytaste.com/tofu-poke-bowl/
5,skinnytaste,tuna bowl,Ahi Poke Bowl with Mango,https://www.skinnytaste.com/ahi-poke-bowl/

Finished: sushi
Unique Skinnytaste links found: 17

,source_name,query,title_text,url
0,skinnytaste,sushi,Spicy Salmon Sushi Pizza,https://www.skinnytaste.com/spicy-salmon-sushi...
1,skinnytaste,sushi bowl,Super Bowl Recipes,https://www.skinnytaste.com/holiday-recipes/su...
2,skinnytaste,sushi bowl,Spicy Canned Salmon Rice Bowl,https://www.skinnytaste.com/spicy-canned-salmo...
3,skinnytaste,sushi roll,California Roll Cucumber Salad,https://www.skinnytaste.com/california-roll-cu...
4,skinnytaste,poke bowl,Tofu Poke Bowl,https://www.skinnytaste.com/tofu-poke-bowl/
5,skinnytaste,poke bowl,Spicy Tuna Poke Bowl,https://www.skinnytaste.com/spicy-tuna-poke-bo...
6,skinnytaste,poke bowl,Ahi Poke Bowl with Mango,https://www.skinnytaste.com/ahi-poke-bowl/
7,skinnytaste,poke bowl,Shoyu Ahi Tuna Poke,https://www.skinnytaste.com/shoyu-aji-poke/
8,skinnytaste,salmon bowl,Teriyaki Salmon Bowl (Air Fryer or Oven),https://www.skinnytaste.com/teriyaki-salmon-bo...
9,skinnytaste,salmon bowl,Asian Salmon Bowl,https://www.skinnytaste.com/seattle-asian-salm...
10,skinnytaste,salmon bowl,Korean-Inspired Salmon Rice Bowl,https://www.skinnytaste.com/korean-salmon-rice...
11,skinnytaste,salmon bowl,"Honey Sriracha Roasted Salmon Rice Bowls (GF, DF)",https://www.skinnytaste.com/salmon-rice-bowls/
12,skinnytaste,salmon bowl,5-Minute Microwave Salmon Rice Bowl with Bok Choy,https://www.skinnytaste.com/microwave-salmon-r...
13,skinnytaste,salmon bowl,Seattle Smoked Salmon Chowder,https://www.skinnytaste.com/smoked-salmon-chow...
14,skinnytaste,salmon bowl,Baked Salmon Cakes,https://www.skinnytaste.com/baked-salmon-cakes/
15,skinnytaste,salmon bowl,Blackened Air Fryer Salmon Bites,https://www.skinnytaste.com/blackened-air-frye...
16,skinnytaste,tuna bowl,Tuna Sub-in-a-Tub,https://www.skinnytaste.com/tuna-sub-in-a-tub/

Skinnytaste supplement link summary:
pizza links: 42 needed: 13
sandwich links: 48 needed: 17
steak links: 47 needed: 25
sushi links: 17 needed: 36

In [22]:
# Cell 21 — Scrape Skinnytaste supplement records for missing classes

def is_valid_skinnytaste_recipe_candidate_url(url):
    """
    Remove obvious non-recipe Skinnytaste URLs before scraping.
    """
    if url is None:
        return False

    parsed = urlparse(url)
    path = parsed.path.strip("/").lower()

    if not path:
        return False

    blocked_prefixes = [
        "holiday-recipes",
        "main-ingredient",
        "recipe-index",
        "category",
        "meal-plans",
        "shopping",
        "cookbook",
        "cookbooks",
        "how-to",
        "about",
        "contact",
        "privacy",
        "saved-recipes",
        "grilled-recipes",
        "one-pot",
    ]

    for prefix in blocked_prefixes:
        if path == prefix or path.startswith(prefix + "/"):
            return False

    blocked_exact_or_contains = [
        "best-pizza-stones",
        "how-to-view-your-saved-recipes",
    ]

    for blocked in blocked_exact_or_contains:
        if blocked in path:
            return False

    return True


def supplement_hard_reject_reason(row):
    """
    Extra hard rejection rules for Skinnytaste supplement records.
    This extends the earlier hard_reject_reason logic.
    """
    base_reason = hard_reject_reason(row)
    if base_reason is not None:
        return base_reason

    food_class = row["food_class"]
    name = row["normalized_recipe_name"]

    if food_class == "pizza":
        if "pizza stone" in name or "best pizza stones" in name:
            return "pizza_equipment_not_recipe"
        if "fruit pizza" in name:
            return "dessert_pizza"

    if food_class == "sandwich":
        if "bread" in name and "sandwich" not in name:
            return "bread_not_sandwich"
        if "recipes" in name:
            return "category_page_not_recipe"
        if "salad" in name and "sandwich" not in name and "wrap" not in name:
            return "salad_not_sandwich"
        if "quesadilla" in name:
            return "quesadilla_not_sandwich"
        if "fajitas" in name:
            return "fajita_not_sandwich"
        if "dip" in name:
            return "dip_not_sandwich"

    if food_class == "steak":
        if "recipes" in name:
            return "category_page_not_recipe"
        if "brussels sprouts" in name:
            return "vegetable_not_steak"
        if "pasta" in name:
            return "steak_pasta_dish"

    if food_class == "sushi":
        if "super bowl" in name:
            return "super_bowl_category_not_sushi"
        if "chowder" in name:
            return "chowder_not_sushi"
        if "salmon cakes" in name:
            return "salmon_cakes_not_sushi"
        if "salmon bites" in name:
            return "salmon_bites_not_sushi"
        if "tuna sub" in name:
            return "tuna_sub_not_sushi"
        if "sushi pizza" in name:
            return "sushi_pizza_hybrid"
        if "california roll cucumber salad" in name:
            return "sushi_style_salad_not_sushi"

    return None


def build_supplement_drop_reason(row):
    """
    Apply nutrition and supplement-specific hard rejection rules.
    """
    reasons = []

    nutrition_reason = nutrition_reject_reason(row)
    if nutrition_reason is not None:
        reasons.append(nutrition_reason)

    hard_reason = supplement_hard_reject_reason(row)
    if hard_reason is not None:
        reasons.append(hard_reason)

    if len(reasons) == 0:
        return ""

    return "|".join(reasons)


def scrape_skinnytaste_supplement_for_class(food_class, links_df, needed_records, existing_urls, existing_names):
    """
    Scrape Skinnytaste supplement records for one class.
    Keeps only clean, non-duplicate records.
    """
    accepted_records = []
    rejected_records = []
    failed_urls = []

    print("Supplement scraping class:", food_class)
    print("Needed records:", needed_records)
    print("Candidate links before URL filtering:", len(links_df))

    if needed_records <= 0:
        return accepted_records, rejected_records, failed_urls

    filtered_links_df = links_df.copy()
    filtered_links_df = filtered_links_df[
        filtered_links_df["url"].apply(is_valid_skinnytaste_recipe_candidate_url)
    ].drop_duplicates(subset=["url"]).reset_index(drop=True)

    print("Candidate links after URL filtering:", len(filtered_links_df))

    for idx, row in filtered_links_df.iterrows():
        if len(accepted_records) >= needed_records:
            break

        url = row["url"]
        query = row["query"]

        if url in existing_urls:
            print("\nSkipping existing URL:")
            print(url)
            continue

        print("\nScraping Skinnytaste URL:")
        print(url)

        record = scrape_skinnytaste_recipe(
            url=url,
            food_class=food_class,
            query=query
        )

        if record is None:
            failed_urls.append({
                "food_class": food_class,
                "query": query,
                "url": url,
                "reason": "scrape_failed"
            })
            print("Result: failed")
            continue

        record["normalized_recipe_name"] = normalize_text_for_filtering(record["recipe_name"])
        record["normalized_source_url"] = normalize_text_for_filtering(record["source_url"])

        normalized_name = record["normalized_recipe_name"]

        if normalized_name in existing_names:
            rejected_records.append({
                **record,
                "drop_reason": "duplicate_recipe_name_existing_dataset"
            })
            print("Result: rejected duplicate name")
            print("Recipe:", record["recipe_name"])
            continue

        drop_reason = build_supplement_drop_reason(record)

        if drop_reason != "":
            rejected_records.append({
                **record,
                "drop_reason": drop_reason
            })
            print("Result: rejected")
            print("Recipe:", record["recipe_name"])
            print("Reason:", drop_reason)
            continue

        accepted_clean_record = {
            "source_site": record["source_site"],
            "food_class": record["food_class"],
            "query": record["query"],
            "recipe_name": record["recipe_name"],
            "ingredients_text": record["ingredients_text"],
            "calories": record["calories"],
            "protein": record["protein"],
            "fat": record["fat"],
            "carbs": record["carbs"],
            "source_url": record["source_url"],
            "scraped_at": record["scraped_at"]
        }

        accepted_records.append(accepted_clean_record)
        existing_urls.add(url)
        existing_names.add(normalized_name)

        print("Result: accepted")
        print("Recipe:", record["recipe_name"])
        print("Calories:", record["calories"])
        print("Collected:", len(accepted_records), "/", needed_records)

    return accepted_records, rejected_records, failed_urls


existing_urls = set(cleaned_candidate_v1_df["source_url"].tolist())
existing_names = set(cleaned_candidate_v1_df["recipe_name"].apply(normalize_text_for_filtering).tolist())

skinnytaste_accepted_records = []
skinnytaste_rejected_records = []
skinnytaste_failed_urls = []

for food_class in SUPPLEMENT_CLASSES:
    print("\n====================================")
    print("Skinnytaste supplement for:", food_class)
    print("====================================")

    links_df = skinnytaste_supplement_links[food_class]
    needed_records = SUPPLEMENT_TARGETS[food_class]

    class_accepted, class_rejected, class_failed = scrape_skinnytaste_supplement_for_class(
        food_class=food_class,
        links_df=links_df,
        needed_records=needed_records,
        existing_urls=existing_urls,
        existing_names=existing_names
    )

    skinnytaste_accepted_records.extend(class_accepted)
    skinnytaste_rejected_records.extend(class_rejected)
    skinnytaste_failed_urls.extend(class_failed)

    print("\nFinished supplement class:", food_class)
    print("Accepted:", len(class_accepted))
    print("Rejected:", len(class_rejected))
    print("Failed:", len(class_failed))

skinnytaste_supplement_df = pd.DataFrame(skinnytaste_accepted_records)
skinnytaste_supplement_rejected_df = pd.DataFrame(skinnytaste_rejected_records)
skinnytaste_supplement_failed_df = pd.DataFrame(skinnytaste_failed_urls)

print("\nSkinnytaste supplement scraping finished.")
print("Accepted supplement shape:", skinnytaste_supplement_df.shape)

if not skinnytaste_supplement_df.empty:
    print("\nAccepted supplement records per class:")
    print(skinnytaste_supplement_df["food_class"].value_counts())

print("\nRejected supplement records:", len(skinnytaste_supplement_rejected_df))
print("Failed supplement URLs:", len(skinnytaste_supplement_failed_df))

skinnytaste_supplement_path = SCRAPED_RAW_DIR / "skinnytaste_text_calorie_supplement_raw.csv"
skinnytaste_rejected_path = LOGS_DIR / "skinnytaste_supplement_rejected_records.csv"
skinnytaste_failed_path = LOGS_DIR / "skinnytaste_supplement_failed_urls.csv"

skinnytaste_supplement_df.to_csv(skinnytaste_supplement_path, index=False)
skinnytaste_supplement_rejected_df.to_csv(skinnytaste_rejected_path, index=False)
skinnytaste_supplement_failed_df.to_csv(skinnytaste_failed_path, index=False)

print("\nSkinnytaste supplement saved to:")
print(skinnytaste_supplement_path)

print("\nSkinnytaste rejected log saved to:")
print(skinnytaste_rejected_path)

print("\nSkinnytaste failed URL log saved to:")
print(skinnytaste_failed_path)

if not skinnytaste_supplement_df.empty:
    display(skinnytaste_supplement_df[[
        "source_site",
        "food_class",
        "query",
        "recipe_name",
        "calories",
        "protein",
        "fat",
        "carbs",
        "source_url"
    ]])

====================================
Skinnytaste supplement for: pizza
====================================
Supplement scraping class: pizza
Needed records: 13
Candidate links before URL filtering: 42
Candidate links after URL filtering: 14

Scraping Skinnytaste URL:
https://www.skinnytaste.com/chicken-crust-pizza/
Result: accepted
Recipe: Chicken Crust Pizza with Veggies
Calories: 287.0
Collected: 1 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/breakfast-pizza/
Result: accepted
Recipe: Breakfast Pizza (Packed With Protein!)
Calories: 271.0
Collected: 2 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/fruit-pizza/
Result: rejected
Recipe: Fruit Pizza
Reason: dessert_pizza

Scraping Skinnytaste URL:
https://www.skinnytaste.com/spicy-salmon-sushi-pizza/
Result: accepted
Recipe: Spicy Salmon Sushi Pizza
Calories: 403.0
Collected: 3 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/pizza-sausage-rolls/
Result: accepted
Recipe: Pizza Sausage Rolls
Calories: 302.0
Collected: 4 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/pepperoni-pizza-bites/
Result: accepted
Recipe: Pepperoni Pizza Bites
Calories: 286.0
Collected: 5 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/spaghetti-squash-crust-pizza/
Result: accepted
Recipe: Spaghetti Squash Crust Pizza
Calories: 303.0
Collected: 6 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/margherita-pizza/
Result: accepted
Recipe: Margarita Pizza
Calories: 236.0
Collected: 7 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/cast-iron-thin-crust-pizza/
Result: accepted
Recipe: Tortilla Pizza Recipe
Calories: 118.0
Collected: 8 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/lavash-flatbread-pizzas/
Result: accepted
Recipe: Lavash Flatbread Pizzas
Calories: 192.0
Collected: 9 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/smoked-salmon-breakfast-flatbread/
Result: accepted
Recipe: Smoked Salmon Breakfast Flatbread
Calories: 247.0
Collected: 10 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/eggs-pizzaiola/
Result: accepted
Recipe: Eggs Pizzaiola
Calories: 266.0
Collected: 11 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/french-bread-pizza-mummies/
Result: accepted
Recipe: French Bread Pizza Mummies
Calories: 239.0
Collected: 12 / 13

Scraping Skinnytaste URL:
https://www.skinnytaste.com/seasons/spring/
No Recipe JSON-LD found for: https://www.skinnytaste.com/seasons/spring/
Result: failed

Finished supplement class: pizza
Accepted: 12
Rejected: 1
Failed: 1

====================================
Skinnytaste supplement for: sandwich
====================================
Supplement scraping class: sandwich
Needed records: 17
Candidate links before URL filtering: 48
Candidate links after URL filtering: 45

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-chicken-sandwich/
Result: accepted
Recipe: Grilled Chicken Sandwich Recipe
Calories: 406.0
Collected: 1 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/english-muffin-breakfast-sandwich/
Result: accepted
Recipe: English Muffin Breakfast Sandwich
Calories: 242.0
Collected: 2 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/open-faced-tuna-sandwich-with-avocado/
Result: accepted
Recipe: Open Faced Tuna Sandwich with Avocado
Calories: 247.0
Collected: 3 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/air-fryer-salmon-sandwich/
Result: accepted
Recipe: Air Fryer Salmon Fish Sandwich
Calories: 493.0
Collected: 4 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/air-fryer-chicken-sandwich/
Result: accepted
Recipe: Air Fryer Chicken Sandwich with Sriracha Mayo
Calories: 334.0
Collected: 5 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/high-protein-bread-oat-sandwich-rolls/
Result: accepted
Recipe: High Protein Bread (Oat Sandwich Rolls)
Calories: 135.5
Collected: 6 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/air-fryer-shrimp-sandwich-with-tartar-sauce/
Result: accepted
Recipe: Air Fryer Fried Shrimp Sandwich with Tartar Sauce
Calories: 352.0
Collected: 7 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/egg-tomato-and-scallion-sandwich/
Result: accepted
Recipe: Egg Tomato and Scallion Sandwich
Calories: 213.0
Collected: 8 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/slow-cooker-french-dip-sandwiches-with/
Result: rejected
Recipe: Slow Cooker French Dip Sandwich
Reason: dip_not_sandwich

Scraping Skinnytaste URL:
https://www.skinnytaste.com/bacon-egg-and-avocado-breakfast-sandwich/
Result: accepted
Recipe: Bacon Egg and Avocado Bagel Breakfast Sandwich
Calories: 369.0
Collected: 9 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-chicken-sandwich-with-avocado/
Result: accepted
Recipe: Grilled Chicken Sandwich with Avocado and Tomato
Calories: 253.0
Collected: 10 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/chicken-club-lettuce-wrap-sandwich/
Result: accepted
Recipe: Chicken Club Lettuce Wrap Sandwich
Calories: 274.0
Collected: 11 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/cubano-chicken-pickle-ham-and-swiss-chicken-roll-ups/
Result: accepted
Recipe: Pickle Ham and Swiss Chicken Roll Ups (Cuban Chicken)
Calories: 280.0
Collected: 12 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/chicken-salad/
Result: rejected
Recipe: Chicken Salad Recipe
Reason: salad_not_sandwich

Scraping Skinnytaste URL:
https://www.skinnytaste.com/buffalo-chicken-salad/
Result: rejected
Recipe: Buffalo Chicken Salad
Reason: salad_not_sandwich

Scraping Skinnytaste URL:
https://www.skinnytaste.com/chicken-fajitas-45-pts/
Result: rejected
Recipe: Chicken Fajitas
Reason: fajita_not_sandwich

Scraping Skinnytaste URL:
https://www.skinnytaste.com/hot-chicken-philly-cheesesteak-dip/
Result: rejected
Recipe: Hot Chicken Philly Cheesesteak Dip
Reason: dip_not_sandwich

Scraping Skinnytaste URL:
https://www.skinnytaste.com/chicken-quesadillas/
Result: rejected
Recipe: Chicken Quesadilla Recipe
Reason: quesadilla_not_sandwich

Scraping Skinnytaste URL:
https://www.skinnytaste.com/skinny-turkey-cuban-sandwich/
Result: accepted
Recipe: Turkey Cuban Sandwich
Calories: 429.0
Collected: 13 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/turkey-club/
Result: accepted
Recipe: Turkey Club
Calories: 351.0
Collected: 14 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/turkey-burgers-with-zucchini/
Result: accepted
Recipe: Turkey Burgers with Zucchini
Calories: 161.0
Collected: 15 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/open-faced-turkey-melts/
Result: accepted
Recipe: Open-Faced Turkey Melts
Calories: 263.0
Collected: 16 / 17

Scraping Skinnytaste URL:
https://www.skinnytaste.com/skinny-italian-meatballs-turkey-1-p/
Result: accepted
Recipe: Turkey Meatballs
Calories: 280.0
Collected: 17 / 17

Finished supplement class: sandwich
Accepted: 17
Rejected: 6
Failed: 0

====================================
Skinnytaste supplement for: steak
====================================
Supplement scraping class: steak
Needed records: 25
Candidate links before URL filtering: 47
Candidate links after URL filtering: 20

Scraping Skinnytaste URL:
https://www.skinnytaste.com/fall-steak-salad-with-sweet-potatoes/
Result: accepted
Recipe: Fall Steak Salad with Sweet Potatoes
Calories: 394.5
Collected: 1 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-flank-steak-with-chimichurri/
Result: accepted
Recipe: Grilled Chimichurri Flank Steak
Calories: 232.0
Collected: 2 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/skirt-steak-tacos/
Result: accepted
Recipe: Grilled Skirt Steak and Elote Tacos
Calories: 418.0
Collected: 3 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/salisbury-steak-meatballs-instant-pot-stove-top-slow-cooker/
Result: accepted
Recipe: Salisbury Steak Meatballs (Instant Pot, Stove Top, Slow Cooker)
Calories: 271.0
Collected: 4 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/air-fryer-breaded-cubed-steak/
Result: accepted
Recipe: Air Fryer Breaded Cubed Steak (bistec empanizado)
Calories: 328.0
Collected: 5 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/air-fryer-steak/
Result: accepted
Recipe: Air Fryer Steak
Calories: 221.0
Collected: 6 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/skinny-salisbury-steak-with-mushroom/
Result: accepted
Recipe: Salisbury Steak with Mushroom Gravy
Calories: 247.0
Collected: 7 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-flank-steak-with-tomatoes-red/
Result: accepted
Recipe: Grilled Steak With Tomatoes, Red Onion and Balsamic
Calories: 198.0
Collected: 8 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-flank-steak-with-black-beans/
Result: accepted
Recipe: Grilled Flank Steak with Black Bean and Corn Salsa
Calories: 250.0
Collected: 9 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/carne-bistec-colombian-steak-with/
Result: accepted
Recipe: Colombian Carne Bistec - Colombian Steak with Onions and Tomatoes
Calories: 188.0
Collected: 10 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/soy-marinated-flank-steak/
Result: accepted
Recipe: Soy Marinated Flank Steak
Calories: 279.0
Collected: 11 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/carne-asada-steak-salad/
Result: accepted
Recipe: Carne Asada Salad
Calories: 390.0
Collected: 12 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/skirt-steak-baby-bok-choy-and-zucchini/
Result: accepted
Recipe: Skirt Steak, Baby Bok Choy and Zucchini Stir-Fry
Calories: 317.0
Collected: 13 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-steak-fajitas/
Result: accepted
Recipe: Grilled Steak Fajitas
Calories: 468.0
Collected: 14 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/loaded-philly-cheesesteak-baked-potato/
Result: accepted
Recipe: Loaded Philly Cheesesteak Baked Potato
Calories: 390.0
Collected: 15 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-steak-lettuce-tacos/
Result: accepted
Recipe: Grilled Steak Lettuce Tacos
Calories: 256.0
Collected: 16 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-balsamic-steak-with-tomatoes-and-arugula/
Result: accepted
Recipe: Grilled Balsamic Steak with Tomatoes and Arugula
Calories: 215.0
Collected: 17 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/steak-caramelized-onions-with-arugula/
Result: accepted
Recipe: Steak & Caramelized Onions with Arugula and Penne
Calories: 384.0
Collected: 18 / 25

Scraping Skinnytaste URL:
https://www.skinnytaste.com/grilled-brussels-sprouts-with-balsamic-glaze/
Result: rejected
Recipe: Grilled Brussels Sprouts with Balsamic Glaze
Reason: vegetable_not_steak

Scraping Skinnytaste URL:
https://www.skinnytaste.com/seasons/spring/
No Recipe JSON-LD found for: https://www.skinnytaste.com/seasons/spring/
Result: failed

Finished supplement class: steak
Accepted: 18
Rejected: 1
Failed: 1

====================================
Skinnytaste supplement for: sushi
====================================
Supplement scraping class: sushi
Needed records: 36
Candidate links before URL filtering: 17
Candidate links after URL filtering: 16

Skipping existing URL:
https://www.skinnytaste.com/spicy-salmon-sushi-pizza/

Scraping Skinnytaste URL:
https://www.skinnytaste.com/spicy-canned-salmon-rice-bowl/
Result: accepted
Recipe: Spicy Canned Salmon Salad Rice Bowl
Calories: 389.0
Collected: 1 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/california-roll-cucumber-salad/
Result: rejected
Recipe: California Roll Cucumber Salad
Reason: sushi_style_salad_not_sushi

Scraping Skinnytaste URL:
https://www.skinnytaste.com/tofu-poke-bowl/
Result: accepted
Recipe: Tofu Poke Bowl
Calories: 520.0
Collected: 2 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/spicy-tuna-poke-bowls/
Result: accepted
Recipe: Spicy Tuna Poke Bowl
Calories: 397.0
Collected: 3 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/ahi-poke-bowl/
Result: accepted
Recipe: Ahi Poke Bowl with Mango
Calories: 527.0
Collected: 4 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/shoyu-aji-poke/
Result: accepted
Recipe: Shoyu Ahi Poke
Calories: 166.0
Collected: 5 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/teriyaki-salmon-bowl-air-fryer-or-oven/
Result: accepted
Recipe: Teriyaki Salmon Bowl (Air Fryer or Oven)
Calories: 491.0
Collected: 6 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/seattle-asian-salmon-bowl/
Result: accepted
Recipe: Seattle Asian Salmon Bowl
Calories: 395.0
Collected: 7 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/korean-salmon-rice-bowl/
Result: accepted
Recipe: Korean Salmon Rice Bowl
Calories: 431.0
Collected: 8 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/salmon-rice-bowls/
Result: accepted
Recipe: Honey Sriracha Roasted Salmon Rice Bowls
Calories: 506.0
Collected: 9 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/microwave-salmon-rice-bowl/
Result: accepted
Recipe: 5-Minute Microwave Salmon Rice Bowl
Calories: 533.0
Collected: 10 / 36

Scraping Skinnytaste URL:
https://www.skinnytaste.com/smoked-salmon-chowder/
Result: rejected
Recipe: Seattle Smoked Salmon Chowder
Reason: chowder_not_sushi

Scraping Skinnytaste URL:
https://www.skinnytaste.com/baked-salmon-cakes/
Result: rejected
Recipe: Baked Salmon Cakes
Reason: salmon_cakes_not_sushi

Scraping Skinnytaste URL:
https://www.skinnytaste.com/blackened-air-fryer-salmon-bites/
Result: rejected
Recipe: Blackened Air Fryer Salmon Bites
Reason: salmon_bites_not_sushi

Scraping Skinnytaste URL:
https://www.skinnytaste.com/tuna-sub-in-a-tub/
Result: rejected
Recipe: Tuna Sub-in-a-Tub
Reason: tuna_sub_not_sushi

Finished supplement class: sushi
Accepted: 10
Rejected: 5
Failed: 0

Skinnytaste supplement scraping finished.
Accepted supplement shape: (57, 11)

Accepted supplement records per class:
food_class
steak       18
sandwich    17
pizza       12
sushi       10
Name: count, dtype: int64

Rejected supplement records: 13
Failed supplement URLs: 2

Skinnytaste supplement saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/scraped_raw/skinnytaste_text_calorie_supplement_raw.csv

Skinnytaste rejected log saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/logs/skinnytaste_supplement_rejected_records.csv

Skinnytaste failed URL log saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/logs/skinnytaste_supplement_failed_urls.csv

,source_site,food_class,query,recipe_name,calories,protein,fat,carbs,source_url
0,skinnytaste,pizza,pizza,Chicken Crust Pizza with Veggies,287.0,34.0,14.50,7.0,https://www.skinnytaste.com/chicken-crust-pizza/
1,skinnytaste,pizza,pizza,Breakfast Pizza (Packed With Protein!),271.0,20.5,9.00,27.0,https://www.skinnytaste.com/breakfast-pizza/
2,skinnytaste,pizza,pizza,Spicy Salmon Sushi Pizza,403.0,24.5,26.50,17.0,https://www.skinnytaste.com/spicy-salmon-sushi...
3,skinnytaste,pizza,pizza,Pizza Sausage Rolls,302.0,22.0,10.00,30.0,https://www.skinnytaste.com/pizza-sausage-rolls/
4,skinnytaste,pizza,pizza,Pepperoni Pizza Bites,286.0,18.0,9.50,31.0,https://www.skinnytaste.com/pepperoni-pizza-bi...
5,skinnytaste,pizza,pizza,Spaghetti Squash Crust Pizza,303.0,28.0,17.00,18.0,https://www.skinnytaste.com/spaghetti-squash-c...
6,skinnytaste,pizza,pizza,Margarita Pizza,236.0,15.0,6.50,27.0,https://www.skinnytaste.com/margherita-pizza/
7,skinnytaste,pizza,pizza,Tortilla Pizza Recipe,118.0,4.5,5.00,15.5,https://www.skinnytaste.com/cast-iron-thin-cru...
8,skinnytaste,pizza,flatbread pizza,Lavash Flatbread Pizzas,192.0,12.0,5.00,24.0,https://www.skinnytaste.com/lavash-flatbread-p...
9,skinnytaste,pizza,flatbread pizza,Smoked Salmon Breakfast Flatbread,247.0,15.5,8.00,28.5,https://www.skinnytaste.com/smoked-salmon-brea...
10,skinnytaste,pizza,pizza recipe,Eggs Pizzaiola,266.0,19.0,15.00,13.0,https://www.skinnytaste.com/eggs-pizzaiola/
11,skinnytaste,pizza,pizza recipe,French Bread Pizza Mummies,239.0,10.0,8.00,32.0,https://www.skinnytaste.com/french-bread-pizza...
12,skinnytaste,sandwich,sandwich,Grilled Chicken Sandwich Recipe,406.0,45.0,11.50,29.5,https://www.skinnytaste.com/grilled-chicken-sa...
13,skinnytaste,sandwich,sandwich,English Muffin Breakfast Sandwich,242.0,18.5,9.50,29.5,https://www.skinnytaste.com/english-muffin-bre...
14,skinnytaste,sandwich,sandwich,Open Faced Tuna Sandwich with Avocado,247.0,18.0,8.00,28.0,https://www.skinnytaste.com/open-faced-tuna-sa...
15,skinnytaste,sandwich,sandwich,Air Fryer Salmon Fish Sandwich,493.0,33.0,24.00,31.5,https://www.skinnytaste.com/air-fryer-salmon-s...
16,skinnytaste,sandwich,sandwich,Air Fryer Chicken Sandwich with Sriracha Mayo,334.0,35.0,8.00,31.0,https://www.skinnytaste.com/air-fryer-chicken-...
17,skinnytaste,sandwich,sandwich,High Protein Bread (Oat Sandwich Rolls),135.5,10.5,3.00,18.0,https://www.skinnytaste.com/high-protein-bread...
18,skinnytaste,sandwich,sandwich,Air Fryer Fried Shrimp Sandwich with Tartar Sauce,352.0,34.5,9.35,33.5,https://www.skinnytaste.com/air-fryer-shrimp-s...
19,skinnytaste,sandwich,sandwich,Egg Tomato and Scallion Sandwich,213.0,13.5,9.50,21.0,https://www.skinnytaste.com/egg-tomato-and-sca...
20,skinnytaste,sandwich,sandwich,Bacon Egg and Avocado Bagel Breakfast Sandwich,369.0,25.0,16.00,30.0,https://www.skinnytaste.com/bacon-egg-and-avoc...
21,skinnytaste,sandwich,chicken sandwich,Grilled Chicken Sandwich with Avocado and Tomato,253.0,18.0,5.50,32.5,https://www.skinnytaste.com/grilled-chicken-sa...
22,skinnytaste,sandwich,chicken sandwich,Chicken Club Lettuce Wrap Sandwich,274.0,26.0,17.00,4.5,https://www.skinnytaste.com/chicken-club-lettu...
23,skinnytaste,sandwich,chicken sandwich,Pickle Ham and Swiss Chicken Roll Ups (Cuban C...,280.0,36.0,9.00,12.5,https://www.skinnytaste.com/cubano-chicken-pic...
24,skinnytaste,sandwich,turkey sandwich,Turkey Cuban Sandwich,429.0,47.0,11.00,35.0,https://www.skinnytaste.com/skinny-turkey-cuba...
25,skinnytaste,sandwich,turkey sandwich,Turkey Club,351.0,35.0,11.50,28.5,https://www.skinnytaste.com/turkey-club/
26,skinnytaste,sandwich,turkey sandwich,Turkey Burgers with Zucchini,161.0,18.0,7.00,4.5,https://www.skinnytaste.com/turkey-burgers-wit...
27,skinnytaste,sandwich,turkey sandwich,Open-Faced Turkey Melts,263.0,28.0,10.00,16.5,https://www.skinnytaste.com/open-faced-turkey-...
28,skinnytaste,sandwich,turkey sandwich,Turkey Meatballs,280.0,25.5,11.50,25.0,https://www.skinnytaste.com/skinny-italian-mea...
29,skinnytaste,steak,steak,Fall Steak Salad with Sweet Potatoes,394.5,33.5,17.50,26.0,https://www.skinnytaste.com/fall-steak-salad-w...
30,skinnytaste,steak,steak,Grilled Chimichurri Flank Steak,232.0,24.0,14.00,1.0,https://www.skinnytaste.com/grilled-flank-stea...
31,skinnytaste,steak,steak,Grilled Skirt Steak and Elote Tacos,418.0,31.0,19.50,33.5,https://www.skinnytaste.com/skirt-steak-tacos/
32,skinnytaste,steak,steak,"Salisbury Steak Meatballs (Instant Pot, Stove ...",271.0,28.0,12.00,12.0,https://www.skinnytaste.com/salisbury-steak-me...
33,skinnytaste,steak,steak,Air Fryer Breaded Cubed Steak (bistec empanizado),328.0,33.0,14.00,15.5,https://www.skinnytaste.com/air-fryer-breaded-...
34,skinnytaste,steak,steak,Air Fryer Steak,221.0,39.5,7.00,0.5,https://www.skinnytaste.com/air-fryer-steak/
35,skinnytaste,steak,steak,Salisbury Steak with Mushroom Gravy,247.0,27.0,11.00,10.5,https://www.skinnytaste.com/skinny-salisbury-s...
36,skinnytaste,steak,steak,"Grilled Steak With Tomatoes, Red Onion and Bal...",198.0,25.0,9.00,3.0,https://www.skinnytaste.com/grilled-flank-stea...
37,skinnytaste,steak,steak,Grilled Flank Steak with Black Bean and Corn S...,250.0,25.5,9.50,9.0,https://www.skinnytaste.com/grilled-flank-stea...
38,skinnytaste,steak,steak,Colombian Carne Bistec - Colombian Steak with ...,188.0,25.2,7.20,3.0,https://www.skinnytaste.com/carne-bistec-colom...
39,skinnytaste,steak,beef steak,Soy Marinated Flank Steak,279.0,35.5,12.00,8.0,https://www.skinnytaste.com/soy-marinated-flan...
40,skinnytaste,steak,beef steak,Carne Asada Salad,390.0,38.0,21.50,12.0,https://www.skinnytaste.com/carne-asada-steak-...
41,skinnytaste,steak,beef steak,"Skirt Steak, Baby Bok Choy and Zucchini Stir-Fry",317.0,32.0,12.00,25.0,https://www.skinnytaste.com/skirt-steak-baby-b...
42,skinnytaste,steak,beef steak,Grilled Steak Fajitas,468.0,31.5,17.00,47.5,https://www.skinnytaste.com/grilled-steak-faji...
43,skinnytaste,steak,beef steak,Loaded Philly Cheesesteak Baked Potato,390.0,26.0,13.00,44.0,https://www.skinnytaste.com/loaded-philly-chee...
44,skinnytaste,steak,sirloin steak,Grilled Steak Lettuce Tacos,256.0,25.0,14.00,7.0,https://www.skinnytaste.com/grilled-steak-lett...
45,skinnytaste,steak,grilled steak,Grilled Balsamic Steak with Tomatoes and Arugula,215.0,24.0,12.00,3.0,https://www.skinnytaste.com/grilled-balsamic-s...
46,skinnytaste,steak,grilled steak,Steak & Caramelized Onions with Arugula and Penne,384.0,30.0,15.00,29.5,https://www.skinnytaste.com/steak-caramelized-...
47,skinnytaste,sushi,sushi bowl,Spicy Canned Salmon Salad Rice Bowl,389.0,25.0,14.00,39.0,https://www.skinnytaste.com/spicy-canned-salmo...
48,skinnytaste,sushi,poke bowl,Tofu Poke Bowl,520.0,29.0,24.00,47.0,https://www.skinnytaste.com/tofu-poke-bowl/
49,skinnytaste,sushi,poke bowl,Spicy Tuna Poke Bowl,397.0,32.5,14.50,33.5,https://www.skinnytaste.com/spicy-tuna-poke-bo...
50,skinnytaste,sushi,poke bowl,Ahi Poke Bowl with Mango,527.0,34.0,19.00,60.0,https://www.skinnytaste.com/ahi-poke-bowl/
51,skinnytaste,sushi,poke bowl,Shoyu Ahi Poke,166.0,28.5,4.00,2.5,https://www.skinnytaste.com/shoyu-aji-poke/
52,skinnytaste,sushi,salmon bowl,Teriyaki Salmon Bowl (Air Fryer or Oven),491.0,33.0,10.00,62.5,https://www.skinnytaste.com/teriyaki-salmon-bo...
53,skinnytaste,sushi,salmon bowl,Seattle Asian Salmon Bowl,395.0,27.0,17.00,31.0,https://www.skinnytaste.com/seattle-asian-salm...
54,skinnytaste,sushi,salmon bowl,Korean Salmon Rice Bowl,431.0,33.0,10.00,50.0,https://www.skinnytaste.com/korean-salmon-rice...
55,skinnytaste,sushi,salmon bowl,Honey Sriracha Roasted Salmon Rice Bowls,506.0,38.5,17.50,48.0,https://www.skinnytaste.com/salmon-rice-bowls/
56,skinnytaste,sushi,salmon bowl,5-Minute Microwave Salmon Rice Bowl,533.0,48.5,18.00,51.0,https://www.skinnytaste.com/microwave-salmon-r...

In [23]:
# Cell 22 — Audit Skinnytaste supplement before merging

supplement_audit_df = skinnytaste_supplement_df.copy()

print("Skinnytaste supplement shape:")
print(supplement_audit_df.shape)

print("\nRecords per class:")
print(supplement_audit_df["food_class"].value_counts())

print("\nMissing values:")
print(supplement_audit_df.isna().sum())

print("\nDuplicate source URLs:")
print(supplement_audit_df["source_url"].duplicated().sum())

print("\nDuplicate recipe names:")
print(supplement_audit_df["recipe_name"].duplicated().sum())

print("\nNutrition summary:")
display(supplement_audit_df[["calories", "protein", "fat", "carbs"]].describe())

SUPPLEMENT_REVIEW_KEYWORDS = {
    "pizza": [
        "sushi pizza",
        "fruit pizza"
    ],
    "sandwich": [
        "bread",
        "burger",
        "burgers",
        "meatballs",
        "roll ups"
    ],
    "steak": [
        "baked potato",
        "pasta",
        "salad"
    ],
    "sushi": [
        "poke",
        "salmon bowl",
        "rice bowl",
        "salad rice bowl"
    ]
}

def is_supplement_review_needed(row):
    food_class = row["food_class"]
    name = normalize_text_for_filtering(row["recipe_name"])
    url = normalize_text_for_filtering(row["source_url"])
    combined = name + " " + url

    keywords = SUPPLEMENT_REVIEW_KEYWORDS.get(food_class, [])

    for keyword in keywords:
        if keyword in combined:
            return True

    return False

supplement_audit_df["needs_manual_review"] = supplement_audit_df.apply(
    is_supplement_review_needed,
    axis=1
)

print("\nManual review summary:")
print(supplement_audit_df.groupby("food_class")["needs_manual_review"].value_counts())

print("\nRecords needing manual review:")
review_df = supplement_audit_df[supplement_audit_df["needs_manual_review"] == True]

display(review_df[[
    "source_site",
    "food_class",
    "query",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url"
]].sort_values(["food_class", "recipe_name"]))

print("\nClean-looking supplement records:")
clean_looking_supplement_df = supplement_audit_df[
    supplement_audit_df["needs_manual_review"] == False
].copy()

display(clean_looking_supplement_df[[
    "source_site",
    "food_class",
    "query",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url"
]].sort_values(["food_class", "recipe_name"]))

Skinnytaste supplement shape:
(57, 11)

Records per class:
food_class
steak       18
sandwich    17
pizza       12
sushi       10
Name: count, dtype: int64

Missing values:
source_site         0
food_class          0
query               0
recipe_name         0
ingredients_text    0
calories            0
protein             0
fat                 0
carbs               0
source_url          0
scraped_at          0
dtype: int64

Duplicate source URLs:
0

Duplicate recipe names:
0

Nutrition summary:

         calories    protein        fat      carbs
count   57.000000  57.000000  57.000000  57.000000
mean   316.385965  27.231579  12.290351  24.482456
std    104.727368   9.115022   5.139582  15.333776
min    118.000000   4.500000   3.000000   0.500000
25%    247.000000  22.000000   9.000000  12.000000
50%    286.000000  27.000000  11.500000  27.000000
75%    394.500000  33.000000  15.000000  32.000000
max    533.000000  48.500000  26.500000  62.500000

Manual review summary:
food_class  needs_manual_review
pizza       False                  11
            True                    1
sandwich    False                  13
            True                    4
steak       False                  15
            True                    3
sushi       True                   10
Name: count, dtype: int64

Records needing manual review:

,source_site,food_class,query,recipe_name,calories,protein,fat,carbs,source_url
2,skinnytaste,pizza,pizza,Spicy Salmon Sushi Pizza,403.0,24.5,26.5,17.0,https://www.skinnytaste.com/spicy-salmon-sushi...
17,skinnytaste,sandwich,sandwich,High Protein Bread (Oat Sandwich Rolls),135.5,10.5,3.0,18.0,https://www.skinnytaste.com/high-protein-bread...
23,skinnytaste,sandwich,chicken sandwich,Pickle Ham and Swiss Chicken Roll Ups (Cuban C...,280.0,36.0,9.0,12.5,https://www.skinnytaste.com/cubano-chicken-pic...
26,skinnytaste,sandwich,turkey sandwich,Turkey Burgers with Zucchini,161.0,18.0,7.0,4.5,https://www.skinnytaste.com/turkey-burgers-wit...
28,skinnytaste,sandwich,turkey sandwich,Turkey Meatballs,280.0,25.5,11.5,25.0,https://www.skinnytaste.com/skinny-italian-mea...
40,skinnytaste,steak,beef steak,Carne Asada Salad,390.0,38.0,21.5,12.0,https://www.skinnytaste.com/carne-asada-steak-...
29,skinnytaste,steak,steak,Fall Steak Salad with Sweet Potatoes,394.5,33.5,17.5,26.0,https://www.skinnytaste.com/fall-steak-salad-w...
43,skinnytaste,steak,beef steak,Loaded Philly Cheesesteak Baked Potato,390.0,26.0,13.0,44.0,https://www.skinnytaste.com/loaded-philly-chee...
56,skinnytaste,sushi,salmon bowl,5-Minute Microwave Salmon Rice Bowl,533.0,48.5,18.0,51.0,https://www.skinnytaste.com/microwave-salmon-r...
50,skinnytaste,sushi,poke bowl,Ahi Poke Bowl with Mango,527.0,34.0,19.0,60.0,https://www.skinnytaste.com/ahi-poke-bowl/
55,skinnytaste,sushi,salmon bowl,Honey Sriracha Roasted Salmon Rice Bowls,506.0,38.5,17.5,48.0,https://www.skinnytaste.com/salmon-rice-bowls/
54,skinnytaste,sushi,salmon bowl,Korean Salmon Rice Bowl,431.0,33.0,10.0,50.0,https://www.skinnytaste.com/korean-salmon-rice...
53,skinnytaste,sushi,salmon bowl,Seattle Asian Salmon Bowl,395.0,27.0,17.0,31.0,https://www.skinnytaste.com/seattle-asian-salm...
51,skinnytaste,sushi,poke bowl,Shoyu Ahi Poke,166.0,28.5,4.0,2.5,https://www.skinnytaste.com/shoyu-aji-poke/
47,skinnytaste,sushi,sushi bowl,Spicy Canned Salmon Salad Rice Bowl,389.0,25.0,14.0,39.0,https://www.skinnytaste.com/spicy-canned-salmo...
49,skinnytaste,sushi,poke bowl,Spicy Tuna Poke Bowl,397.0,32.5,14.5,33.5,https://www.skinnytaste.com/spicy-tuna-poke-bo...
52,skinnytaste,sushi,salmon bowl,Teriyaki Salmon Bowl (Air Fryer or Oven),491.0,33.0,10.0,62.5,https://www.skinnytaste.com/teriyaki-salmon-bo...
48,skinnytaste,sushi,poke bowl,Tofu Poke Bowl,520.0,29.0,24.0,47.0,https://www.skinnytaste.com/tofu-poke-bowl/

Clean-looking supplement records:

,source_site,food_class,query,recipe_name,calories,protein,fat,carbs,source_url
1,skinnytaste,pizza,pizza,Breakfast Pizza (Packed With Protein!),271.0,20.5,9.00,27.0,https://www.skinnytaste.com/breakfast-pizza/
0,skinnytaste,pizza,pizza,Chicken Crust Pizza with Veggies,287.0,34.0,14.50,7.0,https://www.skinnytaste.com/chicken-crust-pizza/
10,skinnytaste,pizza,pizza recipe,Eggs Pizzaiola,266.0,19.0,15.00,13.0,https://www.skinnytaste.com/eggs-pizzaiola/
11,skinnytaste,pizza,pizza recipe,French Bread Pizza Mummies,239.0,10.0,8.00,32.0,https://www.skinnytaste.com/french-bread-pizza...
8,skinnytaste,pizza,flatbread pizza,Lavash Flatbread Pizzas,192.0,12.0,5.00,24.0,https://www.skinnytaste.com/lavash-flatbread-p...
6,skinnytaste,pizza,pizza,Margarita Pizza,236.0,15.0,6.50,27.0,https://www.skinnytaste.com/margherita-pizza/
4,skinnytaste,pizza,pizza,Pepperoni Pizza Bites,286.0,18.0,9.50,31.0,https://www.skinnytaste.com/pepperoni-pizza-bi...
3,skinnytaste,pizza,pizza,Pizza Sausage Rolls,302.0,22.0,10.00,30.0,https://www.skinnytaste.com/pizza-sausage-rolls/
9,skinnytaste,pizza,flatbread pizza,Smoked Salmon Breakfast Flatbread,247.0,15.5,8.00,28.5,https://www.skinnytaste.com/smoked-salmon-brea...
5,skinnytaste,pizza,pizza,Spaghetti Squash Crust Pizza,303.0,28.0,17.00,18.0,https://www.skinnytaste.com/spaghetti-squash-c...
7,skinnytaste,pizza,pizza,Tortilla Pizza Recipe,118.0,4.5,5.00,15.5,https://www.skinnytaste.com/cast-iron-thin-cru...
16,skinnytaste,sandwich,sandwich,Air Fryer Chicken Sandwich with Sriracha Mayo,334.0,35.0,8.00,31.0,https://www.skinnytaste.com/air-fryer-chicken-...
18,skinnytaste,sandwich,sandwich,Air Fryer Fried Shrimp Sandwich with Tartar Sauce,352.0,34.5,9.35,33.5,https://www.skinnytaste.com/air-fryer-shrimp-s...
15,skinnytaste,sandwich,sandwich,Air Fryer Salmon Fish Sandwich,493.0,33.0,24.00,31.5,https://www.skinnytaste.com/air-fryer-salmon-s...
20,skinnytaste,sandwich,sandwich,Bacon Egg and Avocado Bagel Breakfast Sandwich,369.0,25.0,16.00,30.0,https://www.skinnytaste.com/bacon-egg-and-avoc...
22,skinnytaste,sandwich,chicken sandwich,Chicken Club Lettuce Wrap Sandwich,274.0,26.0,17.00,4.5,https://www.skinnytaste.com/chicken-club-lettu...
19,skinnytaste,sandwich,sandwich,Egg Tomato and Scallion Sandwich,213.0,13.5,9.50,21.0,https://www.skinnytaste.com/egg-tomato-and-sca...
13,skinnytaste,sandwich,sandwich,English Muffin Breakfast Sandwich,242.0,18.5,9.50,29.5,https://www.skinnytaste.com/english-muffin-bre...
12,skinnytaste,sandwich,sandwich,Grilled Chicken Sandwich Recipe,406.0,45.0,11.50,29.5,https://www.skinnytaste.com/grilled-chicken-sa...
21,skinnytaste,sandwich,chicken sandwich,Grilled Chicken Sandwich with Avocado and Tomato,253.0,18.0,5.50,32.5,https://www.skinnytaste.com/grilled-chicken-sa...
14,skinnytaste,sandwich,sandwich,Open Faced Tuna Sandwich with Avocado,247.0,18.0,8.00,28.0,https://www.skinnytaste.com/open-faced-tuna-sa...
27,skinnytaste,sandwich,turkey sandwich,Open-Faced Turkey Melts,263.0,28.0,10.00,16.5,https://www.skinnytaste.com/open-faced-turkey-...
25,skinnytaste,sandwich,turkey sandwich,Turkey Club,351.0,35.0,11.50,28.5,https://www.skinnytaste.com/turkey-club/
24,skinnytaste,sandwich,turkey sandwich,Turkey Cuban Sandwich,429.0,47.0,11.00,35.0,https://www.skinnytaste.com/skinny-turkey-cuba...
33,skinnytaste,steak,steak,Air Fryer Breaded Cubed Steak (bistec empanizado),328.0,33.0,14.00,15.5,https://www.skinnytaste.com/air-fryer-breaded-...
34,skinnytaste,steak,steak,Air Fryer Steak,221.0,39.5,7.00,0.5,https://www.skinnytaste.com/air-fryer-steak/
38,skinnytaste,steak,steak,Colombian Carne Bistec - Colombian Steak with ...,188.0,25.2,7.20,3.0,https://www.skinnytaste.com/carne-bistec-colom...
45,skinnytaste,steak,grilled steak,Grilled Balsamic Steak with Tomatoes and Arugula,215.0,24.0,12.00,3.0,https://www.skinnytaste.com/grilled-balsamic-s...
30,skinnytaste,steak,steak,Grilled Chimichurri Flank Steak,232.0,24.0,14.00,1.0,https://www.skinnytaste.com/grilled-flank-stea...
37,skinnytaste,steak,steak,Grilled Flank Steak with Black Bean and Corn S...,250.0,25.5,9.50,9.0,https://www.skinnytaste.com/grilled-flank-stea...
31,skinnytaste,steak,steak,Grilled Skirt Steak and Elote Tacos,418.0,31.0,19.50,33.5,https://www.skinnytaste.com/skirt-steak-tacos/
42,skinnytaste,steak,beef steak,Grilled Steak Fajitas,468.0,31.5,17.00,47.5,https://www.skinnytaste.com/grilled-steak-faji...
44,skinnytaste,steak,sirloin steak,Grilled Steak Lettuce Tacos,256.0,25.0,14.00,7.0,https://www.skinnytaste.com/grilled-steak-lett...
36,skinnytaste,steak,steak,"Grilled Steak With Tomatoes, Red Onion and Bal...",198.0,25.0,9.00,3.0,https://www.skinnytaste.com/grilled-flank-stea...
32,skinnytaste,steak,steak,"Salisbury Steak Meatballs (Instant Pot, Stove ...",271.0,28.0,12.00,12.0,https://www.skinnytaste.com/salisbury-steak-me...
35,skinnytaste,steak,steak,Salisbury Steak with Mushroom Gravy,247.0,27.0,11.00,10.5,https://www.skinnytaste.com/skinny-salisbury-s...
41,skinnytaste,steak,beef steak,"Skirt Steak, Baby Bok Choy and Zucchini Stir-Fry",317.0,32.0,12.00,25.0,https://www.skinnytaste.com/skirt-steak-baby-b...
39,skinnytaste,steak,beef steak,Soy Marinated Flank Steak,279.0,35.5,12.00,8.0,https://www.skinnytaste.com/soy-marinated-flan...
46,skinnytaste,steak,grilled steak,Steak & Caramelized Onions with Arugula and Penne,384.0,30.0,15.00,29.5,https://www.skinnytaste.com/steak-caramelized-...

In [24]:
# Cell 23 — Clean Skinnytaste supplement and merge with BBC cleaned candidate

supplement_clean_work_df = skinnytaste_supplement_df.copy()

SUPPLEMENT_REMOVE_RECIPE_NAMES = [
    # Pizza hybrid / weak pizza
    "Spicy Salmon Sushi Pizza",

    # Sandwich weak/non-sandwich items
    "High Protein Bread (Oat Sandwich Rolls)",
    "Pickle Ham and Swiss Chicken Roll Ups (Cuban Chicken)",
    "Turkey Burgers with Zucchini",
    "Turkey Meatballs",

    # Steak weak/non-steak-plate items
    "Fall Steak Salad with Sweet Potatoes",
    "Carne Asada Salad",
    "Loaded Philly Cheesesteak Baked Potato",
    "Steak & Caramelized Onions with Arugula and Penne",
]

# Remove all Skinnytaste sushi supplement for now because it is mostly poke/salmon/rice bowls, not direct sushi.
remove_by_name_mask = supplement_clean_work_df["recipe_name"].isin(SUPPLEMENT_REMOVE_RECIPE_NAMES)
remove_sushi_mask = supplement_clean_work_df["food_class"] == "sushi"

supplement_removed_manual_df = supplement_clean_work_df[
    remove_by_name_mask | remove_sushi_mask
].copy()

skinnytaste_supplement_clean_v1_df = supplement_clean_work_df[
    ~(remove_by_name_mask | remove_sushi_mask)
].copy().reset_index(drop=True)

print("Original Skinnytaste supplement shape:")
print(supplement_clean_work_df.shape)

print("\nManually removed supplement records:")
print(supplement_removed_manual_df.shape)

print("\nManual removal records per class:")
if not supplement_removed_manual_df.empty:
    print(supplement_removed_manual_df["food_class"].value_counts())

display(supplement_removed_manual_df[[
    "source_site",
    "food_class",
    "query",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url"
]].sort_values(["food_class", "recipe_name"]))

print("\nClean Skinnytaste supplement v1 shape:")
print(skinnytaste_supplement_clean_v1_df.shape)

print("\nClean Skinnytaste supplement v1 records per class:")
print(skinnytaste_supplement_clean_v1_df["food_class"].value_counts())

# Merge BBC cleaned candidate with Skinnytaste cleaned supplement
merged_text_calorie_df = pd.concat(
    [cleaned_candidate_v1_df, skinnytaste_supplement_clean_v1_df],
    ignore_index=True
)

# Safety duplicate removal after merge
merged_text_calorie_df["normalized_recipe_name"] = merged_text_calorie_df["recipe_name"].apply(normalize_text_for_filtering)

before_merge_dedup = len(merged_text_calorie_df)

merged_text_calorie_df = merged_text_calorie_df.drop_duplicates(subset=["source_url"], keep="first")
merged_text_calorie_df = merged_text_calorie_df.drop_duplicates(subset=["normalized_recipe_name"], keep="first")

after_merge_dedup = len(merged_text_calorie_df)

merged_text_calorie_df = merged_text_calorie_df.drop(
    columns=["normalized_recipe_name"],
    errors="ignore"
).reset_index(drop=True)

print("\nRows removed by safety dedup after merge:")
print(before_merge_dedup - after_merge_dedup)

print("\nMerged dataset shape:")
print(merged_text_calorie_df.shape)

print("\nMerged records per class:")
print(merged_text_calorie_df["food_class"].value_counts())

print("\nMissing values after merge:")
print(merged_text_calorie_df.isna().sum())

print("\nDuplicate source URLs after merge:")
print(merged_text_calorie_df["source_url"].duplicated().sum())

print("\nDuplicate recipe names after merge:")
print(merged_text_calorie_df["recipe_name"].duplicated().sum())

print("\nNutrition summary after merge:")
display(merged_text_calorie_df[["calories", "protein", "fat", "carbs"]].describe())

print("\nCalories summary by class after merge:")
display(
    merged_text_calorie_df.groupby("food_class")["calories"]
    .agg(["count", "min", "max", "mean", "median"])
    .sort_values("count", ascending=False)
)

# Save files
skinnytaste_supplement_clean_v1_path = CLEAN_DIR / "skinnytaste_text_calorie_supplement_clean_v1.csv"
supplement_removed_manual_path = LOGS_DIR / "skinnytaste_supplement_manual_removed.csv"
merged_text_calorie_path = CLEAN_DIR / "text_calorie_merged_clean_candidate_v1.csv"

skinnytaste_supplement_clean_v1_df.to_csv(skinnytaste_supplement_clean_v1_path, index=False)
supplement_removed_manual_df.to_csv(supplement_removed_manual_path, index=False)
merged_text_calorie_df.to_csv(merged_text_calorie_path, index=False)

print("\nClean Skinnytaste supplement saved to:")
print(skinnytaste_supplement_clean_v1_path)

print("\nManual removed supplement log saved to:")
print(supplement_removed_manual_path)

print("\nMerged clean candidate dataset saved to:")
print(merged_text_calorie_path)

Original Skinnytaste supplement shape:
(57, 11)

Manually removed supplement records:
(19, 11)

Manual removal records per class:
food_class
sushi       10
sandwich     4
steak        4
pizza        1
Name: count, dtype: int64

,source_site,food_class,query,recipe_name,calories,protein,fat,carbs,source_url
2,skinnytaste,pizza,pizza,Spicy Salmon Sushi Pizza,403.0,24.5,26.5,17.0,https://www.skinnytaste.com/spicy-salmon-sushi...
17,skinnytaste,sandwich,sandwich,High Protein Bread (Oat Sandwich Rolls),135.5,10.5,3.0,18.0,https://www.skinnytaste.com/high-protein-bread...
23,skinnytaste,sandwich,chicken sandwich,Pickle Ham and Swiss Chicken Roll Ups (Cuban C...,280.0,36.0,9.0,12.5,https://www.skinnytaste.com/cubano-chicken-pic...
26,skinnytaste,sandwich,turkey sandwich,Turkey Burgers with Zucchini,161.0,18.0,7.0,4.5,https://www.skinnytaste.com/turkey-burgers-wit...
28,skinnytaste,sandwich,turkey sandwich,Turkey Meatballs,280.0,25.5,11.5,25.0,https://www.skinnytaste.com/skinny-italian-mea...
40,skinnytaste,steak,beef steak,Carne Asada Salad,390.0,38.0,21.5,12.0,https://www.skinnytaste.com/carne-asada-steak-...
29,skinnytaste,steak,steak,Fall Steak Salad with Sweet Potatoes,394.5,33.5,17.5,26.0,https://www.skinnytaste.com/fall-steak-salad-w...
43,skinnytaste,steak,beef steak,Loaded Philly Cheesesteak Baked Potato,390.0,26.0,13.0,44.0,https://www.skinnytaste.com/loaded-philly-chee...
46,skinnytaste,steak,grilled steak,Steak & Caramelized Onions with Arugula and Penne,384.0,30.0,15.0,29.5,https://www.skinnytaste.com/steak-caramelized-...
56,skinnytaste,sushi,salmon bowl,5-Minute Microwave Salmon Rice Bowl,533.0,48.5,18.0,51.0,https://www.skinnytaste.com/microwave-salmon-r...
50,skinnytaste,sushi,poke bowl,Ahi Poke Bowl with Mango,527.0,34.0,19.0,60.0,https://www.skinnytaste.com/ahi-poke-bowl/
55,skinnytaste,sushi,salmon bowl,Honey Sriracha Roasted Salmon Rice Bowls,506.0,38.5,17.5,48.0,https://www.skinnytaste.com/salmon-rice-bowls/
54,skinnytaste,sushi,salmon bowl,Korean Salmon Rice Bowl,431.0,33.0,10.0,50.0,https://www.skinnytaste.com/korean-salmon-rice...
53,skinnytaste,sushi,salmon bowl,Seattle Asian Salmon Bowl,395.0,27.0,17.0,31.0,https://www.skinnytaste.com/seattle-asian-salm...
51,skinnytaste,sushi,poke bowl,Shoyu Ahi Poke,166.0,28.5,4.0,2.5,https://www.skinnytaste.com/shoyu-aji-poke/
47,skinnytaste,sushi,sushi bowl,Spicy Canned Salmon Salad Rice Bowl,389.0,25.0,14.0,39.0,https://www.skinnytaste.com/spicy-canned-salmo...
49,skinnytaste,sushi,poke bowl,Spicy Tuna Poke Bowl,397.0,32.5,14.5,33.5,https://www.skinnytaste.com/spicy-tuna-poke-bo...
52,skinnytaste,sushi,salmon bowl,Teriyaki Salmon Bowl (Air Fryer or Oven),491.0,33.0,10.0,62.5,https://www.skinnytaste.com/teriyaki-salmon-bo...
48,skinnytaste,sushi,poke bowl,Tofu Poke Bowl,520.0,29.0,24.0,47.0,https://www.skinnytaste.com/tofu-poke-bowl/

Clean Skinnytaste supplement v1 shape:
(38, 11)

Clean Skinnytaste supplement v1 records per class:
food_class
steak       14
sandwich    13
pizza       11
Name: count, dtype: int64

Rows removed by safety dedup after merge:
1

Merged dataset shape:
(416, 11)

Merged records per class:
food_class
pizza       48
burger      47
rice        47
sandwich    46
pasta       45
salad       45
fries       44
chicken     41
steak       39
sushi       14
Name: count, dtype: int64

Missing values after merge:
source_site         0
food_class          0
query               0
recipe_name         0
ingredients_text    0
calories            0
protein             0
fat                 0
carbs               0
source_url          0
scraped_at          0
dtype: int64

Duplicate source URLs after merge:
0

Duplicate recipe names after merge:
0

Nutrition summary after merge:

          calories     protein         fat       carbs
count   416.000000  416.000000  416.000000  416.000000
mean    474.264423   26.607692   22.134832   40.697115
std     221.537219   13.535983   15.202219   24.178034
min      49.000000    1.000000    1.000000    0.400000
25%     317.000000   17.750000   11.000000   22.000000
50%     435.000000   26.500000   18.000000   39.000000
75%     593.000000   35.000000   30.000000   56.000000
max    1394.000000   69.000000   89.000000  129.000000

Calories summary by class after merge:

            count    min     max        mean  median
food_class
pizza          48  118.0   740.0  427.000000   427.0
burger         47  175.0  1080.0  526.936170   508.0
rice           47  164.0   834.0  470.404255   418.0
sandwich       46  125.0  1256.0  545.913043   470.0
salad          45  111.0   838.0  404.444444   374.0
pasta          45  371.0  1140.0  626.288889   600.0
fries          44  120.0  1394.0  403.590909   379.0
chicken        41  239.0   707.0  409.243902   368.0
steak          39  188.0  1282.0  483.717949   415.0
sushi          14   49.0   862.0  359.000000   351.5

Clean Skinnytaste supplement saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/skinnytaste_text_calorie_supplement_clean_v1.csv

Manual removed supplement log saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/logs/skinnytaste_supplement_manual_removed.csv

Merged clean candidate dataset saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/text_calorie_merged_clean_candidate_v1.csv

In [25]:
# Cell 24 — Create final cleaned text-calorie dataset for modeling

final_text_df = merged_text_calorie_df.copy()

def clean_text_for_modeling(text):
    """
    Basic text cleaning for model input.
    Keeps meaningful ingredient words and numbers.
    """
    if pd.isna(text):
        return ""

    text = str(text).lower()
    text = text.replace("&", " and ")
    text = re.sub(r"[^a-z0-9\s\.\-/]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text


final_text_df["clean_recipe_name"] = final_text_df["recipe_name"].apply(clean_text_for_modeling)
final_text_df["clean_ingredients_text"] = final_text_df["ingredients_text"].apply(clean_text_for_modeling)

final_text_df["input_text"] = (
    "food class: "
    + final_text_df["food_class"].astype(str)
    + " recipe name: "
    + final_text_df["clean_recipe_name"]
    + " ingredients: "
    + final_text_df["clean_ingredients_text"]
)

# Create stable record_id
final_text_df = final_text_df.reset_index(drop=True)
final_text_df.insert(0, "record_id", ["TXT_" + str(i).zfill(5) for i in range(len(final_text_df))])

# Keep final modeling columns
final_modeling_df = final_text_df[[
    "record_id",
    "source_site",
    "food_class",
    "query",
    "recipe_name",
    "ingredients_text",
    "clean_recipe_name",
    "clean_ingredients_text",
    "input_text",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url",
    "scraped_at"
]].copy()

print("Final modeling dataset shape:")
print(final_modeling_df.shape)

print("\nRecords per class:")
print(final_modeling_df["food_class"].value_counts())

print("\nMissing values:")
print(final_modeling_df.isna().sum())

print("\nDuplicate source URLs:")
print(final_modeling_df["source_url"].duplicated().sum())

print("\nDuplicate input_text:")
print(final_modeling_df["input_text"].duplicated().sum())

print("\nInput text length summary:")
final_modeling_df["input_text_length"] = final_modeling_df["input_text"].str.len()
print(final_modeling_df["input_text_length"].describe())

print("\nSample final records:")
display(final_modeling_df[[
    "record_id",
    "food_class",
    "recipe_name",
    "calories",
    "protein",
    "fat",
    "carbs",
    "input_text"
]].head(10))

# Save final cleaned dataset
cleaned_text_calorie_dataset_path = CLEAN_DIR / "cleaned_text_calorie_dataset.csv"
final_modeling_df.to_csv(cleaned_text_calorie_dataset_path, index=False)

print("\nFinal cleaned text-calorie dataset saved to:")
print(cleaned_text_calorie_dataset_path)

Final modeling dataset shape:
(416, 15)

Records per class:
food_class
pizza       48
burger      47
rice        47
sandwich    46
pasta       45
salad       45
fries       44
chicken     41
steak       39
sushi       14
Name: count, dtype: int64

Missing values:
record_id                 0
source_site               0
food_class                0
query                     0
recipe_name               0
ingredients_text          0
clean_recipe_name         0
clean_ingredients_text    0
input_text                0
calories                  0
protein                   0
fat                       0
carbs                     0
source_url                0
scraped_at                0
dtype: int64

Duplicate source URLs:
0

Duplicate input_text:
0

Input text length summary:
count    416.000000
mean     381.918269
std      115.246820
min      109.000000
25%      300.000000
50%      375.500000
75%      440.250000
max      765.000000
Name: input_text_length, dtype: float64

Sample final records:

,record_id,food_class,recipe_name,calories,protein,fat,carbs,input_text
0,TXT_00000,chicken,'Marry me' chicken,584.0,38.0,38.0,21.0,food class: chicken recipe name: marry me chic...
1,TXT_00001,salad,10-minute couscous salad,468.0,16.0,24.0,44.0,food class: salad recipe name: 10-minute cousc...
2,TXT_00002,burger,15-minute chicken & halloumi burgers,737.0,39.0,42.0,49.0,food class: burger recipe name: 15-minute chic...
3,TXT_00003,pasta,15-minute chicken pasta,531.0,43.0,11.0,70.0,food class: pasta recipe name: 15-minute chick...
4,TXT_00004,fries,Air fryer French fries,204.0,3.0,7.0,30.0,food class: fries recipe name: air fryer frenc...
5,TXT_00005,sandwich,Air fryer cheese & ham toastie,627.0,27.0,38.0,43.0,food class: sandwich recipe name: air fryer ch...
6,TXT_00006,fries,Air fryer potato wedges,202.0,3.0,6.0,32.0,food class: fries recipe name: air fryer potat...
7,TXT_00007,fries,Air fryer sweet potato fries,244.0,3.0,3.0,48.0,food class: fries recipe name: air fryer sweet...
8,TXT_00008,fries,Air-fryer chips,140.0,3.0,3.0,24.0,food class: fries recipe name: air-fryer chips...
9,TXT_00009,fries,Air-fryer fish & chips,654.0,26.0,34.0,59.0,food class: fries recipe name: air-fryer fish ...

Final cleaned text-calorie dataset saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/cleaned_text_calorie_dataset.csv

In [26]:
# Cell 25A — Test additional candidate sources for sushi augmentation

ADDITIONAL_SOURCE_CANDIDATES = {
    "eatingwell": {
        "base_url": "https://www.eatingwell.com",
        "search_url_template": "https://www.eatingwell.com/search?q={query}"
    },
    "recipetineats": {
        "base_url": "https://www.recipetineats.com",
        "search_url_template": "https://www.recipetineats.com/?s={query}"
    },
    "the_spruce_eats": {
        "base_url": "https://www.thespruceeats.com",
        "search_url_template": "https://www.thespruceeats.com/search?q={query}"
    },
    "jamie_oliver": {
        "base_url": "https://www.jamieoliver.com",
        "search_url_template": "https://www.jamieoliver.com/search/?s={query}"
    },
    "healthy_food_guide": {
        "base_url": "https://www.healthyfood.com",
        "search_url_template": "https://www.healthyfood.com/?s={query}"
    }
}

test_queries = ["sushi", "sushi roll", "maki", "salmon sushi"]

candidate_source_rows = []

for source_name, config in ADDITIONAL_SOURCE_CANDIDATES.items():
    for query in test_queries:
        encoded_query = quote_plus(query)
        search_url = config["search_url_template"].format(query=encoded_query)

        print("\nTesting source:", source_name)
        print("Query:", query)
        print("URL:", search_url)

        response = safe_get(search_url, sleep_min=1, sleep_max=2, timeout=25)

        if response is None:
            row = {
                "source_name": source_name,
                "query": query,
                "status_code": None,
                "html_length": 0,
                "final_url": None,
                "works": False
            }
            print("No response.")
        else:
            row = {
                "source_name": source_name,
                "query": query,
                "status_code": response.status_code,
                "html_length": len(response.text),
                "final_url": response.url,
                "works": response.status_code == 200 and len(response.text) > 5000
            }

            print("Status code:", response.status_code)
            print("HTML length:", len(response.text))
            print("Final URL:", response.url)
            print("Works:", row["works"])

        candidate_source_rows.append(row)

candidate_source_test_df = pd.DataFrame(candidate_source_rows)

print("\nCandidate source test summary:")
display(candidate_source_test_df)

print("\nWorking sources summary:")
display(candidate_source_test_df[candidate_source_test_df["works"] == True])

Testing source: eatingwell
Query: sushi
URL: https://www.eatingwell.com/search?q=sushi
Status code: 402
HTML length: 612
Final URL: https://www.eatingwell.com/search?q=sushi
Works: False

Testing source: eatingwell
Query: sushi roll
URL: https://www.eatingwell.com/search?q=sushi+roll
Status code: 402
HTML length: 612
Final URL: https://www.eatingwell.com/search?q=sushi+roll
Works: False

Testing source: eatingwell
Query: maki
URL: https://www.eatingwell.com/search?q=maki
Status code: 402
HTML length: 612
Final URL: https://www.eatingwell.com/search?q=maki
Works: False

Testing source: eatingwell
Query: salmon sushi
URL: https://www.eatingwell.com/search?q=salmon+sushi
Status code: 402
HTML length: 612
Final URL: https://www.eatingwell.com/search?q=salmon+sushi
Works: False

Testing source: recipetineats
Query: sushi
URL: https://www.recipetineats.com/?s=sushi
Status code: 200
HTML length: 342953
Final URL: https://www.recipetineats.com/?s=sushi
Works: True

Testing source: recipetineats
Query: sushi roll
URL: https://www.recipetineats.com/?s=sushi+roll
Status code: 200
HTML length: 342434
Final URL: https://www.recipetineats.com/?s=sushi+roll
Works: True

Testing source: recipetineats
Query: maki
URL: https://www.recipetineats.com/?s=maki
Status code: 200
HTML length: 341958
Final URL: https://www.recipetineats.com/?s=maki
Works: True

Testing source: recipetineats
Query: salmon sushi
URL: https://www.recipetineats.com/?s=salmon+sushi
Status code: 200
HTML length: 336297
Final URL: https://www.recipetineats.com/?s=salmon+sushi
Works: True

Testing source: the_spruce_eats
Query: sushi
URL: https://www.thespruceeats.com/search?q=sushi
Status code: 402
HTML length: 612
Final URL: https://www.thespruceeats.com/search?q=sushi
Works: False

Testing source: the_spruce_eats
Query: sushi roll
URL: https://www.thespruceeats.com/search?q=sushi+roll
Status code: 402
HTML length: 612
Final URL: https://www.thespruceeats.com/search?q=sushi+roll
Works: False

Testing source: the_spruce_eats
Query: maki
URL: https://www.thespruceeats.com/search?q=maki
Status code: 402
HTML length: 612
Final URL: https://www.thespruceeats.com/search?q=maki
Works: False

Testing source: the_spruce_eats
Query: salmon sushi
URL: https://www.thespruceeats.com/search?q=salmon+sushi
Status code: 402
HTML length: 612
Final URL: https://www.thespruceeats.com/search?q=salmon+sushi
Works: False

Testing source: jamie_oliver
Query: sushi
URL: https://www.jamieoliver.com/search/?s=sushi
Status code: 404
HTML length: 396612
Final URL: https://www.jamieoliver.com/search/?s=sushi
Works: False

Testing source: jamie_oliver
Query: sushi roll
URL: https://www.jamieoliver.com/search/?s=sushi+roll
Status code: 404
HTML length: 396612
Final URL: https://www.jamieoliver.com/search/?s=sushi+roll
Works: False

Testing source: jamie_oliver
Query: maki
URL: https://www.jamieoliver.com/search/?s=maki
Status code: 404
HTML length: 396612
Final URL: https://www.jamieoliver.com/search/?s=maki
Works: False

Testing source: jamie_oliver
Query: salmon sushi
URL: https://www.jamieoliver.com/search/?s=salmon+sushi
Status code: 404
HTML length: 396612
Final URL: https://www.jamieoliver.com/search/?s=salmon+sushi
Works: False

Testing source: healthy_food_guide
Query: sushi
URL: https://www.healthyfood.com/?s=sushi
Status code: 200
HTML length: 245295
Final URL: https://www.healthyfood.com/?s=sushi
Works: True

Testing source: healthy_food_guide
Query: sushi roll
URL: https://www.healthyfood.com/?s=sushi+roll
Status code: 200
HTML length: 263352
Final URL: https://www.healthyfood.com/?s=sushi+roll
Works: True

Testing source: healthy_food_guide
Query: maki
URL: https://www.healthyfood.com/?s=maki
Status code: 200
HTML length: 217312
Final URL: https://www.healthyfood.com/?s=maki
Works: True

Testing source: healthy_food_guide
Query: salmon sushi
URL: https://www.healthyfood.com/?s=salmon+sushi
Status code: 200
HTML length: 271262
Final URL: https://www.healthyfood.com/?s=salmon+sushi
Works: True

Candidate source test summary:

,source_name,query,status_code,html_length,final_url,works
0,eatingwell,sushi,402,612,https://www.eatingwell.com/search?q=sushi,False
1,eatingwell,sushi roll,402,612,https://www.eatingwell.com/search?q=sushi+roll,False
2,eatingwell,maki,402,612,https://www.eatingwell.com/search?q=maki,False
3,eatingwell,salmon sushi,402,612,https://www.eatingwell.com/search?q=salmon+sushi,False
4,recipetineats,sushi,200,342953,https://www.recipetineats.com/?s=sushi,True
5,recipetineats,sushi roll,200,342434,https://www.recipetineats.com/?s=sushi+roll,True
6,recipetineats,maki,200,341958,https://www.recipetineats.com/?s=maki,True
7,recipetineats,salmon sushi,200,336297,https://www.recipetineats.com/?s=salmon+sushi,True
8,the_spruce_eats,sushi,402,612,https://www.thespruceeats.com/search?q=sushi,False
9,the_spruce_eats,sushi roll,402,612,https://www.thespruceeats.com/search?q=sushi+roll,False
10,the_spruce_eats,maki,402,612,https://www.thespruceeats.com/search?q=maki,False
11,the_spruce_eats,salmon sushi,402,612,https://www.thespruceeats.com/search?q=salmon+...,False
12,jamie_oliver,sushi,404,396612,https://www.jamieoliver.com/search/?s=sushi,False
13,jamie_oliver,sushi roll,404,396612,https://www.jamieoliver.com/search/?s=sushi+roll,False
14,jamie_oliver,maki,404,396612,https://www.jamieoliver.com/search/?s=maki,False
15,jamie_oliver,salmon sushi,404,396612,https://www.jamieoliver.com/search/?s=salmon+s...,False
16,healthy_food_guide,sushi,200,245295,https://www.healthyfood.com/?s=sushi,True
17,healthy_food_guide,sushi roll,200,263352,https://www.healthyfood.com/?s=sushi+roll,True
18,healthy_food_guide,maki,200,217312,https://www.healthyfood.com/?s=maki,True
19,healthy_food_guide,salmon sushi,200,271262,https://www.healthyfood.com/?s=salmon+sushi,True

Working sources summary:

,source_name,query,status_code,html_length,final_url,works
4,recipetineats,sushi,200,342953,https://www.recipetineats.com/?s=sushi,True
5,recipetineats,sushi roll,200,342434,https://www.recipetineats.com/?s=sushi+roll,True
6,recipetineats,maki,200,341958,https://www.recipetineats.com/?s=maki,True
7,recipetineats,salmon sushi,200,336297,https://www.recipetineats.com/?s=salmon+sushi,True
16,healthy_food_guide,sushi,200,245295,https://www.healthyfood.com/?s=sushi,True
17,healthy_food_guide,sushi roll,200,263352,https://www.healthyfood.com/?s=sushi+roll,True
18,healthy_food_guide,maki,200,217312,https://www.healthyfood.com/?s=maki,True
19,healthy_food_guide,salmon sushi,200,271262,https://www.healthyfood.com/?s=salmon+sushi,True

In [27]:
# Cell 25B — Extract sushi recipe links from RecipeTinEats and Healthy Food Guide

from urllib.parse import urlparse

WORKING_SUSHI_SOURCES = {
    "recipetineats": ADDITIONAL_SOURCE_CANDIDATES["recipetineats"],
    "healthy_food_guide": ADDITIONAL_SOURCE_CANDIDATES["healthy_food_guide"]
}

SUSHI_AUGMENT_QUERIES = [
    "sushi",
    "sushi roll",
    "sushi rolls",
    "maki",
    "california roll",
    "salmon sushi",
    "tuna sushi",
    "avocado sushi",
    "sushi rice"
]


def is_valid_recipetineats_recipe_url(url):
    """
    RecipeTinEats recipe URLs are usually simple post URLs.
    This filter removes category/tag/page/search URLs.
    """
    parsed = urlparse(url)
    netloc = parsed.netloc.lower()
    path = parsed.path.strip("/").lower()

    if "recipetineats.com" not in netloc:
        return False

    if not path:
        return False

    blocked_parts = [
        "category",
        "tag",
        "recipes",
        "recipe-index",
        "about",
        "contact",
        "search",
        "privacy",
        "newsletter",
        "cookbook",
        "round-ups",
        "collections"
    ]

    for blocked in blocked_parts:
        if path == blocked or path.startswith(blocked + "/"):
            return False

    if "?" in url:
        return False

    return True


def is_valid_healthy_food_guide_recipe_url(url):
    """
    Healthy Food Guide recipe URLs usually contain /recipe/.
    """
    parsed = urlparse(url)
    netloc = parsed.netloc.lower()
    path = parsed.path.strip("/").lower()

    if "healthyfood.com" not in netloc:
        return False

    if "/recipe/" in parsed.path.lower() or path.startswith("recipe/"):
        return True

    return False


def extract_sushi_links_from_new_source(source_name, query, max_links=30):
    """
    Extract candidate sushi recipe links from a search page.
    """
    config = WORKING_SUSHI_SOURCES[source_name]
    encoded_query = quote_plus(query)
    search_url = config["search_url_template"].format(query=encoded_query)

    response = safe_get(search_url, sleep_min=1, sleep_max=2, timeout=25)

    if response is None:
        print("No response returned.")
        return pd.DataFrame(columns=["source_name", "query", "title_text", "url"])

    print("\nSource:", source_name)
    print("Query:", query)
    print("Search URL:", search_url)
    print("Status code:", response.status_code)
    print("HTML length:", len(response.text))

    soup = BeautifulSoup(response.text, "html.parser")
    rows = []

    for a_tag in soup.find_all("a", href=True):
        href = a_tag.get("href")
        title_text = a_tag.get_text(" ", strip=True)

        if not href:
            continue

        full_url = urljoin(config["base_url"], href)

        if source_name == "recipetineats":
            is_valid = is_valid_recipetineats_recipe_url(full_url)

        elif source_name == "healthy_food_guide":
            is_valid = is_valid_healthy_food_guide_recipe_url(full_url)

        else:
            is_valid = False

        if not is_valid:
            continue

        title_clean = normalize_text_for_filtering(title_text)
        url_clean = normalize_text_for_filtering(full_url)
        combined = title_clean + " " + url_clean

        sushi_terms = [
            "sushi",
            "maki",
            "california roll",
            "salmon roll",
            "tuna roll",
            "avocado roll",
            "sushi rice"
        ]

        if not any(term in combined for term in sushi_terms):
            continue

        rows.append({
            "source_name": source_name,
            "query": query,
            "title_text": title_text,
            "url": full_url
        })

    links_df = pd.DataFrame(rows)

    if not links_df.empty:
        links_df = links_df.drop_duplicates(subset=["url"]).reset_index(drop=True)

    print("Candidate sushi links found:", len(links_df))

    if not links_df.empty:
        display(links_df.head(max_links))

    return links_df


all_new_sushi_link_dfs = []

for source_name in WORKING_SUSHI_SOURCES.keys():
    print("\n====================================")
    print("Extracting sushi links from:", source_name)
    print("====================================")

    for query in SUSHI_AUGMENT_QUERIES:
        links_df = extract_sushi_links_from_new_source(
            source_name=source_name,
            query=query,
            max_links=20
        )

        if links_df is not None and not links_df.empty:
            all_new_sushi_link_dfs.append(links_df)

        time.sleep(1)

if all_new_sushi_link_dfs:
    new_sushi_links_df = pd.concat(all_new_sushi_link_dfs, ignore_index=True)
    new_sushi_links_df = new_sushi_links_df.drop_duplicates(subset=["url"]).reset_index(drop=True)
else:
    new_sushi_links_df = pd.DataFrame(columns=["source_name", "query", "title_text", "url"])

print("\nNew sushi link extraction finished.")
print("Total unique sushi candidate links:", len(new_sushi_links_df))

print("\nLinks per source:")
if not new_sushi_links_df.empty:
    print(new_sushi_links_df["source_name"].value_counts())
    display(new_sushi_links_df)
else:
    print("No links found.")

====================================
Extracting sushi links from: recipetineats
====================================

Source: recipetineats
Query: sushi
Search URL: https://www.recipetineats.com/?s=sushi
Status code: 200
HTML length: 342953
Candidate sushi links found: 0

Source: recipetineats
Query: sushi roll
Search URL: https://www.recipetineats.com/?s=sushi+roll
Status code: 200
HTML length: 342434
Candidate sushi links found: 0

Source: recipetineats
Query: sushi rolls
Search URL: https://www.recipetineats.com/?s=sushi+rolls
Status code: 200
HTML length: 332514
Candidate sushi links found: 0

Source: recipetineats
Query: maki
Search URL: https://www.recipetineats.com/?s=maki
Status code: 200
HTML length: 341958
Candidate sushi links found: 2

,source_name,query,title_text,url
0,recipetineats,maki,,https://www.recipetineats.com/making-of-a-cook...
1,recipetineats,maki,,https://www.recipetineats.com/the-making-of-a-...

Source: recipetineats
Query: california roll
Search URL: https://www.recipetineats.com/?s=california+roll
Status code: 200
HTML length: 316025
Candidate sushi links found: 0

Source: recipetineats
Query: salmon sushi
Search URL: https://www.recipetineats.com/?s=salmon+sushi
Status code: 200
HTML length: 336297
Candidate sushi links found: 0

Source: recipetineats
Query: tuna sushi
Search URL: https://www.recipetineats.com/?s=tuna+sushi
Status code: 200
HTML length: 342189
Candidate sushi links found: 0

Source: recipetineats
Query: avocado sushi
Search URL: https://www.recipetineats.com/?s=avocado+sushi
Status code: 200
HTML length: 326894
Candidate sushi links found: 0

Source: recipetineats
Query: sushi rice
Search URL: https://www.recipetineats.com/?s=sushi+rice
Status code: 200
HTML length: 344442
Candidate sushi links found: 0

====================================
Extracting sushi links from: healthy_food_guide
====================================

Source: healthy_food_guide
Query: sushi
Search URL: https://www.healthyfood.com/?s=sushi
Status code: 200
HTML length: 246450
Candidate sushi links found: 0

Source: healthy_food_guide
Query: sushi roll
Search URL: https://www.healthyfood.com/?s=sushi+roll
Status code: 200
HTML length: 266292
Candidate sushi links found: 0

Source: healthy_food_guide
Query: sushi rolls
Search URL: https://www.healthyfood.com/?s=sushi+rolls
Status code: 200
HTML length: 259859
Candidate sushi links found: 0

Source: healthy_food_guide
Query: maki
Search URL: https://www.healthyfood.com/?s=maki
Status code: 200
HTML length: 216175
Candidate sushi links found: 0

Source: healthy_food_guide
Query: california roll
Search URL: https://www.healthyfood.com/?s=california+roll
Status code: 200
HTML length: 194369
Candidate sushi links found: 0

Source: healthy_food_guide
Query: salmon sushi
Search URL: https://www.healthyfood.com/?s=salmon+sushi
Status code: 200
HTML length: 268572
Candidate sushi links found: 0

Source: healthy_food_guide
Query: tuna sushi
Search URL: https://www.healthyfood.com/?s=tuna+sushi
Status code: 200
HTML length: 240781
Candidate sushi links found: 0

Source: healthy_food_guide
Query: avocado sushi
Search URL: https://www.healthyfood.com/?s=avocado+sushi
Status code: 200
HTML length: 247186
Candidate sushi links found: 0

Source: healthy_food_guide
Query: sushi rice
Search URL: https://www.healthyfood.com/?s=sushi+rice
Status code: 200
HTML length: 222571
Candidate sushi links found: 0

New sushi link extraction finished.
Total unique sushi candidate links: 2

Links per source:
source_name
recipetineats    2
Name: count, dtype: int64

,source_name,query,title_text,url
0,recipetineats,maki,,https://www.recipetineats.com/making-of-a-cook...
1,recipetineats,maki,,https://www.recipetineats.com/the-making-of-a-...

In [28]:
# Cell 25C — Test specialized sushi/Japanese recipe sources

SPECIALIZED_SUSHI_SOURCE_CANDIDATES = {
    "just_one_cookbook": {
        "base_url": "https://www.justonecookbook.com",
        "search_url_template": "https://www.justonecookbook.com/?s={query}"
    },
    "pickled_plum": {
        "base_url": "https://pickledplum.com",
        "search_url_template": "https://pickledplum.com/?s={query}"
    },
    "chopstick_chronicles": {
        "base_url": "https://www.chopstickchronicles.com",
        "search_url_template": "https://www.chopstickchronicles.com/?s={query}"
    },
    "okonomi_kitchen": {
        "base_url": "https://www.okonomikitchen.com",
        "search_url_template": "https://www.okonomikitchen.com/?s={query}"
    },
    "no_recipes": {
        "base_url": "https://norecipes.com",
        "search_url_template": "https://norecipes.com/?s={query}"
    }
}

specialized_test_queries = [
    "sushi",
    "sushi roll",
    "maki",
    "california roll",
    "salmon sushi",
    "sushi rice"
]

specialized_source_rows = []

for source_name, config in SPECIALIZED_SUSHI_SOURCE_CANDIDATES.items():
    for query in specialized_test_queries:
        encoded_query = quote_plus(query)
        search_url = config["search_url_template"].format(query=encoded_query)

        print("\nTesting source:", source_name)
        print("Query:", query)
        print("URL:", search_url)

        response = safe_get(search_url, sleep_min=1, sleep_max=2, timeout=25)

        if response is None:
            row = {
                "source_name": source_name,
                "query": query,
                "status_code": None,
                "html_length": 0,
                "final_url": None,
                "works": False
            }
            print("No response.")
        else:
            row = {
                "source_name": source_name,
                "query": query,
                "status_code": response.status_code,
                "html_length": len(response.text),
                "final_url": response.url,
                "works": response.status_code == 200 and len(response.text) > 5000
            }

            print("Status code:", response.status_code)
            print("HTML length:", len(response.text))
            print("Final URL:", response.url)
            print("Works:", row["works"])

        specialized_source_rows.append(row)

specialized_source_test_df = pd.DataFrame(specialized_source_rows)

print("\nSpecialized source test summary:")
display(specialized_source_test_df)

print("\nWorking specialized sources:")
display(specialized_source_test_df[specialized_source_test_df["works"] == True])

Testing source: just_one_cookbook
Query: sushi
URL: https://www.justonecookbook.com/?s=sushi
Status code: 403
HTML length: 5054
Final URL: https://www.justonecookbook.com/?s=sushi
Works: False

Testing source: just_one_cookbook
Query: sushi roll
URL: https://www.justonecookbook.com/?s=sushi+roll
Status code: 403
HTML length: 5054
Final URL: https://www.justonecookbook.com/?s=sushi+roll
Works: False

Testing source: just_one_cookbook
Query: maki
URL: https://www.justonecookbook.com/?s=maki
Status code: 403
HTML length: 5054
Final URL: https://www.justonecookbook.com/?s=maki
Works: False

Testing source: just_one_cookbook
Query: california roll
URL: https://www.justonecookbook.com/?s=california+roll
Status code: 403
HTML length: 5054
Final URL: https://www.justonecookbook.com/?s=california+roll
Works: False

Testing source: just_one_cookbook
Query: salmon sushi
URL: https://www.justonecookbook.com/?s=salmon+sushi
Status code: 403
HTML length: 5054
Final URL: https://www.justonecookbook.com/?s=salmon+sushi
Works: False

Testing source: just_one_cookbook
Query: sushi rice
URL: https://www.justonecookbook.com/?s=sushi+rice
Status code: 403
HTML length: 5054
Final URL: https://www.justonecookbook.com/?s=sushi+rice
Works: False

Testing source: pickled_plum
Query: sushi
URL: https://pickledplum.com/?s=sushi
Status code: 200
HTML length: 328900
Final URL: https://pickledplum.com/?s=sushi
Works: True

Testing source: pickled_plum
Query: sushi roll
URL: https://pickledplum.com/?s=sushi+roll
Status code: 200
HTML length: 326288
Final URL: https://pickledplum.com/?s=sushi+roll
Works: True

Testing source: pickled_plum
Query: maki
URL: https://pickledplum.com/?s=maki
Status code: 200
HTML length: 324724
Final URL: https://pickledplum.com/?s=maki
Works: True

Testing source: pickled_plum
Query: california roll
URL: https://pickledplum.com/?s=california+roll
Status code: 200
HTML length: 310729
Final URL: https://pickledplum.com/?s=california+roll
Works: True

Testing source: pickled_plum
Query: salmon sushi
URL: https://pickledplum.com/?s=salmon+sushi
Status code: 200
HTML length: 306242
Final URL: https://pickledplum.com/?s=salmon+sushi
Works: True

Testing source: pickled_plum
Query: sushi rice
URL: https://pickledplum.com/?s=sushi+rice
Status code: 200
HTML length: 326657
Final URL: https://pickledplum.com/?s=sushi+rice
Works: True

Testing source: chopstick_chronicles
Query: sushi
URL: https://www.chopstickchronicles.com/?s=sushi
Status code: 200
HTML length: 371379
Final URL: https://www.chopstickchronicles.com/?s=sushi
Works: True

Testing source: chopstick_chronicles
Query: sushi roll
URL: https://www.chopstickchronicles.com/?s=sushi+roll
Status code: 200
HTML length: 372690
Final URL: https://www.chopstickchronicles.com/?s=sushi+roll
Works: True

Testing source: chopstick_chronicles
Query: maki
URL: https://www.chopstickchronicles.com/?s=maki
Status code: 200
HTML length: 376528
Final URL: https://www.chopstickchronicles.com/?s=maki
Works: True

Testing source: chopstick_chronicles
Query: california roll
URL: https://www.chopstickchronicles.com/?s=california+roll
Status code: 200
HTML length: 320942
Final URL: https://www.chopstickchronicles.com/?s=california+roll
Works: True

Testing source: chopstick_chronicles
Query: salmon sushi
URL: https://www.chopstickchronicles.com/?s=salmon+sushi
Status code: 200
HTML length: 360596
Final URL: https://www.chopstickchronicles.com/?s=salmon+sushi
Works: True

Testing source: chopstick_chronicles
Query: sushi rice
URL: https://www.chopstickchronicles.com/?s=sushi+rice
Status code: 200
HTML length: 375061
Final URL: https://www.chopstickchronicles.com/?s=sushi+rice
Works: True

Testing source: okonomi_kitchen
Query: sushi
URL: https://www.okonomikitchen.com/?s=sushi
Status code: 200
HTML length: 141326
Final URL: https://www.okonomikitchen.com/?s=sushi
Works: True

Testing source: okonomi_kitchen
Query: sushi roll
URL: https://www.okonomikitchen.com/?s=sushi+roll
Status code: 200
HTML length: 133160
Final URL: https://www.okonomikitchen.com/?s=sushi+roll
Works: True

Testing source: okonomi_kitchen
Query: maki
URL: https://www.okonomikitchen.com/?s=maki
Status code: 200
HTML length: 142256
Final URL: https://www.okonomikitchen.com/?s=maki
Works: True

Testing source: okonomi_kitchen
Query: california roll
URL: https://www.okonomikitchen.com/?s=california+roll
Status code: 200
HTML length: 118162
Final URL: https://www.okonomikitchen.com/?s=california+roll
Works: True

Testing source: okonomi_kitchen
Query: salmon sushi
URL: https://www.okonomikitchen.com/?s=salmon+sushi
Status code: 200
HTML length: 129374
Final URL: https://www.okonomikitchen.com/?s=salmon+sushi
Works: True

Testing source: okonomi_kitchen
Query: sushi rice
URL: https://www.okonomikitchen.com/?s=sushi+rice
Status code: 200
HTML length: 141484
Final URL: https://www.okonomikitchen.com/?s=sushi+rice
Works: True

Testing source: no_recipes
Query: sushi
URL: https://norecipes.com/?s=sushi
Status code: 200
HTML length: 452238
Final URL: https://norecipes.com/?s=sushi
Works: True

Testing source: no_recipes
Query: sushi roll
URL: https://norecipes.com/?s=sushi+roll
Status code: 200
HTML length: 452087
Final URL: https://norecipes.com/?s=sushi+roll
Works: True

Testing source: no_recipes
Query: maki
URL: https://norecipes.com/?s=maki
Status code: 200
HTML length: 453384
Final URL: https://norecipes.com/?s=maki
Works: True

Testing source: no_recipes
Query: california roll
URL: https://norecipes.com/?s=california+roll
Status code: 200
HTML length: 428452
Final URL: https://norecipes.com/?s=california+roll
Works: True

Testing source: no_recipes
Query: salmon sushi
URL: https://norecipes.com/?s=salmon+sushi
Status code: 200
HTML length: 438434
Final URL: https://norecipes.com/?s=salmon+sushi
Works: True

Testing source: no_recipes
Query: sushi rice
URL: https://norecipes.com/?s=sushi+rice
Status code: 200
HTML length: 453642
Final URL: https://norecipes.com/?s=sushi+rice
Works: True

Specialized source test summary:

,source_name,query,status_code,html_length,final_url,works
0,just_one_cookbook,sushi,403,5054,https://www.justonecookbook.com/?s=sushi,False
1,just_one_cookbook,sushi roll,403,5054,https://www.justonecookbook.com/?s=sushi+roll,False
2,just_one_cookbook,maki,403,5054,https://www.justonecookbook.com/?s=maki,False
3,just_one_cookbook,california roll,403,5054,https://www.justonecookbook.com/?s=california+...,False
4,just_one_cookbook,salmon sushi,403,5054,https://www.justonecookbook.com/?s=salmon+sushi,False
5,just_one_cookbook,sushi rice,403,5054,https://www.justonecookbook.com/?s=sushi+rice,False
6,pickled_plum,sushi,200,328900,https://pickledplum.com/?s=sushi,True
7,pickled_plum,sushi roll,200,326288,https://pickledplum.com/?s=sushi+roll,True
8,pickled_plum,maki,200,324724,https://pickledplum.com/?s=maki,True
9,pickled_plum,california roll,200,310729,https://pickledplum.com/?s=california+roll,True
10,pickled_plum,salmon sushi,200,306242,https://pickledplum.com/?s=salmon+sushi,True
11,pickled_plum,sushi rice,200,326657,https://pickledplum.com/?s=sushi+rice,True
12,chopstick_chronicles,sushi,200,371379,https://www.chopstickchronicles.com/?s=sushi,True
13,chopstick_chronicles,sushi roll,200,372690,https://www.chopstickchronicles.com/?s=sushi+roll,True
14,chopstick_chronicles,maki,200,376528,https://www.chopstickchronicles.com/?s=maki,True
15,chopstick_chronicles,california roll,200,320942,https://www.chopstickchronicles.com/?s=califor...,True
16,chopstick_chronicles,salmon sushi,200,360596,https://www.chopstickchronicles.com/?s=salmon+...,True
17,chopstick_chronicles,sushi rice,200,375061,https://www.chopstickchronicles.com/?s=sushi+rice,True
18,okonomi_kitchen,sushi,200,141326,https://www.okonomikitchen.com/?s=sushi,True
19,okonomi_kitchen,sushi roll,200,133160,https://www.okonomikitchen.com/?s=sushi+roll,True
20,okonomi_kitchen,maki,200,142256,https://www.okonomikitchen.com/?s=maki,True
21,okonomi_kitchen,california roll,200,118162,https://www.okonomikitchen.com/?s=california+roll,True
22,okonomi_kitchen,salmon sushi,200,129374,https://www.okonomikitchen.com/?s=salmon+sushi,True
23,okonomi_kitchen,sushi rice,200,141484,https://www.okonomikitchen.com/?s=sushi+rice,True
24,no_recipes,sushi,200,452238,https://norecipes.com/?s=sushi,True
25,no_recipes,sushi roll,200,452087,https://norecipes.com/?s=sushi+roll,True
26,no_recipes,maki,200,453384,https://norecipes.com/?s=maki,True
27,no_recipes,california roll,200,428452,https://norecipes.com/?s=california+roll,True
28,no_recipes,salmon sushi,200,438434,https://norecipes.com/?s=salmon+sushi,True
29,no_recipes,sushi rice,200,453642,https://norecipes.com/?s=sushi+rice,True

Working specialized sources:

,source_name,query,status_code,html_length,final_url,works
6,pickled_plum,sushi,200,328900,https://pickledplum.com/?s=sushi,True
7,pickled_plum,sushi roll,200,326288,https://pickledplum.com/?s=sushi+roll,True
8,pickled_plum,maki,200,324724,https://pickledplum.com/?s=maki,True
9,pickled_plum,california roll,200,310729,https://pickledplum.com/?s=california+roll,True
10,pickled_plum,salmon sushi,200,306242,https://pickledplum.com/?s=salmon+sushi,True
11,pickled_plum,sushi rice,200,326657,https://pickledplum.com/?s=sushi+rice,True
12,chopstick_chronicles,sushi,200,371379,https://www.chopstickchronicles.com/?s=sushi,True
13,chopstick_chronicles,sushi roll,200,372690,https://www.chopstickchronicles.com/?s=sushi+roll,True
14,chopstick_chronicles,maki,200,376528,https://www.chopstickchronicles.com/?s=maki,True
15,chopstick_chronicles,california roll,200,320942,https://www.chopstickchronicles.com/?s=califor...,True
16,chopstick_chronicles,salmon sushi,200,360596,https://www.chopstickchronicles.com/?s=salmon+...,True
17,chopstick_chronicles,sushi rice,200,375061,https://www.chopstickchronicles.com/?s=sushi+rice,True
18,okonomi_kitchen,sushi,200,141326,https://www.okonomikitchen.com/?s=sushi,True
19,okonomi_kitchen,sushi roll,200,133160,https://www.okonomikitchen.com/?s=sushi+roll,True
20,okonomi_kitchen,maki,200,142256,https://www.okonomikitchen.com/?s=maki,True
21,okonomi_kitchen,california roll,200,118162,https://www.okonomikitchen.com/?s=california+roll,True
22,okonomi_kitchen,salmon sushi,200,129374,https://www.okonomikitchen.com/?s=salmon+sushi,True
23,okonomi_kitchen,sushi rice,200,141484,https://www.okonomikitchen.com/?s=sushi+rice,True
24,no_recipes,sushi,200,452238,https://norecipes.com/?s=sushi,True
25,no_recipes,sushi roll,200,452087,https://norecipes.com/?s=sushi+roll,True
26,no_recipes,maki,200,453384,https://norecipes.com/?s=maki,True
27,no_recipes,california roll,200,428452,https://norecipes.com/?s=california+roll,True
28,no_recipes,salmon sushi,200,438434,https://norecipes.com/?s=salmon+sushi,True
29,no_recipes,sushi rice,200,453642,https://norecipes.com/?s=sushi+rice,True

In [29]:
# Cell 25D — Extract sushi recipe links from specialized sources

SPECIALIZED_WORKING_SUSHI_SOURCES = {
    "pickled_plum": SPECIALIZED_SUSHI_SOURCE_CANDIDATES["pickled_plum"],
    "chopstick_chronicles": SPECIALIZED_SUSHI_SOURCE_CANDIDATES["chopstick_chronicles"],
    "okonomi_kitchen": SPECIALIZED_SUSHI_SOURCE_CANDIDATES["okonomi_kitchen"],
    "no_recipes": SPECIALIZED_SUSHI_SOURCE_CANDIDATES["no_recipes"]
}

SPECIALIZED_SUSHI_QUERIES = [
    "sushi",
    "sushi roll",
    "sushi rolls",
    "maki",
    "california roll",
    "salmon sushi",
    "tuna sushi",
    "avocado sushi",
    "sushi rice",
    "spicy tuna roll",
    "salmon roll"
]


def is_valid_specialized_recipe_url(source_name, url):
    """
    Filter obvious non-recipe URLs from specialized recipe sites.
    """
    if url is None:
        return False

    parsed = urlparse(url)
    netloc = parsed.netloc.lower()
    path = parsed.path.strip("/").lower()

    if not path:
        return False

    expected_domains = {
        "pickled_plum": "pickledplum.com",
        "chopstick_chronicles": "chopstickchronicles.com",
        "okonomi_kitchen": "okonomikitchen.com",
        "no_recipes": "norecipes.com"
    }

    expected_domain = expected_domains.get(source_name)

    if expected_domain is None or expected_domain not in netloc:
        return False

    blocked_parts = [
        "category",
        "tag",
        "author",
        "page",
        "about",
        "contact",
        "privacy",
        "terms",
        "shop",
        "store",
        "newsletter",
        "cookbook",
        "recipe-index",
        "recipes",
        "search",
        "wp-content",
        "comments",
        "resources"
    ]

    for blocked in blocked_parts:
        if path == blocked or path.startswith(blocked + "/") or ("/" + blocked + "/") in ("/" + path + "/"):
            return False

    blocked_contains = [
        "making-of-a-cookbook",
        "the-making-of-a",
        "best-",
        "roundup",
        "round-up",
        "collection"
    ]

    for blocked in blocked_contains:
        if blocked in path:
            return False

    return True


def looks_like_sushi_recipe(title_text, url, query):
    """
    Decide whether a candidate URL/title is sushi-related.
    """
    title_clean = normalize_text_for_filtering(title_text)
    url_clean = normalize_text_for_filtering(url)
    query_clean = normalize_text_for_filtering(query)

    combined = " ".join([title_clean, url_clean, query_clean])

    strong_sushi_terms = [
        "sushi",
        "maki",
        "nigiri",
        "sashimi",
        "temaki",
        "futomaki",
        "uramaki",
        "california roll",
        "spicy tuna roll",
        "salmon roll",
        "tuna roll",
        "avocado roll",
        "sushi rice"
    ]

    if any(term in combined for term in strong_sushi_terms):
        return True

    return False


def extract_specialized_sushi_links(source_name, query, max_links=30):
    """
    Extract candidate sushi recipe links from one specialized source search page.
    """
    config = SPECIALIZED_WORKING_SUSHI_SOURCES[source_name]
    encoded_query = quote_plus(query)
    search_url = config["search_url_template"].format(query=encoded_query)

    response = safe_get(search_url, sleep_min=1, sleep_max=2, timeout=25)

    if response is None:
        print("No response returned.")
        return pd.DataFrame(columns=["source_name", "query", "title_text", "url"])

    print("\nSource:", source_name)
    print("Query:", query)
    print("Search URL:", search_url)
    print("Status code:", response.status_code)
    print("HTML length:", len(response.text))

    soup = BeautifulSoup(response.text, "html.parser")
    rows = []

    for a_tag in soup.find_all("a", href=True):
        href = a_tag.get("href")
        title_text = a_tag.get_text(" ", strip=True)

        if not href:
            continue

        full_url = urljoin(config["base_url"], href)

        if not is_valid_specialized_recipe_url(source_name, full_url):
            continue

        if not looks_like_sushi_recipe(title_text, full_url, query):
            continue

        rows.append({
            "source_name": source_name,
            "query": query,
            "title_text": title_text,
            "url": full_url
        })

    links_df = pd.DataFrame(rows)

    if not links_df.empty:
        links_df = links_df.drop_duplicates(subset=["url"]).reset_index(drop=True)

    print("Candidate sushi links found:", len(links_df))

    if not links_df.empty:
        display(links_df.head(max_links))

    return links_df


specialized_sushi_link_dfs = []

for source_name in SPECIALIZED_WORKING_SUSHI_SOURCES.keys():
    print("\n====================================")
    print("Extracting sushi links from:", source_name)
    print("====================================")

    for query in SPECIALIZED_SUSHI_QUERIES:
        links_df = extract_specialized_sushi_links(
            source_name=source_name,
            query=query,
            max_links=20
        )

        if links_df is not None and not links_df.empty:
            specialized_sushi_link_dfs.append(links_df)

        time.sleep(1)

if specialized_sushi_link_dfs:
    specialized_sushi_links_df = pd.concat(specialized_sushi_link_dfs, ignore_index=True)
    specialized_sushi_links_df = specialized_sushi_links_df.drop_duplicates(subset=["url"]).reset_index(drop=True)
else:
    specialized_sushi_links_df = pd.DataFrame(columns=["source_name", "query", "title_text", "url"])

print("\nSpecialized sushi link extraction finished.")
print("Total unique specialized sushi candidate links:", len(specialized_sushi_links_df))

print("\nLinks per source:")
if not specialized_sushi_links_df.empty:
    print(specialized_sushi_links_df["source_name"].value_counts())
    display(specialized_sushi_links_df)
else:
    print("No links found.")

====================================
Extracting sushi links from: pickled_plum
====================================

Source: pickled_plum
Query: sushi
Search URL: https://pickledplum.com/?s=sushi
Status code: 200
HTML length: 328900
Candidate sushi links found: 98

,source_name,query,title_text,url
0,pickled_plum,sushi,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,sushi,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,sushi,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,sushi,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,sushi,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,sushi,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,sushi,,https://pickledplum.com/how-to-make-sushi-at-h...
7,pickled_plum,sushi,Comment,https://pickledplum.com/how-to-make-sushi-at-h...
8,pickled_plum,sushi,,https://pickledplum.com/how-to-make-sushi-rice/
9,pickled_plum,sushi,5 Comments,https://pickledplum.com/how-to-make-sushi-rice...
10,pickled_plum,sushi,,https://pickledplum.com/maki-sushi/
11,pickled_plum,sushi,Comment,https://pickledplum.com/maki-sushi/#commentform
12,pickled_plum,sushi,,https://pickledplum.com/temari-sushi/
13,pickled_plum,sushi,2 Comments,https://pickledplum.com/temari-sushi/#commentform
14,pickled_plum,sushi,,https://pickledplum.com/inari-sushi-recipe/
15,pickled_plum,sushi,10 Comments,https://pickledplum.com/inari-sushi-recipe/#co...
16,pickled_plum,sushi,,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
17,pickled_plum,sushi,13 Comments,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
18,pickled_plum,sushi,,https://pickledplum.com/vegetarian-chirashi-su...
19,pickled_plum,sushi,7 Comments,https://pickledplum.com/vegetarian-chirashi-su...

Source: pickled_plum
Query: sushi roll
Search URL: https://pickledplum.com/?s=sushi+roll
Status code: 200
HTML length: 326288
Candidate sushi links found: 94

,source_name,query,title_text,url
0,pickled_plum,sushi roll,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,sushi roll,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,sushi roll,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,sushi roll,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,sushi roll,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,sushi roll,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,sushi roll,,https://pickledplum.com/maki-sushi/
7,pickled_plum,sushi roll,Comment,https://pickledplum.com/maki-sushi/#commentform
8,pickled_plum,sushi roll,,https://pickledplum.com/how-to-make-sushi-at-h...
9,pickled_plum,sushi roll,Comment,https://pickledplum.com/how-to-make-sushi-at-h...
10,pickled_plum,sushi roll,,https://pickledplum.com/philadelphia-roll/
11,pickled_plum,sushi roll,Comment,https://pickledplum.com/philadelphia-roll/#com...
12,pickled_plum,sushi roll,,https://pickledplum.com/how-to-make-sushi-rice/
13,pickled_plum,sushi roll,5 Comments,https://pickledplum.com/how-to-make-sushi-rice...
14,pickled_plum,sushi roll,,https://pickledplum.com/temari-sushi/
15,pickled_plum,sushi roll,2 Comments,https://pickledplum.com/temari-sushi/#commentform
16,pickled_plum,sushi roll,,https://pickledplum.com/inari-sushi-recipe/
17,pickled_plum,sushi roll,10 Comments,https://pickledplum.com/inari-sushi-recipe/#co...
18,pickled_plum,sushi roll,,https://pickledplum.com/california-roll-spicy-...
19,pickled_plum,sushi roll,1 Comment,https://pickledplum.com/california-roll-spicy-...

Source: pickled_plum
Query: sushi rolls
Search URL: https://pickledplum.com/?s=sushi+rolls
Status code: 200
HTML length: 325087
Candidate sushi links found: 94

,source_name,query,title_text,url
0,pickled_plum,sushi rolls,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,sushi rolls,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,sushi rolls,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,sushi rolls,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,sushi rolls,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,sushi rolls,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,sushi rolls,,https://pickledplum.com/maki-sushi/
7,pickled_plum,sushi rolls,Comment,https://pickledplum.com/maki-sushi/#commentform
8,pickled_plum,sushi rolls,,https://pickledplum.com/how-to-make-sushi-at-h...
9,pickled_plum,sushi rolls,Comment,https://pickledplum.com/how-to-make-sushi-at-h...
10,pickled_plum,sushi rolls,,https://pickledplum.com/how-to-make-sushi-rice/
11,pickled_plum,sushi rolls,5 Comments,https://pickledplum.com/how-to-make-sushi-rice...
12,pickled_plum,sushi rolls,,https://pickledplum.com/temari-sushi/
13,pickled_plum,sushi rolls,2 Comments,https://pickledplum.com/temari-sushi/#commentform
14,pickled_plum,sushi rolls,,https://pickledplum.com/inari-sushi-recipe/
15,pickled_plum,sushi rolls,10 Comments,https://pickledplum.com/inari-sushi-recipe/#co...
16,pickled_plum,sushi rolls,,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
17,pickled_plum,sushi rolls,13 Comments,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
18,pickled_plum,sushi rolls,,https://pickledplum.com/what-to-do-with-leftov...
19,pickled_plum,sushi rolls,Comment,https://pickledplum.com/what-to-do-with-leftov...

Source: pickled_plum
Query: maki
Search URL: https://pickledplum.com/?s=maki
Status code: 200
HTML length: 324724
Candidate sushi links found: 98

,source_name,query,title_text,url
0,pickled_plum,maki,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,maki,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,maki,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,maki,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,maki,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,maki,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,maki,,https://pickledplum.com/maki-sushi/
7,pickled_plum,maki,Comment,https://pickledplum.com/maki-sushi/#commentform
8,pickled_plum,maki,,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
9,pickled_plum,maki,13 Comments,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
10,pickled_plum,maki,,https://pickledplum.com/japanese-omelette-recipe/
11,pickled_plum,maki,1 Comment,https://pickledplum.com/japanese-omelette-reci...
12,pickled_plum,maki,,https://pickledplum.com/what-to-do-with-leftov...
13,pickled_plum,maki,Comment,https://pickledplum.com/what-to-do-with-leftov...
14,pickled_plum,maki,,https://pickledplum.com/how-to-make-sushi-at-h...
15,pickled_plum,maki,Comment,https://pickledplum.com/how-to-make-sushi-at-h...
16,pickled_plum,maki,,https://pickledplum.com/25-recipes-using-miso/
17,pickled_plum,maki,Comment,https://pickledplum.com/25-recipes-using-miso/...
18,pickled_plum,maki,,https://pickledplum.com/fried-rice-guide/
19,pickled_plum,maki,2 Comments,https://pickledplum.com/fried-rice-guide/#comm...

Source: pickled_plum
Query: california roll
Search URL: https://pickledplum.com/?s=california+roll
Status code: 200
HTML length: 310729
Candidate sushi links found: 74

,source_name,query,title_text,url
0,pickled_plum,california roll,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,california roll,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,california roll,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,california roll,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,california roll,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,california roll,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,california roll,,https://pickledplum.com/california-roll-spicy-...
7,pickled_plum,california roll,1 Comment,https://pickledplum.com/california-roll-spicy-...
8,pickled_plum,california roll,,https://pickledplum.com/philadelphia-roll/
9,pickled_plum,california roll,Comment,https://pickledplum.com/philadelphia-roll/#com...
10,pickled_plum,california roll,,https://pickledplum.com/maki-sushi/
11,pickled_plum,california roll,Comment,https://pickledplum.com/maki-sushi/#commentform
12,pickled_plum,california roll,,https://pickledplum.com/spicy-tuna-roll-recipe/
13,pickled_plum,california roll,29 Comments,https://pickledplum.com/spicy-tuna-roll-recipe...
14,pickled_plum,california roll,,https://pickledplum.com/how-to-make-sushi-at-h...
15,pickled_plum,california roll,Comment,https://pickledplum.com/how-to-make-sushi-at-h...
16,pickled_plum,california roll,,https://pickledplum.com/daikon-miso-soup/
17,pickled_plum,california roll,2 Comments,https://pickledplum.com/daikon-miso-soup/#comm...
18,pickled_plum,california roll,,https://pickledplum.com/glass-noodle-salad/
19,pickled_plum,california roll,Comment,https://pickledplum.com/glass-noodle-salad/#co...

Source: pickled_plum
Query: salmon sushi
Search URL: https://pickledplum.com/?s=salmon+sushi
Status code: 200
HTML length: 306242
Candidate sushi links found: 68

,source_name,query,title_text,url
0,pickled_plum,salmon sushi,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,salmon sushi,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,salmon sushi,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,salmon sushi,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,salmon sushi,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,salmon sushi,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,salmon sushi,,https://pickledplum.com/how-to-make-sushi-at-h...
7,pickled_plum,salmon sushi,Comment,https://pickledplum.com/how-to-make-sushi-at-h...
8,pickled_plum,salmon sushi,,https://pickledplum.com/maki-sushi/
9,pickled_plum,salmon sushi,Comment,https://pickledplum.com/maki-sushi/#commentform
10,pickled_plum,salmon sushi,,https://pickledplum.com/temari-sushi/
11,pickled_plum,salmon sushi,2 Comments,https://pickledplum.com/temari-sushi/#commentform
12,pickled_plum,salmon sushi,,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
13,pickled_plum,salmon sushi,13 Comments,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
14,pickled_plum,salmon sushi,,https://pickledplum.com/what-to-do-with-leftov...
15,pickled_plum,salmon sushi,Comment,https://pickledplum.com/what-to-do-with-leftov...
16,pickled_plum,salmon sushi,,https://pickledplum.com/daikon-miso-soup/
17,pickled_plum,salmon sushi,2 Comments,https://pickledplum.com/daikon-miso-soup/#comm...
18,pickled_plum,salmon sushi,,https://pickledplum.com/eggplant-miso-soup/
19,pickled_plum,salmon sushi,1 Comment,https://pickledplum.com/eggplant-miso-soup/#co...

Source: pickled_plum
Query: tuna sushi
Search URL: https://pickledplum.com/?s=tuna+sushi
Status code: 200
HTML length: 326664
Candidate sushi links found: 92

,source_name,query,title_text,url
0,pickled_plum,tuna sushi,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,tuna sushi,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,tuna sushi,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,tuna sushi,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,tuna sushi,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,tuna sushi,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,tuna sushi,,https://pickledplum.com/how-to-make-sushi-at-h...
7,pickled_plum,tuna sushi,Comment,https://pickledplum.com/how-to-make-sushi-at-h...
8,pickled_plum,tuna sushi,,https://pickledplum.com/conbini-style-tuna-may...
9,pickled_plum,tuna sushi,2 Comments,https://pickledplum.com/conbini-style-tuna-may...
10,pickled_plum,tuna sushi,,https://pickledplum.com/tuna-tartare/
11,pickled_plum,tuna sushi,Comment,https://pickledplum.com/tuna-tartare/#commentform
12,pickled_plum,tuna sushi,,https://pickledplum.com/tekkadon-tuna-bowl/
13,pickled_plum,tuna sushi,1 Comment,https://pickledplum.com/tekkadon-tuna-bowl/#co...
14,pickled_plum,tuna sushi,,https://pickledplum.com/how-to-make-sushi-rice/
15,pickled_plum,tuna sushi,5 Comments,https://pickledplum.com/how-to-make-sushi-rice...
16,pickled_plum,tuna sushi,,https://pickledplum.com/maki-sushi/
17,pickled_plum,tuna sushi,Comment,https://pickledplum.com/maki-sushi/#commentform
18,pickled_plum,tuna sushi,,https://pickledplum.com/temari-sushi/
19,pickled_plum,tuna sushi,2 Comments,https://pickledplum.com/temari-sushi/#commentform

Source: pickled_plum
Query: avocado sushi
Search URL: https://pickledplum.com/?s=avocado+sushi
Status code: 200
HTML length: 284503
Candidate sushi links found: 42

,source_name,query,title_text,url
0,pickled_plum,avocado sushi,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,avocado sushi,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,avocado sushi,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,avocado sushi,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,avocado sushi,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,avocado sushi,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,avocado sushi,,https://pickledplum.com/maki-sushi/
7,pickled_plum,avocado sushi,Comment,https://pickledplum.com/maki-sushi/#commentform
8,pickled_plum,avocado sushi,,https://pickledplum.com/temari-sushi/
9,pickled_plum,avocado sushi,2 Comments,https://pickledplum.com/temari-sushi/#commentform
10,pickled_plum,avocado sushi,,https://pickledplum.com/vegetarian-chirashi-su...
11,pickled_plum,avocado sushi,7 Comments,https://pickledplum.com/vegetarian-chirashi-su...
12,pickled_plum,avocado sushi,,https://pickledplum.com/philadelphia-roll/
13,pickled_plum,avocado sushi,Comment,https://pickledplum.com/philadelphia-roll/#com...
14,pickled_plum,avocado sushi,,https://pickledplum.com/easy-lunch-ideas/
15,pickled_plum,avocado sushi,Comment,https://pickledplum.com/easy-lunch-ideas/#comm...
16,pickled_plum,avocado sushi,,https://pickledplum.com/tuna-tartare/
17,pickled_plum,avocado sushi,Comment,https://pickledplum.com/tuna-tartare/#commentform
18,pickled_plum,avocado sushi,,https://pickledplum.com/vegan-japanese-recipes/
19,pickled_plum,avocado sushi,Comment,https://pickledplum.com/vegan-japanese-recipes...

Source: pickled_plum
Query: sushi rice
Search URL: https://pickledplum.com/?s=sushi+rice
Status code: 200
HTML length: 326657
Candidate sushi links found: 94

,source_name,query,title_text,url
0,pickled_plum,sushi rice,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,sushi rice,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,sushi rice,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,sushi rice,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,sushi rice,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,sushi rice,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,sushi rice,,https://pickledplum.com/how-to-make-sushi-rice/
7,pickled_plum,sushi rice,5 Comments,https://pickledplum.com/how-to-make-sushi-rice...
8,pickled_plum,sushi rice,,https://pickledplum.com/what-to-do-with-leftov...
9,pickled_plum,sushi rice,Comment,https://pickledplum.com/what-to-do-with-leftov...
10,pickled_plum,sushi rice,,https://pickledplum.com/how-to-make-sushi-at-h...
11,pickled_plum,sushi rice,Comment,https://pickledplum.com/how-to-make-sushi-at-h...
12,pickled_plum,sushi rice,,https://pickledplum.com/how-to-cook-rice-in-a-...
13,pickled_plum,sushi rice,Comment,https://pickledplum.com/how-to-cook-rice-in-a-...
14,pickled_plum,sushi rice,,https://pickledplum.com/slow-cooker-rice/
15,pickled_plum,sushi rice,Comment,https://pickledplum.com/slow-cooker-rice/#comm...
16,pickled_plum,sushi rice,,https://pickledplum.com/maki-sushi/
17,pickled_plum,sushi rice,Comment,https://pickledplum.com/maki-sushi/#commentform
18,pickled_plum,sushi rice,,https://pickledplum.com/ingredient/rice-vinegar/
19,pickled_plum,sushi rice,Comment,https://pickledplum.com/ingredient/rice-vinega...

Source: pickled_plum
Query: spicy tuna roll
Search URL: https://pickledplum.com/?s=spicy+tuna+roll
Status code: 200
HTML length: 325340
Candidate sushi links found: 92

,source_name,query,title_text,url
0,pickled_plum,spicy tuna roll,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,spicy tuna roll,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,spicy tuna roll,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,spicy tuna roll,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,spicy tuna roll,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,spicy tuna roll,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,spicy tuna roll,,https://pickledplum.com/spicy-tuna-roll-recipe/
7,pickled_plum,spicy tuna roll,29 Comments,https://pickledplum.com/spicy-tuna-roll-recipe...
8,pickled_plum,spicy tuna roll,,https://pickledplum.com/spicy-dahl-soup/
9,pickled_plum,spicy tuna roll,Comment,https://pickledplum.com/spicy-dahl-soup/#comme...
10,pickled_plum,spicy tuna roll,,https://pickledplum.com/conbini-style-tuna-may...
11,pickled_plum,spicy tuna roll,2 Comments,https://pickledplum.com/conbini-style-tuna-may...
12,pickled_plum,spicy tuna roll,,https://pickledplum.com/philadelphia-roll/
13,pickled_plum,spicy tuna roll,Comment,https://pickledplum.com/philadelphia-roll/#com...
14,pickled_plum,spicy tuna roll,,https://pickledplum.com/tuna-tartare/
15,pickled_plum,spicy tuna roll,Comment,https://pickledplum.com/tuna-tartare/#commentform
16,pickled_plum,spicy tuna roll,,https://pickledplum.com/maki-sushi/
17,pickled_plum,spicy tuna roll,Comment,https://pickledplum.com/maki-sushi/#commentform
18,pickled_plum,spicy tuna roll,,https://pickledplum.com/szechuan-sauce/
19,pickled_plum,spicy tuna roll,5 Comments,https://pickledplum.com/szechuan-sauce/#commen...

Source: pickled_plum
Query: salmon roll
Search URL: https://pickledplum.com/?s=salmon+roll
Status code: 200
HTML length: 327907
Candidate sushi links found: 98

,source_name,query,title_text,url
0,pickled_plum,salmon roll,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,salmon roll,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,salmon roll,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,salmon roll,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,salmon roll,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,salmon roll,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,salmon roll,,https://pickledplum.com/tomato-smoked-salmon-s...
7,pickled_plum,salmon roll,Comment,https://pickledplum.com/tomato-smoked-salmon-s...
8,pickled_plum,salmon roll,,https://pickledplum.com/philadelphia-roll/
9,pickled_plum,salmon roll,Comment,https://pickledplum.com/philadelphia-roll/#com...
10,pickled_plum,salmon roll,,https://pickledplum.com/salmon-seasoning/
11,pickled_plum,salmon roll,3 Comments,https://pickledplum.com/salmon-seasoning/#comm...
12,pickled_plum,salmon roll,,https://pickledplum.com/honey-mustard-salmon/
13,pickled_plum,salmon roll,Comment,https://pickledplum.com/honey-mustard-salmon/#...
14,pickled_plum,salmon roll,,https://pickledplum.com/japanese-salted-salmon...
15,pickled_plum,salmon roll,1 Comment,https://pickledplum.com/japanese-salted-salmon...
16,pickled_plum,salmon roll,,https://pickledplum.com/maki-sushi/
17,pickled_plum,salmon roll,Comment,https://pickledplum.com/maki-sushi/#commentform
18,pickled_plum,salmon roll,,https://pickledplum.com/ginger-garlic-air-frye...
19,pickled_plum,salmon roll,14 Comments,https://pickledplum.com/ginger-garlic-air-frye...

====================================
Extracting sushi links from: chopstick_chronicles
====================================

Source: chopstick_chronicles
Query: sushi
Search URL: https://www.chopstickchronicles.com/?s=sushi
Status code: 200
HTML length: 371379
Candidate sushi links found: 117

,source_name,query,title_text,url
0,chopstick_chronicles,sushi,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,sushi,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,sushi,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,sushi,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,sushi,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,sushi,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,sushi,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,sushi,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,sushi,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,sushi,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,sushi,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,sushi,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,sushi,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,sushi,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,sushi,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,sushi,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,sushi,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,sushi,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,sushi,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,sushi,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: sushi roll
Search URL: https://www.chopstickchronicles.com/?s=sushi+roll
Status code: 200
HTML length: 372690
Candidate sushi links found: 118

,source_name,query,title_text,url
0,chopstick_chronicles,sushi roll,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,sushi roll,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,sushi roll,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,sushi roll,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,sushi roll,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,sushi roll,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,sushi roll,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,sushi roll,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,sushi roll,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,sushi roll,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,sushi roll,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,sushi roll,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,sushi roll,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,sushi roll,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,sushi roll,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,sushi roll,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,sushi roll,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,sushi roll,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,sushi roll,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,sushi roll,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: sushi rolls
Search URL: https://www.chopstickchronicles.com/?s=sushi+rolls
Status code: 200
HTML length: 358884
Candidate sushi links found: 104

,source_name,query,title_text,url
0,chopstick_chronicles,sushi rolls,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,sushi rolls,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,sushi rolls,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,sushi rolls,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,sushi rolls,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,sushi rolls,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,sushi rolls,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,sushi rolls,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,sushi rolls,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,sushi rolls,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,sushi rolls,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,sushi rolls,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,sushi rolls,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,sushi rolls,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,sushi rolls,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,sushi rolls,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,sushi rolls,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,sushi rolls,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,sushi rolls,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,sushi rolls,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: maki
Search URL: https://www.chopstickchronicles.com/?s=maki
Status code: 200
HTML length: 376528
Candidate sushi links found: 121

,source_name,query,title_text,url
0,chopstick_chronicles,maki,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,maki,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,maki,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,maki,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,maki,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,maki,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,maki,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,maki,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,maki,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,maki,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,maki,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,maki,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,maki,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,maki,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,maki,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,maki,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,maki,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,maki,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,maki,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,maki,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: california roll
Search URL: https://www.chopstickchronicles.com/?s=california+roll
Status code: 200
HTML length: 320942
Candidate sushi links found: 64

,source_name,query,title_text,url
0,chopstick_chronicles,california roll,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,california roll,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,california roll,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,california roll,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,california roll,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,california roll,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,california roll,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,california roll,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,california roll,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,california roll,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,california roll,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,california roll,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,california roll,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,california roll,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,california roll,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,california roll,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,california roll,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,california roll,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,california roll,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,california roll,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: salmon sushi
Search URL: https://www.chopstickchronicles.com/?s=salmon+sushi
Status code: 200
HTML length: 360596
Candidate sushi links found: 105

,source_name,query,title_text,url
0,chopstick_chronicles,salmon sushi,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,salmon sushi,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,salmon sushi,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,salmon sushi,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,salmon sushi,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,salmon sushi,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,salmon sushi,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,salmon sushi,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,salmon sushi,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,salmon sushi,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,salmon sushi,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,salmon sushi,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,salmon sushi,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,salmon sushi,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,salmon sushi,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,salmon sushi,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,salmon sushi,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,salmon sushi,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,salmon sushi,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,salmon sushi,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: tuna sushi
Search URL: https://www.chopstickchronicles.com/?s=tuna+sushi
Status code: 200
HTML length: 340551
Candidate sushi links found: 84

,source_name,query,title_text,url
0,chopstick_chronicles,tuna sushi,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,tuna sushi,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,tuna sushi,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,tuna sushi,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,tuna sushi,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,tuna sushi,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,tuna sushi,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,tuna sushi,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,tuna sushi,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,tuna sushi,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,tuna sushi,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,tuna sushi,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,tuna sushi,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,tuna sushi,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,tuna sushi,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,tuna sushi,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,tuna sushi,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,tuna sushi,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,tuna sushi,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,tuna sushi,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: avocado sushi
Search URL: https://www.chopstickchronicles.com/?s=avocado+sushi
Status code: 200
HTML length: 338486
Candidate sushi links found: 83

,source_name,query,title_text,url
0,chopstick_chronicles,avocado sushi,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,avocado sushi,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,avocado sushi,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,avocado sushi,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,avocado sushi,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,avocado sushi,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,avocado sushi,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,avocado sushi,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,avocado sushi,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,avocado sushi,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,avocado sushi,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,avocado sushi,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,avocado sushi,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,avocado sushi,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,avocado sushi,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,avocado sushi,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,avocado sushi,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,avocado sushi,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,avocado sushi,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,avocado sushi,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: sushi rice
Search URL: https://www.chopstickchronicles.com/?s=sushi+rice
Status code: 200
HTML length: 375061
Candidate sushi links found: 120

,source_name,query,title_text,url
0,chopstick_chronicles,sushi rice,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,sushi rice,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,sushi rice,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,sushi rice,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,sushi rice,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,sushi rice,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,sushi rice,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,sushi rice,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,sushi rice,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,sushi rice,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,sushi rice,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,sushi rice,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,sushi rice,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,sushi rice,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,sushi rice,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,sushi rice,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,sushi rice,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,sushi rice,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,sushi rice,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,sushi rice,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: spicy tuna roll
Search URL: https://www.chopstickchronicles.com/?s=spicy+tuna+roll
Status code: 200
HTML length: 312843
Candidate sushi links found: 56

,source_name,query,title_text,url
0,chopstick_chronicles,spicy tuna roll,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,spicy tuna roll,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,spicy tuna roll,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,spicy tuna roll,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,spicy tuna roll,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,spicy tuna roll,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,spicy tuna roll,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,spicy tuna roll,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,spicy tuna roll,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,spicy tuna roll,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,spicy tuna roll,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,spicy tuna roll,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,spicy tuna roll,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,spicy tuna roll,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,spicy tuna roll,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,spicy tuna roll,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,spicy tuna roll,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,spicy tuna roll,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,spicy tuna roll,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,spicy tuna roll,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

Source: chopstick_chronicles
Query: salmon roll
Search URL: https://www.chopstickchronicles.com/?s=salmon+roll
Status code: 200
HTML length: 354111
Candidate sushi links found: 100

,source_name,query,title_text,url
0,chopstick_chronicles,salmon roll,Quick & Easy,https://www.chopstickchronicles.com/quick/
1,chopstick_chronicles,salmon roll,Main Dish,https://www.chopstickchronicles.com/main-dish/
2,chopstick_chronicles,salmon roll,Dessert,https://www.chopstickchronicles.com/dessert/
3,chopstick_chronicles,salmon roll,Kitchen Tools,https://www.chopstickchronicles.com/kitchen-to...
4,chopstick_chronicles,salmon roll,Pantry,https://www.chopstickchronicles.com/pantry/
5,chopstick_chronicles,salmon roll,Recipe Filter,https://www.chopstickchronicles.com/recipe-fil...
6,chopstick_chronicles,salmon roll,Easy Japanese Recipes,https://www.chopstickchronicles.com/easy/
7,chopstick_chronicles,salmon roll,Appetizer,https://www.chopstickchronicles.com/appetizer/
8,chopstick_chronicles,salmon roll,Beverage,https://www.chopstickchronicles.com/beverage/
9,chopstick_chronicles,salmon roll,Bread,https://www.chopstickchronicles.com/bread/
10,chopstick_chronicles,salmon roll,Breakfast,https://www.chopstickchronicles.com/breakfast/
11,chopstick_chronicles,salmon roll,Condiment & Sauce,https://www.chopstickchronicles.com/condiment-...
12,chopstick_chronicles,salmon roll,Salad,https://www.chopstickchronicles.com/salad/
13,chopstick_chronicles,salmon roll,Side Dish,https://www.chopstickchronicles.com/side-dish/
14,chopstick_chronicles,salmon roll,Soup & Stew,https://www.chopstickchronicles.com/soup-stew/
15,chopstick_chronicles,salmon roll,Bento,https://www.chopstickchronicles.com/bento/
16,chopstick_chronicles,salmon roll,Curry,https://www.chopstickchronicles.com/curry/
17,chopstick_chronicles,salmon roll,Donburi,https://www.chopstickchronicles.com/donburi/
18,chopstick_chronicles,salmon roll,Dumpling,https://www.chopstickchronicles.com/dumpling/
19,chopstick_chronicles,salmon roll,Hot Pot,https://www.chopstickchronicles.com/hot-pot/

====================================
Extracting sushi links from: okonomi_kitchen
====================================

Source: okonomi_kitchen
Query: sushi
Search URL: https://www.okonomikitchen.com/?s=sushi
Status code: 200
HTML length: 141326
Candidate sushi links found: 22

,source_name,query,title_text,url
0,okonomi_kitchen,sushi,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/vegan-take-away...
2,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/onigiri-dog/
3,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/crab-rangoon-na...
4,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/freezer-soy-mar...
5,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/tamagoyaki/
6,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/japanese-chicke...
7,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/eggplant-agebit...
8,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/natto-tamagoyaki/
9,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/japanese-bagels...
10,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/japanese-tablew...
11,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/vegan-tamagoyaki/
12,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/vegan-salmon-fl...
13,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/spicy-tomato-tuna/
14,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/vegan-tomato-tu...
15,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/soba-inari/
16,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/inari-age/
17,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/vegan-mentaiko-...
18,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/vegan-japanese-...
19,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/gyoza-with-wings/

Source: okonomi_kitchen
Query: sushi roll
Search URL: https://www.okonomikitchen.com/?s=sushi+roll
Status code: 200
HTML length: 133160
Candidate sushi links found: 14

,source_name,query,title_text,url
0,okonomi_kitchen,sushi roll,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/vegan-take-away...
2,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/tamagoyaki/
3,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/natto-tamagoyaki/
4,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/vegan-tamagoyaki/
5,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/freezer-soy-mar...
6,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/marbled-matcha-...
7,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/vegan-kimbap-wi...
8,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/kinpira-gobo-br...
9,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/onigiri-dog/
10,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/japanese-bagels...
11,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/spicy-tomato-tuna/
12,okonomi_kitchen,sushi roll,,https://www.okonomikitchen.com/vegan-japanese-...
13,okonomi_kitchen,sushi roll,Privacy Policy,https://www.okonomikitchen.com/privacy-policy/

Source: okonomi_kitchen
Query: sushi rolls
Search URL: https://www.okonomikitchen.com/?s=sushi+rolls
Status code: 200
HTML length: 126341
Candidate sushi links found: 9

,source_name,query,title_text,url
0,okonomi_kitchen,sushi rolls,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,sushi rolls,,https://www.okonomikitchen.com/vegan-take-away...
2,okonomi_kitchen,sushi rolls,,https://www.okonomikitchen.com/freezer-soy-mar...
3,okonomi_kitchen,sushi rolls,,https://www.okonomikitchen.com/marbled-matcha-...
4,okonomi_kitchen,sushi rolls,,https://www.okonomikitchen.com/vegan-kimbap-wi...
5,okonomi_kitchen,sushi rolls,,https://www.okonomikitchen.com/kinpira-gobo-br...
6,okonomi_kitchen,sushi rolls,,https://www.okonomikitchen.com/vegan-tamagoyaki/
7,okonomi_kitchen,sushi rolls,,https://www.okonomikitchen.com/spicy-tomato-tuna/
8,okonomi_kitchen,sushi rolls,Privacy Policy,https://www.okonomikitchen.com/privacy-policy/

Source: okonomi_kitchen
Query: maki
Search URL: https://www.okonomikitchen.com/?s=maki
Status code: 200
HTML length: 142256
Candidate sushi links found: 22

,source_name,query,title_text,url
0,okonomi_kitchen,maki,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,maki,,https://www.okonomikitchen.com/carrot-cake-che...
2,okonomi_kitchen,maki,,https://www.okonomikitchen.com/cheese-crusted-...
3,okonomi_kitchen,maki,,https://www.okonomikitchen.com/crispy-no-fold-...
4,okonomi_kitchen,maki,,https://www.okonomikitchen.com/date-butter/
5,okonomi_kitchen,maki,,https://www.okonomikitchen.com/onigiri-dog/
6,okonomi_kitchen,maki,,https://www.okonomikitchen.com/crispy-shanghai...
7,okonomi_kitchen,maki,,https://www.okonomikitchen.com/cheesy-honey-bu...
8,okonomi_kitchen,maki,,https://www.okonomikitchen.com/teriyaki-chicken/
9,okonomi_kitchen,maki,,https://www.okonomikitchen.com/panuozzo-dough-...
10,okonomi_kitchen,maki,,https://www.okonomikitchen.com/crab-rangoon-na...
11,okonomi_kitchen,maki,,https://www.okonomikitchen.com/lap-cheong-caes...
12,okonomi_kitchen,maki,,https://www.okonomikitchen.com/gochujang-lasag...
13,okonomi_kitchen,maki,,https://www.okonomikitchen.com/chocolate-bague...
14,okonomi_kitchen,maki,,https://www.okonomikitchen.com/chocolate-focac...
15,okonomi_kitchen,maki,,https://www.okonomikitchen.com/chocolate-marbl...
16,okonomi_kitchen,maki,,https://www.okonomikitchen.com/chocolate-butte...
17,okonomi_kitchen,maki,,https://www.okonomikitchen.com/dubai-chocolate...
18,okonomi_kitchen,maki,,https://www.okonomikitchen.com/imo-kenpi-crisp...
19,okonomi_kitchen,maki,,https://www.okonomikitchen.com/chocolate-salt-...

Source: okonomi_kitchen
Query: california roll
Search URL: https://www.okonomikitchen.com/?s=california+roll
Status code: 200
HTML length: 118162
Candidate sushi links found: 2

,source_name,query,title_text,url
0,okonomi_kitchen,california roll,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,california roll,Privacy Policy,https://www.okonomikitchen.com/privacy-policy/

Source: okonomi_kitchen
Query: salmon sushi
Search URL: https://www.okonomikitchen.com/?s=salmon+sushi
Status code: 200
HTML length: 129374
Candidate sushi links found: 11

,source_name,query,title_text,url
0,okonomi_kitchen,salmon sushi,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/vegan-salmon-fl...
2,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/onigiri-dog/
3,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/tamagoyaki/
4,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/eggplant-agebit...
5,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/vegan-tamagoyaki/
6,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/spicy-tomato-tuna/
7,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/vegan-tomato-tu...
8,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/vegan-mentaiko-...
9,okonomi_kitchen,salmon sushi,,https://www.okonomikitchen.com/vegan-japanese-...
10,okonomi_kitchen,salmon sushi,Privacy Policy,https://www.okonomikitchen.com/privacy-policy/

Source: okonomi_kitchen
Query: tuna sushi
Search URL: https://www.okonomikitchen.com/?s=tuna+sushi
Status code: 200
HTML length: 126373
Candidate sushi links found: 8

,source_name,query,title_text,url
0,okonomi_kitchen,tuna sushi,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,tuna sushi,,https://www.okonomikitchen.com/spicy-tomato-tuna/
2,okonomi_kitchen,tuna sushi,,https://www.okonomikitchen.com/vegan-tomato-tu...
3,okonomi_kitchen,tuna sushi,,https://www.okonomikitchen.com/onigiri-dog/
4,okonomi_kitchen,tuna sushi,,https://www.okonomikitchen.com/vegan-tamagoyaki/
5,okonomi_kitchen,tuna sushi,,https://www.okonomikitchen.com/vegan-salmon-fl...
6,okonomi_kitchen,tuna sushi,,https://www.okonomikitchen.com/vegan-tofu-poke...
7,okonomi_kitchen,tuna sushi,Privacy Policy,https://www.okonomikitchen.com/privacy-policy/

Source: okonomi_kitchen
Query: avocado sushi
Search URL: https://www.okonomikitchen.com/?s=avocado+sushi
Status code: 200
HTML length: 123192
Candidate sushi links found: 6

,source_name,query,title_text,url
0,okonomi_kitchen,avocado sushi,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,avocado sushi,,https://www.okonomikitchen.com/vegan-take-away...
2,okonomi_kitchen,avocado sushi,,https://www.okonomikitchen.com/freezer-soy-mar...
3,okonomi_kitchen,avocado sushi,,https://www.okonomikitchen.com/japanese-tablew...
4,okonomi_kitchen,avocado sushi,,https://www.okonomikitchen.com/vegan-tofu-poke...
5,okonomi_kitchen,avocado sushi,Privacy Policy,https://www.okonomikitchen.com/privacy-policy/

Source: okonomi_kitchen
Query: sushi rice
Search URL: https://www.okonomikitchen.com/?s=sushi+rice
Status code: 200
HTML length: 141484
Candidate sushi links found: 22

,source_name,query,title_text,url
0,okonomi_kitchen,sushi rice,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/onigiri-dog/
2,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/vegan-take-away...
3,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/vegan-kimbap-wi...
4,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/crab-rangoon-na...
5,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/freezer-soy-mar...
6,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/tamagoyaki/
7,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/japanese-chicke...
8,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/eggplant-agebit...
9,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/japanese-bagels...
10,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/japanese-tablew...
11,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/vegan-tamagoyaki/
12,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/vegan-salmon-fl...
13,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/spicy-tomato-tuna/
14,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/vegan-tomato-tu...
15,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/soba-inari/
16,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/inari-age/
17,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/vegan-mentaiko-...
18,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/vegan-japanese-...
19,okonomi_kitchen,sushi rice,,https://www.okonomikitchen.com/gyoza-with-wings/

Source: okonomi_kitchen
Query: spicy tuna roll
Search URL: https://www.okonomikitchen.com/?s=spicy+tuna+roll
Status code: 200
HTML length: 121915
Candidate sushi links found: 5

,source_name,query,title_text,url
0,okonomi_kitchen,spicy tuna roll,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,spicy tuna roll,,https://www.okonomikitchen.com/spicy-tomato-tuna/
2,okonomi_kitchen,spicy tuna roll,,https://www.okonomikitchen.com/tonpeiyaki-pork...
3,okonomi_kitchen,spicy tuna roll,,https://www.okonomikitchen.com/vegan-onigiri-j...
4,okonomi_kitchen,spicy tuna roll,Privacy Policy,https://www.okonomikitchen.com/privacy-policy/

Source: okonomi_kitchen
Query: salmon roll
Search URL: https://www.okonomikitchen.com/?s=salmon+roll
Status code: 200
HTML length: 131292
Candidate sushi links found: 12

,source_name,query,title_text,url
0,okonomi_kitchen,salmon roll,Sign up for free daily recipes! →,https://www.okonomikitchen.com/subscribe/
1,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/tamagoyaki/
2,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/vegan-tamagoyaki/
3,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/onigiri-dog/
4,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/teriyaki-chicken/
5,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/how-to-cook-any...
6,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/spicy-tomato-tuna/
7,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/rice-paper-dump...
8,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/vegan-shrimp-eb...
9,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/vegan-japanese-...
10,okonomi_kitchen,salmon roll,,https://www.okonomikitchen.com/vegan-onigiri-j...
11,okonomi_kitchen,salmon roll,Privacy Policy,https://www.okonomikitchen.com/privacy-policy/

====================================
Extracting sushi links from: no_recipes
====================================

Source: no_recipes
Query: sushi
Search URL: https://norecipes.com/?s=sushi
Status code: 200
HTML length: 452238
Candidate sushi links found: 61

,source_name,query,title_text,url
0,no_recipes,sushi,Start Here,https://norecipes.com/start-here/
1,no_recipes,sushi,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,sushi,subscribe,https://norecipes.com/subscribe/
3,no_recipes,sushi,Inari Sushi (Fried Tofu Pocket Sushi),https://norecipes.com/inari-sushi-recipe/
4,no_recipes,sushi,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
5,no_recipes,sushi,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
6,no_recipes,sushi,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
7,no_recipes,sushi,Seasoned Sushi Vinegar,https://norecipes.com/seasoned-sushi-vinegar/
8,no_recipes,sushi,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
9,no_recipes,sushi,Pickled Sushi Ginger (Gari),https://norecipes.com/sushi-ginger-gari/
10,no_recipes,sushi,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
11,no_recipes,sushi,California Roll Sushi Bowl,https://norecipes.com/california-roll-sushi-bowl/
12,no_recipes,sushi,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
13,no_recipes,sushi,Salmon Sashimi Donburi,https://norecipes.com/salmon-sashimi-donburi/
14,no_recipes,sushi,Japanese Pickled Cucumber (Shiozuke),https://norecipes.com/japanese-pickled-cucumber/
15,no_recipes,sushi,Cucumber Sunomono Salad with Crab,https://norecipes.com/sunomono-japanese-cucumb...
16,no_recipes,sushi,Spam Onigiri,https://norecipes.com/spam-onigiri/
17,no_recipes,sushi,Japanese Potato Salad,https://norecipes.com/japanese-potato-salad/
18,no_recipes,sushi,Dashimaki Tamago,https://norecipes.com/dashimaki-tamago/
19,no_recipes,sushi,California Roll,https://norecipes.com/california-roll-recipe/

Source: no_recipes
Query: sushi roll
Search URL: https://norecipes.com/?s=sushi+roll
Status code: 200
HTML length: 452087
Candidate sushi links found: 65

,source_name,query,title_text,url
0,no_recipes,sushi roll,Start Here,https://norecipes.com/start-here/
1,no_recipes,sushi roll,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,sushi roll,subscribe,https://norecipes.com/subscribe/
3,no_recipes,sushi roll,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
4,no_recipes,sushi roll,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
5,no_recipes,sushi roll,California Roll Sushi Bowl,https://norecipes.com/california-roll-sushi-bowl/
6,no_recipes,sushi roll,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
7,no_recipes,sushi roll,Inari Sushi (Fried Tofu Pocket Sushi),https://norecipes.com/inari-sushi-recipe/
8,no_recipes,sushi roll,California Roll,https://norecipes.com/california-roll-recipe/
9,no_recipes,sushi roll,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
10,no_recipes,sushi roll,Seasoned Sushi Vinegar,https://norecipes.com/seasoned-sushi-vinegar/
11,no_recipes,sushi roll,Shrimp Tempura Roll,https://norecipes.com/shrimp-tempura-sushi-roll/
12,no_recipes,sushi roll,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
13,no_recipes,sushi roll,Pickled Sushi Ginger (Gari),https://norecipes.com/sushi-ginger-gari/
14,no_recipes,sushi roll,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
15,no_recipes,sushi roll,Spicy Tuna Roll,https://norecipes.com/spicy-tuna-roll/
16,no_recipes,sushi roll,Caterpillar Roll,https://norecipes.com/caterpillar-roll-recipe/
17,no_recipes,sushi roll,Kinshi Tamago (Golden Egg Threads),https://norecipes.com/usuyaki-tamago-recipe/
18,no_recipes,sushi roll,How to Make Ikura,https://norecipes.com/how-to-make-ikura/
19,no_recipes,sushi roll,Dashi Cured Ikura,https://norecipes.com/ikura-salmon-caviar/

Source: no_recipes
Query: sushi rolls
Search URL: https://norecipes.com/?s=sushi+rolls
Status code: 200
HTML length: 433720
Candidate sushi links found: 50

,source_name,query,title_text,url
0,no_recipes,sushi rolls,Start Here,https://norecipes.com/start-here/
1,no_recipes,sushi rolls,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,sushi rolls,subscribe,https://norecipes.com/subscribe/
3,no_recipes,sushi rolls,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
4,no_recipes,sushi rolls,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
5,no_recipes,sushi rolls,Inari Sushi (Fried Tofu Pocket Sushi),https://norecipes.com/inari-sushi-recipe/
6,no_recipes,sushi rolls,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
7,no_recipes,sushi rolls,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
8,no_recipes,sushi rolls,Seasoned Sushi Vinegar,https://norecipes.com/seasoned-sushi-vinegar/
9,no_recipes,sushi rolls,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
10,no_recipes,sushi rolls,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
11,no_recipes,sushi rolls,California Roll Sushi Bowl,https://norecipes.com/california-roll-sushi-bowl/
12,no_recipes,sushi rolls,California Roll,https://norecipes.com/california-roll-recipe/
13,no_recipes,sushi rolls,Kinshi Tamago (Golden Egg Threads),https://norecipes.com/usuyaki-tamago-recipe/
14,no_recipes,sushi rolls,How to Make Ikura,https://norecipes.com/how-to-make-ikura/
15,no_recipes,sushi rolls,Shrimp Tempura Roll,https://norecipes.com/shrimp-tempura-sushi-roll/
16,no_recipes,sushi rolls,Spicy Tuna Roll,https://norecipes.com/spicy-tuna-roll/
17,no_recipes,sushi rolls,Dashi Cured Ikura,https://norecipes.com/ikura-salmon-caviar/
18,no_recipes,sushi rolls,Seaweed Salad (Wakame Salad),https://norecipes.com/seaweed-salad-recipe/
19,no_recipes,sushi rolls,Meat Wrapped Onigiri (Nikumaki Onigiri),https://norecipes.com/meat-wrapped-onigiri/

Source: no_recipes
Query: maki
Search URL: https://norecipes.com/?s=maki
Status code: 200
HTML length: 453384
Candidate sushi links found: 62

,source_name,query,title_text,url
0,no_recipes,maki,Start Here,https://norecipes.com/start-here/
1,no_recipes,maki,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,maki,subscribe,https://norecipes.com/subscribe/
3,no_recipes,maki,Dashimaki Tamago,https://norecipes.com/dashimaki-tamago/
4,no_recipes,maki,Beef Negimaki (Scallion Roll-Ups),https://norecipes.com/beef-negimaki/
5,no_recipes,maki,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
6,no_recipes,maki,Dashimaki Tamago Sando (Japanese Egg Sandwich),https://norecipes.com/dashimaki-tamago-sando-j...
7,no_recipes,maki,Meat Wrapped Onigiri (Nikumaki Onigiri),https://norecipes.com/meat-wrapped-onigiri/
8,no_recipes,maki,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
9,no_recipes,maki,Harumaki,https://norecipes.com/harumaki-japanese-spring...
10,no_recipes,maki,Datemaki,https://norecipes.com/datemaki/
11,no_recipes,maki,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
12,no_recipes,maki,5 Tips for Making Perfect Crêpes,https://norecipes.com/5-tips-for-making-perfec...
13,no_recipes,maki,Cuban Beef Picadillo (Picadillo Cubano),https://norecipes.com/cuban-beef-picadillo/
14,no_recipes,maki,Katsuobushi: A Pillar of Japanese Cuisine,https://norecipes.com/katsuobushi/
15,no_recipes,maki,Miso Salmon,https://norecipes.com/miso-salmon-recipe/
16,no_recipes,maki,Inari Sushi (Fried Tofu Pocket Sushi),https://norecipes.com/inari-sushi-recipe/
17,no_recipes,maki,Japanese Pickled Cucumber (Shiozuke),https://norecipes.com/japanese-pickled-cucumber/
18,no_recipes,maki,Japanese Pickled Carrots in Soy Sauce,https://norecipes.com/japanese-pickled-carrots/
19,no_recipes,maki,Shoyu Ramen,https://norecipes.com/shoyu-ramen-recipe/

Source: no_recipes
Query: california roll
Search URL: https://norecipes.com/?s=california+roll
Status code: 200
HTML length: 428452
Candidate sushi links found: 45

,source_name,query,title_text,url
0,no_recipes,california roll,Start Here,https://norecipes.com/start-here/
1,no_recipes,california roll,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,california roll,subscribe,https://norecipes.com/subscribe/
3,no_recipes,california roll,California Roll,https://norecipes.com/california-roll-recipe/
4,no_recipes,california roll,California Roll Sushi Bowl,https://norecipes.com/california-roll-sushi-bowl/
5,no_recipes,california roll,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
6,no_recipes,california roll,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
7,no_recipes,california roll,Shrimp Tempura Roll,https://norecipes.com/shrimp-tempura-sushi-roll/
8,no_recipes,california roll,Spicy Tuna Roll,https://norecipes.com/spicy-tuna-roll/
9,no_recipes,california roll,Caterpillar Roll,https://norecipes.com/caterpillar-roll-recipe/
10,no_recipes,california roll,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
11,no_recipes,california roll,Seaweed Salad (Wakame Salad),https://norecipes.com/seaweed-salad-recipe/
12,no_recipes,california roll,Seasoned Sushi Vinegar,https://norecipes.com/seasoned-sushi-vinegar/
13,no_recipes,california roll,Kani Salad,https://norecipes.com/kani-salad/
14,no_recipes,california roll,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
15,no_recipes,california roll,Pickled Sushi Ginger (Gari),https://norecipes.com/sushi-ginger-gari/
16,no_recipes,california roll,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
17,no_recipes,california roll,Omurice (オムライス),https://norecipes.com/omurice-recipe/
18,no_recipes,california roll,Beef Teriyaki,https://norecipes.com/beef-teriyaki-recipe/
19,no_recipes,california roll,What is Umami?,https://norecipes.com/what-is-umami-the-fifth-...

Source: no_recipes
Query: salmon sushi
Search URL: https://norecipes.com/?s=salmon+sushi
Status code: 200
HTML length: 438434
Candidate sushi links found: 52

,source_name,query,title_text,url
0,no_recipes,salmon sushi,Start Here,https://norecipes.com/start-here/
1,no_recipes,salmon sushi,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,salmon sushi,subscribe,https://norecipes.com/subscribe/
3,no_recipes,salmon sushi,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
4,no_recipes,salmon sushi,Salmon Sashimi Donburi,https://norecipes.com/salmon-sashimi-donburi/
5,no_recipes,salmon sushi,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
6,no_recipes,salmon sushi,Salmon Onigiri,https://norecipes.com/salmon-onigiri-rice-balls/
7,no_recipes,salmon sushi,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
8,no_recipes,salmon sushi,Pickled Sushi Ginger (Gari),https://norecipes.com/sushi-ginger-gari/
9,no_recipes,salmon sushi,Spicy Salmon Poke,https://norecipes.com/spicy-salmon-poke/
10,no_recipes,salmon sushi,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
11,no_recipes,salmon sushi,Japanese Pickled Cucumber (Shiozuke),https://norecipes.com/japanese-pickled-cucumber/
12,no_recipes,salmon sushi,Cucumber Sunomono Salad with Crab,https://norecipes.com/sunomono-japanese-cucumb...
13,no_recipes,salmon sushi,Spam Onigiri,https://norecipes.com/spam-onigiri/
14,no_recipes,salmon sushi,Dashimaki Tamago,https://norecipes.com/dashimaki-tamago/
15,no_recipes,salmon sushi,Tamagoyaki (Japanese Omelette),https://norecipes.com/tamagoyaki-recipe/
16,no_recipes,salmon sushi,How to Make Ikura,https://norecipes.com/how-to-make-ikura/
17,no_recipes,salmon sushi,Seaweed Salad (Wakame Salad),https://norecipes.com/seaweed-salad-recipe/
18,no_recipes,salmon sushi,Best Sake for Cooking,https://norecipes.com/what-is-sake/
19,no_recipes,salmon sushi,Beer & Wasabi Pickled Cucumbers,https://norecipes.com/beer-wasabi-pickled-cucu...

Source: no_recipes
Query: tuna sushi
Search URL: https://norecipes.com/?s=tuna+sushi
Status code: 200
HTML length: 440214
Candidate sushi links found: 53

,source_name,query,title_text,url
0,no_recipes,tuna sushi,Start Here,https://norecipes.com/start-here/
1,no_recipes,tuna sushi,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,tuna sushi,subscribe,https://norecipes.com/subscribe/
3,no_recipes,tuna sushi,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
4,no_recipes,tuna sushi,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
5,no_recipes,tuna sushi,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
6,no_recipes,tuna sushi,Seasoned Sushi Vinegar,https://norecipes.com/seasoned-sushi-vinegar/
7,no_recipes,tuna sushi,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
8,no_recipes,tuna sushi,Pickled Sushi Ginger (Gari),https://norecipes.com/sushi-ginger-gari/
9,no_recipes,tuna sushi,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
10,no_recipes,tuna sushi,California Roll Sushi Bowl,https://norecipes.com/california-roll-sushi-bowl/
11,no_recipes,tuna sushi,Spicy Tuna Roll,https://norecipes.com/spicy-tuna-roll/
12,no_recipes,tuna sushi,Tuna Mayo Onigiri,https://norecipes.com/tuna-mayo-onigiri/
13,no_recipes,tuna sushi,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
14,no_recipes,tuna sushi,Tuna Poke,https://norecipes.com/tuna-poke/
15,no_recipes,tuna sushi,Tuna Tartare with Yuzu Gelée,https://norecipes.com/tuna-tartare-with-yuzu-g...
16,no_recipes,tuna sushi,Salmon Sashimi Donburi,https://norecipes.com/salmon-sashimi-donburi/
17,no_recipes,tuna sushi,Japanese Pickled Cucumber (Shiozuke),https://norecipes.com/japanese-pickled-cucumber/
18,no_recipes,tuna sushi,Spam Onigiri,https://norecipes.com/spam-onigiri/
19,no_recipes,tuna sushi,California Roll,https://norecipes.com/california-roll-recipe/

Source: no_recipes
Query: avocado sushi
Search URL: https://norecipes.com/?s=avocado+sushi
Status code: 200
HTML length: 425313
Candidate sushi links found: 41

,source_name,query,title_text,url
0,no_recipes,avocado sushi,Start Here,https://norecipes.com/start-here/
1,no_recipes,avocado sushi,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,avocado sushi,subscribe,https://norecipes.com/subscribe/
3,no_recipes,avocado sushi,Inari Sushi (Fried Tofu Pocket Sushi),https://norecipes.com/inari-sushi-recipe/
4,no_recipes,avocado sushi,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
5,no_recipes,avocado sushi,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
6,no_recipes,avocado sushi,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
7,no_recipes,avocado sushi,California Roll Sushi Bowl,https://norecipes.com/california-roll-sushi-bowl/
8,no_recipes,avocado sushi,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
9,no_recipes,avocado sushi,Shrimp and Avocado Pasta,https://norecipes.com/shrimp-and-avocado-pasta/
10,no_recipes,avocado sushi,Salmon Sashimi Donburi,https://norecipes.com/salmon-sashimi-donburi/
11,no_recipes,avocado sushi,California Roll,https://norecipes.com/california-roll-recipe/
12,no_recipes,avocado sushi,Poke Bowl,https://norecipes.com/homemade-poke-bowl/
13,no_recipes,avocado sushi,Kani Salad,https://norecipes.com/kani-salad/
14,no_recipes,avocado sushi,Shrimp Tempura Roll,https://norecipes.com/shrimp-tempura-sushi-roll/
15,no_recipes,avocado sushi,Vegan Furikake (Matcha Flavor),https://norecipes.com/vegan-furikake-matcha/
16,no_recipes,avocado sushi,Spicy Tuna Roll,https://norecipes.com/spicy-tuna-roll/
17,no_recipes,avocado sushi,Spicy Salmon Poke,https://norecipes.com/spicy-salmon-poke/
18,no_recipes,avocado sushi,Tuna Tartare with Yuzu Gelée,https://norecipes.com/tuna-tartare-with-yuzu-g...
19,no_recipes,avocado sushi,Caterpillar Roll,https://norecipes.com/caterpillar-roll-recipe/

Source: no_recipes
Query: sushi rice
Search URL: https://norecipes.com/?s=sushi+rice
Status code: 200
HTML length: 453642
Candidate sushi links found: 63

,source_name,query,title_text,url
0,no_recipes,sushi rice,Start Here,https://norecipes.com/start-here/
1,no_recipes,sushi rice,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,sushi rice,subscribe,https://norecipes.com/subscribe/
3,no_recipes,sushi rice,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
4,no_recipes,sushi rice,Inari Sushi (Fried Tofu Pocket Sushi),https://norecipes.com/inari-sushi-recipe/
5,no_recipes,sushi rice,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
6,no_recipes,sushi rice,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
7,no_recipes,sushi rice,Seasoned Sushi Vinegar,https://norecipes.com/seasoned-sushi-vinegar/
8,no_recipes,sushi rice,How to Cook Japanese Short-Grain Rice,https://norecipes.com/cook-japanese-short-grai...
9,no_recipes,sushi rice,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
10,no_recipes,sushi rice,Pickled Sushi Ginger (Gari),https://norecipes.com/sushi-ginger-gari/
11,no_recipes,sushi rice,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
12,no_recipes,sushi rice,California Roll Sushi Bowl,https://norecipes.com/california-roll-sushi-bowl/
13,no_recipes,sushi rice,Filipino Garlic Rice (Sinangag),https://norecipes.com/filipino-garlic-rice-sin...
14,no_recipes,sushi rice,Omurice (オムライス),https://norecipes.com/omurice-recipe/
15,no_recipes,sushi rice,All About Riceberry,https://norecipes.com/healthy-riceberry-recipe/
16,no_recipes,sushi rice,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
17,no_recipes,sushi rice,Salmon Sashimi Donburi,https://norecipes.com/salmon-sashimi-donburi/
18,no_recipes,sushi rice,Spam Onigiri,https://norecipes.com/spam-onigiri/
19,no_recipes,sushi rice,California Roll,https://norecipes.com/california-roll-recipe/

Source: no_recipes
Query: spicy tuna roll
Search URL: https://norecipes.com/?s=spicy+tuna+roll
Status code: 200
HTML length: 432596
Candidate sushi links found: 50

,source_name,query,title_text,url
0,no_recipes,spicy tuna roll,Start Here,https://norecipes.com/start-here/
1,no_recipes,spicy tuna roll,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,spicy tuna roll,subscribe,https://norecipes.com/subscribe/
3,no_recipes,spicy tuna roll,Spicy Tuna Roll,https://norecipes.com/spicy-tuna-roll/
4,no_recipes,spicy tuna roll,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
5,no_recipes,spicy tuna roll,California Roll,https://norecipes.com/california-roll-recipe/
6,no_recipes,spicy tuna roll,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
7,no_recipes,spicy tuna roll,Shrimp Tempura Roll,https://norecipes.com/shrimp-tempura-sushi-roll/
8,no_recipes,spicy tuna roll,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
9,no_recipes,spicy tuna roll,California Roll Sushi Bowl,https://norecipes.com/california-roll-sushi-bowl/
10,no_recipes,spicy tuna roll,Tuna Mayo Onigiri,https://norecipes.com/tuna-mayo-onigiri/
11,no_recipes,spicy tuna roll,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
12,no_recipes,spicy tuna roll,Tuna Poke,https://norecipes.com/tuna-poke/
13,no_recipes,spicy tuna roll,Caterpillar Roll,https://norecipes.com/caterpillar-roll-recipe/
14,no_recipes,spicy tuna roll,Seaweed Salad (Wakame Salad),https://norecipes.com/seaweed-salad-recipe/
15,no_recipes,spicy tuna roll,Seasoned Sushi Vinegar,https://norecipes.com/seasoned-sushi-vinegar/
16,no_recipes,spicy tuna roll,Poke Bowl,https://norecipes.com/homemade-poke-bowl/
17,no_recipes,spicy tuna roll,Pickled Sushi Ginger (Gari),https://norecipes.com/sushi-ginger-gari/
18,no_recipes,spicy tuna roll,Omurice (オムライス),https://norecipes.com/omurice-recipe/
19,no_recipes,spicy tuna roll,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/

Source: no_recipes
Query: salmon roll
Search URL: https://norecipes.com/?s=salmon+roll
Status code: 200
HTML length: 436782
Candidate sushi links found: 54

,source_name,query,title_text,url
0,no_recipes,salmon roll,Start Here,https://norecipes.com/start-here/
1,no_recipes,salmon roll,Ingredients,https://norecipes.com/articles/ingredient/
2,no_recipes,salmon roll,subscribe,https://norecipes.com/subscribe/
3,no_recipes,salmon roll,Salmon Onigiri,https://norecipes.com/salmon-onigiri-rice-balls/
4,no_recipes,salmon roll,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
5,no_recipes,salmon roll,Japanese Breakfast Salmon,https://norecipes.com/japanese-breakfast-salmon/
6,no_recipes,salmon roll,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
7,no_recipes,salmon roll,Caterpillar Roll,https://norecipes.com/caterpillar-roll-recipe/
8,no_recipes,salmon roll,Dashimaki Tamago,https://norecipes.com/dashimaki-tamago/
9,no_recipes,salmon roll,Perfect Sushi Rice,https://norecipes.com/sushi-rice-recipe/
10,no_recipes,salmon roll,Tamagoyaki (Japanese Omelette),https://norecipes.com/tamagoyaki-recipe/
11,no_recipes,salmon roll,How to Make Ikura,https://norecipes.com/how-to-make-ikura/
12,no_recipes,salmon roll,Seaweed Salad (Wakame Salad),https://norecipes.com/seaweed-salad-recipe/
13,no_recipes,salmon roll,Cold Somen Noodles & Sauce,https://norecipes.com/cold-somen-noodles/
14,no_recipes,salmon roll,Onsen Tamago (Hot Spring Egg),https://norecipes.com/onsen-tamago-hot-spring-...
15,no_recipes,salmon roll,How to Cook Japanese Short-Grain Rice,https://norecipes.com/cook-japanese-short-grai...
16,no_recipes,salmon roll,Poke Bowl,https://norecipes.com/homemade-poke-bowl/
17,no_recipes,salmon roll,Japanese Kinpira Gobo Recipe (Video),https://norecipes.com/kinpira-gobo/
18,no_recipes,salmon roll,Vegan Furikake (Matcha Flavor),https://norecipes.com/vegan-furikake-matcha/
19,no_recipes,salmon roll,Takikomi Gohan,https://norecipes.com/takikomi-gohan-recipe/

Specialized sushi link extraction finished.
Total unique specialized sushi candidate links: 714

Links per source:
source_name
pickled_plum            314
chopstick_chronicles    232
no_recipes              120
okonomi_kitchen          48
Name: count, dtype: int64

,source_name,query,title_text,url
0,pickled_plum,sushi,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,sushi,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,sushi,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,sushi,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,sushi,No AI,https://pickledplum.com/no-ai/
...,...,...,...,...
709,no_recipes,salmon roll,Nasu Dengaku (Miso Glazed Eggplant),https://norecipes.com/miso-glazed-eggplant-nas...
710,no_recipes,salmon roll,Mushroom Doria (Mushroom Rice Casserole),https://norecipes.com/mushroom-doria-rice-cass...
711,no_recipes,salmon roll,Cabbage & Chicken Stew,https://norecipes.com/cabbage-chicken-stew/
712,no_recipes,salmon roll,Better Chocolate Chip Cookies,https://norecipes.com/better-chocolate-chip-co...
713,no_recipes,salmon roll,Lemon tuna steaks on roasted veggies,https://norecipes.com/lemon-tuna-steaks-on-roa...

In [30]:
# Cell 25E — Refine specialized sushi candidate links before scraping

def clean_candidate_url(url):
    """
    Remove fragments and query strings from URLs.
    """
    if pd.isna(url):
        return ""

    parsed = urlparse(str(url))
    clean_url = f"{parsed.scheme}://{parsed.netloc}{parsed.path}"

    if clean_url.endswith("#"):
        clean_url = clean_url[:-1]

    return clean_url


def is_refined_sushi_recipe_link(row):
    """
    Keep only direct sushi dish recipe links.
    Remove navigation pages, comment links, policy pages, and side/helper recipes.
    """
    source_name = row["source_name"]
    title = normalize_text_for_filtering(row.get("title_text", ""))
    url = clean_candidate_url(row["url"])
    path = urlparse(url).path.strip("/").lower()

    combined = normalize_text_for_filtering(title + " " + path)

    if not path:
        return False

    blocked_terms = [
        "accessibility",
        "privacy",
        "policy",
        "terms",
        "subscribe",
        "start-here",
        "ingredient",
        "ingredients",
        "recipe-filter",
        "recipe-index",
        "all-recipes",
        "collaborate",
        "content-guidelines",
        "no-ai",
        "comment",
        "comments",
        "category",
        "tag",
        "author",
        "shop",
        "cookbook",
        "newsletter",
        "about",
        "contact",
        "quick",
        "main-dish",
        "dessert",
        "kitchen-tools",
        "pantry",
        "appetizer",
        "beverage",
        "bread",
        "breakfast",
        "condiment",
        "salad",
        "side-dish",
        "soup-stew",
        "bento",
        "curry",
        "donburi",
        "dumpling",
        "hot-pot"
    ]

    for term in blocked_terms:
        if term in combined:
            return False

    # Remove helper/side items, not direct sushi dishes
    helper_terms = [
        "sushi-rice",
        "sushi rice",
        "seasoned-sushi-vinegar",
        "sushi vinegar",
        "sushi-ginger",
        "pickled sushi ginger",
        "gari",
        "seaweed-salad",
        "kani-salad",
        "ikura",
        "how-to",
        "what-is",
        "guide",
        "leftover",
        "miso-soup",
        "fried-rice",
        "omelette",
        "tamago",
        "ramen",
        "teriyaki",
        "spring-roll",
        "beef-negimaki",
        "sandwich",
        "onigiri",
        "poke",
        "bowl"
    ]

    for term in helper_terms:
        if term in combined:
            return False

    # Strong direct sushi dish terms
    direct_sushi_terms = [
        "sushi",
        "maki",
        "roll",
        "temaki",
        "futomaki",
        "uramaki",
        "nigiri",
        "chirashi",
        "inari"
    ]

    has_direct_sushi_term = any(term in combined for term in direct_sushi_terms)

    if not has_direct_sushi_term:
        return False

    # Extra source-specific cleanup
    if source_name == "okonomi_kitchen":
        # This source had many weak/non-sushi results in the search output.
        # Keep only if the URL/title is very explicit.
        okonomi_strong_terms = [
            "sushi",
            "maki",
            "roll",
            "temaki",
            "inari"
        ]
        if not any(term in combined for term in okonomi_strong_terms):
            return False

    return True


refined_specialized_sushi_links_df = specialized_sushi_links_df.copy()

refined_specialized_sushi_links_df["url"] = refined_specialized_sushi_links_df["url"].apply(clean_candidate_url)

refined_specialized_sushi_links_df = refined_specialized_sushi_links_df.drop_duplicates(
    subset=["url"]
).reset_index(drop=True)

refined_specialized_sushi_links_df["is_refined_sushi_recipe"] = refined_specialized_sushi_links_df.apply(
    is_refined_sushi_recipe_link,
    axis=1
)

rejected_specialized_sushi_links_df = refined_specialized_sushi_links_df[
    refined_specialized_sushi_links_df["is_refined_sushi_recipe"] == False
].copy()

refined_specialized_sushi_links_df = refined_specialized_sushi_links_df[
    refined_specialized_sushi_links_df["is_refined_sushi_recipe"] == True
].copy()

refined_specialized_sushi_links_df = refined_specialized_sushi_links_df.drop(
    columns=["is_refined_sushi_recipe"],
    errors="ignore"
).reset_index(drop=True)

print("Original specialized sushi links:")
print(len(specialized_sushi_links_df))

print("\nUnique links after URL cleaning:")
print(len(refined_specialized_sushi_links_df) + len(rejected_specialized_sushi_links_df))

print("\nRefined specialized sushi recipe links:")
print(len(refined_specialized_sushi_links_df))

print("\nRejected specialized sushi links:")
print(len(rejected_specialized_sushi_links_df))

print("\nRefined links per source:")
if not refined_specialized_sushi_links_df.empty:
    print(refined_specialized_sushi_links_df["source_name"].value_counts())
    display(refined_specialized_sushi_links_df)
else:
    print("No refined links found.")

print("\nRejected examples:")
display(rejected_specialized_sushi_links_df[[
    "source_name",
    "query",
    "title_text",
    "url"
]].head(30))

Original specialized sushi links:
714

Unique links after URL cleaning:
469

Refined specialized sushi recipe links:
47

Rejected specialized sushi links:
422

Refined links per source:
source_name
chopstick_chronicles    24
no_recipes              12
pickled_plum             8
okonomi_kitchen          3
Name: count, dtype: int64

,source_name,query,title_text,url
0,pickled_plum,sushi,,https://pickledplum.com/maki-sushi/
1,pickled_plum,sushi,,https://pickledplum.com/temari-sushi/
2,pickled_plum,sushi,,https://pickledplum.com/inari-sushi-recipe/
3,pickled_plum,sushi,,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
4,pickled_plum,sushi,,https://pickledplum.com/vegetarian-chirashi-su...
5,pickled_plum,sushi,,https://pickledplum.com/philadelphia-roll/
6,pickled_plum,sushi,,https://pickledplum.com/spicy-tuna-roll-recipe/
7,pickled_plum,sushi roll,,https://pickledplum.com/california-roll-spicy-...
8,chopstick_chronicles,sushi,Sushi,https://www.chopstickchronicles.com/sushi/
9,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/temari-sushi/
10,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/gunkan-sus...
11,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/chirashi-s...
12,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/unagi-sushi/
13,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/temaki-sushi/
14,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/kappa-maki/
15,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/oshinko-roll/
16,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/sushi-cake/
17,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/california...
18,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/pressed-su...
19,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/christmas-...
20,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/inari-sushi/
21,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/ehoumaki/
22,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/sushi-ball...
23,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/sushi-donuts/
24,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/chirashizu...
25,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/futomaki/
26,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/uramaki/
27,chopstick_chronicles,sushi roll,,https://www.chopstickchronicles.com/datemaki/
28,chopstick_chronicles,sushi roll,,https://www.chopstickchronicles.com/hosomaki/
29,chopstick_chronicles,sushi roll,,https://www.chopstickchronicles.com/wild-rice-...
30,chopstick_chronicles,maki,,https://www.chopstickchronicles.com/nama-harum...
31,chopstick_chronicles,maki,,https://www.chopstickchronicles.com/harumaki/
32,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/vegan-take-away...
33,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/soba-inari/
34,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/inari-age/
35,no_recipes,sushi,Inari Sushi (Fried Tofu Pocket Sushi),https://norecipes.com/inari-sushi-recipe/
36,no_recipes,sushi,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
37,no_recipes,sushi,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
38,no_recipes,sushi,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
39,no_recipes,sushi,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
40,no_recipes,sushi,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
41,no_recipes,sushi,California Roll,https://norecipes.com/california-roll-recipe/
42,no_recipes,sushi,Shrimp Tempura Roll,https://norecipes.com/shrimp-tempura-sushi-roll/
43,no_recipes,sushi,Spicy Tuna Roll,https://norecipes.com/spicy-tuna-roll/
44,no_recipes,sushi roll,Caterpillar Roll,https://norecipes.com/caterpillar-roll-recipe/
45,no_recipes,sushi roll,Datemaki,https://norecipes.com/datemaki/
46,no_recipes,maki,5 Tips for Making Perfect Crêpes,https://norecipes.com/5-tips-for-making-perfec...

Rejected examples:

,source_name,query,title_text,url
0,pickled_plum,sushi,All Recipes,https://pickledplum.com/recipe-filter/
1,pickled_plum,sushi,Accessibility,https://pickledplum.com/accessibility/
2,pickled_plum,sushi,Collaborate,https://pickledplum.com/collaborate/
3,pickled_plum,sushi,Content Guidelines,https://pickledplum.com/sharing-content-images...
4,pickled_plum,sushi,No AI,https://pickledplum.com/no-ai/
5,pickled_plum,sushi,Privacy Policy,https://pickledplum.com/privacy-policy/
6,pickled_plum,sushi,,https://pickledplum.com/how-to-make-sushi-at-h...
7,pickled_plum,sushi,,https://pickledplum.com/how-to-make-sushi-rice/
13,pickled_plum,sushi,,https://pickledplum.com/what-to-do-with-leftov...
14,pickled_plum,sushi,,https://pickledplum.com/daikon-miso-soup/
15,pickled_plum,sushi,,https://pickledplum.com/japanese-konbini-food/
16,pickled_plum,sushi,,https://pickledplum.com/shiso-dressing/
17,pickled_plum,sushi,,https://pickledplum.com/eggplant-miso-soup/
18,pickled_plum,sushi,,https://pickledplum.com/kinoko-soba-ankake/
19,pickled_plum,sushi,,https://pickledplum.com/hamachi-crudo/
20,pickled_plum,sushi,,https://pickledplum.com/conbini-style-tuna-may...
21,pickled_plum,sushi,,https://pickledplum.com/szechuan-style-nasu-de...
22,pickled_plum,sushi,,https://pickledplum.com/miso-soup-tofu-wakame/
23,pickled_plum,sushi,,https://pickledplum.com/shiraae-japanese-mashe...
24,pickled_plum,sushi,,https://pickledplum.com/ingredient/umeboshi-ja...
25,pickled_plum,sushi,,https://pickledplum.com/chukadon-donburi/
26,pickled_plum,sushi,,https://pickledplum.com/ingredient/wasabi/
27,pickled_plum,sushi,,https://pickledplum.com/lemon-sour-japanese/
28,pickled_plum,sushi,,https://pickledplum.com/what-to-eat-with-kimchi/
29,pickled_plum,sushi,,https://pickledplum.com/skillet-dolsot-bibimbap/
31,pickled_plum,sushi,,https://pickledplum.com/maitake-mushroom-miso-...
32,pickled_plum,sushi,,https://pickledplum.com/easy-lunch-ideas/
33,pickled_plum,sushi,,https://pickledplum.com/how-to-cook-rice-in-a-...
34,pickled_plum,sushi,,https://pickledplum.com/easy-healthy-soup-reci...
35,pickled_plum,sushi,,https://pickledplum.com/easy-japanese-salad-re...

In [31]:
# Cell 25F — Strict sushi link refinement v2

def is_strict_direct_sushi_link(row):
    """
    Keep only direct sushi dish recipe links.
    This removes guides, comparison articles, helper recipes, desserts, and weak hybrids.
    """
    source_name = row["source_name"]
    title = normalize_text_for_filtering(row.get("title_text", ""))
    url = clean_candidate_url(row["url"])
    path = urlparse(url).path.strip("/").lower()

    combined = normalize_text_for_filtering(title + " " + path)

    if not path:
        return False

    hard_reject_terms = [
        "accessibility",
        "privacy",
        "policy",
        "subscribe",
        "start-here",
        "ingredient",
        "recipe-filter",
        "tips",
        "guide",
        "vs",
        "how-to",
        "making",
        "crepes",
        "cake",
        "christmas",
        "donut",
        "donuts",
        "wild-rice",
        "harumaki",
        "nama-harumaki",
        "datemaki",
        "soba",
        "inari-age",
        "take-away",
        "take away",
        "sushi-rice",
        "sushi rice",
        "seasoned-sushi-vinegar",
        "vinegar",
        "ginger",
        "gari",
        "seaweed-salad",
        "kani-salad",
        "ikura",
        "onigiri",
        "bowl",
        "donburi",
        "sashimi-donburi"
    ]

    for term in hard_reject_terms:
        if term in combined:
            return False

    direct_keep_terms = [
        "maki-sushi",
        "maki sushi",
        "temari-sushi",
        "temari sushi",
        "inari-sushi",
        "inari sushi",
        "chirashi-sushi",
        "chirashi sushi",
        "seafood-chirashi-sushi",
        "seafood chirashi sushi",
        "unagi-sushi",
        "unagi sushi",
        "temaki-sushi",
        "temaki sushi",
        "kappa-maki",
        "kappa maki",
        "oshinko-roll",
        "oshinko roll",
        "california-roll",
        "california roll",
        "pressed-sushi",
        "pressed sushi",
        "futomaki",
        "uramaki",
        "hosomaki",
        "gunkan-sushi",
        "gunkan sushi",
        "shrimp-tempura-sushi-roll",
        "shrimp tempura roll",
        "spicy-tuna-roll",
        "spicy tuna roll",
        "spicy-salmon-sushi-hand-rolls",
        "spicy salmon temaki sushi",
        "caterpillar-roll",
        "caterpillar roll",
        "philadelphia-roll",
        "philadelphia roll"
    ]

    if any(term in combined for term in direct_keep_terms):
        return True

    # Keep very explicit sushi pages only, but avoid broad generic pages from weak sources.
    if source_name in ["no_recipes", "pickled_plum", "chopstick_chronicles"]:
        if combined in ["sushi", "sushi sushi"]:
            return True

    return False


strict_sushi_links_v2_df = refined_specialized_sushi_links_df.copy()

strict_sushi_links_v2_df["url"] = strict_sushi_links_v2_df["url"].apply(clean_candidate_url)

strict_sushi_links_v2_df["is_strict_direct_sushi"] = strict_sushi_links_v2_df.apply(
    is_strict_direct_sushi_link,
    axis=1
)

strict_rejected_sushi_links_v2_df = strict_sushi_links_v2_df[
    strict_sushi_links_v2_df["is_strict_direct_sushi"] == False
].copy()

strict_sushi_links_v2_df = strict_sushi_links_v2_df[
    strict_sushi_links_v2_df["is_strict_direct_sushi"] == True
].copy()

strict_sushi_links_v2_df = strict_sushi_links_v2_df.drop(
    columns=["is_strict_direct_sushi"],
    errors="ignore"
).drop_duplicates(subset=["url"]).reset_index(drop=True)

print("Refined v1 sushi links:")
print(len(refined_specialized_sushi_links_df))

print("\nStrict sushi links v2:")
print(len(strict_sushi_links_v2_df))

print("\nRejected by strict v2:")
print(len(strict_rejected_sushi_links_v2_df))

print("\nStrict sushi links per source:")
if not strict_sushi_links_v2_df.empty:
    print(strict_sushi_links_v2_df["source_name"].value_counts())
    display(strict_sushi_links_v2_df)
else:
    print("No strict links found.")

print("\nRejected examples from v2:")
display(strict_rejected_sushi_links_v2_df[[
    "source_name",
    "query",
    "title_text",
    "url"
]].head(40))

Refined v1 sushi links:
47

Strict sushi links v2:
31

Rejected by strict v2:
16

Strict sushi links per source:
source_name
chopstick_chronicles    14
no_recipes              10
pickled_plum             7
Name: count, dtype: int64

,source_name,query,title_text,url
0,pickled_plum,sushi,,https://pickledplum.com/maki-sushi/
1,pickled_plum,sushi,,https://pickledplum.com/temari-sushi/
2,pickled_plum,sushi,,https://pickledplum.com/inari-sushi-recipe/
3,pickled_plum,sushi,,https://pickledplum.com/vegetarian-chirashi-su...
4,pickled_plum,sushi,,https://pickledplum.com/philadelphia-roll/
5,pickled_plum,sushi,,https://pickledplum.com/spicy-tuna-roll-recipe/
6,pickled_plum,sushi roll,,https://pickledplum.com/california-roll-spicy-...
7,chopstick_chronicles,sushi,Sushi,https://www.chopstickchronicles.com/sushi/
8,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/temari-sushi/
9,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/gunkan-sus...
10,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/chirashi-s...
11,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/unagi-sushi/
12,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/temaki-sushi/
13,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/kappa-maki/
14,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/oshinko-roll/
15,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/california...
16,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/pressed-su...
17,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/inari-sushi/
18,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/futomaki/
19,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/uramaki/
20,chopstick_chronicles,sushi roll,,https://www.chopstickchronicles.com/hosomaki/
21,no_recipes,sushi,Inari Sushi (Fried Tofu Pocket Sushi),https://norecipes.com/inari-sushi-recipe/
22,no_recipes,sushi,Oshinko Roll (Pickled Vegetable Sushi),https://norecipes.com/oshinko-roll-maki-sushi/
23,no_recipes,sushi,Kappa Maki (Cucumber Sushi Rolls),https://norecipes.com/kappa-maki-cucumber-sush...
24,no_recipes,sushi,Seafood Chirashi Sushi (海鮮ちらし寿司),https://norecipes.com/seafood-chirashi-sushi/
25,no_recipes,sushi,Spicy Salmon Temaki Sushi,https://norecipes.com/spicy-salmon-sushi-hand-...
26,no_recipes,sushi,Temaki Sushi Hand Rolls,https://norecipes.com/temaki-sushi/
27,no_recipes,sushi,California Roll,https://norecipes.com/california-roll-recipe/
28,no_recipes,sushi,Shrimp Tempura Roll,https://norecipes.com/shrimp-tempura-sushi-roll/
29,no_recipes,sushi,Spicy Tuna Roll,https://norecipes.com/spicy-tuna-roll/
30,no_recipes,sushi roll,Caterpillar Roll,https://norecipes.com/caterpillar-roll-recipe/

Rejected examples from v2:

,source_name,query,title_text,url
3,pickled_plum,sushi,,https://pickledplum.com/nigiri-vs-sushi-vs-mus...
16,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/sushi-cake/
19,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/christmas-...
21,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/ehoumaki/
22,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/sushi-ball...
23,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/sushi-donuts/
24,chopstick_chronicles,sushi,,https://www.chopstickchronicles.com/chirashizu...
27,chopstick_chronicles,sushi roll,,https://www.chopstickchronicles.com/datemaki/
29,chopstick_chronicles,sushi roll,,https://www.chopstickchronicles.com/wild-rice-...
30,chopstick_chronicles,maki,,https://www.chopstickchronicles.com/nama-harum...
31,chopstick_chronicles,maki,,https://www.chopstickchronicles.com/harumaki/
32,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/vegan-take-away...
33,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/soba-inari/
34,okonomi_kitchen,sushi,,https://www.okonomikitchen.com/inari-age/
45,no_recipes,sushi roll,Datemaki,https://norecipes.com/datemaki/
46,no_recipes,maki,5 Tips for Making Perfect Crêpes,https://norecipes.com/5-tips-for-making-perfec...

In [32]:
# Cell 25G — Test scraping one sushi recipe page from each specialized source

def scrape_specialized_sushi_recipe(url, source_site, food_class="sushi", query=None):
    """
    Scrape one specialized sushi recipe page using Recipe JSON-LD when available.
    Returns a structured recipe record if nutrition exists.
    """
    response = safe_get(url, sleep_min=1, sleep_max=2, timeout=25)

    if response is None:
        print("No response for:", url)
        return None

    if response.status_code != 200:
        print("Failed URL:", url)
        print("Status code:", response.status_code)
        return None

    soup = BeautifulSoup(response.text, "html.parser")
    recipe_json = find_recipe_json_ld(soup)

    if recipe_json is None:
        print("No Recipe JSON-LD found for:", url)
        return None

    recipe_name = recipe_json.get("name")

    ingredients = recipe_json.get("recipeIngredient", [])
    if isinstance(ingredients, list):
        ingredients_text = " ".join([str(item) for item in ingredients])
    else:
        ingredients_text = str(ingredients)

    nutrition = recipe_json.get("nutrition", {})
    if not isinstance(nutrition, dict):
        nutrition = {}

    calories = extract_number(nutrition.get("calories"))
    protein = extract_number(nutrition.get("proteinContent"))
    fat = extract_number(nutrition.get("fatContent"))
    carbs = extract_number(nutrition.get("carbohydrateContent"))

    record = {
        "source_site": source_site,
        "food_class": food_class,
        "query": query,
        "recipe_name": recipe_name,
        "ingredients_text": ingredients_text,
        "calories": calories,
        "protein": protein,
        "fat": fat,
        "carbs": carbs,
        "source_url": url,
        "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

    return record


# Test one URL from each source
test_source_records = []

for source_name in strict_sushi_links_v2_df["source_name"].unique():
    print("\n====================================")
    print("Testing source:", source_name)
    print("====================================")

    sample_row = strict_sushi_links_v2_df[
        strict_sushi_links_v2_df["source_name"] == source_name
    ].iloc[0]

    test_url = sample_row["url"]
    test_query = sample_row["query"]

    print("Test URL:")
    print(test_url)

    test_record = scrape_specialized_sushi_recipe(
        url=test_url,
        source_site=source_name,
        food_class="sushi",
        query=test_query
    )

    print("\nScraped record:")
    print(test_record)

    if test_record is not None:
        print("\nIngredients length:", len(test_record["ingredients_text"]) if test_record["ingredients_text"] else 0)
        print("Calories:", test_record["calories"])
        print("Protein:", test_record["protein"])
        print("Fat:", test_record["fat"])
        print("Carbs:", test_record["carbs"])

        test_source_records.append(test_record)

test_specialized_sushi_df = pd.DataFrame(test_source_records)

print("\nTest scraping summary:")
if not test_specialized_sushi_df.empty:
    display(test_specialized_sushi_df[[
        "source_site",
        "recipe_name",
        "calories",
        "protein",
        "fat",
        "carbs",
        "source_url"
    ]])
else:
    print("No successful test records.")

====================================
Testing source: pickled_plum
====================================
Test URL:
https://pickledplum.com/maki-sushi/

Scraped record:
{'source_site': 'pickled_plum', 'food_class': 'sushi', 'query': 'sushi', 'recipe_name': 'Maki Sushi ', 'ingredients_text': '4 cups sushi rice &#8211; visit my post on how to make sushi rice Persian or Kirby cucumber, cut into 1/2-inch long strips Takuan (pickled daikon radish), cut into 1/2-inch long strips Avocado, pitted, cut into 1/2-inch long strips Cooked sweet potato (don&#8217;t overcook it to the point where it&#8217;s mushy), cut into 1/2-inch long strips. Natto (1 box) Sashimi grade tuna, salmon, or yellowtail (about 5 oz for 8 rolls), cut into 1/2-inch long strips 4 nori sheets Soy sauce, for dipping Wasabi (optional) Pickled ginger (optional)', 'calories': 150.0, 'protein': 2.5, 'fat': 1.5, 'carbs': 30.8, 'source_url': 'https://pickledplum.com/maki-sushi/', 'scraped_at': '2026-05-12 03:08:36'}

Ingredients length: 538
Calories: 150.0
Protein: 2.5
Fat: 1.5
Carbs: 30.8

====================================
Testing source: chopstick_chronicles
====================================
Test URL:
https://www.chopstickchronicles.com/sushi/
No Recipe JSON-LD found for: https://www.chopstickchronicles.com/sushi/

Scraped record:
None

====================================
Testing source: no_recipes
====================================
Test URL:
https://norecipes.com/inari-sushi-recipe/

Scraped record:
{'source_site': 'no_recipes', 'food_class': 'sushi', 'query': 'sushi', 'recipe_name': 'Inari Sushi (Fried Tofu Pocket Sushi)', 'ingredients_text': '6  aburaage ((thin fried tofu)) 1 cup water 1/4 cup sake 3 tablespoons sugar 2 tablespoons soy sauce 300 grams Japanese short-grain rice 4 tablespoons rice vinegar 2 tablespoons sugar 1 teaspoon salt 40 grams gari ((finely chopped)) 1 tablespoon toasted sesame seeds', 'calories': 376.0, 'protein': 9.0, 'fat': 6.0, 'carbs': 67.0, 'source_url': 'https://norecipes.com/inari-sushi-recipe/', 'scraped_at': '2026-05-12 03:08:40'}

Ingredients length: 266
Calories: 376.0
Protein: 9.0
Fat: 6.0
Carbs: 67.0

Test scraping summary:

,source_site,recipe_name,calories,protein,fat,carbs,source_url
0,pickled_plum,Maki Sushi,150.0,2.5,1.5,30.8,https://pickledplum.com/maki-sushi/
1,no_recipes,Inari Sushi (Fried Tofu Pocket Sushi),376.0,9.0,6.0,67.0,https://norecipes.com/inari-sushi-recipe/

In [33]:
# Cell 25H — Scrape strict sushi supplement records from specialized sources

def sushi_specialized_reject_reason(record):
    """
    Reject weak sushi records after scraping.
    Keeps direct sushi dishes only.
    """
    recipe_name = normalize_text_for_filtering(record.get("recipe_name"))
    source_url = normalize_text_for_filtering(record.get("source_url"))
    combined = recipe_name + " " + source_url

    required_cols = ["calories", "protein", "fat", "carbs"]

    for col in required_cols:
        if record.get(col) is None or pd.isna(record.get(col)):
            return "missing_nutrition"

    if record["calories"] < 30:
        return "calories_too_low"

    if record["calories"] > 1600:
        return "calories_too_high"

    if record["protein"] > 120:
        return "protein_outlier"

    if record["fat"] > 120:
        return "fat_outlier"

    if record["carbs"] > 180:
        return "carbs_outlier"

    weak_terms = [
        "sushi rice",
        "perfect sushi rice",
        "seasoned sushi vinegar",
        "sushi vinegar",
        "sushi ginger",
        "pickled sushi ginger",
        "gari",
        "sushi cake",
        "sushi donuts",
        "sushi donut",
        "sushi pizza",
        "sushi bowl",
        "california roll sushi bowl",
        "datemaki",
        "crepes",
        "tips",
        "guide",
        "how to",
        "vs"
    ]

    for term in weak_terms:
        if term in combined:
            return "weak_or_helper_sushi_record"

    direct_terms = [
        "sushi",
        "maki",
        "roll",
        "temaki",
        "futomaki",
        "uramaki",
        "hosomaki",
        "gunkan",
        "chirashi",
        "inari",
        "california roll",
        "spicy tuna",
        "shrimp tempura",
        "caterpillar"
    ]

    if not any(term in combined for term in direct_terms):
        return "not_direct_sushi"

    return ""


existing_urls_for_sushi = set(merged_text_calorie_df["source_url"].tolist())
existing_names_for_sushi = set(
    merged_text_calorie_df["recipe_name"].apply(normalize_text_for_filtering).tolist()
)

sushi_specialized_accepted_records = []
sushi_specialized_rejected_records = []
sushi_specialized_failed_urls = []

print("Strict sushi candidate links:")
print(len(strict_sushi_links_v2_df))

for idx, row in strict_sushi_links_v2_df.iterrows():
    source_name = row["source_name"]
    url = clean_candidate_url(row["url"])
    query = row["query"]

    print("\n====================================")
    print("Index:", idx)
    print("Source:", source_name)
    print("URL:", url)
    print("====================================")

    if url in existing_urls_for_sushi:
        sushi_specialized_rejected_records.append({
            "source_site": source_name,
            "food_class": "sushi",
            "query": query,
            "recipe_name": None,
            "ingredients_text": None,
            "calories": None,
            "protein": None,
            "fat": None,
            "carbs": None,
            "source_url": url,
            "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "drop_reason": "duplicate_url_existing_dataset"
        })
        print("Result: rejected duplicate URL")
        continue

    record = scrape_specialized_sushi_recipe(
        url=url,
        source_site=source_name,
        food_class="sushi",
        query=query
    )

    if record is None:
        sushi_specialized_failed_urls.append({
            "source_site": source_name,
            "query": query,
            "url": url,
            "reason": "scrape_failed_or_no_json_ld"
        })
        print("Result: failed")
        continue

    normalized_name = normalize_text_for_filtering(record.get("recipe_name"))

    if normalized_name in existing_names_for_sushi:
        rejected_record = record.copy()
        rejected_record["drop_reason"] = "duplicate_recipe_name_existing_dataset"
        sushi_specialized_rejected_records.append(rejected_record)
        print("Result: rejected duplicate recipe name")
        print("Recipe:", record.get("recipe_name"))
        continue

    drop_reason = sushi_specialized_reject_reason(record)

    if drop_reason != "":
        rejected_record = record.copy()
        rejected_record["drop_reason"] = drop_reason
        sushi_specialized_rejected_records.append(rejected_record)
        print("Result: rejected")
        print("Recipe:", record.get("recipe_name"))
        print("Reason:", drop_reason)
        continue

    sushi_specialized_accepted_records.append(record)
    existing_urls_for_sushi.add(url)
    existing_names_for_sushi.add(normalized_name)

    print("Result: accepted")
    print("Recipe:", record["recipe_name"])
    print("Calories:", record["calories"])
    print("Accepted so far:", len(sushi_specialized_accepted_records))

sushi_specialized_supplement_df = pd.DataFrame(sushi_specialized_accepted_records)
sushi_specialized_rejected_df = pd.DataFrame(sushi_specialized_rejected_records)
sushi_specialized_failed_df = pd.DataFrame(sushi_specialized_failed_urls)

print("\nSpecialized sushi scraping finished.")
print("Accepted sushi supplement shape:", sushi_specialized_supplement_df.shape)

if not sushi_specialized_supplement_df.empty:
    print("\nAccepted records per source:")
    print(sushi_specialized_supplement_df["source_site"].value_counts())

print("\nRejected sushi records:", len(sushi_specialized_rejected_df))
print("Failed sushi URLs:", len(sushi_specialized_failed_df))

if not sushi_specialized_supplement_df.empty:
    display(sushi_specialized_supplement_df[[
        "source_site",
        "food_class",
        "query",
        "recipe_name",
        "calories",
        "protein",
        "fat",
        "carbs",
        "source_url"
    ]])

if not sushi_specialized_rejected_df.empty:
    print("\nRejected examples:")
    display(sushi_specialized_rejected_df[[
        "source_site",
        "food_class",
        "query",
        "recipe_name",
        "calories",
        "protein",
        "fat",
        "carbs",
        "source_url",
        "drop_reason"
    ]].head(20))

if not sushi_specialized_failed_df.empty:
    print("\nFailed examples:")
    display(sushi_specialized_failed_df.head(20))

# Save outputs
sushi_specialized_supplement_path = SCRAPED_RAW_DIR / "specialized_sushi_supplement_raw.csv"
sushi_specialized_rejected_path = LOGS_DIR / "specialized_sushi_rejected_records.csv"
sushi_specialized_failed_path = LOGS_DIR / "specialized_sushi_failed_urls.csv"

sushi_specialized_supplement_df.to_csv(sushi_specialized_supplement_path, index=False)
sushi_specialized_rejected_df.to_csv(sushi_specialized_rejected_path, index=False)
sushi_specialized_failed_df.to_csv(sushi_specialized_failed_path, index=False)

print("\nSpecialized sushi supplement saved to:")
print(sushi_specialized_supplement_path)

print("\nSpecialized sushi rejected log saved to:")
print(sushi_specialized_rejected_path)

print("\nSpecialized sushi failed URL log saved to:")
print(sushi_specialized_failed_path)

Strict sushi candidate links:
31

====================================
Index: 0
Source: pickled_plum
URL: https://pickledplum.com/maki-sushi/
====================================
Result: accepted
Recipe: Maki Sushi
Calories: 150.0
Accepted so far: 1

====================================
Index: 1
Source: pickled_plum
URL: https://pickledplum.com/temari-sushi/
====================================
Result: accepted
Recipe: Temari Sushi
Calories: 64.0
Accepted so far: 2

====================================
Index: 2
Source: pickled_plum
URL: https://pickledplum.com/inari-sushi-recipe/
====================================
Result: accepted
Recipe: Inari Sushi (Inarizushi - いなり寿司)
Calories: 81.0
Accepted so far: 3

====================================
Index: 3
Source: pickled_plum
URL: https://pickledplum.com/vegetarian-chirashi-sushi-recipe/
====================================
Result: accepted
Recipe: Vegetarian Chirashi Sushi
Calories: 604.0
Accepted so far: 4

====================================
Index: 4
Source: pickled_plum
URL: https://pickledplum.com/philadelphia-roll/
====================================
Result: accepted
Recipe: Philadelphia Roll
Calories: 575.0
Accepted so far: 5

====================================
Index: 5
Source: pickled_plum
URL: https://pickledplum.com/spicy-tuna-roll-recipe/
====================================
Result: accepted
Recipe: Spicy Tuna Roll (Poor Man's)
Calories: 106.0
Accepted so far: 6

====================================
Index: 6
Source: pickled_plum
URL: https://pickledplum.com/california-roll-spicy-california-roll/
====================================
Result: accepted
Recipe: California Roll
Calories: 394.0
Accepted so far: 7

====================================
Index: 7
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/sushi/
====================================
No Recipe JSON-LD found for: https://www.chopstickchronicles.com/sushi/
Result: failed

====================================
Index: 8
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/temari-sushi/
====================================
Result: rejected duplicate recipe name
Recipe: Temari Sushi 手毬寿司

====================================
Index: 9
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/gunkan-sushi-recipe-battleship-sushi/
====================================
Result: accepted
Recipe: Gunkan Sushi (Battleship Sushi)
Calories: 121.0
Accepted so far: 8

====================================
Index: 10
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/chirashi-sushi/
====================================
Result: accepted
Recipe: Chirashi Sushi ちらし寿司
Calories: 430.0
Accepted so far: 9

====================================
Index: 11
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/unagi-sushi/
====================================
Result: accepted
Recipe: Unagi Sushi 鰻寿司
Calories: 341.0
Accepted so far: 10

====================================
Index: 12
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/temaki-sushi/
====================================
Result: accepted
Recipe: Temaki Sushi 手巻き寿司
Calories: 384.0
Accepted so far: 11

====================================
Index: 13
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/kappa-maki/
====================================
Result: accepted
Recipe: Kappa Maki かっぱ巻き : Mini Cucumber Sushi Rolls
Calories: 142.0
Accepted so far: 12

====================================
Index: 14
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/oshinko-roll/
====================================
Result: accepted
Recipe: Oshinko roll お新香巻き
Calories: 148.0
Accepted so far: 13

====================================
Index: 15
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/california-roll-sushi/
====================================
Result: rejected duplicate recipe name
Recipe: California Roll カリフォルニア巻き

====================================
Index: 16
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/pressed-sushi-with-smoked-salmon/
====================================
Result: accepted
Recipe: Pressed Sushi with Smoked Salmon スモークサーモンの押し寿司
Calories: 368.0
Accepted so far: 14

====================================
Index: 17
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/inari-sushi/
====================================
Result: rejected
Recipe: Aunt Keiko's Inarisushi いなり寿司
Reason: missing_nutrition

====================================
Index: 18
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/futomaki/
====================================
Result: accepted
Recipe: Sushi rolls Futomaki 太巻き寿司
Calories: 364.0
Accepted so far: 15

====================================
Index: 19
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/uramaki/
====================================
Result: accepted
Recipe: Uramaki 裏巻き
Calories: 480.0
Accepted so far: 16

====================================
Index: 20
Source: chopstick_chronicles
URL: https://www.chopstickchronicles.com/hosomaki/
====================================
Result: accepted
Recipe: Hosomaki 細巻き
Calories: 183.0
Accepted so far: 17

====================================
Index: 21
Source: no_recipes
URL: https://norecipes.com/inari-sushi-recipe/
====================================
Result: accepted
Recipe: Inari Sushi (Fried Tofu Pocket Sushi)
Calories: 376.0
Accepted so far: 18

====================================
Index: 22
Source: no_recipes
URL: https://norecipes.com/oshinko-roll-maki-sushi/
====================================
Result: accepted
Recipe: Oshinko Roll (Japanese Pickle Sushi)
Calories: 81.0
Accepted so far: 19

====================================
Index: 23
Source: no_recipes
URL: https://norecipes.com/kappa-maki-cucumber-sushi-rolls/
====================================
Result: accepted
Recipe: Kappa Maki (Cucumber Sushi Roll)
Calories: 303.0
Accepted so far: 20

====================================
Index: 24
Source: no_recipes
URL: https://norecipes.com/seafood-chirashi-sushi/
====================================
Result: accepted
Recipe: Seafood Chirashi Sushi
Calories: 677.0
Accepted so far: 21

====================================
Index: 25
Source: no_recipes
URL: https://norecipes.com/spicy-salmon-sushi-hand-roll/
====================================
Result: accepted
Recipe: Spicy Salmon Hand Roll
Calories: 139.0
Accepted so far: 22

====================================
Index: 26
Source: no_recipes
URL: https://norecipes.com/temaki-sushi/
====================================
Result: accepted
Recipe: Temaki Sushi (Hand Rolls)
Calories: 45.0
Accepted so far: 23

====================================
Index: 27
Source: no_recipes
URL: https://norecipes.com/california-roll-recipe/
====================================
Result: accepted
Recipe: Best California Roll
Calories: 190.0
Accepted so far: 24

====================================
Index: 28
Source: no_recipes
URL: https://norecipes.com/shrimp-tempura-sushi-roll/
====================================
Result: accepted
Recipe: Shrimp Tempura Roll
Calories: 232.0
Accepted so far: 25

====================================
Index: 29
Source: no_recipes
URL: https://norecipes.com/spicy-tuna-roll/
====================================
Result: accepted
Recipe: Spicy Tuna Rolls
Calories: 449.0
Accepted so far: 26

====================================
Index: 30
Source: no_recipes
URL: https://norecipes.com/caterpillar-roll-recipe/
====================================
Result: accepted
Recipe: Caterpillar Roll
Calories: 400.0
Accepted so far: 27

Specialized sushi scraping finished.
Accepted sushi supplement shape: (27, 11)

Accepted records per source:
source_site
chopstick_chronicles    10
no_recipes              10
pickled_plum             7
Name: count, dtype: int64

Rejected sushi records: 3
Failed sushi URLs: 1

,source_site,food_class,query,recipe_name,calories,protein,fat,carbs,source_url
0,pickled_plum,sushi,sushi,Maki Sushi,150.0,2.5,1.5,30.8,https://pickledplum.com/maki-sushi/
1,pickled_plum,sushi,sushi,Temari Sushi,64.0,2.7,0.3,12.2,https://pickledplum.com/temari-sushi/
2,pickled_plum,sushi,sushi,Inari Sushi (Inarizushi - いなり寿司),81.0,0.3,2.1,3.7,https://pickledplum.com/inari-sushi-recipe/
3,pickled_plum,sushi,sushi,Vegetarian Chirashi Sushi,604.0,11.3,17.4,96.4,https://pickledplum.com/vegetarian-chirashi-su...
4,pickled_plum,sushi,sushi,Philadelphia Roll,575.0,25.6,13.5,86.0,https://pickledplum.com/philadelphia-roll/
5,pickled_plum,sushi,sushi,Spicy Tuna Roll (Poor Man's),106.0,6.8,2.0,14.3,https://pickledplum.com/spicy-tuna-roll-recipe/
6,pickled_plum,sushi,sushi roll,California Roll,394.0,8.2,15.5,56.2,https://pickledplum.com/california-roll-spicy-...
7,chopstick_chronicles,sushi,sushi,Gunkan Sushi (Battleship Sushi),121.0,3.0,0.3,27.0,https://www.chopstickchronicles.com/gunkan-sus...
8,chopstick_chronicles,sushi,sushi,Chirashi Sushi ちらし寿司,430.0,7.0,3.0,92.0,https://www.chopstickchronicles.com/chirashi-s...
9,chopstick_chronicles,sushi,sushi,Unagi Sushi 鰻寿司,341.0,13.0,2.0,148.0,https://www.chopstickchronicles.com/unagi-sushi/
10,chopstick_chronicles,sushi,sushi,Temaki Sushi 手巻き寿司,384.0,22.0,5.0,57.0,https://www.chopstickchronicles.com/temaki-sushi/
11,chopstick_chronicles,sushi,sushi,Kappa Maki かっぱ巻き : Mini Cucumber Sushi Rolls,142.0,1.0,1.0,32.0,https://www.chopstickchronicles.com/kappa-maki/
12,chopstick_chronicles,sushi,sushi,Oshinko roll お新香巻き,148.0,3.0,1.0,33.0,https://www.chopstickchronicles.com/oshinko-roll/
13,chopstick_chronicles,sushi,sushi,Pressed Sushi with Smoked Salmon スモークサーモンの押し寿司,368.0,11.0,9.0,59.0,https://www.chopstickchronicles.com/pressed-su...
14,chopstick_chronicles,sushi,sushi,Sushi rolls Futomaki 太巻き寿司,364.0,9.0,2.0,73.0,https://www.chopstickchronicles.com/futomaki/
15,chopstick_chronicles,sushi,sushi,Uramaki 裏巻き,480.0,9.0,10.0,89.0,https://www.chopstickchronicles.com/uramaki/
16,chopstick_chronicles,sushi,sushi roll,Hosomaki 細巻き,183.0,3.0,3.0,35.0,https://www.chopstickchronicles.com/hosomaki/
17,no_recipes,sushi,sushi,Inari Sushi (Fried Tofu Pocket Sushi),376.0,9.0,6.0,67.0,https://norecipes.com/inari-sushi-recipe/
18,no_recipes,sushi,sushi,Oshinko Roll (Japanese Pickle Sushi),81.0,2.0,0.3,17.0,https://norecipes.com/oshinko-roll-maki-sushi/
19,no_recipes,sushi,sushi,Kappa Maki (Cucumber Sushi Roll),303.0,6.0,1.0,66.0,https://norecipes.com/kappa-maki-cucumber-sush...
20,no_recipes,sushi,sushi,Seafood Chirashi Sushi,677.0,51.0,21.0,67.0,https://norecipes.com/seafood-chirashi-sushi/
21,no_recipes,sushi,sushi,Spicy Salmon Hand Roll,139.0,8.0,2.0,25.0,https://norecipes.com/spicy-salmon-sushi-hand-...
22,no_recipes,sushi,sushi,Temaki Sushi (Hand Rolls),45.0,7.0,1.0,7.0,https://norecipes.com/temaki-sushi/
23,no_recipes,sushi,sushi,Best California Roll,190.0,9.0,6.0,25.0,https://norecipes.com/california-roll-recipe/
24,no_recipes,sushi,sushi,Shrimp Tempura Roll,232.0,12.0,9.0,25.0,https://norecipes.com/shrimp-tempura-sushi-roll/
25,no_recipes,sushi,sushi,Spicy Tuna Rolls,449.0,25.0,2.0,77.0,https://norecipes.com/spicy-tuna-roll/
26,no_recipes,sushi,sushi roll,Caterpillar Roll,400.0,9.0,15.0,59.0,https://norecipes.com/caterpillar-roll-recipe/

Rejected examples:

,source_site,food_class,query,recipe_name,calories,protein,fat,carbs,source_url,drop_reason
0,chopstick_chronicles,sushi,sushi,Temari Sushi 手毬寿司,189.0,6.0,3.0,33.0,https://www.chopstickchronicles.com/temari-sushi/,duplicate_recipe_name_existing_dataset
1,chopstick_chronicles,sushi,sushi,California Roll カリフォルニア巻き,416.0,9.0,10.0,71.0,https://www.chopstickchronicles.com/california...,duplicate_recipe_name_existing_dataset
2,chopstick_chronicles,sushi,sushi,Aunt Keiko's Inarisushi いなり寿司,200.0,4.0,NaN,42.0,https://www.chopstickchronicles.com/inari-sushi/,missing_nutrition

Failed examples:

,source_site,query,url,reason
0,chopstick_chronicles,sushi,https://www.chopstickchronicles.com/sushi/,scrape_failed_or_no_json_ld

Specialized sushi supplement saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/scraped_raw/specialized_sushi_supplement_raw.csv

Specialized sushi rejected log saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/logs/specialized_sushi_rejected_records.csv

Specialized sushi failed URL log saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/logs/specialized_sushi_failed_urls.csv

In [34]:
# Cell 25I — Merge specialized sushi supplement and create cleaned dataset v2

print("Base merged dataset shape before sushi augmentation:")
print(merged_text_calorie_df.shape)

print("\nBase records per class:")
print(merged_text_calorie_df["food_class"].value_counts())

print("\nSpecialized sushi supplement shape:")
print(sushi_specialized_supplement_df.shape)

# Merge old clean candidate with new sushi supplement
merged_text_calorie_v2_df = pd.concat(
    [merged_text_calorie_df, sushi_specialized_supplement_df],
    ignore_index=True
)

# Safety normalization for duplicate detection
merged_text_calorie_v2_df["normalized_recipe_name"] = merged_text_calorie_v2_df["recipe_name"].apply(
    normalize_text_for_filtering
)

before_dedup = len(merged_text_calorie_v2_df)

merged_text_calorie_v2_df = merged_text_calorie_v2_df.drop_duplicates(
    subset=["source_url"],
    keep="first"
)

merged_text_calorie_v2_df = merged_text_calorie_v2_df.drop_duplicates(
    subset=["normalized_recipe_name"],
    keep="first"
)

after_dedup = len(merged_text_calorie_v2_df)

merged_text_calorie_v2_df = merged_text_calorie_v2_df.drop(
    columns=["normalized_recipe_name"],
    errors="ignore"
).reset_index(drop=True)

print("\nRows removed by safety dedup after sushi merge:")
print(before_dedup - after_dedup)

print("\nMerged v2 raw-clean shape:")
print(merged_text_calorie_v2_df.shape)

print("\nMerged v2 records per class:")
print(merged_text_calorie_v2_df["food_class"].value_counts())

print("\nMissing values after v2 merge:")
print(merged_text_calorie_v2_df.isna().sum())

print("\nDuplicate source URLs after v2 merge:")
print(merged_text_calorie_v2_df["source_url"].duplicated().sum())

print("\nDuplicate recipe names after v2 merge:")
print(merged_text_calorie_v2_df["recipe_name"].duplicated().sum())

print("\nNutrition summary after v2 merge:")
display(merged_text_calorie_v2_df[["calories", "protein", "fat", "carbs"]].describe())

print("\nCalories summary by class after v2 merge:")
display(
    merged_text_calorie_v2_df.groupby("food_class")["calories"]
    .agg(["count", "min", "max", "mean", "median"])
    .sort_values("count", ascending=False)
)

# Rebuild modeling-ready dataset v2
final_text_v2_df = merged_text_calorie_v2_df.copy()

final_text_v2_df["clean_recipe_name"] = final_text_v2_df["recipe_name"].apply(clean_text_for_modeling)
final_text_v2_df["clean_ingredients_text"] = final_text_v2_df["ingredients_text"].apply(clean_text_for_modeling)

final_text_v2_df["input_text"] = (
    "food class: "
    + final_text_v2_df["food_class"].astype(str)
    + " recipe name: "
    + final_text_v2_df["clean_recipe_name"]
    + " ingredients: "
    + final_text_v2_df["clean_ingredients_text"]
)

final_text_v2_df = final_text_v2_df.reset_index(drop=True)
final_text_v2_df.insert(0, "record_id", ["TXT_" + str(i).zfill(5) for i in range(len(final_text_v2_df))])

final_modeling_v2_df = final_text_v2_df[[
    "record_id",
    "source_site",
    "food_class",
    "query",
    "recipe_name",
    "ingredients_text",
    "clean_recipe_name",
    "clean_ingredients_text",
    "input_text",
    "calories",
    "protein",
    "fat",
    "carbs",
    "source_url",
    "scraped_at"
]].copy()

print("\nFinal modeling dataset v2 shape:")
print(final_modeling_v2_df.shape)

print("\nFinal modeling v2 records per class:")
print(final_modeling_v2_df["food_class"].value_counts())

print("\nMissing values in final modeling v2:")
print(final_modeling_v2_df.isna().sum())

print("\nDuplicate source URLs in final modeling v2:")
print(final_modeling_v2_df["source_url"].duplicated().sum())

print("\nDuplicate input_text in final modeling v2:")
print(final_modeling_v2_df["input_text"].duplicated().sum())

print("\nInput text length summary v2:")
final_modeling_v2_df["input_text_length"] = final_modeling_v2_df["input_text"].str.len()
print(final_modeling_v2_df["input_text_length"].describe())

print("\nSample sushi records after v2:")
display(
    final_modeling_v2_df[final_modeling_v2_df["food_class"] == "sushi"][[
        "record_id",
        "source_site",
        "food_class",
        "recipe_name",
        "calories",
        "protein",
        "fat",
        "carbs",
        "source_url"
    ]].head(20)
)

# Save v2 files
merged_text_calorie_v2_path = CLEAN_DIR / "text_calorie_merged_clean_candidate_v2.csv"
cleaned_text_calorie_dataset_v2_path = CLEAN_DIR / "cleaned_text_calorie_dataset_v2.csv"

merged_text_calorie_v2_df.to_csv(merged_text_calorie_v2_path, index=False)
final_modeling_v2_df.drop(columns=["input_text_length"], errors="ignore").to_csv(
    cleaned_text_calorie_dataset_v2_path,
    index=False
)

print("\nMerged clean candidate v2 saved to:")
print(merged_text_calorie_v2_path)

print("\nFinal cleaned text-calorie dataset v2 saved to:")
print(cleaned_text_calorie_dataset_v2_path)

Base merged dataset shape before sushi augmentation:
(416, 11)

Base records per class:
food_class
pizza       48
burger      47
rice        47
sandwich    46
pasta       45
salad       45
fries       44
chicken     41
steak       39
sushi       14
Name: count, dtype: int64

Specialized sushi supplement shape:
(27, 11)

Rows removed by safety dedup after sushi merge:
0

Merged v2 raw-clean shape:
(443, 11)

Merged v2 records per class:
food_class
pizza       48
burger      47
rice        47
sandwich    46
pasta       45
salad       45
fries       44
chicken     41
sushi       41
steak       39
Name: count, dtype: int64

Missing values after v2 merge:
source_site         0
food_class          0
query               0
recipe_name         0
ingredients_text    0
calories            0
protein             0
fat                 0
carbs               0
source_url          0
scraped_at          0
dtype: int64

Duplicate source URLs after v2 merge:
0

Duplicate recipe names after v2 merge:
0

Nutrition summary after v2 merge:

          calories     protein         fat       carbs
count   443.000000  443.000000  443.000000  443.000000
mean    463.027088   25.609932   21.128646   41.330926
std     223.423556   13.923844   15.321915   24.960789
min      45.000000    0.300000    0.300000    0.400000
25%     303.500000   15.000000   10.000000   22.500000
50%     428.000000   25.200000   17.000000   39.000000
75%     580.500000   35.000000   28.000000   57.500000
max    1394.000000   69.000000   89.000000  148.000000

Calories summary by class after v2 merge:

            count    min     max        mean  median
food_class
pizza          48  118.0   740.0  427.000000   427.0
burger         47  175.0  1080.0  526.936170   508.0
rice           47  164.0   834.0  470.404255   418.0
sandwich       46  125.0  1256.0  545.913043   470.0
salad          45  111.0   838.0  404.444444   374.0
pasta          45  371.0  1140.0  626.288889   600.0
fries          44  120.0  1394.0  403.590909   379.0
chicken        41  239.0   707.0  409.243902   368.0
sushi          41   45.0   862.0  313.487805   313.0
steak          39  188.0  1282.0  483.717949   415.0

Final modeling dataset v2 shape:
(443, 15)

Final modeling v2 records per class:
food_class
pizza       48
burger      47
rice        47
sandwich    46
pasta       45
salad       45
fries       44
chicken     41
sushi       41
steak       39
Name: count, dtype: int64

Missing values in final modeling v2:
record_id                 0
source_site               0
food_class                0
query                     0
recipe_name               0
ingredients_text          0
clean_recipe_name         0
clean_ingredients_text    0
input_text                0
calories                  0
protein                   0
fat                       0
carbs                     0
source_url                0
scraped_at                0
dtype: int64

Duplicate source URLs in final modeling v2:
0

Duplicate input_text in final modeling v2:
0

Input text length summary v2:
count    443.000000
mean     379.318284
std      116.412554
min      109.000000
25%      298.500000
50%      372.000000
75%      439.500000
max      765.000000
Name: input_text_length, dtype: float64

Sample sushi records after v2:

,record_id,source_site,food_class,recipe_name,calories,protein,fat,carbs,source_url
32,TXT_00032,bbc_good_food,sushi,Build-your-own salmon sushi burrito,441.0,19.0,26.0,30.0,https://www.bbcgoodfood.com/recipes/build-your...
75,TXT_00075,bbc_good_food,sushi,Chicken onigiri,303.0,11.0,16.0,29.0,https://www.bbcgoodfood.com/recipes/chicken-on...
128,TXT_00128,bbc_good_food,sushi,Easy salmon sushi,216.0,12.0,2.0,41.0,https://www.bbcgoodfood.com/recipes/easy-salmo...
184,TXT_00184,bbc_good_food,sushi,Kelp and smoked salmon sushi rolls,277.0,12.0,12.0,29.0,https://www.bbcgoodfood.com/recipes/kelp-smoke...
274,TXT_00274,bbc_good_food,sushi,Quick sushi bowl,498.0,27.0,11.0,70.0,https://www.bbcgoodfood.com/recipes/quick-sush...
280,TXT_00280,bbc_good_food,sushi,Rice & quinoa prawn sushi bowl,439.0,22.0,10.0,61.0,https://www.bbcgoodfood.com/recipes/rice-quino...
288,TXT_00288,bbc_good_food,sushi,Salmon & cucumber sushi rolls,59.0,3.0,1.0,10.0,https://www.bbcgoodfood.com/recipes/salmon-cuc...
291,TXT_00291,bbc_good_food,sushi,Salmon sushi salad,862.0,27.0,43.0,87.0,https://www.bbcgoodfood.com/recipes/salmon-sus...
295,TXT_00295,bbc_good_food,sushi,Sesame & ginger sushi bowls,449.0,17.0,21.0,44.0,https://www.bbcgoodfood.com/recipes/sesame-gin...
299,TXT_00299,bbc_good_food,sushi,Simple sushi,390.0,8.0,9.0,70.0,https://www.bbcgoodfood.com/recipes/simple-sushi
304,TXT_00304,bbc_good_food,sushi,Smoked salmon & avocado sushi,49.0,2.0,2.0,7.0,https://www.bbcgoodfood.com/recipes/smoked-sal...
340,TXT_00340,bbc_good_food,sushi,Sushi burrito,313.0,18.0,11.0,33.0,https://www.bbcgoodfood.com/recipes/sushi-burrito
341,TXT_00341,bbc_good_food,sushi,"Sushi rice bowl with beef, egg & chilli sauce",621.0,41.0,23.0,63.0,https://www.bbcgoodfood.com/recipes/sushi-rice...
373,TXT_00373,bbc_good_food,sushi,Vegan sushi (kappa maki),109.0,3.0,1.0,22.0,https://www.bbcgoodfood.com/recipes/cucumber-s...
416,TXT_00416,pickled_plum,sushi,Maki Sushi,150.0,2.5,1.5,30.8,https://pickledplum.com/maki-sushi/
417,TXT_00417,pickled_plum,sushi,Temari Sushi,64.0,2.7,0.3,12.2,https://pickledplum.com/temari-sushi/
418,TXT_00418,pickled_plum,sushi,Inari Sushi (Inarizushi - いなり寿司),81.0,0.3,2.1,3.7,https://pickledplum.com/inari-sushi-recipe/
419,TXT_00419,pickled_plum,sushi,Vegetarian Chirashi Sushi,604.0,11.3,17.4,96.4,https://pickledplum.com/vegetarian-chirashi-su...
420,TXT_00420,pickled_plum,sushi,Philadelphia Roll,575.0,25.6,13.5,86.0,https://pickledplum.com/philadelphia-roll/
421,TXT_00421,pickled_plum,sushi,Spicy Tuna Roll (Poor Man's),106.0,6.8,2.0,14.3,https://pickledplum.com/spicy-tuna-roll-recipe/

Merged clean candidate v2 saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/text_calorie_merged_clean_candidate_v2.csv

Final cleaned text-calorie dataset v2 saved to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/cleaned_text_calorie_dataset_v2.csv

In [35]:
# Cell 25J — Train / validation / test split for cleaned dataset v2

from sklearn.model_selection import train_test_split

# Use the final v2 modeling dataset
split_v2_df = final_modeling_v2_df.drop(
    columns=["input_text_length"],
    errors="ignore"
).copy()

RANDOM_STATE = 42

# First split: 70% train, 30% temporary
train_v2_df, temp_v2_df = train_test_split(
    split_v2_df,
    test_size=0.30,
    random_state=RANDOM_STATE,
    stratify=split_v2_df["food_class"]
)

# Second split: 15% validation, 15% test
val_v2_df, test_v2_df = train_test_split(
    temp_v2_df,
    test_size=0.50,
    random_state=RANDOM_STATE,
    stratify=temp_v2_df["food_class"]
)

train_v2_df = train_v2_df.reset_index(drop=True)
val_v2_df = val_v2_df.reset_index(drop=True)
test_v2_df = test_v2_df.reset_index(drop=True)

print("Dataset v2 split finished.")

print("\nTrain v2 shape:")
print(train_v2_df.shape)

print("\nValidation v2 shape:")
print(val_v2_df.shape)

print("\nTest v2 shape:")
print(test_v2_df.shape)

print("\nTrain v2 class distribution:")
print(train_v2_df["food_class"].value_counts())

print("\nValidation v2 class distribution:")
print(val_v2_df["food_class"].value_counts())

print("\nTest v2 class distribution:")
print(test_v2_df["food_class"].value_counts())

# Leakage checks by source_url
train_urls = set(train_v2_df["source_url"])
val_urls = set(val_v2_df["source_url"])
test_urls = set(test_v2_df["source_url"])

print("\nURL overlap checks:")
print("Train-Val overlap:", len(train_urls.intersection(val_urls)))
print("Train-Test overlap:", len(train_urls.intersection(test_urls)))
print("Val-Test overlap:", len(val_urls.intersection(test_urls)))

# Leakage checks by record_id
train_ids = set(train_v2_df["record_id"])
val_ids = set(val_v2_df["record_id"])
test_ids = set(test_v2_df["record_id"])

print("\nRecord ID overlap checks:")
print("Train-Val overlap:", len(train_ids.intersection(val_ids)))
print("Train-Test overlap:", len(train_ids.intersection(test_ids)))
print("Val-Test overlap:", len(val_ids.intersection(test_ids)))

# Save split files
train_v2_path = CLEAN_DIR / "cleaned_text_calorie_train_v2.csv"
val_v2_path = CLEAN_DIR / "cleaned_text_calorie_val_v2.csv"
test_v2_path = CLEAN_DIR / "cleaned_text_calorie_test_v2.csv"

train_v2_df.to_csv(train_v2_path, index=False)
val_v2_df.to_csv(val_v2_path, index=False)
test_v2_df.to_csv(test_v2_path, index=False)

# Save split summary
split_v2_summary_df = pd.DataFrame({
    "split": ["train", "validation", "test"],
    "records": [len(train_v2_df), len(val_v2_df), len(test_v2_df)]
})

split_v2_summary_path = CLEAN_DIR / "text_calorie_split_summary_v2.csv"
split_v2_summary_df.to_csv(split_v2_summary_path, index=False)

print("\nSaved train v2 split to:")
print(train_v2_path)

print("\nSaved validation v2 split to:")
print(val_v2_path)

print("\nSaved test v2 split to:")
print(test_v2_path)

print("\nSaved split v2 summary to:")
print(split_v2_summary_path)

Dataset v2 split finished.

Train v2 shape:
(310, 15)

Validation v2 shape:
(66, 15)

Test v2 shape:
(67, 15)

Train v2 class distribution:
food_class
pizza       34
rice        33
burger      33
sandwich    32
pasta       31
salad       31
fries       31
chicken     29
sushi       29
steak       27
Name: count, dtype: int64

Validation v2 class distribution:
food_class
pasta       7
rice        7
salad       7
burger      7
pizza       7
sandwich    7
fries       6
steak       6
sushi       6
chicken     6
Name: count, dtype: int64

Test v2 class distribution:
food_class
pizza       7
rice        7
sandwich    7
salad       7
fries       7
pasta       7
burger      7
sushi       6
chicken     6
steak       6
Name: count, dtype: int64

URL overlap checks:
Train-Val overlap: 0
Train-Test overlap: 0
Val-Test overlap: 0

Record ID overlap checks:
Train-Val overlap: 0
Train-Test overlap: 0
Val-Test overlap: 0

Saved train v2 split to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/cleaned_text_calorie_train_v2.csv

Saved validation v2 split to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/cleaned_text_calorie_val_v2.csv

Saved test v2 split to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/cleaned_text_calorie_test_v2.csv

Saved split v2 summary to:
/content/drive/MyDrive/Calorify/phase2_text_calorie/data/cleaned/text_calorie_split_summary_v2.csv